### PR TITLE
Use IMDS to get subscription for Azure MSI

### LINKED ISSUE #7301: MSI - fails to login due to tenant ID missing from header.
https://github.com/hashicorp/packer/blob/0c47092ec92c78584ea8218ad62f97a9cd9adaa6/builder/azure/arm/authenticate_msi.go#L22

The current path is not correct for MSI token with the tentantID.

I don't believe the getServicePrincipalTokenWithResource path is correct as documented here.

The path/header should include similar to this `curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s`

EDIT: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-go

image

### PR DESCRIPTION
**Pull request by joellopes03**
Fix MSI fix #7301. Use IMDS to retrieve subscription details

### CODE REVIEW

File: builder/azure/arm/builder.go [hunk 1]
```diff
@@ -74,6 +76,12 @@ func (b *Builder) Run(ui packer.Ui, hook packer.Hook, cache packer.Cache) (packe
 		return nil, err
 	}
 
+	if b.config.useMSI() {
+		if err := newConfigRetriever().FillParameters(b.config); err != nil {
+			return nil, err
+		}
+	}
```
Comment (paulmey) [inline builder/azure/arm/builder.go]: It's kind of ugly to have to copy this code, but I understand why it is necessary now (auth method detection logic). I have a refactor of the azure client config cooking in local repo, I'll try to pick this up then. For now can you add a comment indicating that we shouldn't run this earlier because otherwise ClientConfig will pick the wrong authentication method?

Comment (joellopes03) [reply builder/azure/arm/builder.go]: Added Comment

**Comment by joellopes03** [comment]
Tested Client secret, client cert, device auth and msi. All looks good.

**Comment by ashleyhull-versent** [comment]
Is there a test build?

**Comment by joellopes03** [comment]
> Is there a test build?
[here](https://github.com/joellopes03/packer/releases/tag/packer_master02212019_7301fix) is private build

**Comment by ashleyhull-versent** [comment]
> > Is there a test build?
> > [here](https://github.com/joellopes03/packer/releases/tag/packer_master02212019_7301fix) is private build

lol.. can you compile the linux builds please :D

**Comment by joellopes03** [comment]
> > > Is there a test build?
> > > [here](https://github.com/joellopes03/packer/releases/tag/packer_master02212019_7301fix) is private build
> 
> Can you compile the linux builds please :D

Added couple of Linux builds. Please let me know if you need anything specific.

**Comment by ashleyhull-versent** [comment]
#file packer
packer: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows"

interesting :) the linux packages are not ELFs

**Comment by paulmey** [comment]
Test build: https://github.com/paulmey/packer/releases/tag/v1.3.5-c8a60c77d

**Comment by ashleyhull-versent** [comment]
I'm doing testing, but this looks like it's resolved for my MSI instance.

Thanks for your assistance.

**Comment by ashleyhull-versent** [comment]
Validated.. no regression from my tests.
