### PR TITLE
aws ebs_surrogate: fix unhonored kms_key_id

### LINKED ISSUE #9958: amazon ebs surrogate: cannot specify kms_key_id in launch devices
#### Overview of the Issue

When using the amazon `ebs_surrogate` builder with a custom KMS key for the launched block devices, Packer always uses the default AWS-managed KMS key instead of checking the `kms_key_id` parameter.

#### Reproduction Steps

- Launch Packer build with the supplied config
- Inspect volumes attached to the launched instance

### Packer version

1.6.2

### Simplified Packer Buildfile

```
{
  "builders": [
    {
      "ami_root_device": {
        "delete_on_termination": true,
        "device_name": "/dev/xvda",
        "source_device_name": "/dev/xvdf",
        "volume_size": 8,
        "volume_type": "gp2"
      },
      "ami_virtualization_type": "hvm",
      "launch_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/xvdf",
          "encrypted": true,
          "kms_key_id": "alias/my_key",
          "volume_size": 8,
          "volume_type": "gp2"
        }
      ],
      "region": "{{user `aws_region`}}",
      "source_ami_filter": {
        "filters": {
          "architecture": "x86_64",
          "block-device-mapping.volume-type": "gp2",
          "name": "*amzn2-ami-hvm-*-x86_64-gp2",
          "root-device-type": "ebs",
          "virtualization-type": "hvm"
        },
        "most_recent": true,
        "owners": [
          "amazon"
        ]
      },
      "type": "amazon-ebssurrogate"
    }
  ],
  "provisioners": [ ... ],
  "variables": {
    "aws_region": "us-west-2"
  }
}
```

### Operating system and Environment details

Applies on every environment.

Relevant packer logs:

```
==> amazon-ebssurrogate: Creating snapshot of EBS Volume vol-aaa...
==> amazon-ebssurrogate: Registering the AMI...
==> amazon-ebssurrogate: AMI: ami-aaa
==> amazon-ebssurrogate: Waiting for AMI to become ready...
==> amazon-ebssurrogate: Modifying attributes on AMI (ami-aaa)...
    amazon-ebssurrogate: Modifying: description
    amazon-ebssurrogate: Modifying: users
==> amazon-ebssurrogate: Error modify AMI attributes: InvalidParameter: Snapshots encrypted with the AWS Managed CMK can’t be shared. Specify another snapshot.
==> amazon-ebssurrogate: 	status code: 400, request id: aaa
==> amazon-ebssurrogate: Deregistering the AMI because cancellation or error...
==> amazon-ebssurrogate: Removing snapshots since we cancelled or halted...
==> amazon-ebssurrogate: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebssurrogate: Terminating the source AWS instance...
==> amazon-ebssurrogate: Cleaning up any extra volumes...
==> amazon-ebssurrogate: No volumes to clean up, skipping
==> amazon-ebssurrogate: Deleting temporary security group...
==> amazon-ebssurrogate: Deleting temporary keypair...
Build 'amazon-ebssurrogate' errored after 9 minutes 45 seconds: Error modify AMI attributes: InvalidParameter: Snapshots encrypted with the AWS Managed CMK can’t be shared. Specify another snapshot.
	status code: 400, request id: aaa
```

We can see that the block device handling is slightly different in the builder:

https://github.com/hashicorp/packer/blob/ce2047f30b5dd84fcab7c8c954f9b7509c5a5258/builder/amazon/ebssurrogate/block_device.go#L77-L85

vs

https://github.com/hashicorp/packer/blob/ce2047f30b5dd84fcab7c8c954f9b7509c5a5258/builder/amazon/common/block_device.go#L142-L154

As `ebssurrogate.BlockDevice` embeds `awscommon.BlockDevice`, we can remove the `BuildEC2BlockDeviceMapping` function altogether to get the same functionality.

### PR DESCRIPTION
**Pull request by adongy**
The surrogate builder test situation isn't the best, but this should actually improve coverage as we rely on the common builder test coverage.

I have verified that this fixes the issue and will use the provided key.

Closes #9958

### CODE REVIEW

File: builder/amazon/ebssurrogate/block_device.go [hunk 1]
```diff
@@ -41,50 +38,6 @@ func (bds BlockDevices) BuildEC2BlockDeviceMappings() []*ec2.BlockDeviceMapping
...
-	if blockDevice.SnapshotId != "" {
-		ebsBlockDevice.SnapshotId = aws.String(blockDevice.SnapshotId)
-	}
-	ebsBlockDevice.Encrypted = blockDevice.Encrypted.ToBoolPointer()
-
-	mapping.Ebs = ebsBlockDevice
-
-	return mapping
-}
-
```
Comment (azr) [inline builder/amazon/ebssurrogate/block_device.go:87]: Oh wow, this was the exact same code as https://github.com/hashicorp/packer/blob/8b4993e44c9fa523c4ce692c3a0392087e0813c1/builder/amazon/common/block_device.go#L109-L155 but without the `kms_key_id` case

**Review by azr — APPROVED** [review]
Nice one, LGTM thanks !
