### PR TITLE
qemu: add support for using a network bridge

### LINKED ISSUE #9156: qemu: add support for bridge networking
I'm [trying to install ESXi 7.0](https://github.com/rgl/esxi-vagrant/tree/feature-upgrade-to-esxi-7) and the combination of using the `vmxnet3` nic and the qemu user mode networking does not work (please note that the `e1000e` nic does not work either).

I've manually used the qemu bridge mode and it worked nicely, please see the `raw qemu-kvm` section at https://github.com/rgl/esxi-vagrant/blob/feature-upgrade-to-esxi-7/README.md.

Essentially, I would be fine to just add the `net_bridge` property, set it as `"net_bridge": "virbr0"` and require the user to already have `virbr0` properly configured before calling packer.

### PR DESCRIPTION
**Pull request by rgl**
I've just found out about [0xef53/go-qmp](https://github.com/0xef53/go-qmp) which provides a nicer interface to QMP (e.g. we do not need to manually (un)marshal the structs), what do you think in switching over to that library too?

But please note that the digitalocean repo also seems to support libvirt; the go-qmp is only for QMP.

I also want to make the network device easier to find using QMP, but that will introduce a couple of backward incompatible changes:

1. instead of the netdev being called `user.0` I want to change it to `net0` (because it can now be a `user` or `bridge` netdev).
2. add the `id=nic0` parameter to the qemu `-device` argument. that way, that device is easier to find using QMP. That is, instead of `-device vmxnet3,netdev=net0` it will be `-device vmxnet3,id=nic0,netdev=net0`.
    * this way instead of trying to find the device in the qmp paths `/machine/peripheral/*` and `/machine/peripheral-anon/*` I can directly access it at `/machine/peripheral/nic0`, which simplifies to code a lot.
      * hummm or maybe this should be used anyways just in case the user forgets the `id=nic0`?

This closes #9156.

### CODE REVIEW

**Comment by sylviamoss** [comment]
@rgl Is it possible to find a solution without using 0xef53/go-qmp?

**Comment by rgl** [comment]
@sylviamoss the one in this PR does not use it and works fine :-)

File: builder/qemu/step_configure_qmp.go [hunk 1]
```diff
@@ -26,9 +26,10 @@ type stepConfigureQMP struct {
 }
 
 func (s *stepConfigureQMP) Run(ctx context.Context, state multistep.StateBag) multistep.StepAction {
+	config := state.Get("config").(*Config)
 	ui := state.Get("ui").(packer.Ui)
 
-	if !s.VNCUsePassword {
```
Comment (SwampDragons) [inline builder/qemu/step_configure_qmp.go:31]: You've eliminated the use of VNCUsePassword altogether here. We should probably remove it from the step struct.

File: builder/qemu/step_wait_guest_address.go [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+// bridge, then it sets the guestAddress state property.
+type stepWaitGuestAddress struct{}
+
+func (s *stepWaitGuestAddress) Run(ctx context.Context, state multistep.StateBag) multistep.StepAction {
+	config := state.Get("config").(*Config)
+	ui := state.Get("ui").(packer.Ui)
+	qmpMonitor := state.Get("qmp_monitor").(*qmp.SocketMonitor)
+
+	ui.Say(fmt.Sprintf("Waiting for the guest address to become available in the %s network bridge...", config.NetBridge))
+	for {
```
Comment (SwampDragons) [inline builder/qemu/step_wait_guest_address.go:29]: Should this step have a timeout so that it doesn't loop forever if something is wrong?

File: builder/qemu/builder.go [hunk 3]
```diff
@@ -534,7 +544,11 @@ func (b *Builder) Prepare(raws ...interface{}) ([]string, []string, error) {
 			errs, fmt.Errorf("vnc_port_min must be less than vnc_port_max"))
 	}
 
-	if b.config.VNCUsePassword && b.config.QMPSocketPath == "" {
+	if b.config.NetBridge != "" || b.config.VNCUsePassword {
```
Comment (SwampDragons) [inline builder/qemu/builder.go:547]: In the Prepare() we should probably do a validation check on the operating system to make sure it's a linux-based OS and fail early if someone is trying to run on windows or macOS

File: builder/qemu/step_configure_qmp.go (hunk 1 above)
Comment (rgl) [reply builder/qemu/step_configure_qmp.go:31]: Ah indeed. Good catch!

File: builder/qemu/step_wait_guest_address.go (hunk 2 above)
Comment (rgl) [reply builder/qemu/step_wait_guest_address.go:29]: Should it be hard-coded to value (e.g. 5m)? Or should it introduce another builder config variable? Or is there some variable that I could re-use (e.g. ssh_timeout/winrm_timeout)?

File: builder/qemu/builder.go (hunk 3 above)
Comment (rgl) [reply builder/qemu/builder.go:547]: Ah indeed, I will validate it!

This could probably work in other OSes, but currently, I'm only able to test in Linux/Ubuntu.

Comment (rgl) [reply builder/qemu/builder.go:552]: Its now validating.

File: builder/qemu/step_configure_qmp.go (hunk 1 above)
Comment (rgl) [reply builder/qemu/step_configure_qmp.go:31]: Its now removed.

File: builder/qemu/step_wait_guest_address.go (hunk 2 above)
Comment (SwampDragons) [reply builder/qemu/step_wait_guest_address.go:29]: sorry I forgot to answer this. I think for now we can use the ssh_timeout and if that doesn't make sense in the future we can change.

**Comment by SwampDragons** [comment]
rebased to fix conflicts.

**Comment by SwampDragons** [comment]
welp. Broke that didn't I. I'll fix first thing in the AM. 😅

File: builder/qemu/step_wait_guest_address.go (hunk 2 above)
Comment (rgl) [reply builder/qemu/step_wait_guest_address.go:29]: Do you want this in another PR?

Comment (SwampDragons) [reply builder/qemu/step_wait_guest_address.go:29]: Oh, oops. Forgot I was waiting on this. Yes, another PR would be awesome.

Comment (rgl) [reply builder/qemu/step_wait_guest_address.go:29]: Its at https://github.com/hashicorp/packer/pull/9287
