### PR TITLE
Fix recurring bug #3878, make destination ESXi host selectable in con…

### LINKED ISSUE #3878: vSphere post-processor fails, but running ovftool with same input manually works
I am having problems with the vSphere post-processor. It always fails when executing the ovftool.
I tried running with debug logging enabled `PACKER_LOG=DEBUG packer build windows2012r2-vanilla.json` but I didn't get a better understanding on why it failed.

I see that the following command fails:
```
2016/09/09 12:11:34 packer: 2016/09/09 12:11:34 Starting ovftool with parameters: --noSSLVerify=true --acceptAllEulas --name="windows2012r2-vanilla-1473415423" --datastore="MyDatasotre" --diskMode="thin" --network="Infrastructure Services" --vmFolder="" output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
```
so I tried running ovftool with the same input, and it worked. I literally wrote ovftool and then copy/pasted the same line from the debug log, and it worked. 

- Packer version: 0.10.1
- Host platform:   Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-36-generic x86_64)

- My json, which literally clones a vmx and tries to deploy it to vSphere:
```
{
 "variables": {
        "vm_name": "windows2012r2-vanilla-{{timestamp}}",
        "source_path": "/opt/packer/output-vmware-iso/windows2012r2-bt-1473334055.vmx",
        "ssh_username": "myuser",
        "ssh_password": "mypass",
        "vsphere_user": "myvpshereuser",
        "vsphere_pass": "myvspherepass"
    },
    "builders": [
        {
            "type": "vmware-vmx",
            "vm_name": "{{user `vm_name`}}",
            "source_path": "{{user `source_path`}}",
            "ssh_username": "{{user `ssh_username`}}",
            "ssh_password": "{{user `ssh_password`}}",
            "boot_wait": "1m",
            "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
            "skip_compaction": true
        }
    ],
    "post-processors": [
        {
            "type": "vsphere",
            "host": "vcenter.somecompany.net",
            "password": "{{user `vsphere_pass`}}",
            "username": "{{user `vsphere_user`}}",
            "insecure": true,
            "vm_name": "{{user `vm_name`}}",
            "datacenter": "MyDatacenter",
            "cluster": "MyCluster",
            "datastore": "MyDatastore",
            "disk_mode": "thin",
            "vm_network": "Infrastructure Services",
            "overwrite": false
        }
    ]
}
```

- Debug log output from `PACKER_LOG=1
```

[pveljano@f20160908x001]packer$ PACKER_LOG=DEBUG packer build -debug win2012r2-vmware-deploy.json 
2016/09/09 12:03:43 [INFO] Packer version: 0.10.1
2016/09/09 12:03:43 Packer Target OS/Arch: linux amd64
2016/09/09 12:03:43 Built with Go Version: go1.6.2
2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 Using internal plugin for virtualbox-iso
2016/09/09 12:03:43 Using internal plugin for amazon-chroot
2016/09/09 12:03:43 Using internal plugin for amazon-ebs
2016/09/09 12:03:43 Using internal plugin for azure-arm
2016/09/09 12:03:43 Using internal plugin for googlecompute
2016/09/09 12:03:43 Using internal plugin for null
2016/09/09 12:03:43 Using internal plugin for openstack
2016/09/09 12:03:43 Using internal plugin for qemu
2016/09/09 12:03:43 Using internal plugin for amazon-instance
2016/09/09 12:03:43 Using internal plugin for parallels-iso
2016/09/09 12:03:43 Using internal plugin for parallels-pvm
2016/09/09 12:03:43 Using internal plugin for vmware-vmx
2016/09/09 12:03:43 Using internal plugin for digitalocean
2016/09/09 12:03:43 Using internal plugin for docker
2016/09/09 12:03:43 Using internal plugin for virtualbox-ovf
2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 Using internal plugin for vmware-iso
2016/09/09 12:03:43 Using internal plugin for ansible
2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 Using internal plugin for puppet-masterless
2016/09/09 12:03:43 Using internal plugin for salt-masterless
2016/09/09 12:03:43 Using internal plugin for shell
2016/09/09 12:03:43 Using internal plugin for windows-shell
2016/09/09 12:03:43 Using internal plugin for windows-restart
2016/09/09 12:03:43 Using internal plugin for ansible-local
2016/09/09 12:03:43 Using internal plugin for chef-client
2016/09/09 12:03:43 Using internal plugin for chef-solo
2016/09/09 12:03:43 Using internal plugin for powershell
2016/09/09 12:03:43 Using internal plugin for puppet-server
2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 Using internal plugin for docker-push
2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 Using internal plugin for vagrant
2016/09/09 12:03:43 Using internal plugin for vagrant-cloud
2016/09/09 12:03:43 Using internal plugin for vsphere
2016/09/09 12:03:43 Using internal plugin for amazon-import
2016/09/09 12:03:43 Using internal plugin for compress
2016/09/09 12:03:43 Using internal plugin for docker-import
2016/09/09 12:03:43 Using internal plugin for docker-tag
2016/09/09 12:03:43 Using internal plugin for artifice
2016/09/09 12:03:43 Using internal plugin for atlas
2016/09/09 12:03:43 Using internal plugin for docker-save
2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 Attempting to open config file: /home/pveljano/.packerconfig
2016/09/09 12:03:43 [WARN] Config file doesn't exist: /home/pveljano/.packerconfig
2016/09/09 12:03:43 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[parallels-pvm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm digitalocean:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean amazon-ebs:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs googlecompute:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file vmware-vmx:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx virtualbox-ovf:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf azure-arm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm null:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null openstack:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack amazon-instance:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance parallels-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso docker:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker vmware-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso virtualbox-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso amazon-chroot:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot qemu:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu] PostProcessors:map[shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local docker-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import artifice:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice docker-save:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save docker-push:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push vagrant-cloud:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud vsphere:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere amazon-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import compress:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress docker-tag:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag atlas:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas vagrant:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant] Provisioners:map[powershell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell ansible:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible windows-shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell ansible-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local chef-solo:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo windows-restart:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart chef-client:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client puppet-server:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file puppet-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless salt-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell]}
2016/09/09 12:03:43 Setting cache directory: /opt/packer/packer_cache
2016/09/09 12:03:43 Loading builder: vmware-vmx
2016/09/09 12:03:43 Plugin could not be found. Checking same directory as executable.
2016/09/09 12:03:43 Current exe path: /opt/packer/packer
2016/09/09 12:03:43 Creating plugin client for path: /opt/packer/packer
2016/09/09 12:03:43 Starting plugin: /opt/packer/packer []string{"/opt/packer/packer", "plugin", "packer-builder-vmware-vmx"}
2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 Waiting for RPC address for: /opt/packer/packer
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 [INFO] Packer version: 0.10.1
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Packer Target OS/Arch: linux amd64
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Built with Go Version: go1.6.2
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-instance
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for null
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for parallels-pvm
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for virtualbox-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for virtualbox-ovf
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vmware-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-chroot
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for azure-arm
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-ebs
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for parallels-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vmware-vmx
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for openstack
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for qemu
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for digitalocean
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for googlecompute
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for ansible-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for salt-masterless
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for windows-restart
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for windows-shell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for puppet-server
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for ansible
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for chef-client
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for chef-solo
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for powershell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for puppet-masterless
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vagrant
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vagrant-cloud
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-import
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for atlas
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-push
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-tag
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vsphere
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for artifice
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for compress
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-import
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-save
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Attempting to open config file: /home/pveljano/.packerconfig
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 [WARN] Config file doesn't exist: /home/pveljano/.packerconfig
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[amazon-ebs:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs parallels-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso qemu:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu amazon-instance:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance virtualbox-ovf:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf azure-arm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file docker:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker virtualbox-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso amazon-chroot:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot openstack:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack googlecompute:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute null:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null parallels-pvm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm vmware-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso vmware-vmx:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx digitalocean:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean] PostProcessors:map[vagrant-cloud:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud amazon-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-push:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push docker-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import docker-save:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local vagrant:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant atlas:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas docker-tag:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag vsphere:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere artifice:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice compress:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress] Provisioners:map[shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local windows-restart:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart ansible:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file puppet-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless salt-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless windows-shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell puppet-server:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell chef-client:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client chef-solo:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo powershell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell ansible-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local]}
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Setting cache directory: /opt/packer/packer_cache
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 args: []string{"packer-builder-vmware-vmx"}
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin minimum port: 10000
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin maximum port: 25000
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin address: unix /tmp/packer-plugin152702333
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Waiting for connection...
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Serving a plugin connection...
2016/09/09 12:03:43 Loading post-processor: vsphere
2016/09/09 12:03:43 Plugin could not be found. Checking same directory as executable.
2016/09/09 12:03:43 Current exe path: /opt/packer/packer
2016/09/09 12:03:43 Creating plugin client for path: /opt/packer/packer
2016/09/09 12:03:43 Starting plugin: /opt/packer/packer []string{"/opt/packer/packer", "plugin", "packer-post-processor-vsphere"}
2016/09/09 12:03:43 Waiting for RPC address for: /opt/packer/packer
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 [INFO] Packer version: 0.10.1
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Packer Target OS/Arch: linux amd64
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Built with Go Version: go1.6.2
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for azure-arm
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for digitalocean
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-ebs
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for null
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for openstack
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for qemu
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for virtualbox-ovf
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vmware-vmx
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-chroot
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-instance
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for parallels-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vmware-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for googlecompute
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for parallels-pvm
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for virtualbox-iso
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for chef-solo
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for file
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for salt-masterless
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for windows-restart
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for chef-client
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for ansible-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for powershell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for puppet-masterless
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for puppet-server
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for windows-shell
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for ansible
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for amazon-import
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-save
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for shell-local
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vagrant-cloud
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-push
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-tag
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vagrant
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for vsphere
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for artifice
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for atlas
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for compress
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Using internal plugin for docker-import
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Attempting to open config file: /home/pveljano/.packerconfig
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 [WARN] Config file doesn't exist: /home/pveljano/.packerconfig
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Packer config: &{DisableCheckpoint:false DisableCheckpointSignature:false PluginMinPort:10000 PluginMaxPort:25000 Builders:map[null:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-null parallels-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-iso vmware-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-iso file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-file googlecompute:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-googlecompute azure-arm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-azure-arm digitalocean:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-digitalocean openstack:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-openstack virtualbox-ovf:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-ovf amazon-chroot:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-chroot virtualbox-iso:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-virtualbox-iso docker:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-docker parallels-pvm:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-parallels-pvm amazon-ebs:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-ebs qemu:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-qemu vmware-vmx:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-vmware-vmx amazon-instance:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-builder-amazon-instance] PostProcessors:map[vagrant-cloud:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant-cloud docker-push:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-push vsphere:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vsphere compress:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-compress artifice:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-artifice atlas:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-atlas docker-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-import amazon-import:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-amazon-import docker-save:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-save shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-shell-local docker-tag:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-docker-tag vagrant:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-post-processor-vagrant] Provisioners:map[windows-restart:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-restart chef-client:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-client puppet-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-masterless puppet-server:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-puppet-server chef-solo:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-chef-solo file:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-file shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell powershell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-powershell windows-shell:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-windows-shell ansible:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible salt-masterless:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-salt-masterless shell-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-shell-local ansible-local:/opt/packer/packer-PACKERSPACE-plugin-PACKERSPACE-packer-provisioner-ansible-local]}
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Setting cache directory: /opt/packer/packer_cache
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 args: []string{"packer-post-processor-vsphere"}
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin minimum port: 10000
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin maximum port: 25000
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected home directory from env var: /home/pveljano
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Plugin address: unix /tmp/packer-plugin505344231
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Waiting for connection...
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Serving a plugin connection...
Debug mode enabled. Builds will not be parallelized.
vmware-vmx output will be in this color.

2016/09/09 12:03:43 ui: Debug mode enabled. Builds will not be parallelized.
2016/09/09 12:03:43 ui: vmware-vmx output will be in this color.
2016/09/09 12:03:43 ui: 
2016/09/09 12:03:43 Build debug mode: true
2016/09/09 12:03:43 Force build: false
2016/09/09 12:03:43 Preparing build: vmware-vmx
2016/09/09 12:03:43 Debug enabled, so waiting for build to finish: vmware-vmx
2016/09/09 12:03:43 Starting build run: vmware-vmx
2016/09/09 12:03:43 Running builder: vmware-vmx
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 VMware app path: /usr/bin/vmware
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 vmrun path: /usr/bin/vmrun
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 vdisk-manager path: /usr/bin/vmware-vdiskmanager
2016/09/09 12:03:43 packer: 2016/09/09 12:03:43 Detected VMware WS version: 12
2016/09/09 12:03:43 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepPrepareTools'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepPrepareTools'. Press enter to continue. 
2016/09/09 12:03:47 ui: scan err: unexpected newline
2016/09/09 12:03:47 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepOutputDir'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepOutputDir'. Press enter to continue. 
2016/09/09 12:03:49 ui: scan err: unexpected newline
2016/09/09 12:03:49 packer: 2016/09/09 12:03:49 No floppy files specified. Floppy disk will not be made.
2016/09/09 12:03:49 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepCreateFloppy'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepCreateFloppy'. Press enter to continue. 
2016/09/09 12:03:50 ui: scan err: unexpected newline
2016/09/09 12:03:50 ui: ==> vmware-vmx: Cloning source VM...
==> vmware-vmx: Cloning source VM...
2016/09/09 12:03:50 packer: 2016/09/09 12:03:50 Cloning from: /opt/packer/output-vmware-iso.1/windows2012r2-bt-1473334055.vmx
2016/09/09 12:03:50 packer: 2016/09/09 12:03:50 Cloning to: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:03:50 packer: 2016/09/09 12:03:50 Executing: /usr/bin/vmrun [-T ws clone /opt/packer/output-vmware-iso.1/windows2012r2-bt-1473334055.vmx output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx full]
2016/09/09 12:08:12 packer: 2016/09/09 12:08:12 stdout:
2016/09/09 12:08:12 packer: 2016/09/09 12:08:12 stderr:
2016/09/09 12:08:12 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepCloneVMX'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepCloneVMX'. Press enter to continue. 
2016/09/09 12:08:29 ui: scan err: unexpected newline
2016/09/09 12:08:29 packer: 2016/09/09 12:08:29 Writing VMX to: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:08:29 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepConfigureVMX'. Press enter to continue. 
2016/09/09 12:08:32 ui: scan err: unexpected newline
2016/09/09 12:08:32 packer: 2016/09/09 12:08:32 Suppressing messages in VMX
2016/09/09 12:08:32 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepSuppressMessages'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepSuppressMessages'. Press enter to continue. 
2016/09/09 12:08:33 ui: scan err: unexpected newline
2016/09/09 12:08:33 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepHTTPServer'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepHTTPServer'. Press enter to continue. 
2016/09/09 12:08:34 ui: scan err: unexpected newline
2016/09/09 12:08:34 packer: 2016/09/09 12:08:34 Looking for available port between 5900 and 6000
2016/09/09 12:08:34 packer: 2016/09/09 12:08:34 Trying port: 5985
2016/09/09 12:08:34 packer: 2016/09/09 12:08:34 Found available VNC port: 5985
2016/09/09 12:08:34 packer: 2016/09/09 12:08:34 Writing VMX to: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:08:34 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepConfigureVNC'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepConfigureVNC'. Press enter to continue. 
2016/09/09 12:08:36 ui: scan err: unexpected newline
2016/09/09 12:08:36 ui: ==> vmware-vmx: Starting virtual machine...
==> vmware-vmx: Starting virtual machine...
2016/09/09 12:08:36 packer: 2016/09/09 12:08:36 Executing: /usr/bin/vmrun [-T ws start output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx gui]
2016/09/09 12:08:40 packer: 2016/09/09 12:08:40 stdout:
2016/09/09 12:08:40 packer: 2016/09/09 12:08:40 stderr:
2016/09/09 12:08:40 ui: ==> vmware-vmx: Waiting 1m0s for boot...
==> vmware-vmx: Waiting 1m0s for boot...
2016/09/09 12:09:40 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepRun'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepRun'. Press enter to continue. 
2016/09/09 12:09:50 ui: scan err: unexpected newline
2016/09/09 12:09:50 ui: ==> vmware-vmx: Connecting to VM via VNC
==> vmware-vmx: Connecting to VM via VNC
2016/09/09 12:09:50 packer: 2016/09/09 12:09:50 Connected to VNC desktop: Clone of windows2012r2-bt-1473334055
2016/09/09 12:09:50 packer: 2016/09/09 12:09:50 Host IP for the VMware machine: 172.16.128.1
2016/09/09 12:09:50 ui: ==> vmware-vmx: Typing the boot command over VNC...
==> vmware-vmx: Typing the boot command over VNC...
2016/09/09 12:09:50 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepTypeBootCommand'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepTypeBootCommand'. Press enter to continue. 
2016/09/09 12:09:51 ui: scan err: unexpected newline
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 [INFO] Waiting for SSH, up to timeout: 5m0s
2016/09/09 12:09:51 ui: ==> vmware-vmx: Waiting for SSH to become available...
==> vmware-vmx: Waiting for SSH to become available...
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 Lookup up IP information...
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 DHCP leases path: /etc/vmware/vmnet8/dhcpd/dhcpd.leases
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 Detected IP: 172.16.128.139
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 [INFO] Attempting SSH connection...
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 reconnecting to TCP connection for SSH
2016/09/09 12:09:51 packer: 2016/09/09 12:09:51 handshaking with SSH
2016/09/09 12:09:52 packer: 2016/09/09 12:09:52 handshake complete!
2016/09/09 12:09:52 packer: 2016/09/09 12:09:52 opening new ssh session
2016/09/09 12:09:52 packer: 2016/09/09 12:09:52 [INFO] agent forwarding enabled
==> vmware-vmx: Connected to SSH!
2016/09/09 12:09:52 ui: ==> vmware-vmx: Connected to SSH!
2016/09/09 12:09:52 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepConnect'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepConnect'. Press enter to continue. 
2016/09/09 12:09:56 ui: scan err: unexpected newline
2016/09/09 12:09:56 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepUploadTools'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepUploadTools'. Press enter to continue. 
2016/09/09 12:09:59 ui: scan err: unexpected newline
2016/09/09 12:09:59 packer: 2016/09/09 12:09:59 Running the provision hook
2016/09/09 12:09:59 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepProvision'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepProvision'. Press enter to continue. 
2016/09/09 12:10:03 ui: scan err: unexpected newline
2016/09/09 12:10:03 ui: ==> vmware-vmx: Gracefully halting virtual machine...
==> vmware-vmx: Gracefully halting virtual machine...
2016/09/09 12:10:03 packer: 2016/09/09 12:10:03 Executing shutdown command: shutdown /s /t 10 /f /d p:4:1 /c "Packer Shutdown"
2016/09/09 12:10:03 packer: 2016/09/09 12:10:03 opening new ssh session
2016/09/09 12:10:03 packer: 2016/09/09 12:10:03 starting remote command: shutdown /s /t 10 /f /d p:4:1 /c "Packer Shutdown"
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 remote command exited with '0': shutdown /s /t 10 /f /d p:4:1 /c "Packer Shutdown"
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 Shutdown stdout:
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 Shutdown stderr:
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 Waiting max 5m0s for shutdown to complete
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 stdout: Total running VMs: 1
2016/09/09 12:10:04 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 stderr:
2016/09/09 12:10:04 packer: 2016/09/09 12:10:04 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:05 packer: 2016/09/09 12:10:05 stdout: Total running VMs: 1
2016/09/09 12:10:05 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:05 packer: 2016/09/09 12:10:05 stderr:
2016/09/09 12:10:05 packer: 2016/09/09 12:10:05 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:06 packer: 2016/09/09 12:10:06 stdout: Total running VMs: 1
2016/09/09 12:10:06 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:06 packer: 2016/09/09 12:10:06 stderr:
2016/09/09 12:10:06 packer: 2016/09/09 12:10:06 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:06 packer: 2016/09/09 12:10:06 stdout: Total running VMs: 1
2016/09/09 12:10:06 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:06 packer: 2016/09/09 12:10:06 stderr:
2016/09/09 12:10:07 packer: 2016/09/09 12:10:07 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:07 packer: 2016/09/09 12:10:07 stdout: Total running VMs: 1
2016/09/09 12:10:07 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:07 packer: 2016/09/09 12:10:07 stderr:
2016/09/09 12:10:07 packer: 2016/09/09 12:10:07 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:08 packer: 2016/09/09 12:10:08 stdout: Total running VMs: 1
2016/09/09 12:10:08 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:08 packer: 2016/09/09 12:10:08 stderr:
2016/09/09 12:10:08 packer: 2016/09/09 12:10:08 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 stdout: Total running VMs: 1
2016/09/09 12:10:09 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 stderr:
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 stdout: Total running VMs: 1
2016/09/09 12:10:09 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 stderr:
2016/09/09 12:10:09 packer: 2016/09/09 12:10:09 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:10 packer: 2016/09/09 12:10:10 stdout: Total running VMs: 1
2016/09/09 12:10:10 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:10 packer: 2016/09/09 12:10:10 stderr:
2016/09/09 12:10:10 packer: 2016/09/09 12:10:10 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:11 packer: 2016/09/09 12:10:11 stdout: Total running VMs: 1
2016/09/09 12:10:11 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:11 packer: 2016/09/09 12:10:11 stderr:
2016/09/09 12:10:11 packer: 2016/09/09 12:10:11 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:11 packer: 2016/09/09 12:10:11 stdout: Total running VMs: 1
2016/09/09 12:10:11 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:11 packer: 2016/09/09 12:10:11 stderr:
2016/09/09 12:10:12 packer: 2016/09/09 12:10:12 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:12 packer: 2016/09/09 12:10:12 stdout: Total running VMs: 1
2016/09/09 12:10:12 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:12 packer: 2016/09/09 12:10:12 stderr:
2016/09/09 12:10:12 packer: 2016/09/09 12:10:12 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:13 packer: 2016/09/09 12:10:13 stdout: Total running VMs: 1
2016/09/09 12:10:13 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:13 packer: 2016/09/09 12:10:13 stderr:
2016/09/09 12:10:13 packer: 2016/09/09 12:10:13 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 stdout: Total running VMs: 1
2016/09/09 12:10:14 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 stderr:
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 stdout: Total running VMs: 1
2016/09/09 12:10:14 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 stderr:
2016/09/09 12:10:14 packer: 2016/09/09 12:10:14 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:15 packer: 2016/09/09 12:10:15 stdout: Total running VMs: 1
2016/09/09 12:10:15 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:15 packer: 2016/09/09 12:10:15 stderr:
2016/09/09 12:10:15 packer: 2016/09/09 12:10:15 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:16 packer: 2016/09/09 12:10:16 stdout: Total running VMs: 1
2016/09/09 12:10:16 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:16 packer: 2016/09/09 12:10:16 stderr:
2016/09/09 12:10:16 packer: 2016/09/09 12:10:16 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:16 packer: 2016/09/09 12:10:16 stdout: Total running VMs: 1
2016/09/09 12:10:16 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:16 packer: 2016/09/09 12:10:16 stderr:
2016/09/09 12:10:17 packer: 2016/09/09 12:10:17 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:17 packer: 2016/09/09 12:10:17 stdout: Total running VMs: 1
2016/09/09 12:10:17 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:17 packer: 2016/09/09 12:10:17 stderr:
2016/09/09 12:10:17 packer: 2016/09/09 12:10:17 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:18 packer: 2016/09/09 12:10:18 stdout: Total running VMs: 1
2016/09/09 12:10:18 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:18 packer: 2016/09/09 12:10:18 stderr:
2016/09/09 12:10:18 packer: 2016/09/09 12:10:18 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:18 packer: 2016/09/09 12:10:18 stdout: Total running VMs: 1
2016/09/09 12:10:18 packer: /opt/packer/output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:18 packer: 2016/09/09 12:10:18 stderr:
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 stdout: Total running VMs: 0
    vmware-vmx: Waiting for VMware to clean up after itself...
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 stderr:
2016/09/09 12:10:19 ui:     vmware-vmx: Waiting for VMware to clean up after itself...
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 Waiting on lock files: []string{"output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx.lck/M55288.lck"}
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 Waiting on lock files: []string{"output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx.lck/M55288.lck"}
2016/09/09 12:10:19 packer: 2016/09/09 12:10:19 No more lock files found. VMware is clean.
2016/09/09 12:10:24 packer: 2016/09/09 12:10:24 VM shut down.
2016/09/09 12:10:24 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepShutdown'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepShutdown'. Press enter to continue. 
2016/09/09 12:10:27 ui: scan err: unexpected newline
2016/09/09 12:10:27 ui: ==> vmware-vmx: Deleting unnecessary VMware files...
==> vmware-vmx: Deleting unnecessary VMware files...
2016/09/09 12:10:27 ui:     vmware-vmx: Deleting: output-vmware-vmx/vmware.log
    vmware-vmx: Deleting: output-vmware-vmx/vmware.log
2016/09/09 12:10:27 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepCleanFiles'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepCleanFiles'. Press enter to continue. 
2016/09/09 12:10:40 ui: scan err: unexpected newline
2016/09/09 12:10:40 packer: 2016/09/09 12:10:40 Skipping disk compaction step...
2016/09/09 12:10:40 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepCompactDisk'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepCompactDisk'. Press enter to continue. 
2016/09/09 12:10:43 ui: scan err: unexpected newline
2016/09/09 12:10:43 packer: 2016/09/09 12:10:43 Writing VMX to: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:43 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepConfigureVMX'. Press enter to continue. 
2016/09/09 12:10:45 ui: scan err: unexpected newline
2016/09/09 12:10:45 ui: ==> vmware-vmx: Cleaning VMX prior to finishing up...
==> vmware-vmx: Cleaning VMX prior to finishing up...
2016/09/09 12:10:45 ui:     vmware-vmx: Unmounting floppy from VMX...
    vmware-vmx: Unmounting floppy from VMX...
2016/09/09 12:10:45 packer: 2016/09/09 12:10:45 Deleting key: floppy0.present
2016/09/09 12:10:45 ui:     vmware-vmx: Disabling VNC server...
    vmware-vmx: Disabling VNC server...
2016/09/09 12:10:45 packer: 2016/09/09 12:10:45 Writing VMX to: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
2016/09/09 12:10:45 ui: ask: ==> vmware-vmx: Pausing after run of step 'StepCleanVMX'. Press enter to continue.
==> vmware-vmx: Pausing after run of step 'StepCleanVMX'. Press enter to continue. 
2016/09/09 12:10:48 ui: scan err: unexpected newline
2016/09/09 12:10:48 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepCleanVMX'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepCleanVMX'. Press enter to continue. 
2016/09/09 12:10:49 ui: scan err: unexpected newline
2016/09/09 12:10:49 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVMX'. Press enter to continue. 
2016/09/09 12:10:51 ui: scan err: unexpected newline
2016/09/09 12:10:51 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepCompactDisk'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepCompactDisk'. Press enter to continue. 
2016/09/09 12:10:53 ui: scan err: unexpected newline
2016/09/09 12:10:53 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepCleanFiles'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepCleanFiles'. Press enter to continue. 
2016/09/09 12:10:59 ui: scan err: unexpected newline
2016/09/09 12:10:59 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepShutdown'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepShutdown'. Press enter to continue. 
2016/09/09 12:11:02 ui: scan err: unexpected newline
2016/09/09 12:11:02 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepProvision'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepProvision'. Press enter to continue. 
2016/09/09 12:11:06 ui: scan err: unexpected newline
2016/09/09 12:11:06 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepUploadTools'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepUploadTools'. Press enter to continue. 
2016/09/09 12:11:07 ui: scan err: unexpected newline
2016/09/09 12:11:07 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepConnect'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepConnect'. Press enter to continue. 
2016/09/09 12:11:09 ui: scan err: unexpected newline
2016/09/09 12:11:09 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepTypeBootCommand'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepTypeBootCommand'. Press enter to continue. 
2016/09/09 12:11:12 ui: scan err: unexpected newline
2016/09/09 12:11:12 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepRun'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepRun'. Press enter to continue. 
2016/09/09 12:11:15 ui: scan err: unexpected newline
2016/09/09 12:11:15 packer: 2016/09/09 12:11:15 Executing: /usr/bin/vmrun [-T ws list]
2016/09/09 12:11:15 packer: 2016/09/09 12:11:15 stdout: Total running VMs: 0
2016/09/09 12:11:15 packer: 2016/09/09 12:11:15 stderr:
2016/09/09 12:11:15 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVNC'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVNC'. Press enter to continue. 
2016/09/09 12:11:20 ui: scan err: unexpected newline
2016/09/09 12:11:20 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepHTTPServer'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepHTTPServer'. Press enter to continue. 
2016/09/09 12:11:21 ui: scan err: unexpected newline
2016/09/09 12:11:21 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepSuppressMessages'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepSuppressMessages'. Press enter to continue. 
2016/09/09 12:11:26 ui: scan err: unexpected newline
2016/09/09 12:11:26 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVMX'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepConfigureVMX'. Press enter to continue. 
2016/09/09 12:11:27 ui: scan err: unexpected newline
2016/09/09 12:11:27 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepCloneVMX'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepCloneVMX'. Press enter to continue. 
2016/09/09 12:11:31 ui: scan err: unexpected newline
2016/09/09 12:11:31 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepCreateFloppy'. Press enter to continue. 
2016/09/09 12:11:32 ui: scan err: unexpected newline
2016/09/09 12:11:32 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepOutputDir'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepOutputDir'. Press enter to continue. 
2016/09/09 12:11:33 ui: scan err: unexpected newline
2016/09/09 12:11:33 ui: ask: ==> vmware-vmx: Pausing before cleanup of step 'StepPrepareTools'. Press enter to continue.
==> vmware-vmx: Pausing before cleanup of step 'StepPrepareTools'. Press enter to continue. 
2016/09/09 12:11:34 ui: scan err: unexpected newline
2016/09/09 12:11:34 ui: ==> vmware-vmx: Running post-processor: vsphere
==> vmware-vmx: Running post-processor: vsphere
2016/09/09 12:11:34 ui:     vmware-vmx (vsphere): Uploading output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx to vSphere
    vmware-vmx (vsphere): Uploading output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx to vSphere
2016/09/09 12:11:34 ui:     vmware-vmx (vsphere): Uploading output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx to vSphere
    vmware-vmx (vsphere): Uploading output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx to vSphere
2016/09/09 12:11:34 packer: 2016/09/09 12:11:34 Starting ovftool with parameters: --noSSLVerify=true --acceptAllEulas --name="windows2012r2-vanilla-1473415423" --datastore="MyDatasotre" --diskMode="thin" --network="Infrastructure Services" --vmFolder="" output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
2016/09/09 12:11:36 Deleting original artifact for build 'vmware-vmx'
2016/09/09 12:11:36 ui error: Build 'vmware-vmx' errored: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
Opening OVF target: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
Writing OVF package: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"/"windows2012r2-vanilla-1473415423"/"windows2012r2-vanilla-1473415423".ovf
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors

2016/09/09 12:11:36 Waiting on builds to complete...
2016/09/09 12:11:36 Builds completed. Waiting on interrupt barrier...
2016/09/09 12:11:36 machine readable: error-count []string{"1"}
2016/09/09 12:11:36 ui error: 
==> Some builds didn't complete successfully and had errors:
2016/09/09 12:11:36 machine readable: vmware-vmx,error []string{"1 error(s) occurred:\n\n* Post-processor failed: Failed: exit status 1\nStdout: Opening VMX source: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx\nOpening OVF target: \"vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster\"\nWriting OVF package: \"vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster\"/\"windows2012r2-vanilla-1473415423\"/\"windows2012r2-vanilla-1473415423\".ovf\n\rTransfer Failed                       \nError: System error: (std::exception)\nDeleting directory tree below: \"vi:\nCompleted with errors\n"}
2016/09/09 12:11:36 ui error: --> vmware-vmx: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
Opening OVF target: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
Writing OVF package: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"/"windows2012r2-vanilla-1473415423"/"windows2012r2-vanilla-1473415423".ovf
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors
2016/09/09 12:11:36 ui: 
==> Builds finished but no artifacts were created.
Build 'vmware-vmx' errored: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
Opening OVF target: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
Writing OVF package: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"/"windows2012r2-vanilla-1473415423"/"windows2012r2-vanilla-1473415423".ovf
2016/09/09 12:11:36 waiting for all plugin processes to complete...
2016/09/09 12:11:36 /opt/packer/packer: plugin process exited
2016/09/09 12:11:36 /opt/packer/packer: plugin process exited
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors


==> Some builds didn't complete successfully and had errors:
--> vmware-vmx: 1 error(s) occurred:

* Post-processor failed: Failed: exit status 1
Stdout: Opening VMX source: output-vmware-vmx/windows2012r2-vanilla-1473415423.vmx
Opening OVF target: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"
Writing OVF package: "vi://<credentials-go-here>@vcenter.somecompany.net/MyDatacenter/host/MyCluster"/"windows2012r2-vanilla-1473415423"/"windows2012r2-vanilla-1473415423".ovf
Transfer Failed                       
Error: System error: (std::exception)
Deleting directory tree below: "vi:
Completed with errors


==> Builds finished but no artifacts were created.


```

### PR DESCRIPTION
**Pull request by dpolitis**
Fix recurring bug #3878, make destination ESXi host selectable in config, more informative error output.

- This commit makes the destination ESXi Host selectable in configuration json, via the "esxi_host"
parameter (optional), which can be an ipv4 address or the dns name of the esxi host to register the VM.

- Also when failing, the post-processor prints out the error output of the ovftool, so debugging can be easier.

- Closes #3878

### CODE REVIEW

File: post-processor/vsphere/post-processor.go [hunk 1]
```diff
@@ -58,13 +71,17 @@ func (p *PostProcessor) Configure(raws ...interface{}) error {
 
 	// Defaults
 	if p.config.DiskMode == "" {
-		p.config.DiskMode = "thick"
+		p.config.DiskMode = "thin"
```
Comment (mwhooker) [inline post-processor/vsphere/post-processor.go]: what's the effect of this change?

File: post-processor/vsphere/post-processor.go [hunk 2]
```diff
@@ -122,6 +139,14 @@ func (p *PostProcessor) PostProcess(ui packer.Ui, artifact packer.Artifact) (pac
 		ovftool_uri += "/Resources/" + p.config.ResourcePool
 	}
 
+	if p.config.ESXiHost != "" {
```
Comment (mwhooker) [inline post-processor/vsphere/post-processor.go]: I would prefer not to see regexes here. Can we add a flag to manually specify dns host or ip host?

File: post-processor/vsphere/post-processor.go [hunk 3]
```diff
@@ -135,11 +160,15 @@ func (p *PostProcessor) PostProcess(ui packer.Ui, artifact packer.Artifact) (pac
...
 			"<password>",
 			-1))
-	cmd := exec.Command("ovftool", args...)
-	cmd.Stdout = os.Stdout
-	cmd.Stderr = os.Stderr
+
+	var out bytes.Buffer
+	cmd := exec.Command(ovftool, args...)
+	cmd.Stdout = &out
+	cmd.Stderr = &out
```
Comment (mwhooker) [inline post-processor/vsphere/post-processor.go]: Is there a reason to not forward ovftool output to stderr/out? I see you're capturing stderr below, but I would like to see these tee'd out to the os descriptors.

It's also possible `out` will contain junk, since it's being written to simultaneously by two outputs.

something like

```go
var errOut bytes.Buffer
cmd := exec.Command("ovftool", args...)
errWriter = io.MultiWriter(os.StdErr, errOut)
cmd.Stdout = os.Stdout
cmd.Stderr = errWriter
```

File: post-processor/vsphere/post-processor.go (hunk 1 above)
Comment (dpolitis) [reply post-processor/vsphere/post-processor.go]: Thank you for your prompt response. This change is useful for example, when building VMs in remote nested esxi host with limited storage capabilities. By marking the disk type as thin, we force the use of a sparse rather a raw disk image. It can be handy sometimes.

File: post-processor/vsphere/post-processor.go (hunk 3 above)
Comment (dpolitis) [reply post-processor/vsphere/post-processor.go]: The previous behavior did not put ovftool errors on stderr. It was very difficult to pinpoint the cause of failure. I think your edit is much of improvement. "ovftool" though should be ovftool (without quotes) for the patch to work. I agree with you.

File: post-processor/vsphere/post-processor.go (hunk 1 above)
Comment (mwhooker) [reply post-processor/vsphere/post-processor.go]: Do you think that change belongs in this patch? Is "thin" a reasonable default?

Comment (dpolitis) [reply post-processor/vsphere/post-processor.go]: I think this change, as not belonging to this patch (my bad) but I consider it as a reasonable default for three reasons:
- time, a raw image would take longer to build, can be cloned faster.
- space, thin takes less space than raw.
- flexibility, it can be transformed to raw, while deploying new vm from that template for example.

**Comment by SwampDragons** [comment]
@mwhooker @dpolitis what's the status on this? Is there still interest in getting it merged? If so, do either of you need anything from me to get it across the finish line?

**Comment by dpolitis** [comment]
I have been using the above patch for quite a while and seems quite stable. Can you inform me about what changes are finally required, because from the conversation timeline I can't figure out, if reviewer agreed with my suggestions on using "thin" instead of "thick" and on the use of regular expressions.

**Comment by azr** [comment]
In the meantime, I see a conflicting file.
It might be worth rebasing the pr to avoid another back and forth 🙂

File: post-processor/vsphere/post-processor.go (hunk 1 above)
Comment (SwampDragons) [reply post-processor/vsphere/post-processor.go]: I'd like to keep the default the same.

File: post-processor/vsphere/post-processor.go (hunk 2 above)
Comment (SwampDragons) [reply post-processor/vsphere/post-processor.go]: I think I'm okay with regexes as long as you add a comment to the regexes giving an example of the kind of string they're supposed to match

File: post-processor/vsphere/post-processor.go (hunk 3 above)
Comment (SwampDragons) [reply post-processor/vsphere/post-processor.go]: I like hooker's example above.

**Comment by SwampDragons** [comment]
Sorry for the delay here -- I've just made some clarifying comments for you containing the things I'd like to see changed.

**Comment by SwampDragons** [comment]
This looks great! All that's missing is some documentation in https://github.com/hashicorp/packer/blob/master/website/source/docs/post-processors/vsphere.html.md

**Comment by dpolitis** [comment]
Added documentation for new optional setting "esxi_host" in https://github.com/hashicorp/packer/blob/master/website/source/docs/post-processors/vsphere.html.md. Hope it's ok.
