### PR TITLE
Hashicorp/packer#9924

### LINKED ISSUE #9924: vsphere-iso does nothing useful when communicator is none
#### Overview of the Issue

I’m using vsphere-iso to build a VM template behind a firewall. There are no provisioners to need WinRM, SSH, nor to test either. Neither will be opened from the firewall’s external interface. The script(s) inserted via floppy-attachment do everything necessary.

#### Reproduction Steps

Set the `communicator` to `none` and build a VM on a VLAN that the packer host cannot reach.

### Packer version

Packer v1.6.2

### Simplified Packer Buildfile

<details>
 <summary>Buildfile</summary>
 
 ```
 {
  "variables": {
    "vsphere_server": "",
    "vsphere_user": "",
    "vsphere_password": "",
    "vsphere_folder": "",
    "vsphere_dc_name": "",
    "vsphere_compute_cluster": "",
    "vsphere_host": "",
    "vsphere_datastore": "",
    "winadmin_password": "",
    "cpu_num": "",
    "mem_size": "",
    "disk_size": "",
    "vmtools_iso_path":"",
    "os_iso_path": "",
    "vsphere_template_name": "",
    "vsphere_portgroup_name": "",
    "vm_notes": "{\n  'Timestamp': '{{isotime \"2006-01-02T03:04:05\"}}',\n  'Packed from': '{{user `os_iso_path`}}'\n}"
  },
  
  "sensitive-variables": ["vsphere_password", "winadmin_password"],
  
  "builders": [
    {
      "type": "vsphere-iso",
      
      "convert_to_template": false,
      
      "floppy_files": [
        "./01-packer/setup/",
        "./scripts/vmtools.cmd"
      ],
      "floppy_dirs": [
        "./01-packer/drivers"
      ],
      
      "vcenter_server":      "{{user `vsphere_server`}}",
      "username":            "{{user `vsphere_user`}}",
      "password":            "{{user `vsphere_password`}}",
      "insecure_connection": "true",
      "datacenter": "{{user `vsphere_dc_name`}}",
      
      "CPUs": "{{user `cpu_num`}}",
      "RAM": "{{user `mem_size`}}",
      "RAM_hot_plug": true,
      "NestedHV": false,
      "firmware": "bios",
      
      "vm_name": "{{user `vsphere_template_name`}}",
      "folder" : "{{user `vsphere_folder`}}",
      "cluster":     "{{user `vsphere_compute_cluster`}}",
      "host": "{{user `vsphere_host`}}",
      "datastore": "{{user `vsphere_datastore`}}",
      
      "iso_paths": [
        "{{user `os_iso_path`}}",
        "{{user `vmtools_iso_path`}}"
      ],
      
      "guest_os_type": "windows9Server64Guest",
      "disk_controller_type":  "lsilogic-sas",
      "storage": [
        {
          "disk_size": "{{user `disk_size`}}",
          "disk_thin_provisioned": true
        }
      ],
      "network_adapters": [
        {
          "network_card": "vmxnet3",
          "network": "{{user `vsphere_portgroup_name`}}"
        }
      ],
      "notes": "{{user `vm_notes`}}",
      
      "communicator": "none"
    }
  ]
}
```
</details>

### Operating system and Environment details

Ubuntu 18.04.5 LTS x86_64
Packer v1.6.2
vSphere 6.7

### Log Fragments and crash.log files

<details>
 <summary>With WinRM and no provisioners</summary>
 
 ```
 $ time packer build -var-file=./01-packer/private.json -var-file=./01-packer/dev.json ./01-packer/W2019DCE.json
vsphere-iso: output will be in this color.

==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Adding configuration parameters...
==> vsphere-iso: Creating floppy disk...
    vsphere-iso: Copying files flatly from floppy_files
    vsphere-iso: Copying directory: ./01-packer/setup/
    vsphere-iso: Adding file: 01-packer/setup/autounattend.xml
    vsphere-iso: Adding file: 01-packer/setup/setup.ps1
    vsphere-iso: Copying file: ./scripts/vmtools.cmd
    vsphere-iso: Done copying files from floppy_files
    vsphere-iso: Collecting paths from floppy_dirs
    vsphere-iso: Resulting paths from floppy_dirs : [./01-packer/drivers]
    vsphere-iso: Recursively copying : ./01-packer/drivers
    vsphere-iso: Done copying paths from floppy_dirs
==> vsphere-iso: Uploading created floppy image
==> vsphere-iso: Adding generated Floppy...
==> vsphere-iso: Set boot order temporary...
==> vsphere-iso: Power on VM...
==> vsphere-iso: Waiting for IP...
==> vsphere-iso: IP address: 192.168.0.2
==> vsphere-iso: Using winrm communicator to connect: 192.168.0.2
==> vsphere-iso: Waiting for WinRM to become available...
==> vsphere-iso: Timeout waiting for WinRM.
==> vsphere-iso: Clear boot order...
==> vsphere-iso: Power off VM...
==> vsphere-iso: Deleting Floppy image ...
==> vsphere-iso: Destroying VM...
Build 'vsphere-iso' errored after 37 minutes 17 seconds: Timeout waiting for WinRM.

==> Wait completed after 37 minutes 17 seconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso: Timeout waiting for WinRM.

==> Builds finished but no artifacts were created.

real    37m17.838s
user    0m1.851s
sys     0m2.178s
$
```
</details>
<details>
 <summary>With communicator set to none</summary>
 
 ```
 $ time packer build -force -var-file=./01-packer/private.json -var-file=./01-packer/dev.json ./01-packer/W2019DCE.json
vsphere-iso: output will be in this color.

==> vsphere-iso: the vm/template Templates/W2019DCE already exists, but deleting it due to -force flag
==> vsphere-iso: Creating VM...
==> vsphere-iso: Customizing hardware...
==> vsphere-iso: Mounting ISO images...
==> vsphere-iso: Adding configuration parameters...
==> vsphere-iso: Eject CD-ROM drives...
Build 'vsphere-iso' finished after 5 seconds 701 milliseconds.

==> Wait completed after 5 seconds 701 milliseconds

==> Builds finished. The artifacts of successful builds are:
--> vsphere-iso: W2019DCE

real    0m6.215s
user    0m0.390s
sys     0m0.109s
$
```
</details>

### Comments

@SwampDragons and @sylviamoss found the if statement causing this behavior. Thanks!
https://github.com/hashicorp/packer/blob/master/builder/vsphere/iso/builder.go#L80

I believe that most of that should be in the prior append and this if statement should be only steps pertaining to packer <--> guest communication.

### PR DESCRIPTION
**Pull request by netapp-jgriffit**
This addresses #9924 where the build with fail when the resulting VM and the Packer host is expected to not communicate and the `communicator` is configured as none to reflect that.

This is my first time contributing here and using Go so I wasn't really sure how to contribute to the automated testing. I did a few tests [here](https://github.com/hashicorp/packer/issues/9924#issuecomment-695059605).

Closes #9924

### CODE REVIEW

File: builder/vsphere/common/step_shutdown.go [hunk 1]
```diff
@@ -56,9 +57,22 @@ func (s *StepShutdown) Run(ctx context.Context, state multistep.StateBag) multis
 		return multistep.ActionContinue
 	}
 
-	if s.Config.DisableShutdown {
+	if state.Get("communicator") == nil {
+
+		ui.Say("The `communicator` is 'none', automatic shutdown disabled.")
+		if s.Config.Command != "" {
+			ui.Message("The parameter `shutdown_command` is ignored as it requires a `communicator`.")
+		}
```
Comment (sylviamoss) [inline builder/vsphere/common/step_shutdown.go:65]: I think this can go inside `ShutdownConfig.Prepare()`
You will have to change the method signature and return to receive the `Comm` config and return a warning. 
Example of how it will look like: 
```
func (c *ShutdownConfig) Prepare(comm communicator.Config) (warnings []string, errs []error) {
	if c.Timeout == 0 {
		c.Timeout = 5 * time.Minute
	}
	if comm.Type == "none" && c.Command != "" {
		warnings = append(warnings, "The parameter `shutdown_command` is ignored as it requires a `communicator`.")
	}
	return
}
```
And in builder/vsphere/iso/config.go you will update the  `ShutdownConfig.Prepare()` call to:
```
	shutdownWarnings, shutdownErrs := c.ShutdownConfig.Prepare(c.Comm)
	warnings = append(warnings, shutdownWarnings...)
	errs = packer.MultiErrorAppend(errs, shutdownErrs...)
```

File: builder/vsphere/common/step_shutdown.go [hunk 2]
```diff
@@ -56,9 +57,22 @@ func (s *StepShutdown) Run(ctx context.Context, state multistep.StateBag) multis
 		return multistep.ActionContinue
 	}
 
-	if s.Config.DisableShutdown {
+	if state.Get("communicator") == nil {
```
Comment (sylviamoss) [inline builder/vsphere/common/step_shutdown.go:60]:
```suggestion
	comm, _ := state.Get("communicator").(packer.Communicator)
	if comm == nil {
```

File: builder/vsphere/common/step_shutdown.go [hunk 3]
```diff
@@ -56,9 +57,22 @@ func (s *StepShutdown) Run(ctx context.Context, state multistep.StateBag) multis
...
+		}
+
+		msg := fmt.Sprintf("Please shutdown virtual machine within %s.", s.Config.Timeout)
+		ui.Message(msg)
+
+	} else if s.Config.DisableShutdown {
 		ui.Say("Automatic shutdown disabled. Please shutdown virtual machine.")
 	} else if s.Config.Command != "" {
+		// Communicator is not needed unless shutdown_command is populated
+		comm := state.Get("communicator").(packer.Communicator)
```
Comment (sylviamoss) [inline builder/vsphere/common/step_shutdown.go:74]:
```suggestion
```

File: builder/vsphere/common/step_shutdown.go (hunk 2 above)
Comment (sylviamoss) [reply builder/vsphere/common/step_shutdown.go:60]: I think is easier to read this way 🤔

File: builder/vsphere/common/step_shutdown.go [hunk 4]
```diff
@@ -16,16 +16,18 @@ import (
 )
 
 type ShutdownConfig struct {
-	// Specify a VM guest shutdown command. VMware guest tools are used by
-	// default.
+	// Specify a VM guest shutdown command. This command will be executed using
+	// the `communicator`. Otherwise the VMware guest tools are used to gracefully
+	// shutdown the VM guest.
```
Comment (sylviamoss) [inline builder/vsphere/common/step_shutdown.go:21]: This requires re-generating the docs with `go generate ./builder/vsphere/...`

File: builder/vsphere/common/step_shutdown.go [hunk 5]
```diff
@@ -16,16 +16,18 @@ import (
...
 	Command string `mapstructure:"shutdown_command"`
 	// Amount of time to wait for graceful VM shutdown.
 	// Defaults to 5m or five minutes.
+	// This will likely need to be modified if the `communicator` is 'none'.
 	Timeout time.Duration `mapstructure:"shutdown_timeout"`
 	// Packer normally halts the virtual machine after all provisioners have
 	// run when no `shutdown_command` is defined. If this is set to `true`, Packer
 	// *will not* halt the virtual machine but will assume that you will send the stop
-	// signal yourself through the preseed.cfg or your final provisioner.
+	// signal yourself through a script or the final provisioner.
```
Comment (sylviamoss) [inline builder/vsphere/common/step_shutdown.go:30]:
```suggestion
	// signal yourself through a preseed.cfg, a script or the final provisioner.
```
What do you think of keeping the pressed.cfg as one of the options?

**Review by sylviamoss — CHANGES_REQUESTED** [review]
I think this is looking good. I added some suggestions and requested some changes. 
The pipeline is failing because of missing generated documentation. 

please [sign the CLA](https://cla.hashicorp.com/hashicorp/packer?pullRequest= 9964) so that we can merge this when it's done 🙂

**Comment by sylviamoss** [comment]
Hello there! Any updates on this?

**Comment by netapp-jgriffit** [comment]
I did this then, saw the request to sign the CLA, discussed with my manager which directed me to legal, then went on vacation. I just returned and need to follow up with legal. My hands are tied at the moment.

**Comment by netapp-jgriffit** [comment]
I was approved to sign the CLA which I did today.

File: builder/vsphere/common/step_shutdown.go (hunk 1 above)
Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go:65]: I learned enough Golang to work on this issue so this is still pretty far out of my understanding.

For the `Prepare()` method it appears that this is receiving the communicator object as the parameter and then adding the the ability to handle warnings to the existing handling of errors.

The `return` line though was originally `return errs`. What is returning at this point? Is that defined by this?
```go
func (c *ShutdownConfig) Prepare() (warnings []string, errs []error) {
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Then assigned here? (to then be appended to the global vars)
```go
shutdownWarnings, shutdownErrs := c.ShutdownConfig.Prepare(c.Comm)
```

Mmmm... I think I understand the rest. At least conceptually. :smile:

Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go:65]: Ellipses tells a variable to iterate. Interesting.

Would the import statement still need the communicator? I believe the answer is yes.

Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go]:
```bash
user@vm1:~/go/src/github.com/hashicorp/packer$ go build -o bin/packer .# github.com/hashicorp/packer/builder/vsphere/clone
builder/vsphere/clone/config.go:73:63: not enough arguments in call to c.ShutdownConfig.Prepare
        have ()
        want (communicator.Config)
builder/vsphere/clone/config.go:73:63: multiple-value c.ShutdownConfig.Prepare() in single-value context
user@vm1:~/go/src/github.com/hashicorp/packer$
```

Need to update `builder/vsphere/clone/config.go` for the modified `Prepare()`...

Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go]: I like that more. It puts the warning at the top.

File: builder/vsphere/common/step_shutdown.go (hunk 3 above)
Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go:73]: Why remove a comment?

File: builder/vsphere/common/step_shutdown.go (hunk 5 above)
Comment (netapp-jgriffit) [reply builder/vsphere/common/step_shutdown.go:31]: agreed

**Comment by netapp-jgriffit** [comment]
Applied the recommendations and the final execution was successful on my end. Pushed the commits and waiting on circleci.

**Comment by netapp-jgriffit** [comment]
`license/cla` is still saying that I've not signed, but I have.

**Comment by azr** [comment]
@netapp-jgriffit about the cla you need to make sure the email you used to sign the commits is the same email as the one for the CLA.

**Comment by netapp-jgriffit** [comment]
Whelp... I was committing with my expanded email address but signed with my SSO short address. I found some information about updating the commit signatures but I'm not confident they won't update commits that are not mine.

Am I able to re-sign the CLA using a different (the expanded) email address?

**Comment by azr** [comment]
> Am I able to re-sign the CLA using a different (the expanded) email address?

Yes you should be :)

**Comment by azr** [comment]
The email used will be the email from Github, so you have to change/add it in Github if you want to add it.

**Comment by netapp-jgriffit** [comment]
> 
> 
> The email used will be the email from Github, so you have to change/add it in Github if you want to add it.

Oh, I did that yesterday not realizing that CircleCI passed that check.

**Comment by netapp-jgriffit** [comment]
@sylviamoss - I've addressed each of the changes requested and clicked the 'Resolve' button but it's saying that there are still requested changes.

**Comment by SwampDragons** [comment]
It won't change the status until someone reviews it and manually changes the review status; we'll try to do it early next week :)

**Comment by netapp-jgriffit** [comment]
Thank you @SwampDragons ! This is my first open-source contribution so this process is all new and exciting. I'm sure the next non-HashiCorp will have a different process. 🤣

**Comment by SwampDragons** [comment]
Totally understand! Thanks for your contribution! I know that the CLA process can be a bit of a doozy.

**Comment by SwampDragons** [comment]
It also looks like there are some merge conflicts because this has been waiting for a merge for so long -- if you could take some time to rebase the branch on the current "master" branch that could save us some time reviewing on Monday.

**Comment by jaevans** [comment]
I built this PR (rebased locally to master) and it solved my similar problem. I'd really like to see this get into the next release. Rebasing only took a few minutes for someone with no experience with the codebase, and was easy to see what needs to be done.

I haven't signed the CLA (and would have to go through legal as well) so I can't push the changes back. Sorry!

**Review by SwampDragons — APPROVED** [review]

**Comment by SwampDragons** [comment]
Thanks!

**Comment by netapp-jgriffit** [comment]
Thank you @SwampDragons ! I'm sorry I couldn't get around to rebasing it myself.

How does versioning work? I know I can build from source and use it but how will I know when it's in in a standard installation? Ubuntu in my case.

**Comment by SwampDragons** [comment]
We are releasing today and it will be part of that release.
