### PR TITLE
if someone logs a line longer than 64*1024 bytes before it contains a…

### LINKED ISSUE #7879: Packer hangs when long lines need to be logged from builders/provisioners
Discovered this with long `log.Print` lines in a builder, but repro's on long lines from shell provisioned. Take for example this Packer template:
```json
{
  "builders": [
    {
      "type": "null",
      "ssh_username": "user",
      "ssh_host": "localhost",
      "ssh_agent_auth": true
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline_shebang": "/bin/bash",
      "inline": [ "printf '=%.0s' {1..500000}" ]
    }
  ]
}
```
When run with extra logging (`PACKER_LOG=1 packer build test.json`), Packer will hang where it would normally log the 500000 `=`'s.

``` sh
$ ./packer version
Packer v1.4.2

$ PACKER_LOG=1 packer build test2.json
2019/07/17 03:47:48 [INFO] Packer version: 1.4.2
2019/07/17 03:47:48 Packer Target OS/Arch: linux amd64
2019/07/17 03:47:48 Built with Go Version: go1.12.6

... plugin discovery etc ...

2019/07/17 03:47:48 Build debug mode: false
2019/07/17 03:47:48 Force build: false
2019/07/17 03:47:48 On error:
2019/07/17 03:47:48 Preparing build: null
null output will be in this color.

2019/07/17 03:47:48 Waiting on builds to complete...
2019/07/17 03:47:48 Starting build run: null
2019/07/17 03:47:48 Running builder: null
2019/07/17 03:47:48 [INFO] (telemetry) Starting builder null
==> null: Using ssh communicator to connect: localhost
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [INFO] Waiting for SSH, up to timeout: 5m0s
==> null: Waiting for SSH to become available...
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [INFO] Attempting SSH connection to localhost:22...
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [DEBUG] Config to &ssh.Config{SSHConfig:(*ssh.ClientConfig)(0xc0004cb5f0), Connection:(func() (net.Conn, error))(0x1151950), Pty:false, DisableAgentForwarding:false, HandshakeTimeout:0, UseSftp:false, KeepAliveInterval:5000000000, Timeout:0}...
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [DEBUG] reconnecting to TCP connection for SSH
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [DEBUG] handshaking with SSH
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [DEBUG] handshake complete!
2019/07/17 03:47:48 packer: 2019/07/17 03:47:48 [DEBUG] Opening new ssh session
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] agent forwarding enabled
==> null: Connected to SSH!
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 Running the provision hook
2019/07/17 03:47:49 [INFO] (telemetry) Starting provisioner shell
==> null: Provisioning with shell script: /tmp/packer-shell787680589
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 Opening /tmp/packer-shell787680589 for reading
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] 39 bytes written for 'uploadData'
2019/07/17 03:47:49 [INFO] 39 bytes written for 'uploadData'
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Opening new ssh session
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Starting remote scp process:  scp -vt /tmp
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Started SCP session, beginning transfers...
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Copying input data into temporary file so we can read the length
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] scp: Uploading script_6318.sh: perms=C0644 size=39
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] SCP session complete, closing stdin pipe.
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Waiting for SSH session to complete.
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] scp stderr (length 30): Sink: C0644 39 script_6318.sh
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Opening new ssh session
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] starting remote command: chmod 0755 /tmp/script_6318.sh
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 03:47:49 [INFO] RPC client: Communicator ended with: 0
2019/07/17 03:47:49 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] RPC client: Communicator ended with: 0
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] Opening new ssh session
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [DEBUG] starting remote command: chmod +x /tmp/script_6318.sh; PACKER_BUILDER_TYPE='null' PACKER_BUILD_NAME='null'  /tmp/script_6318.sh
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 03:47:49 [INFO] 500000 bytes written for 'stdout'
2019/07/17 03:47:49 [INFO] 0 bytes written for 'stderr'
2019/07/17 03:47:49 [INFO] RPC client: Communicator ended with: 0
2019/07/17 03:47:49 [INFO] RPC endpoint: Communicator ended with: 0
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] 500000 bytes written for 'stdout'
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] 0 bytes written for 'stderr'
2019/07/17 03:47:49 packer: 2019/07/17 03:47:49 [INFO] RPC client: Communicator ended with: 0
```
Packer hangs here forever.
Here is an example of a builder triggering this bug: https://gist.github.com/paulmey/d634c61d7b5fb698b08b5cdb2f9cf713

Running on Ubuntu 18.10

### PR DESCRIPTION
**Pull request by SwampDragons**
We have some logic in the log.go file that does a very basic deduplication of loglines to prevent annoying noise for people who run packer with PACKER_LOG=1 but not PACKER_LOG_PATH.

It turns out that if a logline exceeds 64*1024 bytes, the scanner that we used would hang. This PR implements a new scanner function that'll un-stick the log line scanning to keep Packer from hanging forever.

Closes #7879

### CODE REVIEW

**Comment by SwampDragons** [comment]
Good point. I'll look at opening a bug.

**Comment by SwampDragons** [comment]
Done: https://github.com/golang/go/issues/35474

**Comment by SwampDragons** [comment]
Indeed. After I opened that PEBKAC bug and realized where the deadlock actually was, I realized that my monday task was gonna be scanning our code for any more of these situations. Remember that RPC bug we had a while ago where we had to revert a change you made because of some unfindable deadlock? I bet this was the cause.

**Comment by SwampDragons** [comment]
Worth noting that in this workaround, I'm not truncating, just returning the line in chunks so it gets broken up into multiple lines.

**Comment by azr** [comment]
> I bet this was the cause.
Ah yes that must be it !! Ah Daim bug !! 

On a side note I've been poking around this area on the HCL2 changes and I think moving packer to go-plugins would save us from a lot of troubles here !

File: log.go [hunk 1]
```diff
@@ -40,10 +43,50 @@ func logOutput() (logOutput io.Writer, err error) {
 					}
 					os.Stderr.WriteString(fmt.Sprint(scanner.Text() + "\n"))
 				}
+				if err := scanner.Err(); err != nil {
```
Comment (azr) [inline log.go]: I think this check should be move in the for loop to avoid the deadlock; Is that right ?

Comment (SwampDragons) [reply log.go]: @azr nope. The loop ends when the error is generated, just without sending an EOF to the writer. The deadlock was because I wasn't calling `w.Close()` earlier.

Comment (azr) [reply log.go]: ah got it ! I thought it was the loop 🙂
