### PR TITLE
builder/googlecompute: Add WrapStartupScriptFile configuration option

### LINKED ISSUE #9121: googlecompute: using startup_script_file hangs builder
#### Overview of the Issue

Using `startup_script_file` causes googlecompute builder to hang.
`googlecompute: Startup script not finished yet. Waiting...` is repeated many times until timeout error occurs.

#### Reproduction Steps

image.pkr.hcl:
```
source "googlecompute" "runner" {
  account_file = "account.json"
  image_name          = "runner-{{timestamp}}"
  image_family        = "runner"
  project_id          = "xxxx"
  source_image_family = "ubuntu-minimal-2004-lts"
  ssh_username        = "packer"
  startup_script_file = "bootstrap.sh"
  zone                = "europe-west4-c"
}

build {
  sources = [
    "source.googlecompute.runner"
  ]
}
```
bootstrap.sh:
```
#!/usr/bin/env bash

echo "test"
exit 0
```

### Packer version

Packer v1.5.5

### Operating system and Environment details

macOS 10.15.4

### Log Fragments and crash.log files

https://gist.github.com/jacek-jablonski/a26241e9a8b24ed68648dadfe7dcf047

### PR DESCRIPTION
**Pull request by nywilken**
By default the Google builder will wrap any provided startup script file in order to track its execution via custom metadata. This added script can add a bit of complexity to the start script file so a new option is being added `wrap_startup_script`. This option allows a user to disable the script wrapping and just let GCE do its own thing when executing a startup script. 

In the future the plan is to fully deprecate the wrapped script option by setting the default value to false. 

- [x] Validate approach is inline with original issue
- [x] Add testing

Closes #9121

Documentation Preview
image

### CODE REVIEW

File: builder/googlecompute/config.go [hunk 1]
```diff
@@ -195,6 +195,13 @@ type Config struct {
 	// The path to a startup script to run on the VM from which the image will
 	// be made.
 	StartupScriptFile string `mapstructure:"startup_script_file" required:"false"`
+	// If "true", the contents of `startup_script_file` is wrapped in a Packer specific
+	// script that tracks the execution and completion of the provided
+	// script file. The wrapper ensures that the builder will not continue until
+	// the startup script has been executed. Defaults to "true".
+	// - The use of the wrapped script file requires that the user or service account
+	// running the build has the compute.instance.Metadata role.
+	WrapStartupScriptFile config.Trilean `mapstructure:"wrap_startup_script" required:"false"`
```
Comment (azr) [inline builder/googlecompute/config.go:204]: Should this be a simple boolean ? Trilean is neat for when you want three specific behaviors, true, false or unset. 
```suggestion
	WrapStartupScriptFile bool `mapstructure:"wrap_startup_script" required:"false"`
```

Comment (sylviamoss) [reply builder/googlecompute/config.go:204]: I understood that the `unset` behavior is important to know so it could set the default do `true`.

Comment (nywilken) [reply builder/googlecompute/config.go:204]: > I understood that the unset behavior is important to know so it could set the default do true.

@sylviamoss that's correct. I started with a boolean here but the default case should be true until we completely deprecated the wrap script. So I went with the Trilean because the unset state is important here.

Comment (SwampDragons) [reply builder/googlecompute/config.go:204]: If the only issue is being able to default true instead of false, I think we can use mapstructure to do that: https://github.com/hashicorp/packer/blob/master/post-processor/vsphere-template/post-processor.go#L45

Though it's worth verifying that this defaults as we expect.

File: builder/googlecompute/config.go [hunk 2]
```diff
@@ -195,6 +195,13 @@ type Config struct {
 	// The path to a startup script to run on the VM from which the image will
 	// be made.
 	StartupScriptFile string `mapstructure:"startup_script_file" required:"false"`
+	// If "true", the contents of `startup_script_file` is wrapped in a Packer specific
+	// script that tracks the execution and completion of the provided
+	// script file. The wrapper ensures that the builder will not continue until
+	// the startup script has been executed. Defaults to "true".
```
Comment (SwampDragons) [inline builder/googlecompute/config.go:201]: May be worth mentioning in the docs that in the future we intend to make this "false"

File: builder/googlecompute/step_create_instance.go [hunk 3]
```diff
@@ -40,19 +40,24 @@ func (c *Config) createInstanceMetadata(sourceImage *Image, sshPublicKey string)
...
-		instanceMetadata[StartupWrappedScriptKey] = string(content)
-	} else if wrappedStartupScript, exists := instanceMetadata[StartupScriptKey]; exists {
-		instanceMetadata[StartupWrappedScriptKey] = wrappedStartupScript
+		startupScript = string(content)
+	}
+	instanceMetadata[StartupScriptKey] = startupScript
+
+	// Wrap any startup script with our own startup script.
+	if startupScript != "" && c.WrapStartupScriptFile.True() {
+		instanceMetadata[StartupWrappedScriptKey] = startupScript
```
Comment (SwampDragons) [inline builder/googlecompute/step_create_instance.go:56]: nitpick but I don't think we need to re-set this since we're already setting in line 52

Comment (nywilken) [reply builder/googlecompute/step_create_instance.go:56]: Good catch!

File: builder/googlecompute/config.go (hunk 1 above)
Comment (azr) [reply builder/googlecompute/config.go:204]: Ah yes I see, default to true, a solution would be to negate the name of the variable so the golang's 'default to false for bool behaviour' just gives you this:
```suggestion
	UnwrapStartupScriptFile bool `mapstructure:"wrap_startup_script" required:"false"`
```

File: builder/googlecompute/step_create_instance.go (hunk 3 above)
Comment (SwampDragons) [reply builder/googlecompute/step_create_instance.go:56]: I think this is then only thing left before we can merge. Looks good.

File: builder/googlecompute/config.go (hunk 1 above)
Comment (SwampDragons) [reply builder/googlecompute/config.go]: I think negating the name makes it harder to conceptualize, and also when we switch this to defaulting to false it'll be the same issue. Let's go with the original Trilean solution.

File: builder/googlecompute/step_create_instance.go (hunk 3 above)
Comment (nywilken) [reply builder/googlecompute/step_create_instance.go]: So after review it is setting the wrapped startup script. I updated the order a little so that it is clearer what is being set.

File: builder/googlecompute/config.go (hunk 1 above)
Comment (nywilken) [reply builder/googlecompute/config.go:211]: Got it! I reverted back to the original implementation and dropped a few updates to the documentation.

File: Makefile [hunk 4]
```diff
@@ -135,7 +135,7 @@ generate-check: generate ## Check go code generation is on par
 		exit 1; \
 	fi
 
-test: mode-check vet ## Run unit tests
```
Comment (nywilken) [inline Makefile:138]: oops.
