### PR TITLE
provisioner/powershell: Update default execute command to handle script errors

### LINKED ISSUE #4916: PowerShell provisioner silently ignores some types of errors
Packer v1.0.0 on Windows 10 Enterprise 15063.296.

Building a Windows Server 2016 Standard image on Hyper-V.

The following provisioner contains invalid PowerShell commands. I would expect the build to fail. However, these errors are silently ignored.

```
    {
      "type": "powershell",
      "inline": "this is not a valid powershell command"
    }
```

Debug log snippet:

```
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 [DEBUG] connecting to remote shell using WinRM
2017/05/23 09:47:38 ui: ==> hyperv-iso: Connected to WinRM!
==> hyperv-iso: Connected to WinRM!
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Running the provision hook
==> hyperv-iso: Provisioning with Powershell...
2017/05/23 09:47:38 ui: ==> hyperv-iso: Provisioning with Powershell...
==> hyperv-iso: Provisioning with shell script: C:\Users\saares\AppData\Local\Temp\packer-powershell-provisioner887540923
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Found command: this is not a valid powershell command
2017/05/23 09:47:38 ui: ==> hyperv-iso: Provisioning with shell script: C:\Users\saares\AppData\Local\Temp\packer-powershell-provisioner887540923
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Opening C:\Users\saares\AppData\Local\Temp\packer-powershell-provisioner887540923 for reading
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Building command line for: if (Test-Path variable:global:ProgressPreference){$ProgressPreference='SilentlyContinue'};$env:PACKER_BUILDER_TYPE="hyperv-iso"; $env:PACKER_BUILD_NAME="hyperv-iso"; &'c:/Windows/Temp/script.ps1';exit $LastExitCode
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 [INFO] 39 bytes written for 'uploadData'
2017/05/23 09:47:38 [INFO] 39 bytes written for 'uploadData'
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Uploading file to 'c:/Windows/Temp/script.ps1'
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Copying file to $env:TEMP\winrmcp-848ef57a-37f2-474c-60ab-df80537f7458.tmp
2017/05/23 09:47:38 packer.exe: 2017/05/23 09:47:38 Moving file from $env:TEMP\winrmcp-848ef57a-37f2-474c-60ab-df80537f7458.tmp to c:\Windows\Temp\script.ps1
2017/05/23 09:47:41 packer.exe: #< CLIXML
2017/05/23 09:47:41 packer.exe: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>2017/05/23 09:47:41 Removing temporary file $env:TEMP\winrmcp-848ef57a-37f2-474c-60ab-df80537f7458.tmp
2017/05/23 09:47:43 packer.exe: 2017/05/23 09:47:43 [INFO] starting remote command: powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGgAeQBwAGUAcgB2AC0AaQBzAG8AIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAaAB5AHAAZQByAHYALQBpAHMAbwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=
2017/05/23 09:47:46 ui:     hyperv-iso: #< CLIXML
    hyperv-iso: #< CLIXML
2017/05/23 09:47:48 packer.exe: 2017/05/23 09:47:48 [INFO] command 'powershell -executionpolicy bypass -encodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAEUAUgBfAFQAWQBQAEUAPQAiAGgAeQBwAGUAcgB2AC0AaQBzAG8AIgA7ACAAJABlAG4AdgA6AFAAQQBDAEsARQBSAF8AQgBVAEkATABEAF8ATgBBAE0ARQA9ACIAaAB5AHAAZQByAHYALQBpAHMAbwAiADsAIAAmACcAYwA6AC8AVwBpAG4AZABvAHcAcwAvAFQAZQBtAHAALwBzAGMAcgBpAHAAdAAuAHAAcwAxACcAOwBlAHgAaQB0ACAAJABMAGEAcwB0AEUAeABpAHQAQwBvAGQAZQA=' exited with code: 0
2017/05/23 09:47:48 packer.exe: 2017/05/23 09:47:48 [INFO] RPC endpoint: Communicator ended with: 0
2017/05/23 09:47:48 [INFO] 1082 bytes written for 'stderr'
    hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">this : The term 'this' is not recognized as the name of a cmdlet, function, script file, or operable program. Check _x000D__x000A_</S><S S="Error">the spelling of the name, or if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At C:\Windows\Temp\script.ps1:1 char:1_x000D__x000A_</S><S S="Error">+ this is not a valid powershell command_x000D__x000A_</S><S S="Error">+ ~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (this:String) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
2017/05/23 09:47:48 [INFO] 0 bytes written for 'stdout'
2017/05/23 09:47:48 [INFO] RPC client: Communicator ended with: 0
2017/05/23 09:47:48 [INFO] RPC endpoint: Communicator ended with: 0
2017/05/23 09:47:48 packer.exe: 2017/05/23 09:47:48 [INFO] 1082 bytes written for 'stderr'
2017/05/23 09:47:48 packer.exe: 2017/05/23 09:47:48 [INFO] 0 bytes written for 'stdout'
2017/05/23 09:47:48 packer.exe: 2017/05/23 09:47:48 [INFO] RPC client: Communicator ended with: 0
2017/05/23 09:47:48 ui:     hyperv-iso: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><S S="Error">this : The term 'this' is not recognized as the name of a cmdlet, function, script file, or operable program. Check _x000D__x000A_</S><S S="Error">the spelling of the name, or if a path was included, verify that the path is correct and try again._x000D__x000A_</S><S S="Error">At C:\Windows\Temp\script.ps1:1 char:1_x000D__x000A_</S><S S="Error">+ this is not a valid powershell command_x000D__x000A_</S><S S="Error">+ ~~~~_x000D__x000A_</S><S S="Error">    + CategoryInfo          : ObjectNotFound: (this:String) [], CommandNotFoundException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : CommandNotFoundException_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
```

You can see some errors printed there but Packer just continues as if all was fine.

### LINKED ISSUE #9161: Powershell provisioner and #requires directive
#### Overview of the Issue

Provisioning with powershell provisioner succeeds despite the script being invoked violating a `#Requires -Version` directive.

[https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_requires?view=powershell-7)

#### Reproduction Steps
Configure a powershell provisioner invoking a script with a `#Requires -Version x` directive that fails on the to be provisoned target system. Pick a large version number for it to definitely fail on any system. This probably can be reproduced with any requires directive that gets violated during script invocation.

#### Packer log snippet

> 2020/05/02 08:13:32 ui: 2020-05-02T08:13:32+02:00: ==> vbox-base-win2012-r2: Provisioning with Powershell...
2020/05/02 08:13:32 ui: 2020-05-02T08:13:32+02:00: ==> vbox-base-win2012-r2: Provisioning with powershell script: scripts/init_provisioning/post-bootstrap.ps1
2020/05/02 08:13:32 packer.exe plugin: Opening scripts/init_provisioning/post-bootstrap.ps1 for reading
2020/05/02 08:13:32 packer.exe plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5ead0cbd-97e7-8f63-237a-c34ba075b0e4.ps1
2020/05/02 08:13:32 packer.exe plugin: [INFO] 122 bytes written for 'uploadData'
2020/05/02 08:13:32 packer.exe plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5ead0cbd-97e7-8f63-237a-c34ba075b0e4.ps1'
2020/05/02 08:13:32 [INFO] 122 bytes written for 'uploadData'
2020/05/02 08:13:32 packer.exe plugin: Copying file to $env:TEMP\winrmcp-b300f02f-f55c-4e43-6b82-9cb96bb7b655.tmp
2020/05/02 08:13:32 packer.exe plugin: Moving file from $env:TEMP\winrmcp-b300f02f-f55c-4e43-6b82-9cb96bb7b655.tmp to c:\Windows\Temp\packer-ps-env-vars-5ead0cbd-97e7-8f63-237a-c34ba075b0e4.ps1
2020/05/02 08:13:41 packer.exe plugin: Removing temporary file $env:TEMP\winrmcp-b300f02f-f55c-4e43-6b82-9cb96bb7b655.tmp
2020/05/02 08:13:49 packer.exe plugin: [INFO] 1935 bytes written for 'uploadData'
2020/05/02 08:13:49 [INFO] 1935 bytes written for 'uploadData'
2020/05/02 08:13:49 packer.exe plugin: Uploading file to 'C:/Windows/Temp/scripts/post-bootstrap.ps1'
2020/05/02 08:13:49 packer.exe plugin: Copying file to $env:TEMP\winrmcp-9c45e645-e134-4e9d-69d5-0747674cdd84.tmp
2020/05/02 08:13:49 packer.exe plugin: Moving file from $env:TEMP\winrmcp-9c45e645-e134-4e9d-69d5-0747674cdd84.tmp to C:\Windows\Temp\scripts\post-bootstrap.ps1
2020/05/02 08:13:57 packer.exe plugin: Removing temporary file $env:TEMP\winrmcp-9c45e645-e134-4e9d-69d5-0747674cdd84.tmp
2020/05/02 08:14:05 packer.exe plugin: [INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5ead0cbd-97e7-8f63-237a-c34ba075b0e4.ps1; &'C:/Windows/Temp/scripts/post-bootstrap.ps1'; exit $LastExitCode }"
2020/05/02 08:14:15 packer.exe plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5ead0cbd-97e7-8f63-237a-c34ba075b0e4.ps1; &'C:/Windows/Temp/scripts/post-bootstrap.ps1'; exit $LastExitCode }"' exited with code: 0
2020/05/02 08:14:15 packer.exe plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: & : Das Skript "post-bootstrap.ps1" kann nicht ausgeführt werden, da es eine
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: #requires-Anweisung für Windows PowerShell 5.0 enthält. Die für das Skript
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: erforderliche Version von Windows PowerShell stimmt mit der derzeit
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: ausgeführten Windows PowerShell-Version 4.0 nicht überein.
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: In Zeile:1 Zeichen:216
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: + ... a075b0e4.ps1; &'C:/Windows/Temp/scripts/post-bootstrap.ps1'; exit
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: $LastExitCode  ...
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2: +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2:     + CategoryInfo          : ResourceUnavailable: (post-bootstrap.ps1:String)
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2:     [], ScriptRequiresException
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2:     + FullyQualifiedErrorId : ScriptRequiresUnmatchedPSVersion
2020/05/02 08:14:15 ui error: 2020-05-02T08:14:15+02:00: ==> vbox-base-win2012-r2:
2020/05/02 08:14:15 [INFO] 658 bytes written for 'stderr'
2020/05/02 08:14:15 [INFO] 0 bytes written for 'stdout'
2020/05/02 08:14:15 [INFO] RPC client: Communicator ended with: 0
2020/05/02 08:14:15 [INFO] RPC endpoint: Communicator ended with: 0
2020/05/02 08:14:15 packer.exe plugin: [INFO] 658 bytes written for 'stderr'
2020/05/02 08:14:15 packer.exe plugin: [INFO] 0 bytes written for 'stdout'
2020/05/02 08:14:15 packer.exe plugin: [INFO] RPC client: Communicator ended with: 0
2020/05/02 08:14:15 packer.exe plugin: C:/Windows/Temp/scripts/post-bootstrap.ps1 returned with exit code 0

### Packer version
1.5.5

### Operating system and Environment details
Packer Host: Windows Server 2019 (1809 LTS)
Virtualbox guest: Windows Server 2012 R2 (PowerShell v4)

### Log Fragments and crash.log files
[https://gist.github.com/Occams/099bb951b6a4074a3a4dbd5bea920cf0](https://gist.github.com/Occams/099bb951b6a4074a3a4dbd5bea920cf0)

### PR DESCRIPTION
**Pull request by nywilken**
This change sets the ErrorActionPreference and wraps the script execution in a Try/Catch statement so that the provisioner can capture any errors encountered when running the script. In addition to the try/catch the `&` operator is replaced by the `.` sourcing operator to ensure the script is executed in the same scope as the parent command (so that errors bubble up properly).

Tests after change
```
⇶  ACC_TEST_BUILDERS=amazon-ebs ACC_TEST_PROVISIONERS=powershell go test
./provisioner/powershell/... -timeout=1h ok
github.com/hashicorp/packer/provisioner/powershell      915.865s
```

### Todo
- [x] Test against Elevated command execution
- [x] Rename acceptance test fixtures
- [ ] Validate issue is resolved for reporters on 4916
- [x] Validate that LastExitCode is set for scripts with native Windows application failures

Closes #4916
Closes #9161

### CODE REVIEW

**Comment by SwampDragons** [comment]
This probably needs to go into 1.6 since it's going to change behavior.

**Comment by SwampDragons** [comment]
I tested this and it looks good. Not merging yet since this is targeted for v1.6

File: provisioner/powershell/provisioner_acc_test.go [hunk 1]
```diff
@@ -39,6 +39,15 @@ func TestAccPowershellProvisioner_Script(t *testing.T) {
 	acc.TestProvisionersAgainstBuilders(&testProvisioner, t)
 }
 
+func TestAccPowershellProvisioner_Invalid(t *testing.T) {
```
Comment (nywilken) [inline provisioner/powershell/provisioner_acc_test.go:42]:
```suggestion
func TestAccPowershellProvisioner_ExitCodes(t *testing.T) {
```

File: provisioner/powershell/provisioner.go [hunk 2]
```diff
@@ -98,13 +98,15 @@ type Provisioner struct {
...
+		`%s. {{.Vars}};try { & '{{.Path}}' } catch { Write-Error $Error[0]; exit 1 }; if ($LastExitCode) { exit $LastExitCode }}`
 
+	var debugLine string
 	if p.config.DebugMode != 0 {
-		baseCmd += fmt.Sprintf(`Set-PsDebug -Trace %d;`, p.config.DebugMode)
+		debugLine = fmt.Sprintf(`Set-PsDebug -Trace %d;`, p.config.DebugMode)
 	}
-
-	baseCmd += `. {{.Vars}}; &'{{.Path}}'; exit $LastExitCode }`
+	baseCmd = fmt.Sprintf(baseCmd, debugLine)
```
Comment (SwampDragons) [inline provisioner/powershell/provisioner.go:109]: this doesn't look like a valid fmt.Sprintf string to me.

https://play.golang.org/p/tvHz_A_xWqL

Comment (nywilken) [reply provisioner/powershell/provisioner.go]: Yeah, there was a hard to see string interpolation verb at the beginning of the string that was hard to see. I reformatted it back to how it was as it was clearer.

Comment (SwampDragons) [reply provisioner/powershell/provisioner.go]: oh yeah I totally missed that, sorry.
