### PR TITLE
also strip \r to work around windows file ending strangeness

### LINKED ISSUE #7286: vmware-vmx Remote Clone Fails
This is the first time trying to use the vmware-vmx on a remote ESXI host so forgive me if you find that I'm just doing this incorrectly but this feels like it is a bug in the clone process.

My source and destination looks correct but I receive the following error.

Stderr: DiskLib_Check() failed for source disk The system cannot find the file specified (25).

- Packer version: 1.3.4
- Host platform: ESXI
- Log output and config: https://gist.github.com/JohnTheDon01/4ee04312cc228127fa278d0f37423dce

Thanks!

### PR DESCRIPTION
**Pull request by SwampDragons**
Fixes a bug where we'd strip the \n from a \r\n line ending, but not the \r, causing issues referencing the filename.

Closes #7286

### CODE REVIEW

File: builder/vmware/common/driver_esx5.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ type ESX5Driver struct {
 
 func (d *ESX5Driver) Clone(dst, src string, linked bool) error {
 
-	linesToArray := func(lines string) []string { return strings.Split(strings.Trim(lines, "\n"), "\n") }
+	linesToArray := func(lines string) []string { return strings.Split(strings.Trim(lines, "\r\n"), "\n") }
```
Comment (azr) [inline builder/vmware/common/driver_esx5.go]: Quickly reading this, the old behaviour `strings.Trim(lines, "\n")` will not happen any more. Not sure if this could be an issue.

Comment (SwampDragons) [reply builder/vmware/common/driver_esx5.go]: nope, strings.Trim() goes character by character. Not sure why it doesn't ask for an array, but I didn't write it. 🤷‍♀️ 

https://play.golang.org/p/GRCAu4_fHVd
