### PR TITLE
Override post-processor config on the fly

### LINKED ISSUE #8585: Vagrant post-processor literally has "panic" placeholder in Packer 1.5.x in HCL2 mode
#### Overview of the Issue

PR #8423 breaks Vagrant post-processor with panic instruction. Haven't seen other issue tracking this so I thought it's worth to open a separate one.

https://github.com/hashicorp/packer/blob/c3c2622204fbc4358f1761d38ba99616bf1eba33/post-processor/vagrant/post-processor.go#L63

#### Reproduction Steps

Run following buildfile with .pkr.hcl extension, e.g. `packer build file.pkr.hcl`

### Packer version

1.5.1

### Simplified Packer Buildfile

```
source "virtualbox-iso" "packer-debian-10-amd64" {
  iso_urls = [
    "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.2.0-amd64-netinst.iso"
  ]
  iso_checksum = "e43fef979352df15056ac512ad96a07b515cb8789bf0bfd86f99ed0404f885f5"
  ssh_username = "vagrant"
}

build {
  sources = [
    "source.virtualbox-iso.packer-debian-10-amd64"
  ]

  post-processor "vagrant" {
    output = "ephemeral/builds/vagrant-debian10.box"
  }
}
```

### Operating system and Environment details

OS X Catalina

### Log Fragments and crash.log files

```
$ packer build base_debian_vagrant.pkr.hcl
panic: not implemented yet
2020/01/08 15:47:57 packer-post-processor-vagrant plugin:
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: goroutine 71 [running]:
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/post-processor/vagrant.(*PostProcessor).ConfigSpec(0xc00015e010, 0xc00001a630)
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/private/tmp/packer-20191222-94130-1yh62h9/post-processor/vagrant/post-processor.go:63 +0x39
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/packer/rpc.(*commonServer).ConfigSpec(0xc0000aba98, 0x0, 0x0, 0xc0002e6ec0, 0x0, 0x0)
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/private/tmp/packer-20191222-94130-1yh62h9/packer/rpc/common.go:56 +0x38
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: reflect.Value.call(0xc0005dc5a0, 0xc000010768, 0x13, 0x7c7258a, 0x4, 0xc000093f18, 0x3, 0x3, 0x0, 0x0, ...)
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/usr/local/Cellar/go/1.13.5/libexec/src/reflect/value.go:460 +0x5f6
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: reflect.Value.Call(0xc0005dc5a0, 0xc000010768, 0x13, 0xc000080f18, 0x3, 0x3, 0x0, 0x0, 0x0)
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/usr/local/Cellar/go/1.13.5/libexec/src/reflect/value.go:321 +0xb4
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: net/rpc.(*service).call(0xc0000abac0, 0xc0000ee820, 0xc0005b03c0, 0xc0005b03d0, 0xc000136380, 0xc0002e6e20, 0x71f50e0, 0xc0002aa3e0, 0x194, 0x6ef1da0, ...)
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/usr/local/Cellar/go/1.13.5/libexec/src/net/rpc/server.go:377 +0x16f
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: created by net/rpc.(*Server).ServeCodec
2020/01/08 15:47:57 packer-post-processor-vagrant plugin: 	/usr/local/Cellar/go/1.13.5/libexec/src/net/rpc/server.go:474 +0x42b
2020/01/08 15:47:57 ConfigSpec failed: unexpected EOF
2020/01/08 15:47:57 waiting for all plugin processes to complete...
2020/01/08 15:47:57 /usr/local/bin/packer: plugin process exited
2020/01/08 15:47:57 /usr/local/bin/packer: plugin process exited
panic: ConfigSpec failed: unexpected EOF [recovered]
	panic: ConfigSpec failed: unexpected EOF
```

### PR DESCRIPTION
**Pull request by sylviamoss**
To keep the PostPorcessor struct consistent with the others, the configuration override logic was moved from Configure to PostProcess. This way, the Config struct will remain the same all the time and it will be overwritten on the fly whenever it is necessary. 

Closes #8585

### CODE REVIEW

File: post-processor/vagrant/post-processor.go [hunk 1]
```diff
@@ -246,6 +229,17 @@ func (p *PostProcessor) configureSingle(c *Config, raws ...interface{}) error {
 	return nil
 }
 
+func (p *PostProcessor) specificConfig(name string) (Config, error) {
```
Comment (sylviamoss) [inline post-processor/vagrant/post-processor.go]: this is in a new method to allow me to test it
