### PR TITLE
builder/amazon: Add validation for `subnet_id` when specifying `vpc_id`

### LINKED ISSUE #7167: AWS EBS Builder throws Misleading error when there is no default VPC and vpc_id is set, but subnet_id is not.
- Packer version from `packer version`:  v1.3.3
- Host platform : Windows 10 Version 1709
- Debug log output from `PACKER_LOG=1 packer build template.json`.: https://gist.github.com/bgshacklett/4253650df0e405191a29d3804b52634c
- The _simplest example template and scripts_ needed to reproduce the bug. https://gist.github.com/bgshacklett/1b8c5b0228c2ebf83f6365b6bf869048
  
# Summary
If the `vpc_id` argument is set and the `subnet_id` argument is unset when running against an AWS account with no default VPC, a `VPCIdNotSpecified` error will be received. This is misleading as the VPC ID has been specified by the user.

# Steps to Reproduce:
1. Ensure that the AWS account used for testing does _not_ have a Default VPC.
2. Run `packer build` against the configuration provided above.

## Expected Behavior
* An error should be received indicating that the `subnet_id` argument is required.

## Actual Behavior
* The error `VPCIdNotSpecified` is received, indicating that the VPC ID has not been set.

# Potential Solutions
* Remove the `vpc_id` argument from the builder.  

   **Reasoning:** The `vpc_id` argument requires that the `subnet_id` argument be set. As of #4879, when the `subnet_id` argument is set, the builder will automatically search AWS for the parent VPC, making the `vpc_id` argument redundant in all cases.  

   **Potential Downsides:** 
   * The `vpc_id` argument may currently be used as a safety mechanism to ensure that Packer will always run in a given VPC, even if an erroneous subnet ID is passed in.
* Validate that the `subnet_id` argument has a valid value when the `vpc_id` argument is set.  

   **Reasoning:** Per the documentation, the `subnet_id` argument is required if the `vpc_id` argument is set. It is reasonable to expect this to be enforced in code.  

   **Potential Downsides:**
   * Work required to implement the change
   * More code means more potential for bugs.

* Perform further error handling when a `VPCIdNotSpecified` error is received (e.g.: check for the existence of a `subnet_id` argument and [re-]throw the appropriate error).
   **Reasoning:** The `VPCIdNotSpecified` result from the API is ambiguous. Packer has enough information, at this point, to throw a more specific error.

   **Potential Downsides:**
   * Work required to implement the change
   * More code means more potential for bugs; potential for errors to be squashed.

### PR DESCRIPTION
**Pull request by nywilken**
Closes #7167

Changes made within this PR
* builder/amazon/step_pre_validate: Add validation for `subnet_id` when using a non-default `vpc_id`.
* builder/amazon: Add error handling for VPCIdNotSpecified

Test after change:
```
--- PASS: TestRunConfigPrepare (0.00s)
--- PASS: TestRunConfigPrepare_InstanceType (0.00s)
--- PASS: TestRunConfigPrepare_SourceAmi (0.00s)
--- PASS: TestRunConfigPrepare_SourceAmiFilterBlank (0.00s)
--- PASS: TestRunConfigPrepare_SourceAmiFilterOwnersBlank (0.00s)
--- PASS: TestRunConfigPrepare_SourceAmiFilterGood (0.00s)
--- PASS: TestRunConfigPrepare_EnableT2UnlimitedGood (0.00s)
--- PASS: TestRunConfigPrepare_EnableT2UnlimitedBadInstanceType (0.00s)
--- PASS:
TestRunConfigPrepare_EnableT2UnlimitedBadWithSpotInstanceRequest (0.00s)
--- PASS: TestRunConfigPrepare_SpotAuto (0.00s)
--- PASS: TestRunConfigPrepare_SSHPort (0.00s)
--- PASS: TestRunConfigPrepare_UserData (0.00s)
--- PASS: TestRunConfigPrepare_UserDataFile (0.00s)
--- PASS: TestRunConfigPrepare_TemporaryKeyPairName (0.00s)
--- PASS: TestRunConfigPrepare_VpcId (0.00s)
```

### Test Config
```json
{
  "variables": { },
  "builders": [{
    "type": "amazon-ebs",
    "region": "ap-northeast-1",
    "vpc_id": "{{ user `vpc_id` }}",
    "subnet_id": "{{ user `subnet_id` }}",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
        "root-device-type": "ebs"
      },
      "owners": ["099720109477"],
      "most_recent": true
    },
    "instance_type": "t2.micro",
    "ssh_username": "ubuntu",
    "ami_name": "packer-example {{timestamp}}"
  }]
}
```
### No default VPC
Build error before change
```bash
> packer build -var="vpc_id=vpc-xxxxxxxxx" template.json                                                                     amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: packer-example 1573507537
    amazon-ebs: Found Image ID: ami-02be181636ed95ac5
==> amazon-ebs: Creating temporary keypair: packer_5dc9d1d1-5464-19c3-6ead-21d347493d2c
==> amazon-ebs: Creating temporary security group for this instance: packer_5dc9d1d9-d173-17b2-0888-cef2878b5f48
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Error launching source instance: VPCIdNotSpecified: No default VPC for this user
==> amazon-ebs:         status code: 400, request id: b68aa3df-eb1f-4af2-8b2b-aee9cc708b45
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Deleting temporary keypair...
Build 'amazon-ebs' errored: Error launching source instance: VPCIdNotSpecified: No default VPC for this user
        status code: 400, request id: b68aa3df-eb1f-4af2-8b2b-aee9cc708b45

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: VPCIdNotSpecified: No default VPC for this user
        status code: 400, request id: b68aa3df-eb1f-4af2-8b2b-aee9cc708b45

==> Builds finished but no artifacts were created.
```
Build error after change
```bash
> packer build -var="vpc_id=vpc-xxxxxxxxx" template.json 
amazon-ebs output will be in this color.

==> amazon-ebs: Validating subnet information for VPC "vpc-xxxxxxxxx"
Build 'amazon-ebs' errored: Error: subnet_id must be provided for non-default VPCs (vpc-xxxxxxxxx)

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error: subnet_id must be provided for non-default VPCs (vpc-xxxxxxxxx)

==> Builds finished but no artifacts were created.
```
Build with `vpc_id` and `subnet_id`
```bash
> packer build -var "vpc_id=vpc-xxxxxxxxx" -var "subnet_id=subnet-xxxxxxxxx" template.json
amazon-ebs output will be in this color.

==> amazon-ebs: Prevalidating AMI Name: packer-example-1573678462
    amazon-ebs: Found Image ID: ami-0ec539abc2ecc4e85
==> amazon-ebs: Creating temporary keypair: packer_5dcc6d7e-3093-5b1b-fe28-f0bc8f97591f
==> amazon-ebs: Creating temporary security group for this instance: packer_5dcc6d82-a719-90da-5964-5b74b5668aa9
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
    amazon-ebs: Instance ID: i-0e42233bff9fc0fdc
==> amazon-ebs: Waiting for instance (i-0e42233bff9fc0fdc) to become ready...
...
```

### Default VPC 
No subnet_id parameter needed as the AWS API will select the first default subnet id. 
```bash
> packer build -var="vpc_id=vpc-xxxxxxxxx" template.json 
```

### EC2 Classic
Doesn't have an VPC to start so just running the builder with out `vpc_id` or `subnet_id` should work as expected

### CODE REVIEW

File: builder/amazon/common/helper_funcs.go [hunk 1]
```diff
@@ -47,3 +49,14 @@ func DestroyAMIs(imageids []*string, ec2conn *ec2.EC2) error {
 	}
 	return nil
 }
+
+// Returns true if the error matches all these conditions:
+//  * err is of type awserr.Error
+//  * Error.Code() matches code
+//  * Error.Message() contains message
+func isAWSErr(err error, code string, message string) bool {
```
Comment (SwampDragons) [inline builder/amazon/common/helper_funcs.go]: oh, this is very useful. I can think of several places in the code that could use this func.

Comment (azr) [reply builder/amazon/common/helper_funcs.go]: nice !

Comment (nywilken) [reply builder/amazon/common/helper_funcs.go]: This helper was pretty useful in the AWS Terraform provider so I thought we should borrow it :smile: I'll create a separate PR for this helper and update the `err.(awserr.Error)` checks to use this helper instead. There are not many references in the Amazon builder so it should be pretty straight forward.

Comment (nywilken) [reply builder/amazon/common/helper_funcs.go]: Separate PR for helper function https://github.com/hashicorp/packer/pull/8365

File: builder/amazon/common/step_pre_validate.go [hunk 2]
```diff
@@ -76,13 +78,34 @@ func (s *StepPreValidate) Run(ctx context.Context, state multistep.StateBag) mul
...
 	}
+
 	if s.AMISkipBuildRegion {
 		ui.Say("skip_build_region was set; not prevalidating AMI name")
 		return multistep.ActionContinue
 	}
 
 	ec2conn := state.Get("ec2").(*ec2.EC2)
 
+	// Validate VPC settings for non-default VPCs
```
Comment (SwampDragons) [inline builder/amazon/common/step_pre_validate.go]: You asked offline if we should find a way to add acceptance tests for this; to start with, it'd probably be useful to at least add some unit tests. If you look at step_ami_region_copy_test.go you'll see that we've already created a mock ec2 connection that you can put into a statebag before running a step to test it out. In your case, since it turns out step_pre_validate has no unit tests so far, I'd probably simplify things by extracting your VPC validation into its own function on the step and run it independently to check that validation in that one area works as expected. Happy to hop on a call and walk through this if you want.

File: builder/amazon/common/step_pre_validate.go [hunk 3]
```diff
@@ -76,13 +78,34 @@ func (s *StepPreValidate) Run(ctx context.Context, state multistep.StateBag) mul
 		ui.Say("Force Deregister flag found, skipping prevalidating AMI Name")
 		return multistep.ActionContinue
 	}
+
 	if s.AMISkipBuildRegion {
 		ui.Say("skip_build_region was set; not prevalidating AMI name")
 		return multistep.ActionContinue
 	}
 
 	ec2conn := state.Get("ec2").(*ec2.EC2)
```
Comment (SwampDragons) [inline builder/amazon/common/step_pre_validate.go]: if you do end up creating unit tests for this using the mock, you'll need to change this to cast to a *ec2iface.EC2API instead.

File: builder/amazon/common/step_pre_validate.go (hunk 2 above)
Comment (nywilken) [reply builder/amazon/common/step_pre_validate.go]: Thanks for the guidance here. I'll refactor into a separate function and reach out offline to set up a pairing session
