### PR TITLE
[hcl2] inspect command

### LINKED ISSUE #8538: packer subcommands (console,inspect,validate) should support HCL format
### Feature Description

Starting from Packer 1.5.0, we could use HCL templates in place of JSON templates but it looks like `packer validate` doesn't yet support HCL format.

#### test.pkr.hcl
```hcl
source "docker" "example" {
       image = "centos:7"
       commit = "true"
}

build {
    sources = [
        "source.docker.example"
    ]

    provisioner "ansible" {
        playbook_file = "site.yml"
    }
        
}
```

```console
$ packer validate test.pkr.hcl 
Failed to parse template: Error parsing JSON: invalid character 's' looking for beginning of value
At line 1, column 1 (offset 1):
    1: s
      ^
```

### PR DESCRIPTION
**Pull request by azr**
This implements the HCL2 inspect command.

and closes #8538

### CODE REVIEW

File: command/inspect_test.go [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+      amazon-ebs.example-2
+
+    provisioners:
+
+      shell
+
+    post-processors:
+
+      manifest
+
```
Comment (azr) [inline command/inspect_test.go:88]: Example output
