### PR TITLE
fix uint8

### LINKED ISSUE #10515: Error: Unhandled builder type: []uint8
#### Overview of the Issue

Currently a beginner with Packer, and I am currently using a simple HCL2 file. When trying to run my file, the shell provisioner always fails with the error

```
unhandled builder type: []uint8
```

When run with the `-on-error=ask` option, and manually logging in to the provisioned host, I do not see any evidence that the command from the provisioner was run.

A cursory glance at `hcl2template/types.hcl_post-processor.go`, where a similar issue (#9583) was raised in the past, suggests that the type is indeed not handled, lending to the credence that this may be an HCL2 issue.

#### Reproduction Steps

This issue was spotted with the Lumos Labs Orka plugin, using its Orka builder. As of this point, I have not tested a similar JSON file to see whether the issue is specifically relating to HCL2 handling, or whether the issue relates to Packer/Orka integration

### Packer version

1.6.6

### Simplified Packer Buildfile

```
source "orka" "orka" {
    // Specific settings have been redacted due to containing secrets and other Orka-specific details
}

build {
  sources = ["source.orka.orka"]
  provisioner "shell" {
    inline = ["touch packer-ran-successfully"]
  }
}
```

### Operating system and Environment details

macOS Catalina 10.15.7

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

### PR DESCRIPTION
**Pull request by SwampDragons**
May close #10515

### CODE REVIEW

File: hcl2template/types.hcl_provisioner.go [hunk 1]
```diff
@@ -40,6 +40,8 @@ func (p *HCL2Provisioner) HCL2Prepare(buildVars map[string]interface{}) error {
 			switch v := v.(type) {
 			case string:
 				buildValues[k] = cty.StringVal(v)
+			case uint8:
```
Comment (sylviamoss) [inline hcl2template/types.hcl_provisioner.go:43]: I was thinking that maybe it should be better to replace this entire switch with https://github.com/hashicorp/packer-plugin-sdk/blob/main/hcl2helper/values.go#L22. It addresses all the config to cty.Value possible transformation.

**Review by sylviamoss — CHANGES_REQUESTED** [review]
I see that the issue reported tested and it didn't work because it's failing for `[]uint8`. I made a suggestion that should avoid these config->cty.Value transformation error in the future.

File: hcl2template/types.hcl_provisioner.go (hunk 1 above)
Comment (azr) [reply hcl2template/types.hcl_provisioner.go:43]: Eh, thats a good idea but `HCL2ValueFromConfigValue` panics and doesn't handle the uint8/int64/uint64 cases. 
Also, to not have to do two PRs each time we have this issue, I'd implement that one around here: https://github.com/hashicorp/packer/blob/291121dd5524d3b892a6d2a288531ffc8532dd86/hcl2template/shim/values.go#L18

**Comment by SwampDragons** [comment]
I compromised -- wrote a new util function implemented in both the provisioner and postprocessor with a switch that contains most of the same cases as what Moss suggested but doesn't panic on a failure.

File: hcl2template/utils.go [hunk 2]
```diff
@@ -124,3 +124,48 @@ func PrintableCtyValue(v cty.Value) string {
...
+		for i, ev := range v {
+			vals[i] = cty.NumberIntVal(ev)
+		}
+		buildValue = cty.ListVal(vals)
+	case []uint64:
+		vals := make([]cty.Value, len(v))
+		for i, ev := range v {
+			vals[i] = cty.NumberUIntVal(ev)
+		}
+		buildValue = cty.ListVal(vals)
```
Comment (sylviamoss) [inline hcl2template/utils.go:166]: I'm not sure whether a build var can be an empty list or not, but is not possible to create a cty.ListVal from an empty list, so this will fail when `vals` is empty.

```suggestion
                if len(vals) == 0 {
                    return cty.ListValEmpty(cty.Number)
                }
		buildValue = cty.ListVal(vals)
```

Comment (sylviamoss) [reply hcl2template/utils.go:166]: I know the other function doesn't deal with this case, but I wanted to leave it as it was to avoid changing code that I wasn't using with data sources

**Review by sylviamoss — CHANGES_REQUESTED** [review]

File: hcl2template/utils.go (hunk 2 above)
Comment (azr) [reply hcl2template/utils.go:166]: Oh woa, I didn't know:

https://github.com/hashicorp/packer/blob/77c3c12244f3847762788a30feb3f6ec9f1617ff/vendor/github.com/zclconf/go-cty/cty/value_init.go#L155-L158

Comment (azr) [reply hcl2template/utils.go:166]: Oh right I think that's because a ListVal needs a type, `ListValEmpty` exists too, but you have to give it a type

**Review by azr — APPROVED** [review]
This LGTM !

File: hcl2template/utils.go (hunk 2 above)
Comment (sylviamoss) [reply hcl2template/utils.go:166]: Yes! Only tuple and object exist empty without a type, but all the others require a type, even Map if I'm not wrong.

Comment (SwampDragons) [reply hcl2template/utils.go:166]: great catch, thanks Moss.

File: hcl2template/utils.go [hunk 3]
```diff
@@ -124,3 +124,52 @@ func PrintableCtyValue(v cty.Value) string {
...
+		for i, ev := range v {
+			vals[i] = cty.NumberUIntVal(uint64(ev))
+		}
+		buildValue = cty.ListVal(vals)
+	case []int64:
+		vals := make([]cty.Value, len(v))
+		for i, ev := range v {
+			vals[i] = cty.NumberIntVal(ev)
+		}
+		buildValue = cty.ListVal(vals)
```
Comment (sylviamoss) [inline hcl2template/utils.go:160]: There're the other list types too!

**Review by sylviamoss — APPROVED** [review]
Nice!

File: hcl2template/utils.go (hunk 3 above)
Comment (SwampDragons) [reply hcl2template/utils.go:160]: 🤦 thanks
