### PR TITLE
builder/docker: set user during exec.

### LINKED ISSUE #5307: Provisioning of docker builder fails when container run as non-root
Provisioning of docker container (started by docker builder) fails when the container is started as non-root.
The problem seems to be that the `/packer-files` is mounted with permissions allowing for reading/writing only to the user starting the container.
 
Packer version:
```
Packer v1.0.4
```

Template:
```
{
        "provisioners": [
                {
                        "type": "shell",
                        "inline": "touch /provisioned"
                }
        ],
        "builders": [
                {
                        "type": "docker",
                        "image": "jenkins/jenkins:lts",
                        "commit": true
                }
        ]
}
```

Listing the container:
```
jenkins@a38e49e4f41e:/$ ls -l
total 52
lrwxrwxrwx   1 root  root    7 Jul 23 00:00 bin -> usr/bin
drwxr-xr-x   2 root  root 4096 Jul 13 13:04 boot
drwxr-xr-x   5 root  root  360 Sep  6 07:52 dev
lrwxrwxrwx   1 root  root   33 Jul 24 18:09 docker-java-home -> /usr/lib/jvm/java-8-openjdk-amd64
drwxr-xr-x  73 root  root 4096 Sep  6 07:52 etc
drwxr-xr-x   2 root  root 4096 Jul 13 13:04 home
lrwxrwxrwx   1 root  root    7 Jul 23 00:00 lib -> usr/lib
lrwxrwxrwx   1 root  root    9 Jul 23 00:00 lib32 -> usr/lib32
lrwxrwxrwx   1 root  root    9 Jul 23 00:00 lib64 -> usr/lib64
lrwxrwxrwx   1 root  root   10 Jul 23 00:00 libx32 -> usr/libx32
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 media
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 mnt
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 opt
drwx------   2 20153 1017 4096 Sep  6 07:52 packer-files
dr-xr-xr-x 329 root  root    0 Sep  6 07:52 proc
drwx------   2 root  root 4096 Jul 23 00:00 root
drwxr-xr-x   4 root  root 4096 Jul 23 00:00 run
lrwxrwxrwx   1 root  root    8 Jul 23 00:00 sbin -> usr/sbin
drwxr-xr-x   2 root  root 4096 Jul 23 00:00 srv
dr-xr-xr-x  13 root  root    0 Sep  4 10:52 sys
drwxrwxrwt   4 root  root 4096 Sep  5 20:56 tmp
drwxr-xr-x  49 root  root 4096 Sep  5 20:56 usr
drwxr-xr-x  31 root  root 4096 Sep  5 20:56 var
```

[packer build log](https://gist.githubusercontent.com/kostrzewa9ld/72dcbb4fde84ff5326232514cd0b3861/raw/4da85523f695d5fb8e11b740acaae33dabd7671b/packer_build.log)

### PR DESCRIPTION
**Pull request by mwhooker**
Add `exec_user` option to control what user `docker exec` is run as.

closes #5307

### CODE REVIEW

File: builder/docker/config.go [hunk 1]
```diff
@@ -23,19 +23,20 @@ type Config struct {
 	common.PackerConfig `mapstructure:",squash"`
 	Comm                communicator.Config `mapstructure:",squash"`
 
+	Author       string
+	Changes      []string
 	Commit       bool
+	ContainerDir string `mapstructure:"container_dir"`
 	Discard      bool
+	ExecUser     string `mapstructure:"exec_user"`
```
Comment (mwhooker) [inline builder/docker/config.go]: this is the only thing that's added. I sorted the other options
