### PR TITLE
Fix for #7253

### LINKED ISSUE #7253: Bug: build.sh - Build via MINGW fails because of OSTYPE capitalization issues
Version: Packer 1.3.3 (build.sh is the same in master branch, so bug is still present)
Host: Windows 7 64Bit, git Bash (git version 2.19.0.windows.1), mintty 2.9.0 (x86_64-pc-msys)

No Packer template output, because this affects the build scripts.

I have MINGW. In MINGW (at least in my version), the OSTYPE variable has already been set by MINGW, so the uname output isn't used.

```
danowar@powerhouse MINGW64 /h/Work/VCS/Git/packer (master)
$ echo $OSTYPE
msys
```
But the OSTYPE is not in the list where it is decided which path separator to use (because of capitalization issues), so it defaults to ":" as PATH separator, which breaks the Windows style paths that are otherwise enforced by the script.

https://github.com/hashicorp/packer/blob/20c2524881f361c5f0b14b2509ab37a2ab2c0582/scripts/build.sh#L28

I'll open a Pull Request for this. But it seems I've already more than would be good at once:
- created some functions to make stuff more readable
- changed a function name to make purpose more clear (at least to me)
- added FIXMEs where I'm not sure...
- adding more output

So, please tell me how we should proceed. I'm gonna open a fork now and then the pull request...

### PR DESCRIPTION
**Pull request by danowar2k**
Closes #7253.
And does way too much else, it seems. I hope this will not be ignored because of that. Don't want to make it harder than necessary.

Only tested on Windows, though. Are there any tests that test the build scripts itself?

### CODE REVIEW

File: scripts/build.sh [hunk 1]
```diff
@@ -5,63 +5,109 @@
 ALL_XC_ARCH="386 amd64 arm arm64 ppc64le"
 ALL_XC_OS="linux darwin windows freebsd openbsd solaris"
 
+# Exit immediately if a command fails
```
Comment (danowar2k) [inline scripts/build.sh]: Some small comment to indicate what this does

File: scripts/build.sh [hunk 2]
```diff
@@ -5,63 +5,109 @@
...
 set -e
 
+# Validates that a necessary tool is on the PATH
```
Comment (danowar2k) [inline scripts/build.sh]: Two methods that check whether the tools used in this shell script are there to prevent half-finished work.

File: scripts/build.sh [hunk 3]
```diff
@@ -5,63 +5,109 @@
...
+{
+    echo "==> Checking for necessary tools..."
+    validateToolPresence realpath
+    validateToolPresence dirname
+    validateToolPresence tr
+    validateToolPresence find
+}
+
 # Get the parent directory of where this script is.
-SOURCE="${BASH_SOURCE[0]}"
```
Comment (danowar2k) [inline scripts/build.sh]: Most of this was moved into functions

File: scripts/build.sh [hunk 4]
```diff
@@ -5,63 +5,109 @@
...
-        PATHSEP=';'
-        ;;
-    *)	PATHSEP=':'
-esac
-
-function convert_path() {
-    local flag
-    [ "${1:0:1}" = '-' ] && { flag="$1"; shift; }
+# NOTE: I'm unsure why you don't just use realpath like below
+function enterPackerSourceDir
```
Comment (danowar2k) [inline scripts/build.sh]: Functions replacing the inline code.
The "enterPackerSourceDir" function now uses realpath instead of readlink. More readable?

File: scripts/build.sh [hunk 5]
```diff
@@ -5,63 +5,109 @@
...
+{
+    echo "==> Entering Packer source dir..."
+    local BUILD_SCRIPT_PATH="${BASH_SOURCE[0]}"
+    SOURCEDIR=$(dirname $(dirname $(realpath "${BUILD_SCRIPT_PATH}")))
+    cd ${SOURCEDIR}
+}
+
+function ensureOutputStructure {
+    echo "==> Ensuring output directories are present..."
```
Comment (danowar2k) [inline scripts/build.sh]: Idempotent function. Split up the directory structure creation and the removal of old builds.

File: scripts/build.sh [hunk 6]
```diff
@@ -5,63 +5,109 @@
...
+    echo "==> Removing old builds..."
+    rm -f bin/*
+    rm -fr pkg/*
+}
 
-    [ -n "$1" ] || return 0
-    case ${OSTYPE:-`uname`} in
-        cygwin|CYGWIN*)
-            cygpath $flag -- "$1"
+function lowerCaseOSType {
```
Comment (danowar2k) [inline scripts/build.sh]: This ensures that the OSTYPE stuff is lower case

File: scripts/build.sh [hunk 7]
```diff
@@ -5,63 +5,109 @@
...
+            # cygwin only translates ';' to ':' on select environment variables
+            echo ';'
             ;;
-        *)  echo "$1"
+        *)	echo ':'
     esac
 }
 
+function convertPathOnCygwin() {
+    local flag
```
Comment (danowar2k) [inline scripts/build.sh]: Made this function receive two parameters to make it more readable

File: scripts/build.sh [hunk 8]
```diff
@@ -5,63 +5,109 @@
...
+    local somePath
+    if [ "${1:0:1}" = '-' ]; then
```
Comment (danowar2k) [inline scripts/build.sh]: The "optional" flag could be relegated to second parameter which would make logical flow better, but then it wouldn't look command-like (if that's the intent)

File: scripts/build.sh [hunk 9]
```diff
@@ -5,63 +5,109 @@
...
+enterPackerSourceDir
+ensureOutputStructure
+cleanOutputDirs
+
+PATHSEP=$(getPathSeparator)
+
 # XXX works in MINGW?
-which go &>/dev/null || PATH+=":`convert_path "${GOROOT:?}"`/bin"
+# FIXME: What if go is not in the PATH and GOROOT isn't set?
+which go &>/dev/null || PATH+=":`convertPathOnCygwin "${GOROOT:?}"`/bin"
```
Comment (danowar2k) [inline scripts/build.sh]: It's expected that GOROOT is set, but maybe it isn't always?

File: scripts/build.sh [hunk 10]
```diff
@@ -86,17 +132,18 @@ ${GOX:?command not found} \
 set -e
 
 # trim GOPATH to first element
-IFS="$PATHSEP"
-MAIN_GOPATH=($GOPATH)
-MAIN_GOPATH="$(convert_path --unix "$MAIN_GOPATH")"
-IFS=$OLDIFS
+IFS="${PATHSEP}"
+# FIXME: How do you know that the first path of GOPATH is the main GOPATH? Or is the main GOPATH meant to be the first path in GOPATH?
```
Comment (danowar2k) [inline scripts/build.sh]: I'm unsure whether this is about the "first" go path or some kind of "main" path. I'm not familiar with go conventions...

File: scripts/build.sh [hunk 11]
```diff
@@ -86,17 +132,18 @@ ${GOX:?command not found} \
...
+MAIN_GOPATH=(${GOPATH})
+MAIN_GOPATH="$(convertPathOnCygwin --unix "${MAIN_GOPATH[0]}")"
+IFS="${OLDIFS}"
 
 # Copy our OS/Arch to the bin/ directory
 echo "==> Copying binaries for this platform..."
-DEV_PLATFORM="./pkg/$(go env GOOS)_$(go env GOARCH)"
```
Comment (danowar2k) [inline scripts/build.sh]: Why are the local OS and ARCH extracted twice when you still have it?

File: scripts/build.sh [hunk 12]
```diff
@@ -86,17 +132,18 @@ ${GOX:?command not found} \
...
+DEV_PLATFORM="./pkg/${XC_OS}_${XC_ARCH}"
 for F in $(find ${DEV_PLATFORM} -mindepth 1 -maxdepth 1 -type f 2>/dev/null); do
     cp -v ${F} bin/
-    cp -v ${F} ${MAIN_GOPATH}/bin/
+    cp -v ${F} "${MAIN_GOPATH}/bin/"
```
Comment (danowar2k) [inline scripts/build.sh]: Oh, and I don't know if this build script will work with paths with whitespace in them...

**Comment by SwampDragons** [comment]
Our tests build Packer on linux and windows, and I build Packer on OSX; so I think we're safe there. I'll review the code for the next release. This doesn't look too gnarly even though you do have a few refactors at once. I'll let you know if anything is unclear to me.

**Comment by SwampDragons** [comment]
This looks fantastic. Thank you so much for this contribution!

**Comment by azr** [comment]
Ah, I got an error: 
```
./scripts/build.sh: line 35: realpath: command not found
```

**Comment by danowar2k** [comment]
Whoops. Yeah, I should use the functions I define...

I'll fix that ASAP

**Comment by danowar2k** [comment]
Hm, I thought my commit would appear in here...But it seems not. I opened #7265.

**Comment by azr** [comment]
Awesome, thanks 🙂
