### PR TITLE
Fix crash when an unset variable is used

### LINKED ISSUE #8730: Packer with HCL crashes on missing variable default.
#### Overview of the Issue

I accidentally left out the default value for "proxmox_username" below, which results in packer crashing with a segmentation fault.

#### Reproduction Steps

Run the attached build file with the mentioned packer config

### Packer version

Packer v1.5.3-dev
(https://github.com/hashicorp/packer/commit/23fa3107a3f1cd8a3b330c32b8030fad6f9ddb57)

### Simplified Packer Buildfile

<details>
<summary>puppetmaster.pkr.hcl</summary>

```

variable "proxmox_url" {
  default = "https://192.168.122.58:8006/api2/json" // PROXMOX_URL
}
variable "proxmox_username" {
  type = string
}
variable "proxmox_password" {
  default = "not-the-"
}

build {
  sources = [
    "source.proxmox.puppetmaster",
  ]

  provisioner "shell" {
    inline = [
      "sleep 5"
    ]
  }

  post-processor "shell-local" {
    inline = [
      "sleep 5"
    ]
  }
}


source "proxmox" "puppetmaster" {
  proxmox_url = "${var.proxmox_url}"
  username = "${var.proxmox_username}"
  password = "${var.proxmox_password}"
}

```

</details>

### Operating system and Environment details

OpenSuSE Leap 15.1, amd64

### Log Fragments and crash.log files
<details>
<summary>crash.log</summary>

```
2020/02/13 19:38:52 [INFO] Packer version: 1.5.3-dev [go1.13.7 linux amd64]
2020/02/13 19:38:52 Checking 'PACKER_CONFIG' for a config file path
2020/02/13 19:38:52 'PACKER_CONFIG' not set; checking the default config file path
2020/02/13 19:38:52 Attempting to open config file: /home/phaer/.packerconfig
2020/02/13 19:38:52 [WARN] Config file doesn't exist: /home/phaer/.packerconfig
2020/02/13 19:38:52 Setting cache directory: /home/phaer/projects/diebin/cloud/packer/packer_cache
2020/02/13 19:38:52 Creating plugin client for path: /usr/local/bin/packer
2020/02/13 19:38:52 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-proxmox"}
2020/02/13 19:38:52 Waiting for RPC address for: /usr/local/bin/packer
2020/02/13 19:38:52 packer-builder-proxmox plugin: [INFO] Packer version: 1.5.3-dev [go1.13.7 linux amd64]
2020/02/13 19:38:52 packer-builder-proxmox plugin: Checking 'PACKER_CONFIG' for a config file path
2020/02/13 19:38:52 packer-builder-proxmox plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/02/13 19:38:52 packer-builder-proxmox plugin: Attempting to open config file: /home/phaer/.packerconfig
2020/02/13 19:38:52 packer-builder-proxmox plugin: [WARN] Config file doesn't exist: /home/phaer/.packerconfig
2020/02/13 19:38:52 packer-builder-proxmox plugin: Setting cache directory: /home/phaer/projects/diebin/cloud/packer/packer_cache
2020/02/13 19:38:52 packer-builder-proxmox plugin: args: []string{"packer-builder-proxmox"}
2020/02/13 19:38:52 packer-builder-proxmox plugin: Plugin address: unix /tmp/packer-plugin709814317
2020/02/13 19:38:52 packer-builder-proxmox plugin: Waiting for connection...
2020/02/13 19:38:52 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin709814317
2020/02/13 19:38:52 packer-builder-proxmox plugin: Serving a plugin connection...
2020/02/13 19:38:52 waiting for all plugin processes to complete...
2020/02/13 19:38:52 /usr/local/bin/packer: plugin process exited
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7f39e6]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
	/go/pkg/mod/github.com/azr/go-cty@v1.1.1-0.20200203143058-28fcda2fe0cc/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x494f040, 0xc000467738, 0x0, 0x0, 0x0, 0xc0006bdfe0, ...)
	/go/pkg/mod/github.com/azr/go-cty@v1.1.1-0.20200203143058-28fcda2fe0cc/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hcldec.(*AttrSpec).decode(0xc00068e630, 0xc0004a4120, 0x0, 0x0, 0x0, 0xc0005ceac0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hcldec/spec.go:207 +0x312
github.com/hashicorp/hcl/v2/hcldec.ObjectSpec.decode(0xc0005ba0f0, 0xc0004a4120, 0x0, 0x0, 0x0, 0xc0005ceac0, 0xc0006f0df0, 0x42f2d1, 0x434d570, 0xc0006f0df0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hcldec/spec.go:79 +0x238
github.com/hashicorp/hcl/v2/hcldec.decode(0x494e280, 0xc0003d0a50, 0x0, 0x0, 0x0, 0xc0005ceac0, 0x494ef40, 0xc0005ba0f0, 0xde1d00, 0x492a000, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hcldec/decode.go:21 +0x118
github.com/hashicorp/hcl/v2/hcldec.Decode(...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.3.0/hcldec/public.go:15
github.com/hashicorp/packer/hcl2template.decodeHCL2Spec(0x494e280, 0xc0003d0a50, 0xc0005ceac0, 0x7fa55c121300, 0xc00059c200, 0x0, 0x0, 0x0, 0xc000566000, 0x7fa561b08008, ...)
	/home/circleci/project/hcl2template/decode.go:17 +0xa0
github.com/hashicorp/packer/hcl2template.(*Parser).startBuilder(0xc000627370, 0xc00044e570, 0xc0005ceac0, 0xc0003f43c8, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/hcl2template/types.source.go:54 +0x2e4
github.com/hashicorp/packer/hcl2template.(*Parser).getBuilds(0xc0006f1370, 0xc0005ae300, 0x0, 0x0, 0xc0005ae300, 0x0, 0x0, 0x0)
	/home/circleci/project/hcl2template/types.packer_config.go:102 +0x1d5
github.com/hashicorp/packer/hcl2template.(*Parser).Parse(0xc000627370, 0x7ffcb01fefc5, 0x14, 0x0, 0xc0000dd138, 0xc0000dd1a8, 0x38, 0x40, 0xc0005ae080, 0xc000334fc0)
	/home/circleci/project/hcl2template/types.packer_config.go:150 +0xd1
github.com/hashicorp/packer/command.(*BuildCommand).GetBuildsFromHCL(0xc000334f30, 0x7ffcb01fefc5, 0x14, 0x0, 0x0, 0xc000566000, 0x1)
	/home/circleci/project/command/build.go:107 +0x123
github.com/hashicorp/packer/command.(*BuildCommand).GetBuilds(0xc000334f30, 0x7ffcb01fefc5, 0x14, 0x1, 0x1, 0x7fffffffffffffff, 0x0)
	/home/circleci/project/command/build.go:136 +0x543
github.com/hashicorp/packer/command.(*BuildCommand).RunContext(0xc000334f30, 0x494dc00, 0xc0000c7c80, 0xc00004e1a0, 0x1, 0x1, 0xc0000c7c80)
	/home/circleci/project/command/build.go:185 +0xca
github.com/hashicorp/packer/command.(*BuildCommand).Run(0xc000334f30, 0xc00004e1a0, 0x1, 0x1, 0x0)
	/home/circleci/project/command/build.go:55 +0x201
github.com/mitchellh/cli.(*CLI).Run(0xc0002f6640, 0xc0002f6640, 0x1, 0x1)
	/go/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x1da
main.wrappedMain(0x0)
	/home/circleci/project/main.go:238 +0x853
main.realMain(0x0)
	/home/circleci/project/main.go:124 +0xbb
main.main()
	/home/circleci/project/main.go:34 +0x22
```

</details

### PR DESCRIPTION
**Pull request by azr**
This was due to a misunderstanding on my side. When a variable is not set one needs to set it to `cty.NullVal(cty.DynamicPseudoType) `, like so:

https://github.com/hashicorp/packer/blob/23b940dbd54a346e1ed622f8a56f01ac21f95b8b/hcl2template/types.variables.go#L57-L93

I choose not to error when a variable is not set and not used. But when someone does something like this: 
```hcl

variable "proxmox_username" {
  type = string
}

build {
  sources = [
    "source.null.null-builder${var.proxmox_username}",
  ]
}


source "null" "null-builder" {
}
```

The error is the following:

```

  on .vscode/hcl2/crash/var_with_no_default.pkr.hcl line 8, in build:
   8:     "source.null.null-builder${var.proxmox_username}",

Variables may not be used here.

Error: Unsuitable value type

  on .vscode/hcl2/crash/var_with_no_default.pkr.hcl line 7, in build:
   7:   sources = [
   8:     "source.null.null-builder${var.proxmox_username}",
   9:   ]

Unsuitable value: value must be known
```

fix #8730

### CODE REVIEW

File: hcl2template/types.packer_config.go [hunk 1]
```diff
@@ -100,11 +100,10 @@ func (c *PackerConfig) parseLocalVariables(f *hcl.File) ([]*Local, hcl.Diagnosti
 					Expr: attr.Expr,
 				})
 			}
-			allLocals = append(allLocals, locals...)
```
Comment (azr) [inline hcl2template/types.packer_config.go]: I simplified this one because when append will need to extend the size of a `allLocals` it will double its size ( this is the default setting ) which fill make the `make([]*Local, 0, len(attrs))` call unnecessary. We could have guessed the size of `allLocals` but I think this would be premature optimisation and I would rather have easy to read code :D

File: hcl2template/types.build.go [hunk 2]
```diff
@@ -60,6 +60,9 @@ func (p *Parser) decodeBuildConfig(block *hcl.Block) (*BuildBlock, hcl.Diagnosti
 		Config      hcl.Body `hcl:",remain"`
 	}
 	diags := gohcl.DecodeBody(block.Body, nil, &b)
+	if diags.HasErrors() {
```
Comment (sylviamoss) [inline hcl2template/types.build.go]: nice!! 👍  If there's an error we should fail faster :D

File: hcl2template/types.packer_config.go (hunk 1 above)
Comment (sylviamoss) [reply hcl2template/types.packer_config.go]: makes sense! thankss

File: hcl2template/types.build.go (hunk 2 above)
Comment (azr) [reply hcl2template/types.build.go]: yes !

**Comment by azr** [comment]
Question for the team. With this PR a variable can be defined and have no value.But this would be different that for Terraform; so quoting [this message](https://github.com/zclconf/go-cty/issues/43#issuecomment-587993204):

> By default, a Terraform variable is required and so Terraform would emit an error if it isn't set. An author can make a variable optional by providing a default value.
> 
> ```hcl
> variable "example" {
>   type    = string
>   default = "Hello"
> }
> ```
> 
> In some cases there isn't any reasonable default value, and the module simply wants to detect whether or not the value is set. In that case, the author can specify the default as null to say that the variable is optional but it has no default:
> 
> ```hcl
> variable "example" {
>   type    = string
>   default = null
> }
> ```

Should we do the same ?

**Comment by sylviamoss** [comment]
> Should we do the same ?

I think as a terraform user the one might expect to be the same. In terraform if the variable without a default is used, is it going to return an error as your implementation does? 

I like the way you did and I think both solutions are good. If it's not too difficult, I would do it as terraform just for consistency. Maybe just add the option of setting `default = null` without removing what you did.

File: hcl2template/types.variables.go [hunk 3]
```diff
@@ -200,7 +214,7 @@ func (variables *Variables) decodeVariableBlock(block *hcl.Block, ectx *hcl.Eval
 		})
 	}
 
-	(*variables)[block.Labels[0]] = res
+	(*variables)[name] = res
```
Comment (nywilken) [inline hcl2template/types.variables.go]: :100:

File: hcl2template/types.variables.go [hunk 4]
```diff
@@ -39,13 +39,15 @@ type Variable struct {
...
+	// Common name of the variable
+	Name string
 	// Description of the variable
 	Description string
 	// When Sensitive is set to true Packer will try it best to hide/obfuscate
 	// the variable from the output stream. By replacing the text.
 	Sensitive bool
 
-	block *hcl.Block
+	Range hcl.Range
```
[the remark this answers is not in the document]
Comment (azr) [reply hcl2template/types.variables.go]: yes !

File: go.mod [hunk 5]
```diff
@@ -180,6 +179,4 @@ replace git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110
 
 replace github.com/gofrs/flock => github.com/azr/flock v0.0.0-20190823144736-958d66434653
 
-replace github.com/zclconf/go-cty => github.com/azr/go-cty v1.1.1-0.20200203143058-28fcda2fe0cc
```
Comment (azr) [inline go.mod]: My pr was merged; so this can be removed.

**Comment by azr** [comment]
Hey folks ! I think this PR is good to review. I think the behaviour are super close to what we want in the RFC. But since this also fixes a crash I think we should merge it.

I'll gladly update the behaviours if/when the RFC changes later on 🙂.

File: hcl2template/testdata/variables/basic.pkr.hcl [hunk 6]
```diff
@@ -29,6 +29,7 @@ variable "super_secret_password" {
 description = <<IMSENSIBLE
```
Comment (SwampDragons) [inline hcl2template/testdata/variables/basic.pkr.hcl]: Did you mean "sensitive" here instead of "sensible"?

File: website/source/docs/configuration/from-1.5/variables.html.md [hunk 7]
```diff
@@ -278,3 +278,48 @@ precedence over earlier ones:
 
 ~> **Important:** Variables with map and object values behave the same way as
 other variables: the last value found overrides the previous values.
+
+### A variable value must be known :
```
Comment (nywilken) [inline website/source/docs/configuration/from-1.5/variables.html.md]: :100: :+1: :trophy: Nicely done on adding the variables table.

File: hcl2template/testdata/variables/basic.pkr.hcl (hunk 6 above)
Comment (azr) [reply hcl2template/testdata/variables/basic.pkr.hcl]: yes !

File: website/source/docs/configuration/from-1.5/variables.html.md (hunk 7 above)
Comment (azr) [reply website/source/docs/configuration/from-1.5/variables.html.md]: thanks :D
