### PR TITLE
provisioner/powershell: Update cleanup logic

### LINKED ISSUE #9181: Remove-Item Cannot find path of temp scripts
### Overview of the Issue

Using the vsphere-iso builder on Packer 1.5.6, seeing a new issue when finishing a powershell provisioner.   Packer-cleanup-uuid.ps1 script cannot find script-uuid.ps1 files to remove on clean up.

#### Reproduction Steps

Build a Windows image with a powershell provisioner task.

### Packer version

1.5.6

### Operating system and Environment details

docker packer:light

### Log Fragments and crash.log files
<details>
 <summary>Log</summary>
16:44:49 DOCKER: ==> vsphere-iso: Provisioning with powershell script: ./scripts/get-ip.ps1
16:45:15 DOCKER: ==> vsphere-iso: Remove-Item : Cannot find path 'C:\Windows\Temp\script-5eb328c2-39b3-38a7-85eb-ff58af5ee92c.ps1' because it does not
16:45:15 DOCKER: ==> vsphere-iso: exist.
16:45:15 DOCKER: ==> vsphere-iso: At C:\Windows\Temp\packer-cleanup-5eb328c2-8d68-2c83-6532-72f695b5b2ed.ps1:3 char:1
16:45:15 DOCKER: ==> vsphere-iso: + Remove-Item c:/Windows/Temp/script-5eb328c2-39b3-38a7-85eb-ff58af5ee9 ...
16:45:15 DOCKER: ==> vsphere-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:45:15 DOCKER: ==> vsphere-iso:     + CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...f58af5ee92c.ps1:String) [Remove-Item], ItemNotFoundEx
16:45:15 DOCKER: ==> vsphere-iso:    ception
16:45:15 DOCKER: ==> vsphere-iso:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
16:45:15 DOCKER: ==> vsphere-iso:
16:45:15 DOCKER: ==> vsphere-iso: Remove-Item : Cannot find path 'C:\Windows\Temp\script-5eb328c2-39b3-38a7-85eb-ff58af5ee92c.ps1' because it does not
16:45:15 DOCKER: ==> vsphere-iso: exist.
16:45:15 DOCKER: ==> vsphere-iso: At C:\Windows\Temp\packer-cleanup-5eb328c2-8d68-2c83-6532-72f695b5b2ed.ps1:4 char:1
16:45:15 DOCKER: ==> vsphere-iso: + Remove-Item c:/Windows/Temp/script-5eb328c2-39b3-38a7-85eb-ff58af5ee9 ...
16:45:15 DOCKER: ==> vsphere-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
16:45:15 DOCKER: ==> vsphere-iso:     + CategoryInfo          : ObjectNotFound: (C:\Windows\Temp...f58af5ee92c.ps1:String) [Remove-Item], ItemNotFoundEx
16:45:15 DOCKER: ==> vsphere-iso:    ception
16:45:15 DOCKER: ==> vsphere-iso:     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
16:45:15 DOCKER: ==> vsphere-iso:
</details>

### LINKED ISSUE #9189: failed to create a remote cleanup script (401 - invalid content type)
#### Overview of the Issue

After successfully executing provisioner scripts, packer enters a(n apparently endless) loop while attempting to upload a cleanup script.

### Packer version

Packer v1.5.6

### Simplified Packer Buildfile

In this simplified build file, I have removed my own provisioner scripts, but left in the final, necessary Windows init/sysprep script.

The `user_data_file` is this script: [`ec2-userdata.ps1`](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/4a59c7da8e38bb867305c025d7aa50d1eadb9988/packer/windows/scripts/ec2-userdata.ps1), unchanged from the [Buildkite Elastic CI Stack](https://github.com/buildkite/elastic-ci-stack-for-aws/tree/master/packer/windows) version.

<details>

```json
{
  "variables": {
    "region": "ap-southeast-2"
  },
  "builders": [
    {
      "type": "amazon-ebs",
      "region": "{{user `region`}}",
      "source_ami_filter": {
        "filters": {
          "name": "buildkite-stack-windows-*"
        },
        "owners": ["172840064832"],
        "most_recent": true
      },
      "instance_type": "t3.large",
      "spot_price": "auto",
      "user_data_file": "ec2-userdata.ps1",

      "communicator": "winrm",
      "ssh_interface": "public_ip",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,

      "ami_name": "my-buildkite-windows-{{isotime | clean_resource_name}}",
      "ami_description": "Buildkite Elastic Stack (Windows Server 2019)"
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "inline": [
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule",
        "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown"
      ]
    }
  ]
}

```

</details>

### Operating system and Environment details

Client: mac OS 10.15.4, packer from brew

Building: Windows Server 2019.

My customisation starts from `ami-0679552e4c522cd16`, which was built with this [Buildkite Elastic CI Stack template](https://github.com/buildkite/elastic-ci-stack-for-aws/tree/master/packer/windows). (You can tell they're using an older version of Packer because they use `clean_ami_name`.)

### Log Fragments and crash.log files

This log fragment shows the final successful provisioner scripts running, then the first two attempts to upload the cleanup script:

<details>

```
==> amazon-ebs: Provisioning with Powershell...
2020/05/08 13:13:16 packer-provisioner-powershell plugin: Found command: C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule
2020/05/08 13:13:16 packer-provisioner-powershell plugin: Found command: C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown
==> amazon-ebs: Provisioning with powershell script: /var/folders/_y/zz075bh11vb_qt1cm1l6nyxh0000gp/T/powershell-provisioner062842281
2020/05/08 13:13:16 packer-provisioner-powershell plugin: Opening /var/folders/_y/zz075bh11vb_qt1cm1l6nyxh0000gp/T/powershell-provisioner062842281 for reading
2020/05/08 13:13:16 packer-provisioner-powershell plugin: Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5eb4cafd-d618-508a-95d8-02335fcdc570.ps1
2020/05/08 13:13:16 packer-provisioner-powershell plugin: [INFO] 76 bytes written for 'uploadData'
2020/05/08 13:13:16 [INFO] 76 bytes written for 'uploadData'
2020/05/08 13:13:16 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5eb4cafd-d618-508a-95d8-02335fcdc570.ps1'
2020/05/08 13:13:17 packer-builder-amazon-ebs plugin: #< CLIXML
2020/05/08 13:13:18 packer-builder-amazon-ebs plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/05/08 13:13:18 packer-provisioner-powershell plugin: [INFO] 163 bytes written for 'uploadData'
2020/05/08 13:13:18 [INFO] 163 bytes written for 'uploadData'
2020/05/08 13:13:18 packer-builder-amazon-ebs plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Uploading file to 'c:/Windows/Temp/script-5eb4cafd-3169-b04d-430f-3149d0b761af.ps1'
2020/05/08 13:13:19 packer-builder-amazon-ebs plugin: #< CLIXML
2020/05/08 13:13:19 packer-builder-amazon-ebs plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>#< CLIXML
2020/05/08 13:13:19 packer-builder-amazon-ebs plugin: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>[INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5eb4cafd-d618-508a-95d8-02335fcdc570.ps1; &'c:/Windows/Temp/script-5eb4cafd-3169-b04d-430f-3149d0b761af.ps1'; exit $LastExitCode }"
    amazon-ebs:
    amazon-ebs: TaskPath                                       TaskName                          State
    amazon-ebs: --------                                       --------                          -----
    amazon-ebs: \                                              Amazon Ec2 Launch - Instance I... Ready
2020/05/08 13:15:13 packer-builder-amazon-ebs plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5eb4cafd-d618-508a-95d8-02335fcdc570.ps1; &'c:/Windows/Temp/script-5eb4cafd-3169-b04d-430f-3149d0b761af.ps1'; exit $LastExitCode }"' exited with code: 0
2020/05/08 13:15:13 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/05/08 13:15:13 [INFO] 0 bytes written for 'stderr'
2020/05/08 13:15:13 [INFO] 281 bytes written for 'stdout'
2020/05/08 13:15:13 [INFO] RPC client: Communicator ended with: 0
2020/05/08 13:15:13 [INFO] RPC endpoint: Communicator ended with: 0
2020/05/08 13:15:13 packer-provisioner-powershell plugin: [INFO] 281 bytes written for 'stdout'
2020/05/08 13:15:13 packer-provisioner-powershell plugin: [INFO] 0 bytes written for 'stderr'
2020/05/08 13:15:13 packer-provisioner-powershell plugin: [INFO] RPC client: Communicator ended with: 0
2020/05/08 13:15:13 packer-provisioner-powershell plugin: c:/Windows/Temp/script-5eb4cafd-3169-b04d-430f-3149d0b761af.ps1 returned with exit code 0
2020/05/08 13:15:13 packer-provisioner-powershell plugin: [INFO] 248 bytes written for 'uploadData'
2020/05/08 13:15:13 [INFO] 248 bytes written for 'uploadData'
2020/05/08 13:15:13 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1'
2020/05/08 13:15:13 packer-provisioner-powershell plugin: failed to create a remote cleanup script: clean up script "c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1" failed to upload: Error uploading file to $env:TEMP\winrmcp-f616b785-8be2-4965-7228-2d7c6e430b38.tmp: Couldn't create shell: http response error: 401 - invalid content type
2020/05/08 13:15:13 packer-provisioner-powershell plugin: Retryable error: clean up script "c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1" failed to upload: Error uploading file to $env:TEMP\winrmcp-f616b785-8be2-4965-7228-2d7c6e430b38.tmp: Couldn't create shell: http response error: 401 - invalid content type
2020/05/08 13:15:15 packer-provisioner-powershell plugin: [INFO] 248 bytes written for 'uploadData'
2020/05/08 13:15:15 [INFO] 248 bytes written for 'uploadData'
2020/05/08 13:15:15 packer-builder-amazon-ebs plugin: Uploading file to 'c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1'
2020/05/08 13:15:15 packer-provisioner-powershell plugin: failed to create a remote cleanup script: clean up script "c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1" failed to upload: Error uploading file to $env:TEMP\winrmcp-5eeffbc5-a86e-4eb4-58fd-ebdb49dda763.tmp: Couldn't create shell: http response error: 401 - invalid content type
2020/05/08 13:15:15 packer-provisioner-powershell plugin: Retryable error: clean up script "c:/Windows/Temp/packer-cleanup-5eb4cafd-4459-2433-dc89-a74b7f2598ea.ps1" failed to upload: Error uploading file to $env:TEMP\winrmcp-5eeffbc5-a86e-4eb4-58fd-ebdb49dda763.tmp: Couldn't create shell: http response error: 401 - invalid content type
```

</details>

### PR DESCRIPTION
**Pull request by nywilken**
This change reduces the retry timeout from 5m to 1m, and sets the RetryDelay to 10s for a total of 6 retries. In additional to the retry time reduction the cleanup script will now check to see if the provisioner script created by Packer exists before trying to delete to prevent any file not found issues.

Closes #9181
Closes #9189

### CODE REVIEW

File: provisioner/powershell/provisioner.go [hunk 1]
```diff
@@ -335,18 +335,18 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
 		return nil
 	}
 
-	err := retry.Config{StartTimeout: p.config.StartRetryTimeout}.Run(ctx, func(ctx context.Context) error {
+	err := retry.Config{StartTimeout: time.Minute, RetryDelay: func() time.Duration { return 10 * time.Second }}.Run(ctx, func(ctx context.Context) error {
```
Comment (azr) [inline provisioner/powershell/provisioner.go:338]: Nice ! I was worried about changing the default of `p.config.StartRetryTimeout` but this is retrying the cleanup phase which is something else !
