### PR TITLE
Make expunge optional and improve logging output

### LINKED ISSUE #5097: Request for configurable Expunge in Cloudstack Builder
Within the Cloudstack builder, because builder/cloudstack/step_create_instance.go (lines 122-123) explicitly force an expunge operation, the implication is that an Administrative user is required to run Packer against it.  Can we make this a configurable option, please?  This way we can use non-admin users and the build doesn't crash out with:

2017/07/05 15:47:51 ui error: ==> cloudstack: Error destroying instance: Undefined error: {"errorcode":530,"errortext":"Parameter expunge can be passed by Admin only. Or when the allow.user.expunge.recover.vm key is set."}
2017/07/05 15:47:51 ui:     cloudstack: Instance has been deleted!
==> cloudstack: Error destroying instance: Undefined error: {"errorcode":530,"errortext":"Parameter expunge can be passed by Admin only. Or when the allow.user.expunge.recover.vm key is set."}
    cloudstack: Instance has been deleted!

And ends up leaving the instance in place, unfortunately.

While we could just as easily set allow.user.expunge.recover.vm to "true", we currently depend upon events generated by instance deletion and would thus prefer the ability to disable the forced expunge.

Cloudstack 4.8
Packer 1.0.2 running on Mac OSX 10.12.5 creating a CentOS 7 instance

Thanks!

P.S. - Yes Matt - it's THAT Ian again. :)

### PR DESCRIPTION
**Pull request by svanharmelen**
@rickard-von-essen in a way this PR introduces a backwards incompatibility, yet it is a very minor one... Currently the default is to set the `expunge` options to `true`, which means if you destroy the instance it will be expunged immediately.

This PR changes the default to `false` which means that when you delete the instance it will not be expunged immediately, but after the timeout configured in your CloudStack setup. So it will still be expunged, just not immediately anymore.

What do you think abou that? I guess the only possible impact could be that when you are iterating/testing a new build, have a fixed hostname and try to restart a new build before the configured expunge timeout has passed, the expunge has not yet taken place and you will get an error that you cannot create the new instance because one with that name already exists.

In those cases people will have to set the `expunge` option to `true` in their templates.

Closes #5097

### CODE REVIEW

**Comment by rickard-von-essen** [comment]
I think that is fine since it doesn't change the outcome over time.

**Comment by svanharmelen** [comment]
Cool, then I'll will go ahead and merge this one... Thx.

**Comment by rickard-von-essen** [comment]
See my comment in the original issue.

File: builder/cloudstack/step_create_instance.go [hunk 1]
```diff
@@ -161,11 +162,13 @@ func (s *stepCreateInstance) Cleanup(state multistep.StateBag) {
 			return
 		}
 
-		ui.Error(fmt.Sprintf("Error destroying instance: %s", err))
+		ui.Error(fmt.Sprintf("Error destroying instance. Please destroy it manually.\n\n"+
+			"\tName: %s\n"+
+			"\tError: %s", config.InstanceName, err))
+		return
```
Comment (rickard-von-essen) [inline builder/cloudstack/step_create_instance.go]: IMHO I still think we should retry without expunge. You can see it as two actions _mark for deletion_ and _remove now_. If we always can do the first we should do it. It ensures that no instances are laying arround.

Comment (svanharmelen) [inline builder/cloudstack/step_create_instance.go]: Done...

File: builder/cloudstack/step_create_instance.go [hunk 2]
```diff
@@ -162,23 +154,53 @@ func (s *stepCreateInstance) Cleanup(state multistep.StateBag) {
...
+		return "", fmt.Errorf("Error rendering user_data: %s", err)
+	}
 
-	// deployVirtualMachine uses POST by default, so max userdata is 32K
-	maxUD := 32768
+	ud := base64.StdEncoding.EncodeToString([]byte(renderedUserData))
 
+	// DeployVirtualMachine uses POST by default which allows 32K of
+	// userdata. If using GET instead the userdata is limited to 2K.
+	maxUD := 32768
```
Comment (rickard-von-essen) [inline builder/cloudstack/step_create_instance.go]: Could you comment on this change if it was intentional.

**Comment by rickard-von-essen** [comment]
Feel free to merge, I'm off from my computer.

File: builder/cloudstack/step_create_instance.go (hunk 2 above)
Comment (svanharmelen) [inline builder/cloudstack/step_create_instance.go]: Yes, it was intentional. Functionally nothing changed, just wanted to cleanup and condense the code a bit.

Comment (rickard-von-essen) [inline builder/cloudstack/step_create_instance.go]: Check
