### PR TITLE
[HPR-817] command/validate: add option to eval datasources

### LINKED ISSUE #11294: packer validate failures when using the data "sshkey" source
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

I originally reported this as https://github.com/ivoronin/packer-plugin-sshkey/issues/3, but it seems to be an issue in packer itself; there doesn't seem to be anything a datasource plugin can do to make validate work.

#### Reproduction Steps

packer validate sshkey.pkr.hcl` fails with

> Error: 1 error(s) occurred:
> 
> * ssh_private_key_file is invalid: CreateFile <unknown>: The filename, directory name, or volume label syntax is incorrect.
> 
>   on sshkey.pkr.hcl line 12:
>   (source code not available)

(the same is true for real builders, but this minimal example shows the issue)
### Packer version

1.7.5

### Simplified Packer Buildfile

<details>
<summary>sshkey.pkr.hcl</summary>

```hcl
packer {
  required_plugins {
    sshkey = {
      version = ">= 0.1.0"
      source = "github.com/ivoronin/sshkey"
    }
  }
}

data "sshkey" "packer" {}

source "null" "test" {
#  cd_content = {
#    meta-data = "instance-id: \"${uuidv4()}\""
#    user-data = <<-EOF
#      #cloud-config
#      ssh_authorized_keys:
#        - ${data.sshkey.packer.public_key}
#      EOF
#  }
#  cd_label             = "cidata"
  communicator         = "ssh"
  ssh_host             = "localhost"
  ssh_private_key_file = data.sshkey.packer.private_key_path
  ssh_username         = "root"
}

build {
  sources = ["source.null.test"]
}
```

</details>

### Operating system and Environment details

Windows 10 x64 20H2, but it doesn't  really matter

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

<details>
<summary>PACKER_LOG=1 packer validate sshkey.pkr.hcl</summary>

```
2021/09/28 19:38:47 [INFO] Packer version: 1.7.5 [go1.17.1 windows amd64]
2021/09/28 19:38:47 [TRACE] discovering plugins in C:\Program Files\bin
2021/09/28 19:38:47 [TRACE] discovering plugins in C:\Users\re41236\AppData\Roaming\packer.d\plugins
2021/09/28 19:38:47 [TRACE] discovering plugins in .
2021/09/28 19:38:47 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/09/28 19:38:47 [INFO] PACKER_CONFIG env var set; attempting to open config file: C:\Users\re41236\AppData\Roaming\packer.config
2021/09/28 19:38:47 [WARN] Config file doesn't exist: C:\Users\re41236\AppData\Roaming\packer.config
2021/09/28 19:38:47 [INFO] Setting cache directory: C:\projects\FOCUS\automation-templates\packer_cache
e: cannot determine if process is in background: Process background check error: not implemented yet
2021/09/28 19:38:47 [TRACE] listing potential installations for "github.com/ivoronin/sshkey" that match ">= 0.1.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"C:\\Program Files\\bin\\packer.exe", ".", "C:\\Users\\re41236\\AppData\\Roaming\\packer.d\\plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"windows", ARCH:"amd64", Ext:".exe", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc00081e900)}}}}
2021/09/28 19:38:47 [TRACE] Found the following "github.com/ivoronin/sshkey" installations: [{C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe v0.1.0}]
2021/09/28 19:38:47 found external [-packer-default-plugin-name-] datasource from sshkey plugin
2021/09/28 19:38:47 [TRACE] Starting external plugin C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe start datasource -packer-default-plugin-name-
2021/09/28 19:38:47 Starting plugin: C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe []string{"C:\\Users\\re41236\\AppData\\Roaming\\packer.d\\plugins\\github.com\\ivoronin\\sshkey\\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe", "start", "datasource", "-packer-default-plugin-name-"}
2021/09/28 19:38:47 Waiting for RPC address for: C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe
2021/09/28 19:38:47 packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe plugin: 2021/09/28 19:38:47 Plugin port range: [10000,25000]
2021/09/28 19:38:47 packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe plugin: 2021/09/28 19:38:47 Plugin address: tcp 127.0.0.1:10000
2021/09/28 19:38:47 packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe plugin: 2021/09/28 19:38:47 Waiting for connection...
2021/09/28 19:38:47 Received tcp RPC address for C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe: addr is 127.0.0.1:10000
2021/09/28 19:38:47 packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe plugin: 2021/09/28 19:38:47 Serving a plugin connection...
2021/09/28 19:38:47 packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe plugin: 2021/09/28 19:38:47 [TRACE] starting datasource -packer-default-plugin-name-
2021/09/28 19:38:47 [TRACE] Starting internal plugin packer-builder-null
2021/09/28 19:38:47 Starting plugin: C:\Program Files\bin\packer.exe []string{"C:\\Program Files\\bin\\packer.exe", "plugin", "packer-builder-null"}
2021/09/28 19:38:47 Waiting for RPC address for: C:\Program Files\bin\packer.exe
2021/09/28 19:38:47 packer.exe plugin: [INFO] Packer version: 1.7.5 [go1.17.1 windows amd64]
2021/09/28 19:38:47 packer.exe plugin: [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/09/28 19:38:47 packer.exe plugin: [INFO] PACKER_CONFIG env var set; attempting to open config file: C:\Users\re41236\AppData\Roaming\packer.config
2021/09/28 19:38:47 packer.exe plugin: [WARN] Config file doesn't exist: C:\Users\re41236\AppData\Roaming\packer.config
2021/09/28 19:38:47 packer.exe plugin: [INFO] Setting cache directory: C:\projects\FOCUS\automation-templates\packer_cache
2021/09/28 19:38:47 packer.exe plugin: args: []string{"packer-builder-null"}
2021/09/28 19:38:47 packer.exe plugin: Plugin port range: [10000,25000]
2021/09/28 19:38:47 packer.exe plugin: Plugin address: tcp 127.0.0.1:10000
Error: 1 error(s) occurred:
2021/09/28 19:38:47 Received tcp RPC address for C:\Program Files\bin\packer.exe: addr is 127.0.0.1:10000
2021/09/28 19:38:47 packer.exe plugin: Waiting for connection...

2021/09/28 19:38:47 packer.exe plugin: Serving a plugin connection...
* ssh_private_key_file is invalid: CreateFile <unknown>: The filename, directory name, or volume label syntax is incorrect.


  on sshkey.pkr.hcl line 12:
  (source code not available)


* ssh_private_key_file is invalid: CreateFile <unknown>: The filename, directory name, or volume label syntax is incorrect.

  on sshkey.pkr.hcl line 12:
  (source code not available)

2021/09/28 19:38:47 [INFO] (telemetry) Finalizing.
2021/09/28 19:38:48 waiting for all plugin processes to complete...
2021/09/28 19:38:48 C:\Program Files\bin\packer.exe: plugin process exited
2021/09/28 19:38:48 C:\Users\re41236\AppData\Roaming\packer.d\plugins\github.com\ivoronin\sshkey\packer-plugin-sshkey_v0.1.0_x5.0_windows_amd64.exe: plugin process exited
```
</details>

### PR DESCRIPTION
**Pull request by lbajolet-hashicorp**
When packer validate is invoked, it does not try to evaluate the datasources before attempting to decide if the template is valid.

In many cases, this works, but sometimes it will fail as the value is unknown by the validation code.

Since the validation code for all the elements of a Packer template is left to be implemented by plugins, we cannot rely on checking for unknown values everywhere, especially since the unknown references are replaced automatically by a value of the right type for the configuration expected.

So, in order for such configurations to be validable, we add an extra option to packer validate, that will let users evaluate the datasources from a template.

Closes #11294

### CODE REVIEW

File: command/cli.go [hunk 1]
```diff
@@ -129,14 +129,16 @@ type FixArgs struct {
 
 func (va *ValidateArgs) AddFlagSets(flags *flag.FlagSet) {
 	flags.BoolVar(&va.SyntaxOnly, "syntax-only", false, "check syntax only")
+	flags.BoolVar(&va.EvaluateDatasources, "evaluate-datasources", false, "evaluate datasources for validation (may incur costs)")
```
Comment (nywilken) [inline command/cli.go:132]: I'm not sure on the copy but should we indicate that this is for HCL2 templates only?

**Review by nywilken — APPROVED** [review]
This looks good to me. I'm leaving it open for a the weekend in case posters on the original issue have comments or thoughts in response to your last comment.

File: command/cli.go (hunk 1 above)
Comment (lbajolet-hashicorp) [reply command/cli.go:132]: I can add this in the message sure, doesn't hurt to be precise

**Comment by nywilken** [comment]
With the latest validation option changes this PR needs to be rebased. We also need to update the documented flags for the validate command. https://developer.hashicorp.com/packer/docs/commands/validate

I suggest adding more details to the flag description about possibly incurring cost for some datasource evaluations.

File: website/content/docs/commands/build.mdx [hunk 2]
```diff
@@ -58,3 +58,12 @@ artifacts that are created will be outputted at the end of the build.
...
 - `-var-file` - Set template variables from a file.
+
+- `-warn-on-undeclared-var` - Warn when the template assigns undeclared
+  variables. This is especially relevant for HCL2 templates with .pkrvars.hcl
+  dependencies, as defining a value for a variable is not enough on its own for
+  Packer to function, there also needs to be some variable definitions in the
+  template. However, for some cases, templates may only declare what they locally
+  need for building, and reference a global variable file with more variable
+  assignations than there are definitions. This would yield a warning for each
+  assigned and non-declared variable. This option will enable those warnings.
```
Comment (nywilken) [inline website/content/docs/commands/build.mdx:69]: Small copy change. What do you think?
```suggestion
- `-warn-on-undeclared-var` - Setting this flag will yield a warning for each assignment within a variable definitions file (*.pkrvars.hcl | *.pkrvars.json) that does not have an accompanying variable block. This can occur when using a var-file that contains a large amount of unused variables for a given HCL2 template. For HCL2 template builds defining a value for a variable in a var-file is not enough on its own for Packer to function, as there also needs to be a variable block definition in the template files `pkr.hcl` for the variable. By default `packer build` will not warn when a var-file contains one or more undeclared variables. 
```

File: website/content/docs/commands/validate.mdx [hunk 3]
```diff
@@ -31,6 +31,12 @@ Errors validating build 'vmware'. 1 error(s) occurred:
 - `-syntax-only` - Only the syntax of the template is checked. The
   configuration is not validated.
 
+- `-evaluate-datasources` - Evaluate the datasources when validating the template.
+  This is only valid on HCL2 templates, since JSON templates do not feature
+  datasources, this option will be ignored. Note that because datasources may rely
+  on external services for fetching data, this will incur some costs at validation
+  when the services being contacted are billing for the operation.
+
```
Comment (nywilken) [inline website/content/docs/commands/validate.mdx:39]: Slight reword with a call out for the billing warning 
```suggestion
- `-evaluate-datasources` - Evaluate all data sources when validating a template.
  This is only valid on HCL2 templates, since JSON templates do not feature
  data sources. For JSON templates this flag will be ignored. 
  
  ~> **Warning:** Data sources may rely on external services for fetching data, which can incur some costs at validation if the services being contacted are billing per operation.
```

File: website/content/docs/commands/validate.mdx [hunk 4]
```diff
@@ -39,6 +45,15 @@ Errors validating build 'vmware'. 1 error(s) occurred:
...
 
+- `-no-warn-on-undeclared-var` - Silence warnings when the template assigns
+  undeclared variables. This is especially relevant for HCL2 templates with
+  .pkrvars.hcl dependencies, as defining a value for a variable is not enough on
+  its own for Packer to function, there also needs to be some variable definitions
+  in the template. However, for some cases, templates may only declare what they
+  locally need for building, and reference a global variable file with more variable
+  assignations than there are definitions. This would yield a warning for each
+  assigned and non-declared variable. This option will disable those warnings.
+
```
Comment (nywilken) [inline website/content/docs/commands/validate.mdx:56]:
```suggestion
- `-no-warn-on-undeclared-var` - Silence warnings when the a variable definition file contains variable assignments for undeclared variables. This can occur when using a var-file that contains a large amount of unused variables for a given HCL2 template. For HCL2 template defining a value for a variable in a var-file is not enough on its own for Packer to function, as there also needs to be a variable block definition in the template files `pkr.hcl` for the variable. By default `packer validate` will warn when a var-file contains one or more undeclared variables. 
```

**Review by nywilken — APPROVED** [review]
I left a few suggestions to the documentation. Feel free to reword if you like or merge when ready. Approving in advance.
