### PR TITLE
[WIP] Handle HTTP download errors

### LINKED ISSUE #6203: ISO download - HTTP Not Found error is reported as checksum error
**Environment**:

Packer v1.2.3
Fedora 27 x86_64

**Summary**:

A 404 error while downloading the ISO file is reported as a checksum error.

```
packer build centos7.json 
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: ec7500d4b006702af6af023b1f8f1b890b6c7ee54400bb98cef968b883cd6546
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
```

**Detailed Error**:

```
2018/04/26 11:04:42 Build debug mode: false
2018/04/26 11:04:42 Force build: false
2018/04/26 11:04:42 On error: 
2018/04/26 11:04:42 Preparing build: virtualbox-iso
2018/04/26 11:04:42 Waiting on builds to complete...
2018/04/26 11:04:42 Starting build run: virtualbox-iso
2018/04/26 11:04:42 Running builder: virtualbox-iso
2018/04/26 11:04:42 [INFO] (telemetry) Starting builder virtualbox-iso
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 VBoxManage path: /usr/bin/VBoxManage
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 VBoxManage --version output: 5.2.10r122088
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 VirtualBox version: 5.2.10
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 guest_additions_url is blank; querying driver for iso.
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Found Default Guest Additions ISO: /usr/share/virtualbox/VBoxGuestAdditions.iso
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Guest additions URL: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
2018/04/26 11:04:42 ui: ==> virtualbox-iso: Downloading or copying Guest additions
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Acquiring lock to download: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
2018/04/26 11:04:42 ui:     virtualbox-iso: Downloading or copying: file:///usr/share/virtualbox/VBoxGuestAdditions.iso
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/usr/share/virtualbox/VBoxGuestAdditions.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 [DEBUG] Using local file: /usr/share/virtualbox/VBoxGuestAdditions.iso
2018/04/26 11:04:42 ui: ==> virtualbox-iso: Downloading or copying ISO
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Acquiring lock to download: http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
2018/04/26 11:04:42 ui:     virtualbox-iso: Downloading or copying: http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Parsed URL: &url.URL{Scheme:"http", Opaque:"", User:(*url.Userinfo)(nil), Host:"centos.bhs.mirrors.ovh.net", Path:"/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 [DEBUG] Downloading: http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
2018/04/26 11:04:42 packer: 2018/04/26 11:04:42 Starting download over HTTP: http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
2018/04/26 11:04:44 packer: 2018/04/26 11:04:44 Verifying checksum of /home/gtirloni/code/idi-ops/packer-centos/packer_cache/82033202c5b6577463e1216fdee605c01aa0eaccad9c5a84bdac8dad41a1fba4.iso
2018/04/26 11:04:44 ui:     virtualbox-iso: Error downloading: checksums didn't match expected: ec7500d4b006702af6af023b1f8f1b890b6c7ee54400bb98cef968b883cd6546
2018/04/26 11:04:44 ui error: ==> virtualbox-iso: ISO download failed.
2018/04/26 11:04:44 [INFO] (telemetry) ending virtualbox-iso
2018/04/26 11:04:44 ui error: Build 'virtualbox-iso' errored: ISO download failed.
2018/04/26 11:04:44 Builds completed. Waiting on interrupt barrier...
2018/04/26 11:04:44 machine readable: error-count []string{"1"}
2018/04/26 11:04:44 ui error: 
==> Some builds didn't complete successfully and had errors:
2018/04/26 11:04:44 machine readable: virtualbox-iso,error []string{"ISO download failed."}
2018/04/26 11:04:44 ui error: --> virtualbox-iso: ISO download failed.
2018/04/26 11:04:44 ui: 
==> Builds finished but no artifacts were created.
2018/04/26 11:04:44 [INFO] (telemetry) Finalizing.
2018/04/26 11:04:45 waiting for all plugin processes to complete...
2018/04/26 11:04:45 /home/gtirloni/bin/packer: plugin process exited
2018/04/26 11:04:45 /home/gtirloni/bin/packer: plugin process exited
2018/04/26 11:04:45 /home/gtirloni/bin/packer: plugin process exited
```

**Additional Information**:

```
$ curl -v http://centos.bhs.mirrors.ovh.net/ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso
*   Trying 213.32.5.7...
* TCP_NODELAY set
* Connected to centos.bhs.mirrors.ovh.net (213.32.5.7) port 80 (#0)
> GET /ftp.centos.org/7.4.1708/isos/x86_64/CentOS-7-x86_64-DVD-1708.iso HTTP/1.1
> Host: centos.bhs.mirrors.ovh.net
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.6.2
< Date: Thu, 26 Apr 2018 14:00:51 GMT
< Content-Type: text/html
< X-Varnish: 19139690
< Age: 0
< Via: 1.1 varnish-v4
< Transfer-Encoding: chunked
< X-IPLB-Instance: 5868
< 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
* Connection #0 to host centos.bhs.mirrors.ovh.net left intact
```

### PR DESCRIPTION
**Pull request by gtirloni**
Checks for HTTP error codes (400-599) in both HEAD and GET operations (a failure in the latter should be rare if the former worked but it still seems possible).

Closes #6203

### CODE REVIEW

**Comment by gtirloni** [comment]
This is my first code PR and I'd appreciate any feedback.

File: common/download.go [hunk 1]
```diff
@@ -290,6 +290,8 @@ func (d *HTTPDownloader) Download(dst *os.File, src *url.URL) error {
 				}
 			}
 		}
+	} else if err != nil || (resp.StatusCode >= 400 && resp.StatusCode < 600) {
+		return fmt.Errorf("%s", resp.Status)
```
Comment (SwampDragons) [inline common/download.go]: I'd like a slightly more descriptive error message explaining when this is failing.
