### PR TITLE
fix hyper-v admin check

### LINKED ISSUE #5216: PowerShell failure with Hyper-V builder
BUG-ish:

I'm having an issue trying to create a Hyper-V image for Ubuntu 16.04 LTS. This seemed like a pretty simple use case (as seen in the template) and there a ton of examples. However, I'm getting an odd security error from PowerShell. 

- Packer Version: 1.0.3
- Host platform: Windows 10 Pro
- Debug output: [gist](https://gist.github.com/mikejr83/5e6cb5cbc3d53395fafc1971401c2115)
- Template: [gist](https://gist.github.com/mikejr83/693ada2b7e4446991aeb9781eeb07f4b)

PowerShell execution failure: 

    hyperv-iso: Failed creating Hyper-V driver: PowerShell error: Exception calling "IsInRole" with "1" argument(s): "The trust relationship between the primary domain and the trusted domain failed.

PowerShell script contents:

    ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('S-1-5-32-578')
  
So it looks like it's trying to see if the current user is in the Hyper V Administrators group. Is there a way to bypass this check? For some reason on my development machine it fails.

### PR DESCRIPTION
**Pull request by mwhooker**
Fixes #5216

### CODE REVIEW

File: builder/hyperv/common/driver_ps_4.go [hunk 1]
```diff
@@ -291,33 +291,44 @@ func (d *HypervPS4Driver) verifyPSHypervModule() error {
...
-
-	log.Printf("Enter method: %s", "verifyHypervPermissions")
-
+func (d *HypervPS4Driver) isCurrentUserAHyperVAdministrator() (bool, error) {
 	//SID:S-1-5-32-578 = 'BUILTIN\Hyper-V Administrators'
 	//https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems
-	hypervAdminCmd := "([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole('S-1-5-32-578')"
+
+	var script = `
+$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
```
Comment (SwampDragons) [inline builder/hyperv/common/driver_ps_4.go]: Will this work in other languages?  I remember there was an issue when checking for whether someone was an administrator in the normal windows OS.

File: common/powershell/powershell.go [hunk 2]
```diff
@@ -17,6 +17,14 @@ const (
 	powerShellTrue  = "True"
 )
 
+func IsTrue(s string) bool {
```
Comment (SwampDragons) [inline common/powershell/powershell.go]: This is a nice little abstraction.
