### PR TITLE
Remove ansible proxy

### LINKED ISSUE #5419: Ansible provisioner should not clean up until after -on-error=ask
When running a packer build with -on-error=ask, and when using the ansible provisioner, and the ansible build fails, the container is left running while packer waits for you to answer the -on-error prompt. This gives one an opportunity to debug the failed build before cleanup happens.

The obvious way to debug the issue is to re-run the ansible command that the provisioner ran (maybe after making some changes to the playbooks). Unfortunately this does not work, for a few reasons:

1. The ansible provisioner creates a temporary inventory file, which one can see on the command-line as a parameter like "-i /tmp/packer-provisioner-ansible981180270". But this temporary file is deleted, even before one answers the -on-error prompt.

2. Even if one preservers the contents of the temporary inventory file, one still can not re-run the ansible command. The temporary forwarded port used by the SSH communicator to communicate with the virtualbox guest is also deleted at this point.

Both of the above resources should only be cleaned up after one answered 'clean up' to the -on-error prompt. 

(A related cosmetic issue has already been reported as issue #5412 : the ansible command line that the provisioner prints has no shell escaping, and thus can not be executed via straight copy & paste).

### LINKED ISSUE #6196: Packer + Ansible + Windows: Script modules not working
Describe the problem and include the following information:

Executing Script module in Ansible 2.4.1.0 via Packer 1.1.1 to Windows 2012R2 Instance in AWS.  Script module is executing a powershell script, and fails with below error.  The Ansible playbook can run successfully if run directly via ansible to the same temporary instance created by Packer.

amazon-ebs: TASK [winlodrest : Download all Windows Common Installers from S3 Bucket to Instance] ***
    amazon-ebs: task path: /home/ubuntu/packer-builds/packer-restwindows/roles/winlodrest/tasks/main.yml:1
 amazon-ebs: <127.0.0.1> (0, '', '')
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": true,
    amazon-ebs:     "failed": true,
    amazon-ebs:     "msg": "non-zero return code",
    amazon-ebs:     "rc": 1,
    amazon-ebs:     "stderr": "& was unexpected at this time.\r\nShared connection to 127.0.0.1 closed.\r\n",
    amazon-ebs:     "stdout": "",
    amazon-ebs:     "stdout_lines": []
    amazon-ebs: }

- Packer version 1.1.1
- Ubuntu 14.04.5
- Ansible version:
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

- Debug log output from `PACKER_LOG=1 packer build template.json`.
  https://gist.github.com/PrebleBrier/9dd9d9485d92572134d3c0b0fc95520c
- The _simplest example template and scripts_ needed to reproduce the bug.
 https://gist.github.com/PrebleBrier/5f59ddf4659c9224dd5bfb65cec406d4

### LINKED ISSUE #6379: Issues with ansible provisioner with cloud builder and local ssh proxy
Ansible bug report: https://github.com/ansible/ansible/issues/41377

Packer Version: 1.2.4
Host Platform: macOS
Debug Log: https://gist.github.com/sivel/483fd134f4d8552d6a521901b5265e5c

In the above mentioned bug report, the packer file is defined as:

```json
{
  "min_packer_version": "1.2.3",
  "builders": [
    {
      "type": "googlecompute",
      "ssh_username": "packer",
      "project_id": "<YOUR_PROJECT_ID>",
      "source_image": "ubuntu-1604-xenial-v20180522",
      "zone": "us-central1-f",
      "image_family": "repro-image",
      "image_name": "repro-bug-{{isotime | clean_image_name}}",
      "disk_type": "pd-ssd"
    }
  ],
  "provisioners": [
    {
      "type": "ansible",
      "playbook_file": "./repro-image-playbook.yml",
      "extra_arguments": [
        "--ssh-extra-args",
        "-o IdentitiesOnly=yes"
      ]
    }
  ]
}
```

We can see the `googlecompute` builder defines `"ssh_username": "packer"`, however the `ansible` provisioner does not define a `user`.

When packer creates the local ssh proxy for communicating with the google compute instance, it utilizes the `packer` user.  Due to no `user` being supplied for the `ansible` provisioner, an inventory is created that looks like the following where `ansible_user` becomes defined as `daniel`.

```
default ansible_host=127.0.0.1 ansible_user=daniel ansible_port=51644
```

The remote host does not have a user `daniel`, however due to the way that the local proxy seems to work, an ssh command specifying `-o User=daniel` is ignored, and ssh connects through the proxy to the remote instance as the `packer` user.

Later, when ansible attempts to perform temp dir building, it executes `echo ~daniel`, which fails to expand due to the lack of the `daniel` user, and produces a literal `~daniel`.

In the end this causes issues, as a directory is created at `/home/packer/~daniel`, and commands may fail to find the correct directory when using `~daniel` as it is not an absolute path.

This situation would not be possible without the local ssh proxy, that ignores the `-o User=daniel` configuration.  Otherwise, the connection would have failed with an auth error.

As it stands, this allowed ansible to think it was connecting as `daniel`, but really connected as `packer`.

### LINKED ISSUE #6877: Ansible remote provisioner hangs building CentOS VMs in Virtualbox
**Environment:**
- Host platform: OSX Sierra 10.12 / OSX Mojave 10.14 (both platforms tested independently, same behaviour)
- Packer version: 1.3.1
- Ansible version: ansible 2.7.0
- VIrtualbox version: 5.2.18
- Provisioner configuration in playbook:
```
  "provisioners": [
    {
      "type": "ansible",
  	  "playbook_file": "ansible/anscentosmgmt.yml",
      "extra_arguments": [ "-vv" ],
      "ansible_env_vars": [ "ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS='-o ControlMaster=auto -o ControlPersist=60s'" ],
      "user": "root"
    }
  ]
```

**Summary of build task:**
- Kickstart build of CentOS 7.5 VM 
- Ansible playbook carrying out basic OS config followed by application install. Playbook consists of about 10 different roles.

**Observed behaviour:**
- First of all this is not new, I have seen this behaviour in previous packer / ansible / guest OS versions over the last couple of years. It's a lot worse with CentOS7 guests - going back to CentOS6 has been the solution in the past.
- Having reviewed a number of tickets it seems this is a repeating regression - multiple tickets have been logged, fixed and closed in the past for this.
- Ansible remote provisioner will hang forever at completely random points throughout the playbook, and the issues don't seem to be ansible task type related.
- " [DEBUG] Opening new ssh session" seems to always be the last log entry, hence suspect this has to do with ssh session handling.
- However stopping the guest VM will immediately kill off the packer job, hence SSH session is assumed to be established.

**Packer logs:**
2018/10/18 16:33:33 packer: 2018/10/18 16:33:33 [DEBUG] Opening new ssh session
2018/10/18 16:33:33 packer: 2018/10/18 16:33:33 [DEBUG] starting remote command: /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1539876812.741955-174870228422670/ /root/.ansible/tmp/ansible-tmp-1539876812.741955-174870228422670/AnsiballZ_systemd.py && sleep 0'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [INFO] RPC endpoint: Communicator ended with: 0
2018/10/18 16:33:45 [INFO] 0 bytes written for 'stdout'
2018/10/18 16:33:45 [INFO] 0 bytes written for 'stderr'
2018/10/18 16:33:45 [INFO] RPC client: Communicator ended with: 0
2018/10/18 16:33:45 [INFO] RPC endpoint: Communicator ended with: 0
2018/10/18 16:33:45 [INFO] 0 bytes written for 'stdin'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [INFO] 0 bytes written for 'stdout'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [INFO] 0 bytes written for 'stderr'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [INFO] RPC client: Communicator ended with: 0
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [INFO] 0 bytes written for 'stdin'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 ansible provisioner pty-req request
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 new exec request: /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1539876812.741955-174870228422670/AnsiballZ_systemd.py && sleep 0'
2018/10/18 16:33:45 packer: 2018/10/18 16:33:45 [DEBUG] Opening new ssh session

The following appears when you shut down the guest VM:
2018/10/18 17:26:13 packer: 2018/10/18 17:26:13 [ERROR] ssh session open error: 'ssh: unexpected packet in response to channel open: <nil>', attempting reconnect
2018/10/18 17:26:13 packer: 2018/10/18 17:26:13 [DEBUG] reconnecting to TCP connection for SSH
2018/10/18 17:26:13 packer: 2018/10/18 17:26:13 [ERROR] reconnection error: dial tcp 127.0.0.1:3262: connect: connection refused
2018/10/18 17:26:13 [INFO] 0 bytes written for 'stderr'
2018/10/18 17:26:13 [INFO] 0 bytes written for 'stdout'
2018/10/18 17:26:13 [INFO] 0 bytes written for 'stdin'

### LINKED ISSUE #7667: ansible 2.8 breaks packer ansible provisioner
The recent release of ansible 2.8 (upgrade from ansible 2.7.10) appears to break the packer ansible provisioner. I am running the same packer templates and playbooks. When I run using ansible 2.8 the provisioner hangs on the gathering facts task and does not move past. I confirmed running ansible directly (without the provisioner) works properly. Everything works properly with ansible 2.7.10. 

Template snippet:

`        {
            "type": "ansible",
            "playbook_file": "/home/ubuntu/",
            "command": "ansible-playbook"
}
`

Packer –version 1.4.1 using the AWS EBS builder on an EC2 instance (details below)

Operating system details:
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### LINKED ISSUE #7680: Packer WinRM  Ansible http response error: 401
Hi 
I'm trying to build windows 2016 ami and provision it with ansible. I've following error: 

```
 ==> amazon-ebs: Provisioning with Powershell...
==> amazon-ebs: Provisioning with powershell script: /tmp/powershell-provisioner284254996
    amazon-ebs: TaskPath                                       TaskName                          State
    amazon-ebs: --------                                       --------                          -----
    amazon-ebs: \                                              Amazon Ec2 Launch - Instance I... Ready
==> amazon-ebs: Provisioning with Ansible...
==> amazon-ebs: Executing Ansible: ansible-playbook --extra-vars packer_build_name=amazon-ebs packer_builder_type=amazon-ebs -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible975257195 /home/build-server_0_playbook.yml -e ansible_ssh_private_key_file=/tmp/ansible-key377479228 --connection packer -vvv --extra-vars ansible_shell_type=powershell ansible_shell_executable=None
    amazon-ebs: ansible-playbook 2.7.5
    amazon-ebs:   config file = /etc/ansible/ansible.cfg
    amazon-ebs:   configured module search path = ['/home/pr0t/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
    amazon-ebs:   ansible python module location = /home/repositories/infra-ami/venv/lib/python3.7/site-packages/ansible
    amazon-ebs:   executable location = /venv/bin/ansible-playbook
    amazon-ebs:   python version = 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
    amazon-ebs: Using /etc/ansible/ansible.cfg as config file
    amazon-ebs: /tmp/packer-provisioner-ansible975257195 did not meet host_list requirements, check plugin documentation if this is unexpected
    amazon-ebs: /tmp/packer-provisioner-ansible975257195 did not meet script requirements, check plugin documentation if this is unexpected
    amazon-ebs: Parsed /tmp/packer-provisioner-ansible975257195 inventory source with ini plugin
    amazon-ebs:
    amazon-ebs: PLAYBOOK: build-server_0_playbook.yml **************************
    amazon-ebs: 1 plays in build-server_0_playbook.yml
    amazon-ebs:
    amazon-ebs: PLAY [build-server] ********************************************
    amazon-ebs:
    amazon-ebs: TASK [Gathering Facts] *********************************************************
    amazon-ebs: task path: build-server_0_playbook.yml:3
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: pr0t
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=46089 -o 'IdentityFile="/tmp/ansible-key377479228"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=pr0t -o ConnectTimeout=10 -o ControlPath=/home/pr0t/.ansible/cp/4a94304e09 127.0.0.1 'PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand *redacted*'
==> amazon-ebs: http response error: 401 - invalid content type
```

My setup: 

packer json file : 
 ```
"communicator": "winrm",
"user_data_file":"packer/win.cmd",
"winrm_username": "Administrator",
"winrm_timeout": "10m"
 "provisioners": [
        {
            "type": "powershell",
            "inline": [
                "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/InitializeInstance.ps1 -Schedule",
                "C:/ProgramData/Amazon/EC2-Windows/Launch/Scripts/SysprepInstance.ps1 -NoShutdown"
            ]
        },
        {
            "type":  "ansible",
            "playbook_file": "build-server_0_playbook.yml",
            "extra_arguments": [
                "--connection", "packer", 
                "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
              ]
            }
        ],
```
win.cmd:
```
<powershell>
# turn off PowerShell execution policy restrictions
Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope LocalMachine

# configure WinRM
winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="2048"}'
winrm set winrm/config/winrs '@{MaxConcurrentUsers="100"}'
winrm set winrm/config/winrs '@{MaxProcessesPerShell="0"}'
winrm set winrm/config/winrs '@{MaxShellsPerUser="0"}'
winrm set winrm/config '@{MaxTimeoutms="7200000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/service/auth '@{CredSSP="true"}'
winrm set winrm/config/client '@{TrustedHosts="*"}'


# open port 5985 in the internal Windows firewall to allow WinRM communication
netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow

net stop winrm
sc config winrm start=auto
net start winrm

</powershell>
```
 [Ansible connection plugin](https://github.com/hashicorp/packer/blob/v1.4.0/examples/ansible/connection-plugin/2.6.x/packer.py)

Versions: 
ansible 2.7.10
packer 1.4.0

### LINKED ISSUE #7979: [BUG] Ansible 2.8.3 is not able to create directory on Windows ("amazon-ebs: Parameter format not correct - ;") when is used with Packer.
### Bug description
Ansible 2.8.3 cannot create directory on Windows with (with Ansible 2.7.10 everything is fine) when is triggered by Packer.

### Packer version
```
1.4.2
```
##### OS / ENVIRONMENT
```
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```

### Reproduction
- The packer is triggered on Amazon EC2 instance.
- [Ansible playbook](https://gist.github.com/kopaczew/9e3d0ffde3719c7dddf4cc9262b98059)
- [Packer template](https://gist.github.com/kopaczew/b38cc7bd803c12dbc7ee69543c3f2661). The base AMI for Windows was prepared according to [Ansible documentation](https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html)
- [Packer connection plugin](https://github.com/hashicorp/packer/blob/master/test/fixtures/provisioner-ansible/connection_plugins/packer.py) - the documentation comment prepared according [this site](https://www.packer.io/docs/provisioners/ansible.html#winrm-communicator)
- Ansible version:
```
ansible 2.8.3
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```
The command:
```
packer build template.json
```
ends in failure ([packer logs](https://gist.github.com/kopaczew/97751e2a0b375979732327e131fbf12f))

When I install Ansible in the following versoin:
```
ansible 2.7.10
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]

```
The command:
```
packer build template.json
```
ends in success ([packer logs](https://gist.github.com/kopaczew/2eeefc891f8f3e5ee5861e522bd80389)).

I also tried to run Ansible without packer and both versions (2.7.10 and 2.8.3) can create windows directory.

### LINKED ISSUE #8383: Ansible win_reboot fails during Packer provisioning
I'm trying to reboot my Windows host during the Packer provisioning process, using Ansible.  I have the following Ansible playbook:

```
---
- hosts: all
  tasks:
  - win_reboot:
```

I'm calling it with this packer config:
```
{
    "variables": {
      "aws_profile": ""
    },
    "builders": [{
      "type": "amazon-ebs",
      "region": "eu-west-2",
      "profile": "{{user `aws_profile`}}",
      "source_ami": "ami-xxxxxxxxxxxxxx",
      "vpc_filter": {
        "filters": {
          "tag:Type": "main"
        }
      },
      "subnet_filter": {
        "filters": {
          "tag:Type": "connectivity"
        },
        "most_free": true
      },
      "iam_instance_profile": "Packer",
      "instance_type": "t3.2xlarge",
      "ami_name": "Test  {{timestamp}}",
      "user_data_file": "./user_data.ps1",
      "communicator": "winrm",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "decode_authorization_messages": true
    }],
   "provisioners": [
      {
        "type": "ansible",
        "playbook_file": "test.yml",
        "extra_arguments": [
          "--connection", "packer",
          "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
        ]
      }
    ]
  }
```

This produces the following from Ansible:
```
    amazon-ebs: TASK [win_reboot] **************************************************************
    amazon-ebs: fatal: [default]: FAILED! => {"changed": false, "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: .LastBootUpTime was unexpected at this time.\r\n", "reboot": false}
    amazon-ebs:         to retry, use: --limit @/home/user@company.com/ami-windows-core/ansible/test/test.retry
```

If I remove the provisioner, build the ami and boot an instance and then run the Ansible directly using ansible-playbook then it works as expected.  My hosts file for the manual run sets the following:
```
ansible_user=administrator 
ansible_connection=winrm 
ansible_winrm_server_cert_validation=ignore
ansible_winrm_scheme=https 
```

Not sure if this is relevant, but adding the -vvvv flag to extra_arguments seems to show the win_reboot module attempting to connect over SSH rather than WinRM.

```
    amazon-ebs: TASK [Restart host to allow Docker service to start] ***************************
    amazon-ebs: task path: /home/user@company.com/ami-windows-core/ansible/docker.yml:39
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: user@company.com
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=43737 -o 'IdentityFile="/tmp/ansible-key841056755"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user@company.com -o ConnectTimeout=10 -o ControlPath=/home/user@company.com/.ansible/cp/3a5ce3a7d3 127.0.0.1 '(Get-WmiObject -ClassName Win32_OperatingSystem).LastBootUpTime'
    amazon-ebs: <127.0.0.1> (1, b'', b'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /home/user@company.com/.ssh/config\r\ndebug1: /home/user@company.com/.ssh/config line 1: Applying options for *\r\ndebug1: /home/user@company.com/.ssh/config line 16: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 179674\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n.LastBootUpTime was unexpected at this time.\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n')
    amazon-ebs: <127.0.0.1> Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
    amazon-ebs: debug1: Reading configuration data /home/user@company.com/.ssh/config
    amazon-ebs: debug1: /home/user@company.com/.ssh/config line 1: Applying options for *
    amazon-ebs: debug1: /home/user@company.com/.ssh/config line 16: Applying options for *
    amazon-ebs: debug1: Reading configuration data /etc/ssh/ssh_config
    amazon-ebs: debug1: /etc/ssh/ssh_config line 58: Applying options for *
    amazon-ebs: debug1: auto-mux: Trying existing master
    amazon-ebs: debug2: fd 4 setting O_NONBLOCK
    amazon-ebs: debug2: mux_client_hello_exchange: master version 4
    amazon-ebs: debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
    amazon-ebs: debug3: mux_client_request_session: entering
    amazon-ebs: debug3: mux_client_request_alive: entering
    amazon-ebs: debug3: mux_client_request_alive: done pid = 179674
    amazon-ebs: debug3: mux_client_request_session: session request sent
    amazon-ebs: debug1: mux_client_request_session: master session id: 2
    amazon-ebs: .LastBootUpTime was unexpected at this time.
    amazon-ebs: debug3: mux_client_read_packet: read header failed: Broken pipe
    amazon-ebs: debug2: Received exit status from master 1
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": false,
    amazon-ebs:     "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /home/user@company.com/.ssh/config\r\ndebug1: /home/user@company.com/.ssh/config line 1: Applying options for *\r\ndebug1: /home/user@company.com/.ssh/config line 16: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 179674\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\n.LastBootUpTime was unexpected at this time.\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n",
    amazon-ebs:     "reboot": false
    amazon-ebs: }
```

### LINKED ISSUE #8446: Unable to Build Azure Windows Image with Ansible Provisioner and WinRM
Versions Used
Packer: 1.4.5
Ansible: 2.9.1
Python: 3.7

I am trying to spin up a windows VM on Azure using Packer and Ansible Provisioner. But it is failing to establish connection and there is no way I am able debug the errors since it is a lot of errors. Any Help would be great. I am posting the below Debug Logs which I get when I run the Packer build command with Packer_log=1 

```
==> azure-arm: Waiting for WinRM to become available...
2019/12/03 18:42:58 packer: 2019/12/03 18:42:58 [INFO] Attempting WinRM connection...
2019/12/03 18:42:58 packer: 2019/12/03 18:42:58 [DEBUG] connecting to remote shell using WinRM
2019/12/03 18:43:06 packer: 2019/12/03 18:43:06 Checking that WinRM is connected with: 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA'
2019/12/03 18:43:06 packer: 2019/12/03 18:43:06 [INFO] starting remote command: powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA
==> azure-arm: #< CLIXML
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 [INFO] command 'powershell.exe -EncodedCommand aQBmACAAKABUAGUAcwB0AC0AUABhAHQAaAAgAHYAYQByAGkAYQBiAGwAZQA6AGcAbABvAGIAYQBsADoAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAKQB7ACQAUAByAG8AZwByAGUAcwBzAFAAcgBlAGYAZQByAGUAbgBjAGUAPQAnAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUAJwB9ADsAIABlAGMAaABvACAAIgBXAGkAbgBSAE0AIABjAG8AbgBuAGUAYwB0AGUAZAAuACIA' exited with code: 0
    azure-arm: WinRM connected.
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 Connected to machine
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 Running the provision hook
2019/12/03 18:43:24 [INFO] (telemetry) Starting provisioner powershell
==> azure-arm: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">2</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="2"><TNRef RefId="0" /><MS><I64 N="SourceId">3</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm: Connected to WinRM!
==> azure-arm: Provisioning with Powershell...
==> azure-arm: Provisioning with powershell script: ./AnsibleSetup.ps1
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 Opening ./AnsibleSetup.ps1 for reading
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 Uploading env vars to c:/Windows/Temp/packer-ps-env-vars-5de6abfb-ca99-1024-6899-2218882f7ccd.ps1
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 [INFO] 74 bytes written for 'uploadData'
2019/12/03 18:43:24 [INFO] 74 bytes written for 'uploadData'
2019/12/03 18:43:24 packer: 2019/12/03 18:43:24 Uploading file to 'c:/Windows/Temp/packer-ps-env-vars-5de6abfb-ca99-1024-6899-2218882f7ccd.ps1'
2019/12/03 18:43:25 packer: 2019/12/03 18:43:25 [INFO] 332 bytes written for 'uploadData'
2019/12/03 18:43:25 [INFO] 332 bytes written for 'uploadData'
2019/12/03 18:43:25 packer: 2019/12/03 18:43:25 Uploading file to 'c:/Windows/Temp/script-5de6abfb-8325-56ce-6757-32c2efaa2f05.ps1'
2019/12/03 18:43:26 packer: 2019/12/03 18:43:26 [INFO] starting remote command: powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5de6abfb-ca99-1024-6899-2218882f7ccd.ps1; &'c:/Windows/Temp/script-5de6abfb-8325-56ce-6757-32c2efaa2f05.ps1'; exit $LastExitCode }"
    azure-arm: Ok.
    azure-arm:
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5de6abfb-ca99-1024-6899-2218882f7ccd.ps1; &'c:/Windows/Temp/script-5de6abfb-8325-56ce-6757-32c2efaa2f05.ps1'; exit $LastExitCode }"' exited with code: 0
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 [INFO] RPC endpoint: Communicator ended with: 0
2019/12/03 18:43:34 [INFO] 301 bytes written for 'stdout'
2019/12/03 18:43:34 [INFO] 0 bytes written for 'stderr'
    azure-arm: Listener
2019/12/03 18:43:34 [INFO] RPC client: Communicator ended with: 0
2019/12/03 18:43:34 [INFO] RPC endpoint: Communicator ended with: 0
    azure-arm:     Address = *
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 [INFO] 301 bytes written for 'stdout'
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 [INFO] 0 bytes written for 'stderr'
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 [INFO] RPC client: Communicator ended with: 0
    azure-arm:     Transport = HTTPS
    azure-arm:     Port = 5986
    azure-arm:     Hostname
    azure-arm:     Enabled = true
    azure-arm:     URLPrefix = wsman
    azure-arm:     CertificateThumbprint = D5B72F373A23928C9A90214BBD68157992BD99BC
    azure-arm:     ListeningOn = 10.0.0.4, 127.0.0.1, ::1, fe80::5efe:10.0.0.4%22, fe80::b47f:90b5:1c7f:2964%18
    azure-arm:
2019/12/03 18:43:34 packer: 2019/12/03 18:43:34 c:/Windows/Temp/script-5de6abfb-8325-56ce-6757-32c2efaa2f05.ps1 returned with exit code 0
2019/12/03 18:43:34 [INFO] (telemetry) ending powershell
2019/12/03 18:43:34 [INFO] (telemetry) Starting provisioner ansible
==> azure-arm: Provisioning with Ansible...
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 SSH proxy: serving on 127.0.0.1:5986
==> azure-arm: Executing Ansible: ansible-playbook --extra-vars packer_build_name=azure-arm packer_builder_type=azure-arm -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible482475111 /home/powerschool/tools/terraform-poc/ansible/playbooks/install-db-and-sis.yml -e ansible_ssh_private_key_file=/tmp/ansible-key091452712 --connection=packer --extra-vars= ansible_shell_type=powershell ansible_shell_executable=None ansible_become_pass=***** -vvvvv
    azure-arm: ansible-playbook 2.9.1
    azure-arm:   config file = /etc/ansible/ansible.cfg
    azure-arm:   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
    azure-arm:   ansible python module location = /usr/lib/python3.7/dist-packages/ansible
    azure-arm:   executable location = /usr/bin/ansible-playbook
    azure-arm:   python version = 3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]
    azure-arm: Using /etc/ansible/ansible.cfg as config file
    azure-arm: setting up inventory plugins
    azure-arm: host_list declined parsing /tmp/packer-provisioner-ansible482475111 as it did not pass its verify_file() method
    azure-arm: script declined parsing /tmp/packer-provisioner-ansible482475111 as it did not pass its verify_file() method
    azure-arm: auto declined parsing /tmp/packer-provisioner-ansible482475111 as it did not pass its verify_file() method
    azure-arm: Parsed /tmp/packer-provisioner-ansible482475111 inventory source with ini plugin
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm: statically imported: /home/powerschool/tools/terraform-poc/ansible/playbooks/base-setup.yml
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm: statically imported: /home/powerschool/tools/terraform-poc/ansible/playbooks/post-db-install.yml
    azure-arm: Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc
    azure-arm:
    azure-arm: PLAYBOOK: install-db-and-sis.yml ***********************************************
    azure-arm: Positional arguments: /home/powerschool/tools/terraform-poc/ansible/playbooks/install-db-and-sis.yml
    azure-arm: become_method: sudo
    azure-arm: inventory: (u'/tmp/packer-provisioner-ansible482475111',)
    azure-arm: forks: 5
    azure-arm: tags: (u'all',)
    azure-arm: extra_vars: (u'packer_build_name=azure-arm packer_builder_type=azure-arm -o IdentitiesOnly=yes', u'ansible_ssh_private_key_file=/tmp/ansible-key091452712', u' ansible_shell_type=powershell ansible_shell_executable=None ansible_become_pass=aMjrbwczRAT63vMPJUPWoFaTvqr229qv')
    azure-arm: verbosity: 5
    azure-arm: connection: packer
    azure-arm: timeout: 10
    azure-arm: 1 plays in /home/powerschool/tools/terraform-poc/ansible/playbooks/install-db-and-sis.yml
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm:
    azure-arm: PLAY [Install DB and SIS] ******************************************************
    azure-arm: META: ran handlers
    azure-arm: Read vars_file './vars/installation_variables.yml'
    azure-arm:
    azure-arm: TASK [ping] ********************************************************************
    azure-arm: task path: /home/powerschool/tools/terraform-poc/ansible/playbooks/install-db-and-sis.yml:9
    azure-arm: Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_ping.ps1
    azure-arm: Pipelining is enabled.
    azure-arm: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: packer
    azure-arm: <127.0.0.1> SSH: ansible.cfg set ssh_args: (-o)(ForwardAgent=yes)(-o)(ControlMaster=auto)(-o)(ControlPersist=60s)
    azure-arm: <127.0.0.1> SSH: ANSIBLE_HOST_KEY_CHECKING/host_key_checking disabled: (-o)(StrictHostKeyChecking=no)
    azure-arm: <127.0.0.1> SSH: ANSIBLE_REMOTE_PORT/remote_port/ansible_port set: (-o)(Port=5986)
    azure-arm: <127.0.0.1> SSH: ANSIBLE_PRIVATE_KEY_FILE/private_key_file/ansible_ssh_private_key_file set: (-o)(IdentityFile="/tmp/ansible-key091452712")
    azure-arm: <127.0.0.1> SSH: ansible_password/ansible_ssh_password not set: (-o)(KbdInteractiveAuthentication=no)(-o)(PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey)(-o)(PasswordAuthentication=no)
    azure-arm: <127.0.0.1> SSH: ANSIBLE_REMOTE_USER/remote_user/ansible_user/user/-u set: (-o)(User="packer")
    azure-arm: <127.0.0.1> SSH: ANSIBLE_TIMEOUT/timeout set: (-o)(ConnectTimeout=10)
    azure-arm: <127.0.0.1> SSH: PlayContext set ssh_common_args: ()
    azure-arm: <127.0.0.1> SSH: PlayContext set ssh_extra_args: ()
    azure-arm: <127.0.0.1> SSH: found only ControlPersist; added ControlPath: (-o)(ControlPath=/root/.ansible/cp/169091250f)
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 SSH proxy: accepted connection
    azure-arm: <127.0.0.1> SSH: EXEC ssh -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=5986 -o 'IdentityFile="/tmp/ansible-key091452712"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="packer"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/169091250f 127.0.0.1 'chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZQBBAEIAbABBAEcATQBBAFgAdwBCADMAQQBIAEkAQQBZAFEAQgB3AEEASABBAEEAWgBRAEIAeQBBAEYAOABBAGMAdwBCADAAQQBIAEkAQQBMAGcAQgBUAEEASABBAEEAYgBBAEIAcABBAEgAUQBBAEsAQQBCAEEAQQBDAGcAQQBJAGcAQgBnAEEARABBAEEAWQBBAEEAdwBBAEcAQQBBAE0AQQBCAGcAQQBEAEEAQQBJAGcAQQBwAEEAQwB3AEEASQBBAEEAeQBBAEMAdwBBAEkAQQBCAGIAQQBGAE0AQQBkAEEAQgB5AEEARwBrAEEAYgBnAEIAbgBBAEYATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBQAEEASABBAEEAZABBAEIAcABBAEcAOABBAGIAZwBCAHoAQQBGADAAQQBPAGcAQQA2AEEARgBJAEEAWgBRAEIAdABBAEcAOABBAGQAZwBCAGwAQQBFAFUAQQBiAFEAQgB3AEEASABRAEEAZQBRAEIARgBBAEcANABBAGQAQQBCAHkAQQBHAGsAQQBaAFEAQgB6AEEAQwBrAEEAQwBnAEIASgBBAEcAWQBBAEkAQQBBAG8AQQBDADAAQQBiAGcAQgB2AEEASABRAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAHUAQQBFAHcAQQBaAFEAQgB1AEEARwBjAEEAZABBAEIAbwBBAEMAQQBBAEwAUQBCAGwAQQBIAEUAQQBJAEEAQQB5AEEAQwBrAEEASQBBAEIANwBBAEMAQQBBAGQAQQBCAG8AQQBIAEkAQQBiAHcAQgAzAEEAQwBBAEEASQBnAEIAcABBAEcANABBAGQAZwBCAGgAQQBHAHcAQQBhAFEAQgBrAEEAQwBBAEEAYwBBAEIAaABBAEgAawBBAGIAQQBCAHYAQQBHAEUAQQBaAEEAQQBpAEEAQwBBAEEAZgBRAEEASwBBAEYATQBBAFoAUQBCADAAQQBDADAAQQBWAGcAQgBoAEEASABJAEEAYQBRAEIAaABBAEcASQBBAGIAQQBCAGwAQQBDAEEAQQBMAFEAQgBPAEEARwBFAEEAYgBRAEIAbABBAEMAQQBBAGEAZwBCAHoAQQBHADgAQQBiAGcAQgBmAEEASABJAEEAWQBRAEIAMwBBAEMAQQBBAEwAUQBCAFcAQQBHAEUAQQBiAEEAQgAxAEEARwBVAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEUAQQBYAFEAQQBLAEEAQwBRAEEAWgBRAEIANABBAEcAVQBBAFkAdwBCAGYAQQBIAGMAQQBjAGcAQgBoAEEASABBAEEAYwBBAEIAbABBAEgASQBBAEkAQQBBADkAQQBDAEEAQQBXAHcAQgBUAEEARwBNAEEAYwBnAEIAcABBAEgAQQBBAGQAQQBCAEMAQQBHAHcAQQBiAHcAQgBqAEEARwBzAEEAWABRAEEANgBBAEQAbwBBAFEAdwBCAHkAQQBHAFUAQQBZAFEAQgAwAEEARwBVAEEASwBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEEAQQBYAFEAQQBwAEEAQQBvAEEASgBnAEEAawBBAEcAVQBBAGUAQQBCAGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA='
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 authentication attempt from 127.0.0.1:42590 to 127.0.0.1:5986 as packer using none
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 authentication attempt from 127.0.0.1:42590 to 127.0.0.1:5986 as packer using publickey
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 rejecting auth-agent-req@openssh.com request
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 new env request: LANG=C.UTF-8
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 new env request: LC_TERMINAL=iTerm2
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 new env request: LC_TERMINAL_VERSION=3.3.7
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 new exec request: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZQBBAEIAbABBAEcATQBBAFgAdwBCADMAQQBIAEkAQQBZAFEAQgB3AEEASABBAEEAWgBRAEIAeQBBAEYAOABBAGMAdwBCADAAQQBIAEkAQQBMAGcAQgBUAEEASABBAEEAYgBBAEIAcABBAEgAUQBBAEsAQQBCAEEAQQBDAGcAQQBJAGcAQgBnAEEARABBAEEAWQBBAEEAdwBBAEcAQQBBAE0AQQBCAGcAQQBEAEEAQQBJAGcAQQBwAEEAQwB3AEEASQBBAEEAeQBBAEMAdwBBAEkAQQBCAGIAQQBGAE0AQQBkAEEAQgB5AEEARwBrAEEAYgBnAEIAbgBBAEYATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBQAEEASABBAEEAZABBAEIAcABBAEcAOABBAGIAZwBCAHoAQQBGADAAQQBPAGcAQQA2AEEARgBJAEEAWgBRAEIAdABBAEcAOABBAGQAZwBCAGwAQQBFAFUAQQBiAFEAQgB3AEEASABRAEEAZQBRAEIARgBBAEcANABBAGQAQQBCAHkAQQBHAGsAQQBaAFEAQgB6AEEAQwBrAEEAQwBnAEIASgBBAEcAWQBBAEkAQQBBAG8AQQBDADAAQQBiAGcAQgB2AEEASABRAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAHUAQQBFAHcAQQBaAFEAQgB1AEEARwBjAEEAZABBAEIAbwBBAEMAQQBBAEwAUQBCAGwAQQBIAEUAQQBJAEEAQQB5AEEAQwBrAEEASQBBAEIANwBBAEMAQQBBAGQAQQBCAG8AQQBIAEkAQQBiAHcAQgAzAEEAQwBBAEEASQBnAEIAcABBAEcANABBAGQAZwBCAGgAQQBHAHcAQQBhAFEAQgBrAEEAQwBBAEEAYwBBAEIAaABBAEgAawBBAGIAQQBCAHYAQQBHAEUAQQBaAEEAQQBpAEEAQwBBAEEAZgBRAEEASwBBAEYATQBBAFoAUQBCADAAQQBDADAAQQBWAGcAQgBoAEEASABJAEEAYQBRAEIAaABBAEcASQBBAGIAQQBCAGwAQQBDAEEAQQBMAFEAQgBPAEEARwBFAEEAYgBRAEIAbABBAEMAQQBBAGEAZwBCAHoAQQBHADgAQQBiAGcAQgBmAEEASABJAEEAWQBRAEIAMwBBAEMAQQBBAEwAUQBCAFcAQQBHAEUAQQBiAEEAQgAxAEEARwBVAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEUAQQBYAFEAQQBLAEEAQwBRAEEAWgBRAEIANABBAEcAVQBBAFkAdwBCAGYAQQBIAGMAQQBjAGcAQgBoAEEASABBAEEAYwBBAEIAbABBAEgASQBBAEkAQQBBADkAQQBDAEEAQQBXAHcAQgBUAEEARwBNAEEAYwBnAEIAcABBAEgAQQBBAGQAQQBCAEMAQQBHAHcAQQBiAHcAQgBqAEEARwBzAEEAWABRAEEANgBBAEQAbwBBAFEAdwBCAHkAQQBHAFUAQQBZAFEAQgAwAEEARwBVAEEASwBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEEAQQBYAFEAQQBwAEEAQQBvAEEASgBnAEEAawBBAEcAVQBBAGUAQQBCAGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 [INFO] 118166 bytes written for 'stdin'
2019/12/03 18:43:35 [INFO] 118166 bytes written for 'stdin'
2019/12/03 18:43:35 packer: 2019/12/03 18:43:35 [INFO] starting remote command: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZQBBAEIAbABBAEcATQBBAFgAdwBCADMAQQBIAEkAQQBZAFEAQgB3AEEASABBAEEAWgBRAEIAeQBBAEYAOABBAGMAdwBCADAAQQBIAEkAQQBMAGcAQgBUAEEASABBAEEAYgBBAEIAcABBAEgAUQBBAEsAQQBCAEEAQQBDAGcAQQBJAGcAQgBnAEEARABBAEEAWQBBAEEAdwBBAEcAQQBBAE0AQQBCAGcAQQBEAEEAQQBJAGcAQQBwAEEAQwB3AEEASQBBAEEAeQBBAEMAdwBBAEkAQQBCAGIAQQBGAE0AQQBkAEEAQgB5AEEARwBrAEEAYgBnAEIAbgBBAEYATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBQAEEASABBAEEAZABBAEIAcABBAEcAOABBAGIAZwBCAHoAQQBGADAAQQBPAGcAQQA2AEEARgBJAEEAWgBRAEIAdABBAEcAOABBAGQAZwBCAGwAQQBFAFUAQQBiAFEAQgB3AEEASABRAEEAZQBRAEIARgBBAEcANABBAGQAQQBCAHkAQQBHAGsAQQBaAFEAQgB6AEEAQwBrAEEAQwBnAEIASgBBAEcAWQBBAEkAQQBBAG8AQQBDADAAQQBiAGcAQgB2AEEASABRAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAHUAQQBFAHcAQQBaAFEAQgB1AEEARwBjAEEAZABBAEIAbwBBAEMAQQBBAEwAUQBCAGwAQQBIAEUAQQBJAEEAQQB5AEEAQwBrAEEASQBBAEIANwBBAEMAQQBBAGQAQQBCAG8AQQBIAEkAQQBiAHcAQgAzAEEAQwBBAEEASQBnAEIAcABBAEcANABBAGQAZwBCAGgAQQBHAHcAQQBhAFEAQgBrAEEAQwBBAEEAYwBBAEIAaABBAEgAawBBAGIAQQBCAHYAQQBHAEUAQQBaAEEAQQBpAEEAQwBBAEEAZgBRAEEASwBBAEYATQBBAFoAUQBCADAAQQBDADAAQQBWAGcAQgBoAEEASABJAEEAYQBRAEIAaABBAEcASQBBAGIAQQBCAGwAQQBDAEEAQQBMAFEAQgBPAEEARwBFAEEAYgBRAEIAbABBAEMAQQBBAGEAZwBCAHoAQQBHADgAQQBiAGcAQgBmAEEASABJAEEAWQBRAEIAMwBBAEMAQQBBAEwAUQBCAFcAQQBHAEUAQQBiAEEAQgAxAEEARwBVAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEUAQQBYAFEAQQBLAEEAQwBRAEEAWgBRAEIANABBAEcAVQBBAFkAdwBCAGYAQQBIAGMAQQBjAGcAQgBoAEEASABBAEEAYwBBAEIAbABBAEgASQBBAEkAQQBBADkAQQBDAEEAQQBXAHcAQgBUAEEARwBNAEEAYwBnAEIAcABBAEgAQQBBAGQAQQBCAEMAQQBHAHcAQQBiAHcAQgBqAEEARwBzAEEAWABRAEEANgBBAEQAbwBBAFEAdwBCAHkAQQBHAFUAQQBZAFEAQgAwAEEARwBVAEEASwBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEEAQQBYAFEAQQBwAEEAQQBvAEEASgBnAEEAawBBAEcAVQBBAGUAQQBCAGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=
2019/12/03 18:43:36 packer: 2019/12/03 18:43:36 [INFO] command 'chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZQBBAEIAbABBAEcATQBBAFgAdwBCADMAQQBIAEkAQQBZAFEAQgB3AEEASABBAEEAWgBRAEIAeQBBAEYAOABBAGMAdwBCADAAQQBIAEkAQQBMAGcAQgBUAEEASABBAEEAYgBBAEIAcABBAEgAUQBBAEsAQQBCAEEAQQBDAGcAQQBJAGcAQgBnAEEARABBAEEAWQBBAEEAdwBBAEcAQQBBAE0AQQBCAGcAQQBEAEEAQQBJAGcAQQBwAEEAQwB3AEEASQBBAEEAeQBBAEMAdwBBAEkAQQBCAGIAQQBGAE0AQQBkAEEAQgB5AEEARwBrAEEAYgBnAEIAbgBBAEYATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBQAEEASABBAEEAZABBAEIAcABBAEcAOABBAGIAZwBCAHoAQQBGADAAQQBPAGcAQQA2AEEARgBJAEEAWgBRAEIAdABBAEcAOABBAGQAZwBCAGwAQQBFAFUAQQBiAFEAQgB3AEEASABRAEEAZQBRAEIARgBBAEcANABBAGQAQQBCAHkAQQBHAGsAQQBaAFEAQgB6AEEAQwBrAEEAQwBnAEIASgBBAEcAWQBBAEkAQQBBAG8AQQBDADAAQQBiAGcAQgB2AEEASABRAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAHUAQQBFAHcAQQBaAFEAQgB1AEEARwBjAEEAZABBAEIAbwBBAEMAQQBBAEwAUQBCAGwAQQBIAEUAQQBJAEEAQQB5AEEAQwBrAEEASQBBAEIANwBBAEMAQQBBAGQAQQBCAG8AQQBIAEkAQQBiAHcAQgAzAEEAQwBBAEEASQBnAEIAcABBAEcANABBAGQAZwBCAGgAQQBHAHcAQQBhAFEAQgBrAEEAQwBBAEEAYwBBAEIAaABBAEgAawBBAGIAQQBCAHYAQQBHAEUAQQBaAEEAQQBpAEEAQwBBAEEAZgBRAEEASwBBAEYATQBBAFoAUQBCADAAQQBDADAAQQBWAGcAQgBoAEEASABJAEEAYQBRAEIAaABBAEcASQBBAGIAQQBCAGwAQQBDAEEAQQBMAFEAQgBPAEEARwBFAEEAYgBRAEIAbABBAEMAQQBBAGEAZwBCAHoAQQBHADgAQQBiAGcAQgBmAEEASABJAEEAWQBRAEIAMwBBAEMAQQBBAEwAUQBCAFcAQQBHAEUAQQBiAEEAQgAxAEEARwBVAEEASQBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEUAQQBYAFEAQQBLAEEAQwBRAEEAWgBRAEIANABBAEcAVQBBAFkAdwBCAGYAQQBIAGMAQQBjAGcAQgBoAEEASABBAEEAYwBBAEIAbABBAEgASQBBAEkAQQBBADkAQQBDAEEAQQBXAHcAQgBUAEEARwBNAEEAYwBnAEIAcABBAEgAQQBBAGQAQQBCAEMAQQBHAHcAQQBiAHcAQgBqAEEARwBzAEEAWABRAEEANgBBAEQAbwBBAFEAdwBCAHkAQQBHAFUAQQBZAFEAQgAwAEEARwBVAEEASwBBAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBCAGIAQQBEAEEAQQBYAFEAQQBwAEEAQQBvAEEASgBnAEEAawBBAEcAVQBBAGUAQQBCAGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=' exited with code: 1
2019/12/03 18:43:36 [INFO] 0 bytes written for 'stdout'
2019/12/03 18:43:36 [INFO] 34 bytes written for 'stderr'
2019/12/03 18:43:36 [INFO] RPC client: Communicator ended with: 1
2019/12/03 18:43:36 [INFO] RPC endpoint: Communicator ended with: 1
2019/12/03 18:43:36 packer: 2019/12/03 18:43:36 [INFO] RPC endpoint: Communicator ended with: 1
2019/12/03 18:43:36 packer: 2019/12/03 18:43:36 [INFO] 0 bytes written for 'stdout'
2019/12/03 18:43:36 packer: 2019/12/03 18:43:36 [INFO] 34 bytes written for 'stderr'
2019/12/03 18:43:36 packer: 2019/12/03 18:43:36 [INFO] RPC client: Communicator ended with: 1
    azure-arm: <127.0.0.1> (1, '', 'OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/root/.ansible/cp/169091250f" does not exist\r\ndebug2: resolving "127.0.0.1" port 5986\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 127.0.0.1 [127.0.0.1] port 5986.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /tmp/ansible-key091452712 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /tmp/ansible-key091452712-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3\r\ndebug1: Remote protocol version 2.0, remote software version Go\r\ndebug1: no match: Go\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 127.0.0.1:5986 as \'packer\'\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com,zlib\r\ndebug2: compression stoc: none,zlib@openssh.com,zlib\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1\r\ndebug2: host key algorithms: ssh-rsa\r\ndebug2: ciphers ctos: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr\r\ndebug2: ciphers stoc: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr\r\ndebug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96\r\ndebug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96\r\ndebug2: compression ctos: none\r\ndebug2: compression stoc: none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ssh-rsa\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ssh-rsa SHA256:cU0dWipf+o37NEIdXuu7zh8E1i6RnR0CqFMEh73Rg44\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"\r\ndebug1: checking without port identifier\r\ndebug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"\r\nWarning: Permanently added \'[127.0.0.1]:5986\' (RSA) to the list of known hosts.\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug2: key: /tmp/ansible-key091452712 ((nil)), explicit\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey\r\ndebug3: start over, passed a different list publickey\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /tmp/ansible-key091452712\r\ndebug3: sign_and_send_pubkey: RSA SHA256:5LrpPhtOFL6StrAe/MniekW8Yih9xbW6bJJZZGp0WqA\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 52\r\ndebug1: Authentication succeeded (publickey).\r\nAuthenticated to 127.0.0.1 ([127.0.0.1]:5986).\r\ndebug1: setting up multiplex master socket\r\ndebug3: muxserver_listen: temporary control path /root/.ansible/cp/169091250f.Vx87z8aAf5z4eQiU\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug1: channel 0: new [/root/.ansible/cp/169091250f]\r\ndebug3: muxserver_listen: mux listener channel 0 fd 4\r\ndebug2: fd 3 setting TCP_NODELAY\r\ndebug3: ssh_packet_set_tos: set IP_TOS 0x08\r\ndebug1: control_persist_detach: backgrounding master process\r\ndebug2: control_persist_detach: background process is 20636\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug1: forking to background\r\ndebug1: Entering interactive session.\r\ndebug1: pledge: id\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\ndebug1: multiplexing control connection\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug3: fd 5 is O_NONBLOCK\r\ndebug1: channel 1: new [mux-control]\r\ndebug3: channel_post_mux_listener: new mux channel 1 fd 5\r\ndebug3: mux_master_read_cb: channel 1: hello sent\r\ndebug2: set_control_persist_exit_time: cancel scheduled exit\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4\r\ndebug2: process_mux_master_hello: channel 1 slave version 4\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4\r\ndebug2: process_mux_alive_check: channel 1: alive check\r\ndebug3: mux_client_request_alive: done pid = 20638\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 2926\r\ndebug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 1, subsys 0, term "xterm-256color", cmd "chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZ\r\ndebug3: process_mux_new_session: got fds stdin 6, stdout 7, stderr 8\r\ndebug2: fd 6 setting O_NONBLOCK\r\ndebug2: fd 7 setting O_NONBLOCK\r\ndebug2: fd 8 setting O_NONBLOCK\r\ndebug1: channel 2: new [client-session]\r\ndebug2: process_mux_new_session: channel_new: 2 linked to control channel 1\r\ndebug2: channel 2: send open\r\ndebug3: send packet: type 90\r\ndebug3: receive packet: type 91\r\ndebug2: channel_input_open_confirmation: channel 2: callback start\r\ndebug1: Requesting authentication agent forwarding.\r\ndebug2: channel 2: request auth-agent-req@openssh.com confirm 0\r\ndebug3: send packet: type 98\r\ndebug2: client_session2_setup: id 2\r\ndebug1: Sending environment.\r\ndebug1: Sending env LANG = C.UTF-8\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending env LC_TERMINAL = iTerm2\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending env LC_TERMINAL_VERSION = 3.3.7\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending command: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEE\r\ndebug2: channel 2: request exec confirm 1\r\ndebug3: send packet: type 98\r\ndebug3: mux_session_confirm: sending success reply\r\ndebug2: channel_input_open_confirmation: channel 2: callback done\r\ndebug2: channel 2: open confirm rwindow 2097152 rmax 32768\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: receive packet: type 99\r\ndebug2: channel_input_status_confirm: type 99 id 2\r\ndebug2: exec request accepted on channel 2\r\ndebug2: channel 2: rcvd adjust 32768\r\ndebug2: channel 2: rcvd adjust 32768\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: read<=0 rfd 6 len 0\r\ndebug2: channel 2: read failed\r\ndebug2: channel 2: close_read\r\ndebug2: channel 2: input open -> drain\r\ndebug2: channel 2: ibuf empty\r\ndebug2: channel 2: send eof\r\ndebug3: send packet: type 96\r\ndebug2: channel 2: input drain -> closed\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: rcvd adjust 3478\r\ndebug2: channel 2: rcvd ext data 34\r\nParameter format not correct - ;\r\ndebug2: channel 2: written 34 to efd 8\r\ndebug3: receive packet: type 98\r\ndebug1: client_input_channel_req: channel 2 rtype exit-status reply 0\r\ndebug3: mux_exit_message: channel 2: exit message, exitval 1\r\ndebug3: receive packet: type 97\r\ndebug2: channel 2: rcvd close\r\ndebug2: channel 2: output open -> drain\r\ndebug3: channel 2: will not send data after close\r\ndebug2: channel 2: obuf empty\r\ndebug2: channel 2: close_write\r\ndebug2: channel 2: output drain -> closed\r\ndebug2: channel 2: send close\r\ndebug3: send packet: type 97\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: gc: notify user\r\ndebug3: mux_master_session_cleanup_cb: entering for channel 2\r\ndebug2: channel 1: rcvd close\r\ndebug2: channel 1: output open -> drain\r\ndebug2: channel 1: close_read\r\ndebug2: channel 1: input open -> closed\r\ndebug2: channel 2: gc: user detached\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: garbage collecting\r\ndebug1: channel 2: free: client-session, nchannels 3\r\ndebug3: channel 2: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o1/16 fd 5/5 cc -1)\r\n  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)\r\n\r\ndebug2: channel 1: obuf empty\r\ndebug2: channel 1: close_write\r\ndebug2: channel 1: output drain -> closed\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: gc: notify user\r\ndebug3: mux_master_control_cleanup_cb: entering for channel 1\r\ndebug2: channel 1: gc: user detached\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: garbage collecting\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug1: channel 1: free: mux-control, nchannels 2\r\ndebug3: channel 1: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o3/0 fd 5/5 cc -1)\r\n\r\ndebug2: Received exit status from master 1\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\n')
    azure-arm: <127.0.0.1> Failed to connect to the host via ssh: OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017
    azure-arm: debug1: Reading configuration data /etc/ssh/ssh_config
    azure-arm: debug1: /etc/ssh/ssh_config line 19: Applying options for *
    azure-arm: debug1: auto-mux: Trying existing master
    azure-arm: debug1: Control socket "/root/.ansible/cp/169091250f" does not exist
    azure-arm: debug2: resolving "127.0.0.1" port 5986
    azure-arm: debug2: ssh_connect_direct: needpriv 0
    azure-arm: debug1: Connecting to 127.0.0.1 [127.0.0.1] port 5986.
    azure-arm: debug2: fd 3 setting O_NONBLOCK
    azure-arm: debug1: fd 3 clearing O_NONBLOCK
    azure-arm: debug1: Connection established.
    azure-arm: debug3: timeout: 10000 ms remain after connect
    azure-arm: debug1: permanently_set_uid: 0/0
    azure-arm: debug1: key_load_public: No such file or directory
    azure-arm: debug1: identity file /tmp/ansible-key091452712 type -1
    azure-arm: debug1: key_load_public: No such file or directory
    azure-arm: debug1: identity file /tmp/ansible-key091452712-cert type -1
    azure-arm: debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3
    azure-arm: debug1: Remote protocol version 2.0, remote software version Go
    azure-arm: debug1: no match: Go
    azure-arm: debug2: fd 3 setting O_NONBLOCK
    azure-arm: debug1: Authenticating to 127.0.0.1:5986 as 'packer'
    azure-arm: debug3: put_host_port: [127.0.0.1]:5986
    azure-arm: debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
    azure-arm: debug3: send packet: type 20
    azure-arm: debug1: SSH2_MSG_KEXINIT sent
    azure-arm: debug3: receive packet: type 20
    azure-arm: debug1: SSH2_MSG_KEXINIT received
    azure-arm: debug2: local client KEXINIT proposal
    azure-arm: debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
    azure-arm: debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
    azure-arm: debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    azure-arm: debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
    azure-arm: debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    azure-arm: debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
    azure-arm: debug2: compression ctos: none,zlib@openssh.com,zlib
    azure-arm: debug2: compression stoc: none,zlib@openssh.com,zlib
    azure-arm: debug2: languages ctos:
    azure-arm: debug2: languages stoc:
    azure-arm: debug2: first_kex_follows 0
    azure-arm: debug2: reserved 0
    azure-arm: debug2: peer server KEXINIT proposal
    azure-arm: debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
    azure-arm: debug2: host key algorithms: ssh-rsa
    azure-arm: debug2: ciphers ctos: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
    azure-arm: debug2: ciphers stoc: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr
    azure-arm: debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
    azure-arm: debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96
    azure-arm: debug2: compression ctos: none
    azure-arm: debug2: compression stoc: none
    azure-arm: debug2: languages ctos:
    azure-arm: debug2: languages stoc:
    azure-arm: debug2: first_kex_follows 0
    azure-arm: debug2: reserved 0
    azure-arm: debug1: kex: algorithm: curve25519-sha256@libssh.org
    azure-arm: debug1: kex: host key algorithm: ssh-rsa
    azure-arm: debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    azure-arm: debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
    azure-arm: debug3: send packet: type 30
    azure-arm: debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
    azure-arm: debug3: receive packet: type 31
    azure-arm: debug1: Server host key: ssh-rsa SHA256:cU0dWipf+o37NEIdXuu7zh8E1i6RnR0CqFMEh73Rg44
    azure-arm: debug3: put_host_port: [127.0.0.1]:5986
    azure-arm: debug3: put_host_port: [127.0.0.1]:5986
    azure-arm: debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
    azure-arm: debug1: checking without port identifier
    azure-arm: debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
    azure-arm: Warning: Permanently added '[127.0.0.1]:5986' (RSA) to the list of known hosts.
    azure-arm: debug3: send packet: type 21
    azure-arm: debug2: set_newkeys: mode 1
    azure-arm: debug1: rekey after 134217728 blocks
    azure-arm: debug1: SSH2_MSG_NEWKEYS sent
    azure-arm: debug1: expecting SSH2_MSG_NEWKEYS
    azure-arm: debug3: receive packet: type 21
    azure-arm: debug1: SSH2_MSG_NEWKEYS received
    azure-arm: debug2: set_newkeys: mode 0
    azure-arm: debug1: rekey after 134217728 blocks
    azure-arm: debug2: key: /tmp/ansible-key091452712 ((nil)), explicit
    azure-arm: debug3: send packet: type 5
    azure-arm: debug3: receive packet: type 6
    azure-arm: debug2: service_accept: ssh-userauth
    azure-arm: debug1: SSH2_MSG_SERVICE_ACCEPT received
    azure-arm: debug3: send packet: type 50
    azure-arm: debug3: receive packet: type 51
    azure-arm: debug1: Authentications that can continue: publickey
    azure-arm: debug3: start over, passed a different list publickey
    azure-arm: debug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey
    azure-arm: debug3: authmethod_lookup publickey
    azure-arm: debug3: remaining preferred: ,gssapi-keyex,hostbased,publickey
    azure-arm: debug3: authmethod_is_enabled publickey
    azure-arm: debug1: Next authentication method: publickey
    azure-arm: debug1: Trying private key: /tmp/ansible-key091452712
    azure-arm: debug3: sign_and_send_pubkey: RSA SHA256:5LrpPhtOFL6StrAe/MniekW8Yih9xbW6bJJZZGp0WqA
    azure-arm: debug3: send packet: type 50
    azure-arm: debug2: we sent a publickey packet, wait for reply
    azure-arm: debug3: receive packet: type 52
    azure-arm: debug1: Authentication succeeded (publickey).
    azure-arm: Authenticated to 127.0.0.1 ([127.0.0.1]:5986).
    azure-arm: debug1: setting up multiplex master socket
    azure-arm: debug3: muxserver_listen: temporary control path /root/.ansible/cp/169091250f.Vx87z8aAf5z4eQiU
    azure-arm: debug2: fd 4 setting O_NONBLOCK
    azure-arm: debug3: fd 4 is O_NONBLOCK
    azure-arm: debug3: fd 4 is O_NONBLOCK
    azure-arm: debug1: channel 0: new [/root/.ansible/cp/169091250f]
    azure-arm: debug3: muxserver_listen: mux listener channel 0 fd 4
    azure-arm: debug2: fd 3 setting TCP_NODELAY
    azure-arm: debug3: ssh_packet_set_tos: set IP_TOS 0x08
    azure-arm: debug1: control_persist_detach: backgrounding master process
    azure-arm: debug2: control_persist_detach: background process is 20636
    azure-arm: debug2: fd 4 setting O_NONBLOCK
    azure-arm: debug1: forking to background
    azure-arm: debug1: Entering interactive session.
    azure-arm: debug1: pledge: id
    azure-arm: debug2: set_control_persist_exit_time: schedule exit in 60 seconds
    azure-arm: debug1: multiplexing control connection
    azure-arm: debug2: fd 5 setting O_NONBLOCK
    azure-arm: debug3: fd 5 is O_NONBLOCK
    azure-arm: debug1: channel 1: new [mux-control]
    azure-arm: debug3: channel_post_mux_listener: new mux channel 1 fd 5
    azure-arm: debug3: mux_master_read_cb: channel 1: hello sent
    azure-arm: debug2: set_control_persist_exit_time: cancel scheduled exit
    azure-arm: debug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4
    azure-arm: debug2: process_mux_master_hello: channel 1 slave version 4
    azure-arm: debug2: mux_client_hello_exchange: master version 4
    azure-arm: debug3: mux_client_forwards: request forwardings: 0 local, 0 remote
    azure-arm: debug3: mux_client_request_session: entering
    azure-arm: debug3: mux_client_request_alive: entering
    azure-arm: debug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4
    azure-arm: debug2: process_mux_alive_check: channel 1: alive check
    azure-arm: debug3: mux_client_request_alive: done pid = 20638
    azure-arm: debug3: mux_client_request_session: session request sent
    azure-arm: debug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 2926
    azure-arm: debug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 1, subsys 0, term "xterm-256color", cmd "chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZ
    azure-arm: debug3: process_mux_new_session: got fds stdin 6, stdout 7, stderr 8
    azure-arm: debug2: fd 6 setting O_NONBLOCK
    azure-arm: debug2: fd 7 setting O_NONBLOCK
    azure-arm: debug2: fd 8 setting O_NONBLOCK
    azure-arm: debug1: channel 2: new [client-session]
    azure-arm: debug2: process_mux_new_session: channel_new: 2 linked to control channel 1
    azure-arm: debug2: channel 2: send open
    azure-arm: debug3: send packet: type 90
    azure-arm: debug3: receive packet: type 91
    azure-arm: debug2: channel_input_open_confirmation: channel 2: callback start
    azure-arm: debug1: Requesting authentication agent forwarding.
    azure-arm: debug2: channel 2: request auth-agent-req@openssh.com confirm 0
    azure-arm: debug3: send packet: type 98
    azure-arm: debug2: client_session2_setup: id 2
    azure-arm: debug1: Sending environment.
    azure-arm: debug1: Sending env LANG = C.UTF-8
    azure-arm: debug2: channel 2: request env confirm 0
    azure-arm: debug3: send packet: type 98
    azure-arm: debug1: Sending env LC_TERMINAL = iTerm2
    azure-arm: debug2: channel 2: request env confirm 0
    azure-arm: debug3: send packet: type 98
    azure-arm: debug1: Sending env LC_TERMINAL_VERSION = 3.3.7
    azure-arm: debug2: channel 2: request env confirm 0
    azure-arm: debug3: send packet: type 98
    azure-arm: debug1: Sending command: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEE
    azure-arm: debug2: channel 2: request exec confirm 1
    azure-arm: debug3: send packet: type 98
    azure-arm: debug3: mux_session_confirm: sending success reply
    azure-arm: debug2: channel_input_open_confirmation: channel 2: callback done
    azure-arm: debug2: channel 2: open confirm rwindow 2097152 rmax 32768
    azure-arm: debug1: mux_client_request_session: master session id: 2
    azure-arm: debug3: receive packet: type 99
    azure-arm: debug2: channel_input_status_confirm: type 99 id 2
    azure-arm: debug2: exec request accepted on channel 2
    azure-arm: debug2: channel 2: rcvd adjust 32768
    azure-arm: debug2: channel 2: rcvd adjust 32768
    azure-arm: debug2: channel 2: rcvd adjust 16384
    azure-arm: debug2: channel 2: rcvd adjust 16384
    azure-arm: debug2: channel 2: read<=0 rfd 6 len 0
    azure-arm: debug2: channel 2: read failed
    azure-arm: debug2: channel 2: close_read
    azure-arm: debug2: channel 2: input open -> drain
    azure-arm: debug2: channel 2: ibuf empty
    azure-arm: debug2: channel 2: send eof
    azure-arm: debug3: send packet: type 96
    azure-arm: debug2: channel 2: input drain -> closed
    azure-arm: debug2: channel 2: rcvd adjust 16384
    azure-arm: debug2: channel 2: rcvd adjust 3478
    azure-arm: debug2: channel 2: rcvd ext data 34
    azure-arm: Parameter format not correct - ;
    azure-arm: debug2: channel 2: written 34 to efd 8
    azure-arm: debug3: receive packet: type 98
    azure-arm: debug1: client_input_channel_req: channel 2 rtype exit-status reply 0
    azure-arm: debug3: mux_exit_message: channel 2: exit message, exitval 1
    azure-arm: debug3: receive packet: type 97
    azure-arm: debug2: channel 2: rcvd close
    azure-arm: debug2: channel 2: output open -> drain
    azure-arm: debug3: channel 2: will not send data after close
    azure-arm: debug2: channel 2: obuf empty
    azure-arm: debug2: channel 2: close_write
    azure-arm: debug2: channel 2: output drain -> closed
    azure-arm: debug2: channel 2: send close
    azure-arm: debug3: send packet: type 97
    azure-arm: debug2: channel 2: is dead
    azure-arm: debug2: channel 2: gc: notify user
    azure-arm: debug3: mux_master_session_cleanup_cb: entering for channel 2
    azure-arm: debug2: channel 1: rcvd close
    azure-arm: debug2: channel 1: output open -> drain
    azure-arm: debug2: channel 1: close_read
    azure-arm: debug2: channel 1: input open -> closed
    azure-arm: debug2: channel 2: gc: user detached
    azure-arm: debug2: channel 2: is dead
    azure-arm: debug2: channel 2: garbage collecting
    azure-arm: debug1: channel 2: free: client-session, nchannels 3
    azure-arm: debug3: channel 2: status: The following connections are open:
    azure-arm:   #1 mux-control (t16 nr0 i3/0 o1/16 fd 5/5 cc -1)
    azure-arm:   #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)
    azure-arm:
    azure-arm: debug2: channel 1: obuf empty
    azure-arm: debug2: channel 1: close_write
    azure-arm: debug2: channel 1: output drain -> closed
    azure-arm: debug2: channel 1: is dead (local)
    azure-arm: debug2: channel 1: gc: notify user
    azure-arm: debug3: mux_master_control_cleanup_cb: entering for channel 1
    azure-arm: debug2: channel 1: gc: user detached
    azure-arm: debug2: channel 1: is dead (local)
    azure-arm: debug2: channel 1: garbage collecting
    azure-arm: debug3: mux_client_read_packet: read header failed: Broken pipe
    azure-arm: debug1: channel 1: free: mux-control, nchannels 2
    azure-arm: debug3: channel 1: status: The following connections are open:
    azure-arm:   #1 mux-control (t16 nr0 i3/0 o3/0 fd 5/5 cc -1)
    azure-arm:
    azure-arm: debug2: Received exit status from master 1
    azure-arm: debug2: set_control_persist_exit_time: schedule exit in 60 seconds
    azure-arm: fatal: [default]: FAILED! => {
    azure-arm:     "changed": false,
2019/12/03 18:43:37 packer: 2019/12/03 18:43:37 shutting down the SSH proxy
2019/12/03 18:43:37 [INFO] (telemetry) ending ansible
    azure-arm:     "module_stderr": "OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/root/.ansible/cp/169091250f\" does not exist\r\ndebug2: resolving \"127.0.0.1\" port 5986\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 127.0.0.1 [127.0.0.1] port 5986.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 10000 ms remain after connect\r\ndebug1: permanently_set_uid: 0/0\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /tmp/ansible-key091452712 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /tmp/ansible-key091452712-cert type -1\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.3\r\ndebug1: Remote protocol version 2.0, remote software version Go\r\ndebug1: no match: Go\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 127.0.0.1:5986 as 'packer'\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com,zlib\r\ndebug2: compression stoc: none,zlib@openssh.com,zlib\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1\r\ndebug2: host key algorithms: ssh-rsa\r\ndebug2: ciphers ctos: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr\r\ndebug2: ciphers stoc: aes128-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr\r\ndebug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96\r\ndebug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha2-256,hmac-sha1,hmac-sha1-96\r\ndebug2: compression ctos: none\r\ndebug2: compression stoc: none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ssh-rsa\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ssh-rsa SHA256:cU0dWipf+o37NEIdXuu7zh8E1i6RnR0CqFMEh73Rg44\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: put_host_port: [127.0.0.1]:5986\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\ndebug1: checking without port identifier\r\ndebug3: hostkeys_foreach: reading file \"/root/.ssh/known_hosts\"\r\nWarning: Permanently added '[127.0.0.1]:5986' (RSA) to the list of known hosts.\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug2: key: /tmp/ansible-key091452712 ((nil)), explicit\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey\r\ndebug3: start over, passed a different list publickey\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Trying private key: /tmp/ansible-key091452712\r\ndebug3: sign_and_send_pubkey: RSA SHA256:5LrpPhtOFL6StrAe/MniekW8Yih9xbW6bJJZZGp0WqA\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 52\r\ndebug1: Authentication succeeded (publickey).\r\nAuthenticated to 127.0.0.1 ([127.0.0.1]:5986).\r\ndebug1: setting up multiplex master socket\r\ndebug3: muxserver_listen: temporary control path /root/.ansible/cp/169091250f.Vx87z8aAf5z4eQiU\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug3: fd 4 is O_NONBLOCK\r\ndebug1: channel 0: new [/root/.ansible/cp/169091250f]\r\ndebug3: muxserver_listen: mux listener channel 0 fd 4\r\ndebug2: fd 3 setting TCP_NODELAY\r\ndebug3: ssh_packet_set_tos: set IP_TOS 0x08\r\ndebug1: control_persist_detach: backgrounding master process\r\ndebug2: control_persist_detach: background process is 20636\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug1: forking to background\r\ndebug1: Entering interactive session.\r\ndebug1: pledge: id\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\ndebug1: multiplexing control connection\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug3: fd 5 is O_NONBLOCK\r\ndebug1: channel 1: new [mux-control]\r\ndebug3: channel_post_mux_listener: new mux channel 1 fd 5\r\ndebug3: mux_master_read_cb: channel 1: hello sent\r\ndebug2: set_control_persist_exit_time: cancel scheduled exit\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x00000001 len 4\r\ndebug2: process_mux_master_hello: channel 1 slave version 4\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000004 len 4\r\ndebug2: process_mux_alive_check: channel 1: alive check\r\ndebug3: mux_client_request_alive: done pid = 20638\r\ndebug3: mux_client_request_session: session request sent\r\ndebug3: mux_master_read_cb: channel 1 packet type 0x10000002 len 2926\r\ndebug2: process_mux_new_session: channel 1: request tty 0, X 0, agent 1, subsys 0, term \"xterm-256color\", cmd \"chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEEARwBVAEEAZ\r\ndebug3: process_mux_new_session: got fds stdin 6, stdout 7, stderr 8\r\ndebug2: fd 6 setting O_NONBLOCK\r\ndebug2: fd 7 setting O_NONBLOCK\r\ndebug2: fd 8 setting O_NONBLOCK\r\ndebug1: channel 2: new [client-session]\r\ndebug2: process_mux_new_session: channel_new: 2 linked to control channel 1\r\ndebug2: channel 2: send open\r\ndebug3: send packet: type 90\r\ndebug3: receive packet: type 91\r\ndebug2: channel_input_open_confirmation: channel 2: callback start\r\ndebug1: Requesting authentication agent forwarding.\r\ndebug2: channel 2: request auth-agent-req@openssh.com confirm 0\r\ndebug3: send packet: type 98\r\ndebug2: client_session2_setup: id 2\r\ndebug1: Sending environment.\r\ndebug1: Sending env LANG = C.UTF-8\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending env LC_TERMINAL = iTerm2\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending env LC_TERMINAL_VERSION = 3.3.7\r\ndebug2: channel 2: request env confirm 0\r\ndebug3: send packet: type 98\r\ndebug1: Sending command: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABVAG4AcgBlAHMAdAByAGkAYwB0AGUAZAAgAC0ARQBuAGMAbwBkAGUAZABDAG8AbQBtAGEAbgBkACAASgBnAEIAagBBAEcAZwBBAFkAdwBCAHcAQQBDADQAQQBZAHcAQgB2AEEARwAwAEEASQBBAEEAMgBBAEQAVQBBAE0AQQBBAHcAQQBEAEUAQQBJAEEAQQArAEEAQwBBAEEASgBBAEIAdQBBAEgAVQBBAGIAQQBCAHMAQQBBAG8AQQBKAEEAQgBsAEEASABnAEEAWgBRAEIAagBBAEYAOABBAGQAdwBCAHkAQQBHAEUAQQBjAEEAQgB3AEEARwBVAEEAYwBnAEIAZgBBAEgATQBBAGQAQQBCAHkAQQBDAEEAQQBQAFEAQQBnAEEAQwBRAEEAYQBRAEIAdQBBAEgAQQBBAGQAUQBCADAAQQBDAEEAQQBmAEEAQQBnAEEARQA4AEEAZABRAEIAMABBAEMAMABBAFUAdwBCADAAQQBIAEkAQQBhAFEAQgB1AEEARwBjAEEAQwBnAEEAawBBAEgATQBBAGMAQQBCAHMAQQBHAGsAQQBkAEEAQgBmAEEASABBAEEAWQBRAEIAeQBBAEgAUQBBAGMAdwBBAGcAQQBEADAAQQBJAEEAQQBrAEE\r\ndebug2: channel 2: request exec confirm 1\r\ndebug3: send packet: type 98\r\ndebug3: mux_session_confirm: sending success reply\r\ndebug2: channel_input_open_confirmation: channel 2: callback done\r\ndebug2: channel 2: open confirm rwindow 2097152 rmax 32768\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: receive packet: type 99\r\ndebug2: channel_input_status_confirm: type 99 id 2\r\ndebug2: exec request accepted on channel 2\r\ndebug2: channel 2: rcvd adjust 32768\r\ndebug2: channel 2: rcvd adjust 32768\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: read<=0 rfd 6 len 0\r\ndebug2: channel 2: read failed\r\ndebug2: channel 2: close_read\r\ndebug2: channel 2: input open -> drain\r\ndebug2: channel 2: ibuf empty\r\ndebug2: channel 2: send eof\r\ndebug3: send packet: type 96\r\ndebug2: channel 2: input drain -> closed\r\ndebug2: channel 2: rcvd adjust 16384\r\ndebug2: channel 2: rcvd adjust 3478\r\ndebug2: channel 2: rcvd ext data 34\r\nParameter format not correct - ;\r\ndebug2: channel 2: written 34 to efd 8\r\ndebug3: receive packet: type 98\r\ndebug1: client_input_channel_req: channel 2 rtype exit-status reply 0\r\ndebug3: mux_exit_message: channel 2: exit message, exitval 1\r\ndebug3: receive packet: type 97\r\ndebug2: channel 2: rcvd close\r\ndebug2: channel 2: output open -> drain\r\ndebug3: channel 2: will not send data after close\r\ndebug2: channel 2: obuf empty\r\ndebug2: channel 2: close_write\r\ndebug2: channel 2: output drain -> closed\r\ndebug2: channel 2: send close\r\ndebug3: send packet: type 97\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: gc: notify user\r\ndebug3: mux_master_session_cleanup_cb: entering for channel 2\r\ndebug2: channel 1: rcvd close\r\ndebug2: channel 1: output open -> drain\r\ndebug2: channel 1: close_read\r\ndebug2: channel 1: input open -> closed\r\ndebug2: channel 2: gc: user detached\r\ndebug2: channel 2: is dead\r\ndebug2: channel 2: garbage collecting\r\ndebug1: channel 2: free: client-session, nchannels 3\r\ndebug3: channel 2: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o1/16 fd 5/5 cc -1)\r\n  #2 client-session (t4 r0 i3/0 o3/0 fd -1/-1 cc -1)\r\n\r\ndebug2: channel 1: obuf empty\r\ndebug2: channel 1: close_write\r\ndebug2: channel 1: output drain -> closed\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: gc: notify user\r\ndebug3: mux_master_control_cleanup_cb: entering for channel 1\r\ndebug2: channel 1: gc: user detached\r\ndebug2: channel 1: is dead (local)\r\ndebug2: channel 1: garbage collecting\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug1: channel 1: free: mux-control, nchannels 2\r\ndebug3: channel 1: status: The following connections are open:\r\n  #1 mux-control (t16 nr0 i3/0 o3/0 fd 5/5 cc -1)\r\n\r\ndebug2: Received exit status from master 1\r\ndebug2: set_control_persist_exit_time: schedule exit in 60 seconds\r\n",
    azure-arm:     "module_stdout": "",
    azure-arm:     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    azure-arm:     "rc": 1
    azure-arm: }
    azure-arm:
    azure-arm: PLAY RECAP *********************************************************************
    azure-arm: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    azure-arm:
==> azure-arm: Error executing Ansible: Non-zero exit status: exit status 2
```
And the template.json is 

```
{
    "variables": {
        "winrm_user": "packer"
    },
    "builders": [
        {
            "type": "azure-arm",
            "client_id": "xxxxxxxxxxxxxx",
            "client_secret": "xxxxxxxxxxxxx",
            "tenant_id": "xxxxxxxxxxxxx",
            "subscription_id": "xxxxxxxxxxxxx",
            "managed_image_resource_group_name": "xxxxxxxxxxxxxxxxxx",
            "managed_image_name": "myPackerImage3",
            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2012-R2-Datacenter",
            "communicator": "winrm",
	    "winrm_port": 5986,
	    "winrm_timeout": "3m",
            "winrm_use_ssl": true,
            "winrm_insecure": true,
            "winrm_username": "packer",
            "location": "East US",
            "vm_size": "Standard_DS2_v2"
        }
    ],
    "provisioners": [
        {
            "type": "powershell",
            "scripts": [
                "./AnsibleSetup.ps1"
            ]
        },
        {
            "type": "ansible",
            "user": "packer",
            "local_port": 5986,
            "playbook_file": "../ansible/playbooks/install-db-and-sis.yml",
            "ansible_env_vars": [
                "ANSIBLE_HOST_KEY_CHECKING=False",
                "ANSIBLE_SSH_ARGS='-o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s'",
                "ANSIBLE_NOCOLOR=True",
                "WINRM_PASSWORD={{.WinRMPassword}}"
            ],
            "extra_arguments": [
                "--connection=packer",
                "--extra-vars= ansible_shell_type=powershell ansible_shell_executable=None ansible_become_pass={{.WinRMPassword}}",
                "-vvvvv"
            ]
        },
        {
            "type": "windows-restart",
            "restart_check_command": "powershell -command \"& {Write-Output 'restarted.'}\""
        },
        {
            "type": "powershell",
            "inline": [
              "Add-WindowsFeature Web-Server",
              "& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit",
              "while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
            ]
          }
    ],
    "post-processors": [
        {
          "type": "manifest",
          "output": "output-manifest.json"
        }
      ]
}
```

The Powershell Provisioner works fine to enable WinRM but after that when trying to execute a ansible playbook it  gives me a long list of errors.

### LINKED ISSUE #8617: Remove Ansible provisioner SSH Proxy
Now that we supply the host IP through the generatedData field, I think we can remove the ssh proxy. this will probably remove a lot of issues with the Ansible provisioner.

### LINKED ISSUE #8726: Packer with ansible provisioners (Windows 2016 AMI creation on AWS) - Failed to connect to the host via ssh: Warning
- Packer Version:  1.5.1
builder: amazon-ebs
os_type: Windows
communicator: winrm

- Ansible Version: 2.9.3
- Python Version: 2.7.5
   
### Debug Logs:

==> amazon-ebs: Provisioning with Ansible...
2020/02/16 19:09:14 packer-provisioner-ansible plugin: SSH proxy: serving on 127.0.0.1:34071
==> amazon-ebs: Executing Ansible: ansible-playbook --extra-vars packer_build_name=amazon-
ebs packer_builder_type=amazon-ebs -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible805584169 /root/win-playbook1.yml -e ansible_ssh_private_key_file=/tmp/ansible-key475469426 --connection packer -vvv --extra-vars ansible_shell_type=powershell ansible_shell_executable=None
    amazon-ebs: ansible-playbook 2.9.3
    amazon-ebs:   config file = /etc/ansible/ansible.cfg
    amazon-ebs:   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
    amazon-ebs:   ansible python module location = /usr/lib/python2.7/site-packages/ansible
    amazon-ebs:   executable location = /bin/ansible-playbook
    amazon-ebs:   python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
    amazon-ebs: Using /etc/ansible/ansible.cfg as config file
    amazon-ebs: host_list declined parsing /tmp/packer-provisioner-ansible805584169 as it did not pass its verify_file() method
    amazon-ebs: script declined parsing /tmp/packer-provisioner-ansible805584169 as it did not pass its verify_file() method
    amazon-ebs: auto declined parsing /tmp/packer-provisioner-ansible805584169 as it did not pass its verify_file() method
    amazon-ebs: Parsed /tmp/packer-provisioner-ansible805584169 inventory source with ini plugin
    amazon-ebs:
    amazon-ebs: PLAYBOOK: win-playbook1.yml ****************************************************
    amazon-ebs: 1 plays in /root/win-playbook1.yml
    amazon-ebs:
    amazon-ebs: PLAY [all] *********************************************************************
    amazon-ebs: META: ran handlers
    amazon-ebs:
    amazon-ebs: TASK [18.9.26.1.1,CCE-37775-4 | Ensure 'Application - Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'] ***
    amazon-ebs: task path: /root/win-playbook1.yml:6
    amazon-ebs: Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_regedit.ps1
    amazon-ebs: Pipelining is enabled.
    amazon-ebs: <127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: root
    amazon-ebs: <127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=34071 -o 'IdentityFile="/tmp/ansible-key475469426"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/187f5d0b62 127.0.0.1 'chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA='
2020/02/16 19:09:14 packer-provisioner-ansible plugin: SSH proxy: accepted connection
2020/02/16 19:09:15 packer-provisioner-ansible plugin: authentication attempt from 127.0.0.1:57412 to 127.0.0.1:34071 as root using none
2020/02/16 19:09:15 packer-provisioner-ansible plugin: authentication attempt from 127.0.0.1:57412 to 127.0.0.1:34071 as root using publickey
2020/02/16 19:09:15 packer-provisioner-ansible plugin: new env request: LANG=en_US.UTF-8
2020/02/16 19:09:15 packer-provisioner-ansible plugin: new exec request: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=
2020/02/16 19:09:15 packer-provisioner-ansible plugin: [INFO] 112272 bytes written for 'stdin'
2020/02/16 19:09:15 [INFO] 112272 bytes written for 'stdin'
2020/02/16 19:09:15 packer-builder-amazon-ebs plugin: [INFO] starting remote command: chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=
2020/02/16 19:09:15 packer-builder-amazon-ebs plugin: [INFO] command 'chcp.com 65001 > $null ; PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UABvAHcAZQByAFMAaABlAGwAbAAgAC0ATgBvAFAAcgBvAGYAaQBsAGUAIAAtAE4AbwBuAEkAbgB0AGUAcgBhAGMAdABpAHYAZQAgAC0ARQB4AGUAYwB1AHQAaQBvAG4AUABvAGwAaQBjAHkAIABGwAQQBHAE0AQQBYAHcAQgAzAEEASABJAEEAWQBRAEIAdwBBAEgAQQBBAFoAUQBCAHkAQQBBAD0APQA=' exited with code: 1
2020/02/16 19:09:15 packer-builder-amazon-ebs plugin: [INFO] RPC endpoint: Communicator ended with: 1
2020/02/16 19:09:15 [INFO] 0 bytes written for 'stdout'
2020/02/16 19:09:15 [INFO] 34 bytes written for 'stderr'
2020/02/16 19:09:15 [INFO] RPC client: Communicator ended with: 1
2020/02/16 19:09:15 [INFO] RPC endpoint: Communicator ended with: 1
2020/02/16 19:09:15 packer-provisioner-ansible plugin: [INFO] 0 bytes written for 'stdout'
2020/02/16 19:09:15 packer-provisioner-ansible plugin: [INFO] 34 bytes written for 'stderr'
2020/02/16 19:09:15 packer-provisioner-ansible plugin: [INFO] RPC client: Communicator ended with: 1
    amazon-ebs: <127.0.0.1> (1, '', "Warning: Permanently added '[127.0.0.1]:34071' (RSA) to the list of known hosts.\r\nParameter format not correct - ;\r\n")
    amazon-ebs: <127.0.0.1> Failed to connect to the host via ssh: Warning: Permanently added '[127.0.0.1]:34071' (RSA) to the list of known hosts.
    amazon-ebs: Parameter format not correct - ;
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": false,
    amazon-ebs:     "module_stderr": "Warning: Permanently added '[127.0.0.1]:34071' (RSA) to the list of known hosts.\r\nParameter format not correct - ;\r\n",
    amazon-ebs:     "module_stdout": "",
    amazon-ebs:     "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    amazon-ebs:     "rc": 1
    amazon-ebs: }
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: default                    : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    amazon-ebs:
2020/02/16 19:09:15 packer-provisioner-ansible plugin: shutting down the SSH proxy
2020/02/16 19:09:15 [INFO] (telemetry) ending ansible
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Cleaning up any extra volumes...
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Deleting temporary keypair...
2020/02/16 19:09:45 [INFO] (telemetry) ending amazon-ebs
2020/02/16 19:09:45 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/02/16 19:09:45 machine readable: amazon-ebs,error []string{"Error executing Ansible: Non-zero exit status: exit status 2"}
==> Builds finished but no artifacts were created.
2020/02/16 19:09:45 [INFO] (telemetry) Finalizing.
Build 'amazon-ebs' errored: Error executing Ansible: Non-zero exit status: exit status 2

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error executing Ansible: Non-zero exit status: exit status 2

==> Builds finished but no artifacts were created.
2020/02/16 19:09:46 waiting for all plugin processes to complete...
2020/02/16 19:09:46 /usr/local/bin/packer: plugin process exited
2020/02/16 19:09:46 /usr/local/bin/packer: plugin process exited
2020/02/16 19:09:46 /usr/local/bin/packer: plugin process exited

#### Overview of the Issue########

I am using Packer 1.5.1, ansible 2.9.3 to build Windows 2016 AMI in AWS environment (Public AMI ID ami-08c7081300f7d9abb)
Connected to WinRM, able to run powershell-provisioner, however not able to run ansible provisioner for hardening Windows 2016 based on CIS benchmark

Error:  amazon-ebs: <127.0.0.1> Failed to connect to the host via ssh: Warning: Permanently added

#### Reproduction Steps####

Steps to reproduce this issue

### Packer version###

1.5.1

### Simplified Packer Buildfile [winpacker1]####

```
  "builders": [{
    "type":"amazon-ebs",
    "access_key": "{{user `aws_access_key`}}",
    "secret_key": "{{user `aws_secret_key`}}",
    "region": "{{user `aws_region`}}",
    "instance_type": "t2.medium",
    "iam_instance_profile": "Admin",
    "associate_public_ip_address": false,

    "availability_zone":"us-east-1b",
    "vpc_id":"{{user `aws_vpc_id`}}",
    "subnet_id":"{{user `aws_subnet_id`}}",
    "security_group_id":"{{user `aws_security_group_id`}}",
    "ami_name": "packer-example-{{timestamp}}",
    "user_data_file": "windows-aws1.txt",
    "communicator": "winrm",
    "winrm_username": "Administrator",
    "winrm_password": "SuperS3cr3t!",

    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "Windows_Server-2016-English-Full-Base-2019.11.13",
        "root-device-type": "ebs"
      },
      "owners": ["amazon"],
      "most_recent": true
    },
    "launch_block_device_mappings": [
    {
      "device_name": "/dev/xvda",
      "volume_size": 80,
      "volume_type": "gp2",
      "delete_on_termination": true
    }
  ]
  }],

  "provisioners": [{
    "type": "powershell",
    "inline": [
      "dir c:\\"
    ]
  },
  {
      "type":  "ansible",
      "playbook_file": "./win-playbook1.yml",
      "extra_arguments": [
        "--connection", "packer", "-vvv",
        "--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"
      ]
  }]
}
```

### User_data_file [windows-aws1.txt]###

<powershell>
##Set administrator password
net user Administrator SuperS3cr3t!
wmic useraccount where "name='Administrator'" set PasswordExpires=FALSE

##First, make sure WinRM can't be connected to
netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new enable=yes action=block

##Delete any existing WinRM listeners
winrm delete winrm/config/listener?Address=*+Transport=HTTP  2>$Null
winrm delete winrm/config/listener?Address=*+Transport=HTTPS 2>$Null

##Create a new WinRM listener and configure
winrm create winrm/config/listener?Address=*+Transport=HTTP
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="0"}'
winrm set winrm/config '@{MaxTimeoutms="7200000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service '@{MaxConcurrentOperationsPerUser="12000"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
winrm set winrm/config/client/auth '@{Basic="true"}'

##Configure UAC to allow privilege elevation in remote shells
$Key = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
$Setting = 'LocalAccountTokenFilterPolicy'
Set-ItemProperty -Path $Key -Name $Setting -Value 1 -Force

##Configure and restart the WinRM Service; Enable the required firewall exception
Stop-Service -Name WinRM
Set-Service -Name WinRM -StartupType Automatic
netsh advfirewall firewall set rule name="Windows Remote Management (HTTP-In)" new action=allow localip=any remoteip=any
Start-Service -Name WinRM
</powershell>

### Sample YML file "win-playbook1.yml" I'm using - for reference###

```
---
- hosts: localhost
  gather_facts: no

  tasks:
   - name: "18.9.26.1.1,CCE-37775-4 | Ensure 'Application - Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled'"
     win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Eventlog\Application
        name: "Retention"
        data: "0"
        type: string

   - name: "18.9.8.2,CCE-38217-6 | Ensure 'Set the default behavior for AutoRun' is set to 'Enabled - Do not execute any autorun commands'"
     win_regedit:
        path: HKLM:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
        name: "NoAutorun"
        data: "1"
        type: dword

```

### Operating system and Environment details###

Windows_Server-2016-English-Full-Base-2019.11.13

### Connection_plugins, OS version and packer-log file attached###

I'm using the following connection_plugins: https://github.com/hashicorp/packer/tree/master/examples/ansible/connection-plugin/2.6.x/packer.py

OS version of the Build Machine: CentOS Linux release 7.5.1804 (Core)

### Log Fragments and crash.log files###

Packer-log file captured from the build machine::  [Packer-log.txt](https://github.com/hashicorp/packer/files/4211426/Packer-log.txt)

### LINKED ISSUE #8773: Issue while running Ansible provisioner from packer on windows target
Hello All,

I am trying to spin up a windows VM with above version combination in two different machine, on Azure using Packer and Ansible Provisioner. But it is failing to establish connection to the node. Any Help would be great. Below are the logs and configuration details,

**Versions Used on 1st machine**
packer v1.5.4
ansible 2.9.0
Python 3.6.8

**Versions Used on 2nd machine**
packer v1.5.1
ansible 2.8.1
Python 2.7.5

**error log 1:**
[0;32m    azure-arm:[0m
[0;32m    azure-arm: TASK [Gathering Facts] *********************************************************[0m
[0;32m    azure-arm: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "ssl: auth method ssl requires a password", "unreachable": true}[0m
[0;32m    azure-arm:[0m

**error log 2:**
[0;32m    azure-arm: TASK [trying to create a file] ***********************************************[0m
[0;32m    azure-arm: fatal: [172.16.15.11]: UNREACHABLE! => {"changed": false, "msg": "basic: HTTPConnectionPool(host='172.16.15.11', port=5985): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f3271f08710>, 'Connection to 172.16.15.11 timed out. (connect timeout=30)'))", "unreachable": true}[0m

packer file:
======
{   
 "builders": [
        {
            "type": "azure-arm",
            "subscription_id": "{{user `subscription_id`}}",
            "client_id": "{{user `client_id`}}",
            "client_secret": "{{user `client_secret`}}",
            "tenant_id": "{{user `tenant_id`}}",
            "managed_image_resource_group_name": "myPackerGroup",
            "managed_image_name": "Windowsimage-{{timestamp}}",
            "os_type": "Windows",
            "image_publisher": "MicrosoftWindowsServer",
            "image_offer": "WindowsServer",
            "image_sku": "2019-Datacenter-smalldisk",
            "communicator": "winrm",
            "winrm_username": "packer",
            "winrm_password": "packer",
            "winrm_use_ssl": true,
            "winrm_insecure": true,
            "winrm_timeout": "10m",
	    "virtual_network_name": "XXXXXXXX",
            "virtual_network_subnet_name": "default",
	    "build_resource_group_name": "XXXXXX",
            "azure_tags": {
		"dept": "XXXXXX",
                "task": "Image deployment"
            },
            "vm_size": "Standard_DS1_v2"
        }
    ],
    
    "provisioners": [  
  {
   "type": "ansible",
	    "playbook_file": "./ansible/playbook_all/main.yml"
  } ] } 

Ansible configuration:
=================
---
- name: add host under linux group
  hosts: localhost
  gather_facts: yes
  tasks:
  - name: adding new host
    add_host:
      hostname: 'XXXX'
      groups: windows

- hosts: 'XXXXXX'
  gather_facts: yes
  vars:
    ansible_user: "packer"
    ansible_password: "XXXXXXXXXXX"
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_connection: winrm
    ansible_port: 5985
  tasks:
    - name: trying to create a file
      win_file:
       path: C:\test.txt
       state: touch

    - debug:
        msg: "{{ ansible_os_family }}"

### LINKED ISSUE #8786: Ansible (remote): meta: reset_connection does not reset connection
#### Overview of the Issue

Resetting the connection after adding the ansible_user to a new group to refresh groups does not work. Forcibly resetting the session by deleting the control socket does not work either.

My best guess is that it has something to do with with ansible executing through an ssh proxy.

#### Reproduction Steps

The following works except for when it's run by packer.

```
- hosts: all                                                                                              
  tasks:                                                                                                  
    - name: Make sure we get a new session                                                                
      meta: reset_connection                                                                              
                                                                                                          
    - name: Create group                                                                                  
      group:                                                                                              
        name: packer_ansible_testgroup                                                                    
        state: present                                                                                    
      become: true                                                                                        
                                                                                                          
    - name: Add user to test group                                                                        
      user:                                                                                               
        name: "{{ ansible_user }}"                                                                        
        groups:                                                                                           
          - packer_ansible_testgroup                                                                      
        append: yes                                                                                       
      become: true                                                                                        
                                                                                                          
    - name: Get user groups                                                                               
      command: groups                                                                                     
      register: user_groups                                                                               
                                                                                                          
    - name: Show user groups                                                                              
      debug:                                                                                              
        var: user_groups.stdout                                                                           
                                                                                                          
    - name: reset connection                                                                              
      meta: reset_connection                                                                              
                                                                                                          
    - name: Get user groups                                                                               
      command: groups                                                                                     
      register: user_groups                                                                               
                                                                                                          
    - name: User should be part of 'packer_ansible_testgroup'                                             
      debug:                                                                                              
        var: user_groups.stdout                                                                           
                                                                                                          
    - name: Remove group                                                                                  
      group:                                                                                              
        name: packer_ansible_testgroup                                                                    
        state: absent                                                                                     
      become: true
```


### Packer version

Packer v1.5.1

### Simplified Packer Buildfile
```
{                                                                                                         
    "builders": [                                                                                         
        {                                                                                                 
            "type": "amazon-ebs",                                                                         
            "region": "REGION",                                                                           
            "vpc_filter": {                                                                               
                "filters": {                                                                              
                    "tag:Name": "VPC_NAME"                                                                
                }                                                                                         
            },                                                                                            
            "subnet_filter": {                                                                            
                "filters": {                                                                              
                    "tag:Name": "SUBNET_NAME"                                                             
                },                                                                                        
                "most_free": true                                                                         
            },                                                                                            
            "source_ami_filter": {                                                                        
              "filters": {                                                                                
                "virtualization-type": "hvm",                                                             
                "name": "ubuntu/images/*ubuntu-bionic-18.04-amd64-server-*",                              
                "root-device-type": "ebs"                                                                 
              },                                                                                          
              "owners": ["099720109477"],                                                                 
              "most_recent": true                                                                         
            },                                                                                            
            "instance_type": "t2.micro",                                                                  
            "ssh_username": "ubuntu",                                                                     
            "ami_name": "AMI_NAME"                                                                        
        }                                                                                                 
    ],                                                                                                    
  "provisioners": [                                                                                       
    {                                                                                                     
        "type": "shell",                                                                                  
        "script": "provisioners/shell/disable-unattended-upgrades.sh",                                    
        "expect_disconnect": true                                                                         
    },                                                                                                    
    {                                                                                                     
        "type": "shell",                                                                                  
        "script": "provisioners/shell/install-ansible-dependencies.sh"                                    
    },                                                                                                    
    {                                                                                                     
        "type": "ansible",                                                                                
        "playbook_file": "provisioners/ansible/build.yaml",                                               
        "user": "ubuntu"                                                                                  
    }                                                                                                     
  ]                                                                                                       
}  
```

### Operating system and Environment details
Host platform Ubuntu 18.04
Target platform Ubuntu 18.04

Tested with ansible 2.8 and 2.9

### LINKED ISSUE #8790: Packer v1.5.4 fails with SSL: UNKNOWN_PROTOCOL when it checks for ipv6 address
I'm currently using Packer v1.5.2-dev version to make the ec2 Windows 2012r2 AMI build working. 
I have tried to use Packer V1.5.4 but it fails due to the unknown protocol error 

#### error logs shows as below

amzn-win2012r2-sysprep-base: Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
amzn-win2012r2-sysprep-base: <127.0.0.1> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 35358 TO 127.0.0.1==> amzn-win2012r2-sysprep-base: failed to handshake
amzn-win2012r2-sysprep-base: checking if winrm_host 127.0.0.1 is an IPv6 address 
amzn-win2012r2-sysprep-base: fatal: [default]: UNREACHABLE! => {  amzn-win2012r2-sysprep-base: "changed": false,  amzn-win2012r2-sysprep-base: "msg": "ssl: HTTPSConnectionPool(host='127.0.0.1', port=35358): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:727)'),))",
amzn-win2012r2-sysprep-base: "unreachable": true  amzn-win2012r2-sysprep-base: }

#### I am creating a docker container container in jenkins 

1. [Docker file ](https://gist.github.com/WeekendsBull/e231ce720677b2e85082c2485def9b62)
2. The docker container runs a shell file to call [Packer template ](https://gist.github.com/WeekendsBull/cf9a90767163e37265f20725b6165b3f)
  
### Packer version

From Packer V 1.5.4 (currently works on Packer v1.5.2-dev)
 
### Operating system and Environment details

AWS Ec2 windows 2012r2 Latest version

### Log Fragments and crash.log files

[Full logs](https://gist.github.com/WeekendsBull/8f98092f183ccd7da09cbe5caa0e5423) 
 
Here is my environment variables in a shell file to call packer template. 
      export AWS_POLL_DELAY_SECONDS=180
      export AWS_MAX_ATTEMPTS=40 
      export AWS_PROFILE=${AWS_PROFILE}  
      export AWS_DEFAULT_REGION=${region}  
      export ANSIBLE_HOST_KEY_CHECKING=False

Here is a log file when I build successfully from [Packer v1.5.2-dev](https://gist.github.com/WeekendsBull/10e466606561f3e7ba1ce757a328cd22)

Note: please do not kill the link for packer v1.5.2-dev

### LINKED ISSUE #8968: Packer+ansible+windows: Requested entry (plugin_type: connection plugin: packer setting: use_tty ) was not defined in configuration
#### Overview of the Issue

It does not seem possible to generate a windows image with packer and ansible currently
It uses packer connection plugin
the packer connection plugin has documentation entry and one-liner description. also `"--extra-vars", "ansible_shell_type=powershell ansible_shell_executable=None"`
Likely related to other packer+ansible issues.

It used to work at least about a year ago but not sure when it broke after.

#### Reproduction Steps

git clone https://github.com/juju4/ansible-harden-windows
```
$ . ~/.azure/credentials
$ cd packer
$ packer build azure-windows_server_2019.json
```

### Packer version

1.5.5

### Simplified Packer Buildfile

https://github.com/juju4/ansible-harden-windows/blob/master/packer/azure-windows_server_2019.json

### Operating system and Environment details

Tested with Ansible 2.8.10, 2.9.2 and 2.9.6
Target Windows Server 2016 and 2019

### Log Fragments and crash.log files

```
2020/03/28 21:24:45 ui: [0;32m    azure-arm: Traceback (most recent call last):[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/plugins/__init__.py", line 58, in get_option[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     option_value = C.config.get_config_value(option, plugin_type=get_plugin_class(self), plugin_name=self._load_name, variables=hostvars)[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/config/manager.py", line 418, in get_config_value[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     keys=keys, variables=variables, direct=direct)[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:   File "/usr/local/lib/python3.7/site-packages/ansible/config/manager.py", line 517, in get_config_value_and_origin[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm:     raise AnsibleError('Requested entry (%s) was not defined in configuration.' % to_native(_get_entry(plugin_type, plugin_name, config)))[0m
2020/03/28 21:24:45 ui: [0;32m    azure-arm: ansible.errors.AnsibleError: Requested entry (plugin_type: connection plugin: packer setting: use_tty ) was not defined in configuration.[0m
```
full in https://gist.github.com/juju4/97115fb04553e5ca6939b1ac76bea8b6

### LINKED ISSUE #8973: Ansible Paramiko (network_cli) and ansible(remote) provisioner
Hi

is there any specific configuration that enables ansible network modules (which make use of paramiko instead of ssh) to work with packer local server??

I always get this error:
```
    amazon-ebs: <127.0.0.1> using connection plugin network_cli (was local)
    amazon-ebs: <127.0.0.1> starting connection from persistent connection plugin
    amazon-ebs: <127.0.0.1> local domain socket does not exist, starting it
    amazon-ebs: <127.0.0.1> control socket path is /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: <127.0.0.1> local domain socket listeners started successfully
    amazon-ebs: <127.0.0.1> loaded cliconf plugin ios from path /usr/local/lib/python3.7/site-packages/ansible/plugins/cliconf/ios.py for network_os ios
    amazon-ebs: <127.0.0.1> 
    amazon-ebs: <127.0.0.1> local domain socket path is /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: <127.0.0.1> socket_path: /home/nroot/.ansible/pc/c6c54e275d
    amazon-ebs: fatal: [default]: FAILED! => {
    amazon-ebs:     "changed": false,
    amazon-ebs:     "msg": "Channel closed."
    amazon-ebs: }
```

I think one solution would be to generate the ansible inventory with the instance IP instead of 127.0.0.1 (packer local ssh server).

Thanks in advance.
J.

### PR DESCRIPTION
**Pull request by SwampDragons**
Adds the option to circumvent the proxy adapter that we currently use to enable Ansible to connect to isntances without IP addresses. Currently, this is turned off and will still auto-launch the proxy when we can't glean an IP address (for example, when using the Docker builder), but in the future we may swap the default so that the proxy is _off_ by default except when dealing with IP-less instances.

Closes #5419
Closes #6196
Closes #6379
Closes #6877
Closes #7667
Closes #7680
Closes #7979
Closes #8383
Closes #8446
Closes #8617
Closes #8726
Closes #8773
Closes #8786
Closes #8790
Closes #8968
Closes #8973

### CODE REVIEW

**Comment by SwampDragons** [comment]
@bhcleek I'd love your insights on this, also, since you're the original creator of the Ansible provisioner. Basically, I believe that your proxy workaround is no longer needed now that the provisioner has direct access to the instance IP... but I'm not sure if there's further backstory and reason for the proxy that I'm unaware of here.

**Comment by bhcleek** [comment]
Your original message here identified the reason for the adapter; it's because not all packer builders have an IP, but ansible needs one to function correctly.

If it were purely up to me, I'd say 👎  to this, because it will break use cases that are currently handled for little benefit. However, I could see a case for leaving the adapter in place and only using it when the IP of the target isn't available.

**Comment by SwampDragons** [comment]
> However, I could see a case for leaving the adapter in place and only using it when the IP of the target isn't available. 

You're right--I think that's a better solution than removing it wholesale.

**Comment by SwampDragons** [comment]
Before I decide whether it's worth doing, I want to see what people in #7667 say. If removing the proxy does help unstick those use cases (hard to say, since I'm unable to reproduce, but the folks over at Ansible seem to think it's likely), then I think it's probably worth adding the extra logic to initiate the proxy when the host IP is available. 

Thanks for your thoughts on this :)

**Comment by WeekendsBull** [comment]
@SwampDragons , will it be possible to grab the fix to test this? I saws v1.6 will have the fix right?

**Comment by SwampDragons** [comment]
Hi, @WeekendsBull artifacts can be found here: https://circleci.com/gh/hashicorp/packer/29969#artifacts/containers/0

I'll be super interested to hear if it works for you; thanks for checking.

**Comment by WeekendsBull** [comment]
Thank you, @SwampDragons 
I'm having the issue of "ssl: HTTPSConnectionPool(host='127.0.0.1', port=45051) that I'd like to share my config. 

Since we utilize the designated jenkins-client among many teams internally, i have created a [dockerfile](https://gist.github.com/WeekendsBull/e231ce720677b2e85082c2485def9b62) 
As you can see I'm currently use Packer 1.5.1 and Ansible 2.9.4. 

I am not running docker to run packer but am creating an docker image to run a bash file to run a [packer template](https://gist.github.com/WeekendsBull/cf9a90767163e37265f20725b6165b3f) utilizing aws_profile (not credentials) and attached IAM role. 

My issue is that winrm gets connected using [winrm-bootstrap.txt](https://gist.github.com/WeekendsBull/1f3e187dd7a22a36c0f8bfcd868839a8) running in user-data that I'm passing Administrator and randomly generated password to the packer template. 
I'm currently using the packer connection [packer.py](https://gist.github.com/WeekendsBull/6cd8edd01ddac965e55aa933eb41ef2f)

However, I have noticed that the proxy port gets generated by Ansible (I guess) you can see from winrm-bootstrap.txt above that I tried to put all ports to the firewall but it's doesn't make any sense since it keeps on generating the different ports each build.

I'm going to test with this v1.5.2 and let you know how it works.

Thank you so much

**Comment by WeekendsBull** [comment]
@SwampDragons 
My apology, I left a message in the [wrong ticket](https://github.com/hashicorp/packer/issues/8446). The below is what I have tested with v1.5.2 you got me above. 


Hi @SwampDragons,
Simply running ping work as below that I can see now PORT points to 5986 correctly and grab the remote instance IP address.

xxxx-amzn-win2012r2-sysprep-base: PLAY [all] *********************************************************************
xxxx-amzn-win2012r2-sysprep-base: META: ran handlers
xxxx-amzn-win2012r2-sysprep-base:
xxxx-amzn-win2012r2-sysprep-base: TASK [win_ping] ****************************************************************
xxxx-amzn-win2012r2-sysprep-base: task path: /home/packer/appcode/tmp/amzn-win2012r2sysp/packer/ansible/win-playbook-test.yaml:9
xxxx-amzn-win2012r2-sysprep-base: Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_ping.ps1
xxxx-amzn-win2012r2-sysprep-base: Pipelining is enabled.
xxxx-amzn-win2012r2-sysprep-base: <10.127.49.1> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.127.49.1
xxxx-amzn-win2012r2-sysprep-base: EXEC (via pipeline wrapper)
xxxx-amzn-win2012r2-sysprep-base: ok: [default] => {
xxxx-amzn-win2012r2-sysprep-base:     "changed": false,
xxxx-amzn-win2012r2-sysprep-base:     "invocation": {
xxxx-amzn-win2012r2-sysprep-base:         "module_args": {
xxxx-amzn-win2012r2-sysprep-base:             "data": "pong"
xxxx-amzn-win2012r2-sysprep-base:         }
xxxx-amzn-win2012r2-sysprep-base:     },
xxxx-amzn-win2012r2-sysprep-base:     "ping": "pong"
xxxx-amzn-win2012r2-sysprep-base: }
xxxx-amzn-win2012r2-sysprep-base: META: ran handlers
xxxx-amzn-win2012r2-sysprep-base: META: ran handlers
However, running regular ansible doesn't work (this ansible works currently another jenkins client which is on docker and verified running in Ansible 2.4.0 or 2.4.1).

xxxx-amzn-win2012r2-sysprep-base: connection: packer
xxxx-amzn-win2012r2-sysprep-base: timeout: 10
xxxx-amzn-win2012r2-sysprep-base: become: True
xxxx-amzn-win2012r2-sysprep-base: 1 plays in /home/packer/appcode/tmp/amzn-win2012r2sysp/packer/ansible/win2012r2.yaml
xxxx-amzn-win2012r2-sysprep-base:
xxxx-amzn-win2012r2-sysprep-base: PLAY [Packer Provisoner for xxxx-win2012r2 images] *****************************
xxxx-amzn-win2012r2-sysprep-base: META: ran handlers
xxxx-amzn-win2012r2-sysprep-base:
xxxx-amzn-win2012r2-sysprep-base: TASK [Check Ansible version] ***************************************************
xxxx-amzn-win2012r2-sysprep-base: task path: /home/packer/appcode/tmp/amzn-win2012r2sysp/packer/ansible/win2012r2.yaml:10
xxxx-amzn-win2012r2-sysprep-base: Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
xxxx-amzn-win2012r2-sysprep-base: Pipelining is enabled.
xxxx-amzn-win2012r2-sysprep-base: <10.127.50.248> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.127.50.248
xxxx-amzn-win2012r2-sysprep-base: EXEC (via pipeline wrapper)
xxxx-amzn-win2012r2-sysprep-base: fatal: [default]: FAILED! => {
xxxx-amzn-win2012r2-sysprep-base: "changed": false,
xxxx-amzn-win2012r2-sysprep-base: "module_stderr": "Exception calling "Create" with "1" argument(s): "At line:4 char:21\r\n+ def _ansiballz_main():\r\n+ ~\r\nAn expression was expected after '('.\r\nAt line:13 char:27\r\n+ except (AttributeError, OSError):\r\n+ ~\r\nMissing argument in parameter list.\r\nAt line:15 char:7\r\n+ if scriptdir is not None:\r\n+ ~\r\nMissing '(' after 'if' in if statement.\r\nAt line:22 char:7\r\n+ if sys.version_info < (3,):\r\n+ ~\r\nMissing '(' after 'if' in if statement.\r\nAt line:22 char:30\r\n+ if sys.version_info < (3,):\r\n+ ~\r\nMissing expression after ','.\r\nAt line:22 char:25\r\n+ if sys.version_info < (3,):\r\n+ ~\r\nThe '<' operator is reserved for future use.\r\nAt line:27 char:34\r\n+ def invoke_module(modlib_path, temp_path, json_params):\r\n+ ~\r\nMissing argument in parameter list.\r\nAt line:28 char:40\r\n+ z = zipfile.ZipFile(modlib_path, mode='a')\r\n+ ~\r\nMissing argument in parameter list.\r\nAt line:31 char:33\r\n+ zinfo = zipfile.ZipInfo()\r\n+ ~\r\nAn expression was expected after '('.\r\nAt line:34 char:25\r\n+ z.writestr(zinfo, sitecustomize)\r\n+ ~\r\nMissing argument in parameter list.\r\nNot all parse errors were reported. Correct the reported errors and try again.\r\n"\r\nAt line:6 char:1\r\n+ $exec_wrapper = [ScriptBlock]::Create($split_parts[0])\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n + CategoryInfo : NotSpecified: (:) [], MethodInvocationException\r\n + FullyQualifiedErrorId : ParseException\r\n \r\nThe expression after '&' in a pipeline element produced an object that was not \r\nvalid. It must result in a command name, a script block, or a CommandInfo \r\nobject.\r\nAt line:7 char:2\r\n+ &$exec_wrapper\r\n+ ~~~~~~~~~~~~~\r\n + CategoryInfo : InvalidOperation: (:) [], RuntimeException\r\n + FullyQualifiedErrorId : BadExpression\r\n ",
xxxx-amzn-win2012r2-sysprep-base: "module_stdout": "",
xxxx-amzn-win2012r2-sysprep-base: "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
xxxx-amzn-win2012r2-sysprep-base: "rc": 1
xxxx-amzn-win2012r2-sysprep-base: }
xxxx-amzn-win2012r2-sysprep-base: [default] TASK: Check Ansible version (debug)> User interrupted execution

@WeekendsBull
 
WeekendsBull commented 10 hours ago
Additionally i have tested out packer 1.5.2 and ansible 2.4.1.

xxxx-amzn-win2012r2-sysprep-base:
xxxx-amzn-win2012r2-sysprep-base: TASK [Check Ansible version] ***************************************************
xxxx-amzn-win2012r2-sysprep-base: task path: /home/packer/appcode/tmp/amzn-win2012r2sysp/packer/ansible/win2012r2.yaml:10
xxxx-amzn-win2012r2-sysprep-base: Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
xxxx-amzn-win2012r2-sysprep-base: <10.127.50.116> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.127.50.116
xxxx-amzn-win2012r2-sysprep-base: EXEC (via pipeline wrapper)
xxxx-amzn-win2012r2-sysprep-base: [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call
xxxx-amzn-win2012r2-sysprep-base: last): File "/usr/lib/python2.7/site-
xxxx-amzn-win2012r2-sysprep-base: packages/ansible/plugins/connection/winrm.py", line 276, in _winrm_exec
xxxx-amzn-win2012r2-sysprep-base: self._winrm_send_input(self.protocol, self.shell_id, command_id, data,
xxxx-amzn-win2012r2-sysprep-base: eof=is_last) File "/usr/lib/python2.7/site-
xxxx-amzn-win2012r2-sysprep-base: packages/ansible/plugins/connection/winrm.py", line 256, in _winrm_send_input
xxxx-amzn-win2012r2-sysprep-base: protocol.send_message(xmltodict.unparse(rq)) File "/usr/lib/python2.7/site-
xxxx-amzn-win2012r2-sysprep-base: packages/winrm/protocol.py", line 265, in send_message raise
xxxx-amzn-win2012r2-sysprep-base: WinRMOperationTimeoutError() WinRMOperationTimeoutError
xxxx-amzn-win2012r2-sysprep-base: fatal: [default]: FAILED! => {
xxxx-amzn-win2012r2-sysprep-base: "failed": true,
xxxx-amzn-win2012r2-sysprep-base: "msg": "winrm send_input failed"
xxxx-amzn-win2012r2-sysprep-base: }
xxxx-amzn-win2012r2-sysprep-base: Debugger invoked
xxxx-amzn-win2012r2-sysprep-base: (debug) aborted

**Comment by WeekendsBull** [comment]
winrm send_input failed fixed after I have downgraded from pip pywinrm==04.0 to pywinrm==0.2.0 that I installed pywinrm==0.4.0 because if fixed the ansible_winrm_server_cert_validation=ignore in pywinrm==0.3.0. I think pywinrm==0.2.2 works best on python2.x so far.

**Comment by SwampDragons** [comment]
So it sounds like being able to disable the proxy allows you to get the Ansible provisioner working, then?

**Comment by WeekendsBull** [comment]
@SwampDragons you're correct the above error occurred none packer related issue. Now I have tested further with ansible 2.7.10 + pakcer 1.5.2-dev + pywinrm == 0.2.0 running simply playbook as below.

---
- name: test out local action
  hosts: all
  strategy: debug
  tasks:
    - name: windows command
      win_command: hostname
    
    - name: local command
      command: hostname
      delegate_to: localhost

but I'm not going anywhere due to the error from the ansible. I am going to dig some Ansible to make winrm working but it's nothing but huge frustration.

**Comment by WeekendsBull** [comment]
@SwampDragons I have good news that the packer v1.5.2-dev works with ansible 2.7.16 (tried 2.7.10, 2.7.12 and 2.7.14 which didn't work). Thank you so much for your help. I spotted a few new attribute required by Ansible but I'm good enough moving forward.

**Comment by SwampDragons** [comment]
@WeekendsBull that is good news, thanks for testing. I'll move forward on making the proxy removal a real option.

**Comment by WeekendsBull** [comment]
@SwampDragons Thank you and your team always.

File: provisioner/ansible/provisioner.go [hunk 1]
```diff
@@ -76,6 +79,9 @@ type Provisioner struct {
 	ansibleVersion    string
 	ansibleMajVersion uint
 	generatedData     map[string]interface{}
+
+	setupAdapterFunc   func(ui packer.Ui, comm packer.Communicator) (error, string)
```
Comment (nywilken) [inline provisioner/ansible/provisioner.go]: I would've expected the signature to be `func(ui packer.Ui, comm packer.Communicator) (string, error)`. Is there a reason why the return is `(error, string)` and not `(string, error)`?

Comment (SwampDragons) [reply provisioner/ansible/provisioner.go]: you're right, I should fix this.

File: provisioner/ansible/provisioner.go [hunk 2]
```diff
@@ -174,6 +180,16 @@ func (p *Provisioner) Prepare(raws ...interface{}) error {
 		errs = packer.MultiErrorAppend(errs, fmt.Errorf("user: could not determine current user from environment."))
 	}
 
+	// These fields exist so that we can replace the functions for testing
+	// logic inside of the Provision func; in acutal use, these don't ever
```
Comment (azr) [inline provisioner/ansible/provisioner.go]: NIT:
```suggestion
	// logic inside of the Provision func; in actual use, these don't ever
```

Comment (azr) [reply provisioner/ansible/provisioner.go]: Also super nice !

File: website/source/docs/provisioners/ansible.html.md.erb [hunk 3]
```diff
@@ -180,6 +180,13 @@ Optional Parameters:
 -   `user` (string) - The `ansible_user` to use. Defaults to the user running
     packer.
 
+-   `use_proxy` (boolean) - Whether or not to set up a localhost proxy adapter
+    so that Ansible has an IP address to connect to, even if your guest does not
+    have an IP address. For example, the adapter is necessary for Docker builds
+    to use the Ansible provisioner. Defaults to "true". If you set this option
```
Comment (azr) [inline website/source/docs/provisioners/ansible.html.md.erb]: NIT: One thing we could do here is make docs generated from the `Config` struct 🤔

File: provisioner/ansible/provisioner.go [hunk 4]
```diff
@@ -307,50 +300,117 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
+			" to use localhost proxy.")
+		p.config.UseProxy = confighelper.TriTrue
+	}
 
-		w := bufio.NewWriter(tf)
-		w.WriteString(host)
-		for _, group := range p.config.Groups {
-			fmt.Fprintf(w, "[%s]\n%s", group, host)
+	privKeyFile := ""
+	if !p.config.UseProxy.False() {
```
Comment (azr) [inline provisioner/ansible/provisioner.go]: Oh I got confused for a bit but now I get it; we will always start it unless it's explicitly set to false. 👍

Comment (azr) [reply provisioner/ansible/provisioner.go]: Do you think it would be a good idea to switch the content of two blocks ?
```suggestion
	if p.config.UseProxy.False() == true {
	    ui.Message("Not using Proxy adapter for Ansible run...")
	} else {
```

File: provisioner/ansible/provisioner.go [hunk 5]
```diff
@@ -307,50 +300,117 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
+			err := p.createInventoryFile("127.0.0.1", p.config.LocalPort)
+			if err != nil {
+				return err
+			}
+		} else {
+			err := p.createInventoryFile(generatedData["Host"].(string),
+				int(generatedData["Port"].(int64)))
+			if err != nil {
+				return err
+			}
```
Comment (azr) [inline provisioner/ansible/provisioner.go]: NIT: I would have made of this block something simpler :
```go
	hostIp, hostPort := "127.0.0.1", p.config.LocalPort
	if p.config.UseProxy.False() == true {
		hostIp, hostPort = generatedData["Host"].(string), int(generatedData["Port"].(int64)))
	}
	err := p.createInventoryFile(hostIp, hostPort)
```

File: provisioner/ansible/provisioner.go [hunk 6]
```diff
@@ -307,50 +300,117 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
 		}
-		tf.Close()
-		p.config.InventoryFile = tf.Name()
 		defer func() {
 			p.config.InventoryFile = ""
 		}()
+		defer os.Remove(p.config.InventoryFile)
```
Comment (azr) [inline provisioner/ansible/provisioner.go]: NIT: this one could be in the previous defer statement

File: provisioner/ansible/provisioner.go [hunk 7]
```diff
@@ -32,6 +32,7 @@ import (
 	"github.com/hashicorp/packer/common"
 	"github.com/hashicorp/packer/common/adapter"
 	"github.com/hashicorp/packer/helper/config"
+	confighelper "github.com/hashicorp/packer/helper/config"
```
Comment (azr) [inline provisioner/ansible/provisioner.go]: ah funny, it is possible to import a package twice !? TIL

**Comment by nywilken** [comment]
@SwampDragons I know we discussed this already, but I wanted to circle back for completeness. When testing with docker+ansible unmodified config I am getting the following error 

```
==> docker: Executing Ansible: ansible-playbook --extra-vars packer_build_name=docker packer_builder_type=docker -o IdentitiesOnly=yes -i /tmp/packer-provisioner-ansible406720585 /vagrant/an
sible/playbook.yml --extra-vars target_user=
    docker:
    docker: PLAY [all] *********************************************************************
    docker:
    docker: TASK [Gathering Facts] *********************************************************
    docker: fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname default: Temporary failure in name resolutio
n", "unreachable": true}
    docker:
    docker: PLAY RECAP *********************************************************************
    docker: 127.0.0.1                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
    docker:
==> docker: Provisioning step had errors: Running the cleanup provisioner, if present...
==> docker: Killing the container: 22059794310da0d2770e25acee0d8e8c88744820ce31416ca42875f45fe53c70
Build 'docker' errored: Error executing Ansible: Non-zero exit status: exit status 4
```

Sample Build Config
```
{
    "builders": [{
        "type": "docker",
        "image": "centos:7",
        "commit": true
    }],
    "provisioners": [
        {
        "type": "ansible",
        "playbook_file": "ansible/playbook.yml",
        "user": "root",
        "extra_arguments": [
            "--extra-vars", "target_user={{user `target_user`}}"
            ]
        }
    ]
}```

File: website/source/docs/provisioners/ansible.html.md.erb (hunk 3 above)
Comment (SwampDragons) [reply website/source/docs/provisioners/ansible.html.md.erb]: I felt like that was outside of the scope of this PR; we can change to generating the docs in a separate, dedicated PR.

File: provisioner/ansible/provisioner.go (hunk 4 above)
Comment (SwampDragons) [reply provisioner/ansible/provisioner.go]: That might be more intuitive 🤔

File: provisioner/ansible/provisioner.go (hunk 7 above)
Comment (SwampDragons) [reply provisioner/ansible/provisioner.go]: oh oops.

File: provisioner/ansible/provisioner.go (hunk 4 above)
Comment (SwampDragons) [reply provisioner/ansible/provisioner.go]: Thinking on it more, I don't think this is any better. For me the original way is more intuitive, so I think this is just gonna be a personal preference thing.

File: provisioner/ansible/provisioner.go (hunk 5 above)
Comment (SwampDragons) [reply provisioner/ansible/provisioner.go]: Yep, this is better.

**Comment by SwampDragons** [comment]
I have the basic proxy working now, and have verified that it works with docker and aws. I still need to add some more tests for the logic around using the ssh key from the generatedData before I am comfortable merging, but people should be able to test it out now.

File: provisioner/ansible/provisioner.go (hunk 4 above)
Comment (azr) [reply provisioner/ansible/provisioner.go]: Got it 👍 🙂 yeah that's personal !

File: website/source/docs/provisioners/ansible.html.md.erb (hunk 3 above)
Comment (azr) [reply website/source/docs/provisioners/ansible.html.md.erb]: Got it !

File: provisioner/ansible/provisioner.go (hunk 2 above)
Comment (azr) [reply provisioner/ansible/provisioner.go]: Heh wierd, the commit didn't work !

File: provisioner/ansible/provisioner.go [hunk 8]
```diff
@@ -307,50 +301,155 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
+		SSHPrivateKeyFile := generatedData["SSHPrivateKeyFile"].(string)
+		if SSHPrivateKeyFile != "" {
+			privKeyFile = SSHPrivateKeyFile
+		} else {
+			// See if we can get a private key and write that to a tmpfile
+			SSHPrivateKey := generatedData["SSHPrivateKey"].([]byte)
+			tmpSSHPrivateKey, err := tmp.File("ansible-key")
+			if err != nil {
+				return fmt.Errorf("Error writing private key to temp file for"+
+					"ansible connection", err)
```
Comment (azr) [inline provisioner/ansible/provisioner.go]:
```suggestion
					"ansible connection: %v", err)
```

File: provisioner/ansible/mock_ansible.go [hunk 9]
```diff
@@ -0,0 +1,31 @@
...
+import (
+	"fmt"
+
+	"github.com/hashicorp/packer/packer"
+)
+
+type provisionLogicTracker struct {
+	setupAdapterCalled   bool
+	executeAnsibleCalled bool
+	happyPath            bool
```
Comment (nywilken) [inline provisioner/ansible/mock_ansible.go:14]: :100:

File: provisioner/ansible/provisioner.go [hunk 10]
```diff
@@ -307,50 +302,185 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
+		switch connType {
+		case "ssh":
+			ui.Message("Not using Proxy adapter for Ansible run:\n" +
+				"\tUsing ssh keys from Packer communicator...")
+			// In this situation, we need to make sure we have the
+			// private key we actually use to access the instance.
+			SSHPrivateKeyFile := generatedData["SSHPrivateKeyFile"].(string)
+			if SSHPrivateKeyFile != "" {
+				privKeyFile = SSHPrivateKeyFile
+			} else {
```
Comment (nywilken) [inline provisioner/ansible/provisioner.go:439]: Nit on removing the if/else 
```suggestion
			privKeyFile := generatedData["SSHPrivateKeyFile"].(string)
			if privKeyFile == "" {

```

File: provisioner/ansible/provisioner.go [hunk 11]
```diff
@@ -63,10 +63,14 @@ type Config struct {
 	UseSFTP              bool     `mapstructure:"use_sftp"`
 	InventoryDirectory   string   `mapstructure:"inventory_directory"`
 	InventoryFile        string   `mapstructure:"inventory_file"`
+	KeepInventoryFile    bool     `mapstructure:"keep_inventory_file"`
```
Comment (SwampDragons) [inline provisioner/ansible/provisioner.go:66]: I found this helpful when debugging, and realized it would be helpful to users who want to debug, too, so I turned it into an option instead of just commenting out the code while I worked on it. It probably should be its own PR but it's such a small element of the overall diff I figured it doesn't add that much extra complexity to review.

Comment (nywilken) [reply provisioner/ansible/provisioner.go:66]: It's a nice touch for sure. When I first reviewed the PR I thought that it would be helpful for users if they run into issues debugging. Nicely done :heavy_check_mark:
