### PR TITLE
Option to keep ISO attached for live distributions

### LINKED ISSUE #5949: virtualbox-iso builder: Option to keep ISO attached for final VM
Some operating systems are designed to boot primarily from installation media rather than any other attached storage devices. For example, virtual machines packed for SmartOS or Tails will fail to boot, as packer omits the ISO virtual disc device from the final virtual disk image. Could packer offer a configuration option, default false, to bundle the ISO virtual disc device in the final virtual disk image, and keep the ISO disc as top boot priority?

Is there a `vboxmanage` snippet I can include to accomplish this?

I think the RemoveDevices step in the virtualbox builder source code is where this option could be queried.

As a workaround, I will look into premade virtual disk sets for SmartOS and Tails.

### PR DESCRIPTION
**Pull request by mcandre**
Expose the `--iso` option for `VBoxManage export` up to virtualbox-iso builder configuration as `"bundle_iso"`, and ensure that the remove device step does not detach the ISO when this option is enabled. This option helps some operating systems like SmartOS and TAILS, that require installation media to continue to be present even after installation in order to successfully boot.

Closes #5949

### CODE REVIEW

**Comment by SwampDragons** [comment]
Can you run make fmt on the code to unstick the tests please?

File: builder/virtualbox/common/step_export.go [hunk 1]
```diff
@@ -22,11 +22,28 @@ type StepExport struct {
...
+
+		for _, option := range s.ExportOpts {
+			if option == "--iso" || option == "-I" {
+				foundISOOption = true
+				break
+			}
+		}
+
+		if !foundISOOption {
+			s.ExportOpts = append(s.ExportOpts, "--iso")
```
Comment (SwampDragons) [inline builder/virtualbox/common/step_export.go]: instead of messing around with the foundISOOption variable, why not just move this line up into the original loop?  

```
for _, option := range s.ExportOpts {
		if option == "--iso" || option == "-I" {
			s.ExportOpts = append(s.ExportOpts, "--iso")
			break
		}
}
```

**Comment by SwampDragons** [comment]
Apart from my comment above and the need to resolve conflicts, this looks good. If you can address those things, I'll merge.

**Comment by SwampDragons** [comment]
@mcandre If you're interested in getting this into the 1.2.3 release I need the changes by tomorrow; if you aren't in a rush I'll bump this to 1.3.0.

**Comment by SwampDragons** [comment]
@mcandre Is this still something you're interested in getting across the finish line, or should I close it?

File: builder/virtualbox/common/step_export.go (hunk 1 above)
Comment (mcandre) [reply builder/virtualbox/common/step_export.go]: Feel free to submit a PR for that change lol

**Comment by SwampDragons** [comment]
Closing due to inactivity.

File: builder/virtualbox/common/step_export.go (hunk 1 above)
Comment (mcandre) [reply builder/virtualbox/common/step_export.go]: That’s a good improvement, will add this when I get around to resolving the merge conflict

**Comment by mcandre** [comment]
Hey, could someone help me resolve the merge conflicts? I did a lot of work on this feature and feel burnt out after seeing the effort go to waste with the merge conflicts over time :/

**Comment by SwampDragons** [comment]
Resolved. Can you address the request I made in April?

**Comment by SwampDragons** [comment]
@mcandre I've resolved conflicts again and I cleaned up the loop that I asked you to look at, so this is ready to merge. Thanks for this work.

That said, this isn't really the way PR review is supposed to work. Normally when a maintainer requests changes to code you submit, it's your responsibility to make those changes and to keep the PR up to date until you do. It's unfair to other contributors who do follow those norms to demand that maintainers do extra legwork to make your changes mergeable. Please keep that in mind if you make more contributions to Packer (which I do hope you do). 

Thanks again!
