### PR TITLE
fix nasty edge case where we can't find guest additions on windows if they are on a different drive

### LINKED ISSUE #5700: Hyper-V ISO builder fails to download ISO file from local drive
Packer version: 1.1.3

Host platform: Win 10.  
Version:  1709. 
OS build: 16299.98

Trying to build a Ubuntu VM on Hyper-V with Packer 1.1.3 fails when Packer tries to download the Ubuntu ISO file from a local disk (but a different disk than where the packer configuration lives). The command line output is:

    & packer.exe build -var-file="E:\documents\Petrik\documents\operations\calvinverse\base.linux\build\temp\build\packer_variables.json" "E:\documents\Petrik\documents\operations\calvinverse\base.linux\build\temp\build\packer.json"
    hyperv-iso output will be in this color

    ==> hyperv-iso: Creating temporary directory...
    ==> hyperv-iso: Downloading or copying ISO
        hyperv-iso: Downloading or copying: file://F:/iso/linux/ubuntu-16.04.1-server-amd64.iso
        hyperv-iso: Error downloading: CreateFile /iso/linux/ubuntu-16.04.1-server-amd64.iso: The system cannot find the path specified.
    ==> hyperv-iso: ISO download failed.
    ==> hyperv-iso: Deleting output directory...
    ==> hyperv-iso: Deleting temporary directory...
    Build 'hyperv-iso' errored: ISO download failed.

    ==> Some builds didn't complete successfully and had errors:
    --> hyperv-iso: ISO download failed.

    ==> Builds finished but no artifacts were created.

The build log and the configurations can be found in this [gist](https://gist.github.com/pvandervelde/67e69235470a2168f52b20863340f146).

This might potentially be related to #5620

### LINKED ISSUE #5713: Guest additions download failed after upgrading from 1.1.1 to 1.1.3
I have a packer template similar to this one: https://github.com/boxcutter/ubuntu

After upgrade to 1.1.3, I'm getting the following:

```
2017/12/18 17:14:03 ui: virtualbox-iso output will be in this color.
2017/12/18 17:14:03 ui: vmware-iso output will be in this color.
2017/12/18 17:14:03 ui: 
2017/12/18 17:14:03 Build debug mode: false
2017/12/18 17:14:03 Force build: false
2017/12/18 17:14:03 On error: 
2017/12/18 17:14:03 Preparing build: virtualbox-iso
2017/12/18 17:14:03 Preparing build: vmware-iso
2017/12/18 17:14:03 Starting build run: virtualbox-iso
2017/12/18 17:14:03 Running builder: virtualbox-iso
2017/12/18 17:14:03 [INFO] (telemetry) Starting builder virtualbox-iso
2017/12/18 17:14:03 Waiting on builds to complete...
2017/12/18 17:14:03 Starting build run: vmware-iso
2017/12/18 17:14:03 Running builder: vmware-iso
2017/12/18 17:14:03 [INFO] (telemetry) Starting builder vmware-iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 [DEBUG] builder/virtualbox: VBOX_MSI_INSTALL_PATH = C:\Program Files\Oracle\VirtualBox\
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 VBoxManage path: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Searching for file 'C:/Program Files (x86)/VMware/VMware Workstation/vmware.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Found file 'C:/Program Files (x86)/VMware/VMware Workstation/vmware.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Searching for file 'C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Found file 'C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Searching for file 'C:/Program Files (x86)/VMware/VMware Workstation/vmware-vdiskmanager.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Found file 'C:/Program Files (x86)/VMware/VMware Workstation/vmware-vdiskmanager.exe'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 VMware app path: C:/Program Files (x86)/VMware/VMware Workstation/vmware.exe
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 vmrun path: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 vdisk-manager path: C:/Program Files (x86)/VMware/VMware Workstation/vmware-vdiskmanager.exe
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Detected VMware WS version: 14
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Searching for file 'C:/Program Files (x86)/VMware/VMware Workstation/linux.iso'
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Found file 'C:/Program Files (x86)/VMware/VMware Workstation/linux.iso'
2017/12/18 17:14:03 ui: ==> vmware-iso: Downloading or copying ISO
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Acquiring lock to download: file://Volumes/Storage/software/ubuntu/ubuntu-16.04.3-server-amd64.iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Acquiring lock to download: http://releases.ubuntu.com/16.04.3/ubuntu-16.04.3-server-amd64.iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 VBoxManage --version output: 5.1.30r118389
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 VirtualBox version: 5.1.30
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Verifying checksum of E:\PackerCache\2b6eba7bfd46552a598360d9b28d3a584f91260d3fef906c8987bc74be115182.iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Found Default Guest Additions ISO: C:\Program Files\Oracle\VirtualBox/VBoxGuestAdditions.iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Guest additions URL: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
2017/12/18 17:14:03 ui: ==> virtualbox-iso: Downloading or copying Guest additions
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Acquiring lock to download: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
2017/12/18 17:14:03 ui:     virtualbox-iso: Downloading or copying: file://C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 Parsed URL: &url.URL{Scheme:"file", Opaque:"", User:(*url.Userinfo)(nil), Host:"C:", Path:"/Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso", RawPath:"", ForceQuery:false, RawQuery:"", Fragment:""}
2017/12/18 17:14:03 packer.exe: 2017/12/18 17:14:03 [DEBUG] Using local file: /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
2017/12/18 17:14:03 ui:     virtualbox-iso: Error downloading: CreateFile /Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso: The system cannot find the path specified.
2017/12/18 17:14:03 ui error: ==> virtualbox-iso: Guest additions download failed.
2017/12/18 17:14:03 [INFO] (telemetry) ending virtualbox-iso
2017/12/18 17:14:03 [INFO] (telemetry) found error: Guest additions download failed.
2017/12/18 17:14:03 ui error: Build 'virtualbox-iso' errored: Guest additions download failed.
```

What could be the issue?

### PR DESCRIPTION
**Pull request by SwampDragons**
fixes #5713
fixes #5700

See the gloriously detailed comment here for context: https://github.com/hashicorp/packer/issues/5713#issuecomment-353263035

I've tested this on osx, as well as on windows both on the same and on a different drive.  I've confirmed that this fixes the issue reported in 5713, and it doesn't seem to break anything else.  Would love some sanity-check confirmation from other windows users that this has fixed things.

### CODE REVIEW

**Comment by SwampDragons** [comment]
looking into test failures, and seeing wether I can add a few more filepath tests to DownloadableURL

**Comment by arizvisa** [comment]
Don't forget to include UNC paths in the testcases that are prefixed with a double-backslash. Some of us Windows people desire that too.

**Comment by arizvisa** [comment]
I mean, or you could just give a code review to that PR i submitted like forever ago...

**Comment by SwampDragons** [comment]
@arizvisa 

 

Reviewed.  If you wanna work with me on this please let me know.

**Comment by arizvisa** [comment]
Hey, just realized what you're working on adding with this PR and maybe this will help with conversions, but in my GH-2377 branch that I submitted a PR for, I added an interface to downloader called "LocalDownloader" which exposes a .toPath() method for converting a busted windows-url to a local path.

You can see the different cases that I handled at : https://github.com/arizvisa/packer/blob/GH-2377/common/download.go#L361, so if you're trying to verify that the url is actually something valid that can be used, then maybe that .toPath() method can be copied or exposed somehow(?)

**Comment by SwampDragons** [comment]
oh, nice.  I'll take a look.

**Comment by SwampDragons** [comment]
@AndrewSav I've tested this branch on my windows vm and it appears to have cleared up your issue.  Will you please sanity-check me and confirm that it isn't causing you trouble?  I can create you a binary if you need it.

**Comment by AndrewSav** [comment]
@SwampDragons, It can take up to 48 hours. A binary would be appreciated as it would speed things up a bit.

**Comment by SwampDragons** [comment]
[packer.zip](https://github.com/hashicorp/packer/files/1619841/packer.zip)
Windows build of this branch ^^

**Comment by andrewsav-datacom** [comment]
@SwampDragons testing it now. a tar without extension in the zip gave me a pause but I figured that out.

**Comment by andrewsav-datacom** [comment]
@SwampDragons it seems to be working, thank you for the fix. I just tested my test case from the original issue, I cannot vouch if the fix did not break something else ;)

**Comment by SwampDragons** [comment]
@AndrewSav Glad to hear it.

File: builder/virtualbox/ovf/config.go [hunk 1]
```diff
@@ -103,14 +101,12 @@ func NewConfig(raws ...interface{}) (*Config, []string, error) {
...
 			errs = packer.MultiErrorAppend(errs, fmt.Errorf("source_path is invalid: %s", err))
 		}
-		// file must exist now.
-		fileURL, _ := url.Parse(c.SourcePath)
-		if fileURL.Scheme == "file" {
-			if _, err := os.Stat(fileURL.Path); err != nil {
-				errs = packer.MultiErrorAppend(errs,
-					fmt.Errorf("source file needs to exist at time of config validation: %s", err))
-			}
+		_, err := common.FileExistsLocally(c.SourcePath)
```
Comment (mwhooker) [inline builder/virtualbox/ovf/config.go]: since the first parameter isn't used, I feel like this should be rewritten to something like

`func ValidateFileExistence(string) bool`

and just return true or false

So instead of saying "return a 2x2 result matrix and we'll decide what to do", we can just wrap all our business logic in a yes/no answer.

You could also have it return an error instead of a bool if you feel the error from stat is useful

**Comment by mwhooker** [comment]
left a comment/advice. feel free to take it or not. lgtm

File: builder/virtualbox/ovf/config.go (hunk 1 above)
Comment (SwampDragons) [reply builder/virtualbox/ovf/config.go]: oh I like this.  you're completely right; as used right now I really want a simple yes or no answer.

**Comment by bstoots** [comment]
Is this change included in the latest 1.3.2 release?  I'm still encountering this issue and want to know if I should file a separate issue or not.

**Comment by SwampDragons** [comment]
Please do open a new issue!  This was merged several releases ago, so if you're seeing something similar it's new/different/has been reintroduced.
