### PR TITLE
Docker windows

### LINKED ISSUE #6006: docker: add support for windows containers
packer version 1.20 and 1.21 (and 1.22-dev)
Host platform: Windows 10 1607 and Windows Server 1709

I seem to have multiple issues with packer when using the docker builder with very basic templates and any provisioner.  If I remove all provisoners, I can get a docker container up but without much point!

1 - Powershell - any scripts I attempt to provision seem to invoke a default behavior where packer sets some environment variables and then uploads them.  This fails (see my comments on issue #5963  and #5994) with 
```
docker: Error processing command: Error uploading ps script containing env vars: Failed to upload to '${env:SYSTEMROOT}/Temp/packer-env-vars-5aa6a518-1965-a0f8-f75e-43d6e7ba190e.ps1' in container: destination "07ac5a4dd067dd6fcc62a3d8d69c065078781c6fbcc4c83b855dc7a54b8df976:${env:SYSTEMROOT}\Temp" must be a directory
```

and yet I can attach to the docker container and SYSTEMROOT is set to C:\Windows and \Temp directory exists inside.  I've already commented on a similar issue though.  Remove the single 1 powershell provision request and no issues.

2 - File - If I try and upload a simple .BAT file, it seems packer is trying to chown of the file as it uploads:

```
Build 'docker' errored: Failed to set owner of the uploaded file: exit status 126, container 99bf8ea3137758238d76a4c0c787191933b05773a696135e7605a72ac8785340 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"ApplicationName":"","CommandLine":"/bin/sh -c \"chown -R root c:/windows/temp/myscript.bat\"","User":"root","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```
again, if I remove the simple file provision step, no issues - container is up but no real point.

3 - windows-shell -similar to 2 above

```
packer.exe: 2018/03/12 16:42:05 Retryable error: Error uploading script: Failed to set owner of the uploaded file: exit status 126, container 189ec2db6928fe4d3dcb2754792e7c24f0f40e8b7138c67f2e0c4a701de28923 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"ApplicationName":"","CommandLine":"/bin/sh -c \"chown -R root c:/Windows/Temp/script.bat\"","User":"root","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":false,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
```
Of course I can supply more info, but the JSON for all issues above really are very simple:

```
{
	"builders": [
		{
			"type": "docker",
			"image": "microsoft/windowsservercore:1709",
			"container_dir": "c:/app",
			"run_command": ["-d", "-i", "-t", "-p", "5986:5986", "-e powershell", "{{.Image}}"],
			"export_path": "image.zip",
		}
	],
	"provisioners": [
		{
			"type": "windows-shell",
			"scripts": [
				"./myscript.bat"
			]
		}
	]
}
```

I wondered if all this was due to packer using the default docker communicator.  So I tried to switch to WinRM as this is for a windows container.  I had no luck with that either in that it fails to connect at all as it seems the winrm_host value I specify is never passed according to the debug log:
```
ui: ==> docker: Waiting for WinRM to become available...
2018/03/12 16:45:13 packer.exe: 2018/03/12 16:45:13 [INFO] Attempting WinRM connection...
2018/03/12 16:45:13 packer.exe: 2018/03/12 16:45:13 [DEBUG] connecting to remote shell using WinRM
2018/03/12 16:45:14 packer.exe: 2018/03/12 16:45:14 [ERROR] connection error: unknown error Post https://:5986/wsman: dial tcp :5986: connectex: No connection could be made because the target machine actively refused it.
```

Thanks!

### PR DESCRIPTION
**Pull request by SwampDragons**
This adds a new docker communicator, the windows_container_communicator. Fairly self-explanatory; this communicator allows us to build windows containers using docker for windows. 

Windows containers don't support docker cp, so I had to get creative with Powershell to get these uploads and downloads working.

Closes #6006

### CODE REVIEW

**Comment by SwampDragons** [comment]
here's a windows build of this branch in case people would like to give it a try.
[packer.zip](https://github.com/hashicorp/packer/files/3024381/packer.zip)

File: builder/docker/config.go [hunk 1]
```diff
@@ -23,21 +23,22 @@ type Config struct {
...
+	ExportPath       string `mapstructure:"export_path"`
+	Image            string
+	Message          string
+	Privileged       bool `mapstructure:"privileged"`
+	Pty              bool
+	Pull             bool
+	RunCommand       []string `mapstructure:"run_command"`
+	Volumes          map[string]string
+	FixUploadOwner   bool `mapstructure:"fix_upload_owner"`
+	WindowsContainer bool `mapstructure:"windows_container"`
```
Comment (azr) [inline builder/docker/config.go]: Here, may be this could be a pointer var ?
```suggestion
	WindowsContainer *bool `mapstructure:"windows_container"`
```
This way when WindowsContainer is not set we guess it based on the current os ? using `if runtime.GOOS == "windows"`

**Comment by azr** [comment]
Okay, I just tested it, sorry it took so much time for me to test !
I got an error testing it with the example build file from the doc, did I do something wrong ?
```json
{"builders": [{"type": "docker",
      "image": "microsoft/windowsservercore:1709",
      "container_dir": "c:/app",
      "windows_container": true,
      "commit": true}]}
```
```powershell
PS C:\Users\azr\go\src\github.com\hashicorp\packer> go run . build -force .\.vscode\docker-windows.json
docker output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: microsoft/windowsservercore:1709
    docker: 1709: Pulling from microsoft/windowsservercore
    docker: 5847a47b8593: Pulling fs layer
    docker: 7f4a716683dc: Pulling fs layer
    docker: 5847a47b8593: Downloading
    docker: 7f4a716683dc: Downloading
    docker: unknown blob
==> docker: Error pulling Docker image: Bad exit status: 1
Build 'docker' errored: Error pulling Docker image: Bad exit status: 1

==> Some builds didn't complete successfully and had errors:
--> docker: Error pulling Docker image: Bad exit status: 1

==> Builds finished but no artifacts were created.
exit status 1
```

**Comment by SwampDragons** [comment]
Probably this? https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10#switch-to-windows-containers

**Comment by azr** [comment]
Oh, no ! I 100% expected linux docker image to not be a thing windows and did not double check this... Sorry ! Okay your link + a docker update had it work! 

BTW I could cp on my docker container after installing the docker on windows tool.

<details>
<summary> dockerfile & logs </summary>

```Dockerfile
FROM microsoft/windowsservercore:1709

COPY Dockerfile Dockerfile
```

```
PS C:\Users\azr\go\src\github.com\hashicorp\packer\dockrtest> docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM microsoft/windowsservercore:1709
 ---> 01f134bbc6ef
Step 2/2 : COPY Dockerfile Dockerfile
 ---> ead0d6d07d1c
Successfully built ead0d6d07d1c
```
</details>

**Comment by SwampDragons** [comment]
Oh? Which docker on windows tool?  I think since it didn't come by default it's better to keep the mount as we have here to minimize the number of necessary extra tools, but maybe that means they'll add it to normal docker for windows soon?

**Comment by azr** [comment]
Okay !
Actually, may be it was just updating my docker that had it work ? Because I couldn't reproduce a fail copy case, it just worked straight out of the update. But I do remember that at some point the docker-windows ui proposed to install some extensions which I did and on mac if you do not install docker this way, the copy also does not work: so I made assumptions. 🙂

**Comment by SwampDragons** [comment]
Huh, interesting. I thought that I had updated my docker daemon before I tested.
