### PR TITLE
builder/vsphere: Don't try to delete a cd file from the remote datastore if the upload of the cd failed

### LINKED ISSUE #10042: vsphere-iso: Create custom ISO fails when running deleting cd_files due to wrong file path string.
Running Packer using the vsphere-iso builder and having 
```json
  "iso_checksum": "443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93",
  "iso_url": "iso/ubuntu-20.04.1-live-server-amd64.iso",
  "cd_files": ["./http/user-data", "./http/meta-data"],
  "cd_label": "cidata",
```
specified, packer fails to create the VM because it tries to delete the custom ISO file from a wrongly concatenated path from the vSphere datastore.

#### Reproduction Steps
- Configure the above 4 parameters in the packer JSON.
- Create a subfolder http with the file user-data and meta-data in it.
- Copy&Paste the oscdimg.exe utility to C:\Windows\System32
- Run packer against a single ESXi 6.7 host as described at the end of the vSphere-ISO builder (Section Working with Clusters > Standalone Hosts).
- Wait for the ISO deletion to fail.

### Packer version
From 1.63

### Simplified Packer Buildfile

```json
{
  "variables": {
    "vm_name": "ubuntu2004-amd64-base",
    "vcenter_address": "YourHostIP",
    "vcenter_user": "root",
    "vcenter_password": "YourPW",
    "vcenter_dc": "",
    "vcenter_cluster": "",
    "vcenter_host": "YourHostIP",
    "vcenter_datastore": "YourDataStoreName",
    "vcenter_ignore_ssl": "true"
  },
  "sensitive-variables": [
    "vcenter_password"
  ],
  "builders": [
    {
      "type": "vsphere-iso",
      "name": "{{ user `vm_name` }}",
      "vcenter_server": "{{ user `vcenter_address` }}",
      "username": "{{ user `vcenter_user` }}",
      "password": "{{ user `vcenter_password` }}",
      "insecure_connection": "{{ user `vcenter_ignore_ssl` }}",
      "pause_before_connecting": "5m",

      "host": "{{ user `vcenter_host` }}",
      "datastore": "{{ user `vcenter_datastore` }}",

      "vm_name": "{{ user `vm_name` }}",
      "guest_os_type": "ubuntu64Guest",
      "convert_to_template": false,

      "CPUs": 2,
      "RAM": 2048,
      "network_adapters": {
        "network": "VM Network",
        "network_card": "vmxnet3"
      },
      "disk_controller_type": "pvscsi",      
      "storage": {
			  "disk_size": 15000,
				"disk_thin_provisioned":true
			},

      "ssh_username": "Username",
      "ssh_password": "UserPW",
      "ssh_port": 22,
      "ssh_timeout": "20m",
      "ssh_handshake_attempts": "1000000",
			
      "ip_wait_timeout": "30m",
      "ip_settle_timeout": "5m",

      "iso_checksum": "443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93",
      "iso_url": "iso/ubuntu-20.04.1-live-server-amd64.iso",
      "cd_files": ["./http/user-data", "./http/meta-data"],
      "cd_label": "cidata",
      "boot_wait": "2s",
      "boot_command": [
			  "<enter><wait2><enter><wait><f6><esc><wait>",
				" autoinstall<wait2> ds=nocloud;",
				"<wait><enter>"
      ],
      "shutdown_command": "echo 'YourUser'|sudo -S shutdown -P now"
    }
  ],
  "post-processors": []

```

### Operating system and Environment details
Windows Server 2016 Standard x64

### Log Fragments and crash.log files
```
2020/10/05 14:26:35 Waiting on builds to complete...
2020/10/05 14:26:35 Starting build run: ubuntu2004-amd64-base
2020/10/05 14:26:35 Running builder: vsphere-iso
2020/10/05 14:26:35 [INFO] (telemetry) Starting builder vsphere-iso
==> ubuntu2004-amd64-base: Retrieving ISO
2020/10/05 14:26:35 packer.exe plugin: Acquiring lock for: iso/ubuntu-20.04.1-live-server-amd64.iso?checksum=sha256%3A443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93 (C:\Users\admin_am\Desktop\Kube\ubuntu\packer_cache\e30b34e4d3c536763868a42bb9d5b8f14af297b8.iso.lock)
==> ubuntu2004-amd64-base: Trying iso/ubuntu-20.04.1-live-server-amd64.iso
==> ubuntu2004-amd64-base: Trying iso/ubuntu-20.04.1-live-server-amd64.iso?checksum=sha256%3A443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93
==> ubuntu2004-amd64-base: iso/ubuntu-20.04.1-live-server-amd64.iso?checksum=sha256%3A443511f6bf12402c12503733059269a2e10dec602916c0a75263e5d990f6bb93 => C:/Users/admin_am/Desktop/Kube/ubuntu/iso/ubuntu-20.04.1-live-server-amd64.iso
2020/10/05 14:26:38 packer.exe plugin: Leaving retrieve loop for ISO
2020/10/05 14:26:38 packer.exe plugin: CD label is set to cidata
2020/10/05 14:26:38 packer.exe plugin: CD path: C:\Users\admin_am\AppData\Local\Temp\3\packer970598031.iso
2020/10/05 14:26:38 packer.exe plugin: Wrote 696 bytes to user-data
==> ubuntu2004-amd64-base: Creating CD disk...
2020/10/05 14:26:38 packer.exe plugin: Wrote 0 bytes to meta-data
2020/10/05 14:26:38 packer.exe plugin: Executing: oscdimg.exe [-j1 -o -m -lcidata C:\Users\admin_am\AppData\Local\Temp\3\packer_to_cdrom062326946 C:\Users\admin_am\AppData\Local\Temp\3\packer970598031.iso]
    ubuntu2004-amd64-base: OSCDIMG 2.54 CD-ROM and DVD-ROM Premastering Utility
    ubuntu2004-amd64-base: Copyright (C) Microsoft, 1993-2007. All rights reserved.
    ubuntu2004-amd64-base: Licensed only for producing Microsoft authorized content.
    ubuntu2004-amd64-base: Scanning source tree
    ubuntu2004-amd64-base: Scanning source tree complete (2 files in 1 directories)
    ubuntu2004-amd64-base: Computing directory information complete
    ubuntu2004-amd64-base: Image file is 53248 bytes (before optimization)
    ubuntu2004-amd64-base: Writing 2 files in 1 directories to C:\Users\admin_am\AppData\Local\Temp\3\packer970598031.iso
    ubuntu2004-amd64-base: Storage optimization saved 0 files, 0 bytes (0% of image)
    ubuntu2004-amd64-base: After optimization, image file is 53248 bytes
    ubuntu2004-amd64-base: Done.
    ubuntu2004-amd64-base: 100% complete
    ubuntu2004-amd64-base: Done copying paths from CD_dirs
==> ubuntu2004-amd64-base: Uploading ubuntu-20.04.1-live-server-amd64.iso to packer_cache/ubuntu-20.04.1-live-server-amd64.iso
==> ubuntu2004-amd64-base: File ubuntu-20.04.1-live-server-amd64.iso already uploaded; continuing
==> ubuntu2004-amd64-base: Uploading packer970598031.iso to packer_cache/packer970598031.iso
==> ubuntu2004-amd64-base: Deleting cd_files image from remote datastore ...
2020/10/05 14:26:38 packer.exe plugin: Deleting CD disk: C:\Users\admin_am\AppData\Local\Temp\3\packer970598031.iso
2020/10/05 14:26:38 [INFO] (telemetry) ending vsphere-iso
Build 'ubuntu2004-amd64-base' errored after 3 seconds 128 milliseconds: File /vmfs/volumes/5c7d26db-43b2e830-cd39-f8f21e293cf8/C:/Users/admin_am/AppData/Local/Temp/3/packer970598031.iso was not found
==> Wait completed after 3 seconds 128 milliseconds
2020/10/05 14:26:38 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/10/05 14:26:38 machine readable: ubuntu2004-amd64-base,error []string{"File /vmfs/volumes/5c7d26db-43b2e830-cd39-f8f21e293cf8/C:/Users/admin_am/AppData/Local/Temp/3/packer970598031.iso was not found"}
==> Builds finished but no artifacts were created.
2020/10/05 14:26:38 [INFO] (telemetry) Finalizing.
2020/10/05 14:26:38 Cancelling builder after context cancellation context canceled

==> Wait completed after 3 seconds 128 milliseconds

==> Some builds didn't complete successfully and had errors:
--> ubuntu2004-amd64-base: File /vmfs/volumes/5c7d26db-43b2e830-cd39-f8f21e293cf8/C:/Users/admin_am/AppData/Local/Temp/3/packer970598031.iso was not found

==> Builds finished but no artifacts were created.
2020/10/05 14:26:38 waiting for all plugin processes to complete...
2020/10/05 14:26:38 C:\Users\admin_am\Desktop\Kube\ubuntu\packer.exe: plugin process exited
```
### ESXi host message
grafik

### PR DESCRIPTION
**Pull request by SwampDragons**
This PR does two things: 

1) tracks whether the CD upload was successful before trying to clean the CD up from the remote datastore. 

2) Doesn't set an error in state that will overwrite the actual build error if the CD cleanup fails

Closes #10042

I tested this by manually forcing the upload step to fail with a custom error.

### CODE REVIEW

File: builder/vsphere/common/step_remote_upload.go [hunk 1]
```diff
@@ -66,8 +69,11 @@ func (s *StepRemoteUpload) uploadFile(path string, d driver.Driver, ui packer.Ui
 
 	ui.Say(fmt.Sprintf("Uploading %s to %s", filename, remotePath))
 
-	if err := ds.MakeDirectory(remoteDirectory); err != nil {
-		return "", err
+	if exists := ds.DirExists(remotePath); exists == false {
```
Comment (nywilken) [inline builder/vsphere/common/step_remote_upload.go:72]: Is this always going to be true since the file has not been uploaded yet?

File: builder/vsphere/common/step_remote_upload.go [hunk 2]
```diff
@@ -86,20 +92,21 @@ func (s *StepRemoteUpload) Cleanup(state multistep.StateBag) {
...
+			if err != nil {
+				log.Printf("Error finding datastore to delete custom CD; please delete manually: %s", err)
+				return
+			}
+
+			err = ds.Delete(UploadedCDPath.(string))
+			if err != nil {
+				log.Printf("Error deleting custom CD from remote datastore; please delete manually: %s", err)
+				return
+			}
```
Comment (nywilken) [inline builder/vsphere/common/step_remote_upload.go:109]: Nit: We can use this second if as a guard clause a return immediately if this is nothing to delete. 
```go
		if UploadedCDPath, ok := state.GetOk("cd_path"); !ok {
		    return
		}
		ui.Say("Deleting cd_files image from remote datastore ...")

		ds, err := d.FindDatastore(s.Datastore, s.Host)
		if err != nil {
			log.Printf("Error finding datastore to delete custom CD; please delete manually: %s", err)
			return
		}

		err = ds.Delete(UploadedCDPath.(string))
		if err != nil {
			log.Printf("Error deleting custom CD from remote datastore; please delete manually: %s", err)
			return
		}
```

**Review by nywilken — APPROVED** [review]
This looks good to me. I left a question and a nit.

**Comment by nywilken** [comment]
> Closes #10042 though there may be another issue that needs to be resolved for the user who opened it.

Looks like this is good to go given that the original poster considers the issue resolved after testing https://github.com/hashicorp/packer/issues/10042#issuecomment-715905582. Do you have anything else in mind for this change?

**Review by azr — APPROVED** [review]
Nice one !

**Comment by SwampDragons** [comment]
> Do you have anything else in mind for this change?

Nope, we've already iterated a few times.

File: builder/vsphere/common/step_remote_upload.go (hunk 2 above)
Comment (SwampDragons) [reply builder/vsphere/common/step_remote_upload.go:109]: If we do it the way you've written UploadedCDPath is scoped in such a way that we can't use it later. We'd have to change it to 

```	
UploadedCDPath, ok := state.GetOk("cd_path")
	if !ok {
		return
	}
```

Comment (nywilken) [reply builder/vsphere/common/step_remote_upload.go]: Ah yes, my bad. Oversight on that line.
