### PR TITLE
Disabling automatic checkpoints in hyperv-iso builder

### LINKED ISSUE #5371: Hyper-V ISO builder needs to disable & delete automatic checkpoints before running Vagrant postprocessor
Hyper-V added a new feature that automatically takes checkpoints of VMs when they're started. When you stop the VM, it's deleted. [Link](https://blogs.technet.microsoft.com/virtualization/2017/04/20/making-it-easier-to-revert/). This causes a problem for Packer because when the box file is created - it includes a copy of the VM configuration. If that config has a checkpoint but the files aren't copied into the box, then importing it will fail in Vagrant.

My proposed fix is to automatically disable the automatic checkpoints in the `hyperv-iso` builder to make it deterministic and not carry extra checkpoints that weren't intended in the original Packer build scripts. I would scope it to check for the new option first, and only change it if it's present after creating the VM but before starting it.

eg:

```powershell
if ((get-command set-vm).Parameters["AutomaticCheckpointsEnabled"]) { 
  set-vm -AutomaticCheckpointsEnabled $false
}
```

### Steps to reproduce

1. Build [Packerfile](https://github.com/StefanScherer/packer-windows/blob/my/windows_2016_insider.json) - `packer build -only=hyperv-iso .\windows_2016_insider.json`
1. `vagrant box add --name windows_2016_insider windows_2016_insider_hyperv.box`
1. `vagrant init windows_2016_insider`
1. `vagrant up`
### Expected behavior
VM should have started

### Actual behavior
```none
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) HvsiIcs
    default: 2) DockerNAT
    default: 3) nat
    default: 4) Ethernet
    default: 5) Default Switch
    default:
    default: What switch would you like to use? 4
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

"Missing Checkpoint present."
```

The box contains both a vhdx and avhdx:

```none
-a----        9/21/2017  11:55 AM        4194304 WindowsServer2016Insider.vhdx
-a----        9/21/2017  11:56 AM    12788432896 WindowsServer2016Insider_4082B281-E871-442B-8574-91A5D8F4E935.avhdx
```

### Version Information

- Packer version - Packer v1.1.0
- Host platform - Windows 10 Insider - 16291.0.amd64fre.rs3_release.170912-1708. Although this would apply to any Windows 10 insider build since around May

### References

https://github.com/hashicorp/vagrant/issues/8988

### PR DESCRIPTION
**Pull request by PatrickLang**
Closes #5371 by disabling automatic checkpoints on systems that support it.

### Work checklist
- [x] Test results - same scripts as in #5371 
- [x] Test results - same scripts succeed on Windows 10 1703 which doesn't have auto checkpoints

### Test results - Build succeeds on a Windows 10 Insider machine

```none
==> hyperv-iso: Running post-processor: vagrant
==> hyperv-iso (vagrant): Creating Vagrant box for 'hyperv' provider
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Hard Disks\WindowsServer2016Insider.vhdx to C:\Users\plang\AppData\Local\Temp\packer364298891\Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.VMRS
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.VMRS to C:\Users\plang\AppData\Local\Temp\packer364298891\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.VMRS
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmcx
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmcx to C:\Users\plang\AppData\Local\Temp\packer364298891\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmcx
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmgs
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmgs to C:\Users\plang\AppData\Local\Temp\packer364298891\Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmgs
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\box.xml
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\box.xml to C:\Users\plang\AppData\Local\Temp\packer364298891\Virtual Machines\box.xml
    hyperv-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2016.template
    hyperv-iso (vagrant): Compressing: Vagrantfile
    hyperv-iso (vagrant): Compressing: Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Compressing: Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.VMRS
    hyperv-iso (vagrant): Compressing: Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmcx
    hyperv-iso (vagrant): Compressing: Virtual Machines\A3AC8AB5-43AD-4FE3-95BB-1E7919B203F1.vmgs
    hyperv-iso (vagrant): Compressing: Virtual Machines\box.xml
    hyperv-iso (vagrant): Compressing: metadata.json
Build 'hyperv-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> hyperv-iso: 'hyperv' provider box: windows_2016_insider_hyperv.box
```

Double checking box contents:

```none
Rename-Item windows_2016_insider_hyperv.box rs3_release_16296_insider_hyperv-nocheckpoint.b
ox
vagrant box add --name rs3_release_16296_insider_hyperv-nocheckpoint rs3_release_16296_insider_hyperv-nocheckpoint.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'rs3_release_16296_insider_hyperv-nocheckpoint' (v0) for provider:
    box: Unpacking necessary files from: file://D:/source/packer-windows/rs3_release_16296_insider_hyperv-nocheckpoint.box
    box: Progress: 100% (Rate: 427M/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'rs3_release_16296_insider_hyperv-nocheckpoint' (v0) for 'hyperv'!
```

Now it only has one VHDX as expected:

```none
    Directory: D:\.vagrant.d\boxes\rs3_release_16296_insider_hyperv-nocheckpoint\0\hyperv\Virtual Hard Disks


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/21/2017   3:26 PM    11647582208 WindowsServer2016Insider.vhdx
```

And `vagrant init`, `vagrant up` can import & start the VM again:

```none
vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured startup memory is 4096
==> default: Configured cpus number is 4
==> default: Configured enable virtualization extensions is true
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) HvsiIcs
    default: 2) DockerNAT
    default: 3) nat
    default: 4) Default Switch
    default: 5) Ethernet
    default:
    default: What switch would you like to use? 5
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
    default: Setting VM Integration Services
    default: Successfully imported a VM with name: WindowsServer2016Insider
==> default: Starting the machine...
```

### Test results - Windows 10 1703
This doesn't support the new auto checkpoint feature. It works as expected

```none
==> hyperv-iso: Running post-processor: vagrant
==> hyperv-iso (vagrant): Creating Vagrant box for 'hyperv' provider
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Hard Disks\WindowsServer2016Insider.vhdx to C:\Users\Patrick\AppData\Local\T
emp\packer241205263\Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.VMRS
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.VMRS to C:\Users\Patrick\AppDa
ta\Local\Temp\packer241205263\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.VMRS
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.vmcx
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.vmcx to C:\Users\Patrick\AppDa
ta\Local\Temp\packer241205263\Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.vmcx
    hyperv-iso (vagrant): Copying: output-hyperv-iso\Virtual Machines\box.xml
    hyperv-iso (vagrant): Copyed output-hyperv-iso\Virtual Machines\box.xml to C:\Users\Patrick\AppData\Local\Temp\packer241205263\Virt
ual Machines\box.xml
    hyperv-iso (vagrant): Using custom Vagrantfile: vagrantfile-windows_2016.template
    hyperv-iso (vagrant): Compressing: Vagrantfile
    hyperv-iso (vagrant): Compressing: Virtual Hard Disks\WindowsServer2016Insider.vhdx
    hyperv-iso (vagrant): Compressing: Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.VMRS
    hyperv-iso (vagrant): Compressing: Virtual Machines\4B63D131-33B1-4DA9-99BD-E76B4D827A14.vmcx
    hyperv-iso (vagrant): Compressing: Virtual Machines\box.xml
    hyperv-iso (vagrant): Compressing: metadata.json
Build 'hyperv-iso' finished.

==> Builds finished. The artifacts of successful builds are:
--> hyperv-iso: 'hyperv' provider box: windows_2016_insider_hyperv.box
PS 09/21/2017 22:18:18 C:\Users\Patrick\Source\packer-windows
>vagrant box add --name windows_2016_insider_16278 .\windows_2016_insider_hyperv.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'windows_2016_insider_16278' (v0) for provider:
    box: Unpacking necessary files from: file://C:/Users/Patrick/Source/packer-windows/windows_2016_insider_hyperv.box
    box: Progress: 100% (Rate: 357M/s, Estimated time remaining: --:--:--)
==> box: Successfully added box 'windows_2016_insider_16278' (v0) for 'hyperv'!
PS 09/21/2017 22:25:19 C:\Users\Patrick\Source\packer-windows
>mkdir \vagrant\16278


    Directory: C:\vagrant


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/21/2017  10:26 PM                16278


PS 09/21/2017 22:26:11 C:\Users\Patrick\Source\packer-windows
>cd \vagrant\16278
PS 09/21/2017 22:26:16 C:\vagrant\16278
>vagrant init windows_2016_insider_16278
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
PS 09/21/2017 22:26:30 C:\vagrant\16278
>vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Ethernet
    default: 2) pfSense-Internal
    default: 3) hyperv_Private
    default: 4) Wifi
    default: 5) nat
    default: 6) DemoNet
    default:
    default: What switch would you like to use? 4
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
    default: Setting VM Integration Services
    default: Successfully imported a VM with name: WindowsServer2016Insider
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
    default: IP: 169.254.21.109
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 192.168.1.133:5985
    default: WinRM username: vagrant
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: negotiate
==> default: Machine booted and ready!
```

Signed-off-by: Patrick Lang <plang@microsoft.com>

### CODE REVIEW

**Comment by PatrickLang** [comment]
@mwhooker any chance you can take a look? Got discussion and agreement with other Packer hyperv-iso builder users on the linked issue #5371

**Comment by mwhooker** [comment]
seems good to me. Do you think someone would ever want the option to have checkpoints? Seems like not, seeing as this is an automated process. I guess we can add an option to reenable checkpoints if it ever comes up

File: common/powershell/hyperv/hyperv.go [hunk 1]
```diff
@@ -213,10 +213,27 @@ New-VM -Name $vmName -Path $path -MemoryStartupBytes $memoryStartupBytes -NewVHD
 			return err
 		}
 
+		err = DisableAutomaticCheckpoints(vmName)
```
Comment (mwhooker) [inline common/powershell/hyperv/hyperv.go]: not very concerned with this here, especially because it follows existing style in the file, but for functions that return a single error, I like to see:

```
if err = ...; err != nil {
    return err
}
```

because it keeps the logic local

**Comment by PatrickLang** [comment]
The automatic checkpoints were intended for users that set up VMs and use them interactively with Hyper-V Manager and it's VM console. The goal was that if someone accidently messed something up - they had a checkpoint back to where they started. I don't think it's enabled on servers automatically so at the very least we should make sure Packer works the same on Windows 10 & Windows Server.

I'm willing to do a separate PR to add this as an option later, but it may also need changes to the postprocessor. This is a localized change that prevents problems for people using the next Windows 10 Fall Creators Update (1709) which is currently available through the Windows Insider program and will ship this fall.

File: common/powershell/hyperv/hyperv.go (hunk 1 above)
Comment (PatrickLang) [reply common/powershell/hyperv/hyperv.go]: Should I change it throughout the file now or save it for a separate PR?

Comment (mwhooker) [reply common/powershell/hyperv/hyperv.go]: If you want to change it in this PR, go for it, but I won't reject it if you don't change it

**Comment by ptveite** [comment]
Will this be included in the 1.1.1 release? This has been a big pain.

**Comment by mwhooker** [comment]
@ptveite yup! just merged it

**Comment by svpernova09** [comment]
Is this default behavior in Packer 1.1.1? I'm still seeing 2 drivers when building a hyper-v vagrant box. Do I need to add a configuration option to Packer?

```
    hyperv-iso (vagrant): Compressing: Virtual Hard Disks\ubuntu-16.04-amd64.vhdx
    hyperv-iso (vagrant): Compressing: Virtual Hard Disks\ubuntu-16.04-amd64_548657A0-80E7-4401-A171-2AA5182DDFE2.avhdx```

**Comment by zoredache** [comment]
This patch only appears to have fixed the problem for Generation 1 VMs.

The `DisableAutomaticCheckpoints` that [gets called](https://github.com/hashicorp/packer/blob/master/common/powershell/hyperv/hyperv.go#L226) in the block that handles creation of generation 1 VMs is not performed in the block that handles generation 2 VMs.
