### PR TITLE
packer init: better error handling with a special care for gh rate limit errors 

### LINKED ISSUE #11259: Packer rate-limited by github API, does not log issue by default and no clear way to resolve the issue
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

Hello, we are using packer to build some AWS AMIs. We have found that packer is getting rate-limited by github, but don't have any clear way to resolve that issue, as it appears that these are github API requests that are being made by packer itself, and we haven't been able to find a way to give packer a github "personal access token" to use.

We run the packer build in a CI system, and we started noticing that the builds were frequently failing when we called `packer init` and would display just this error message:

```
no release version found for the github.com/hashicorp/amazon plugin matching the constraint(s): ">= 1.0.0"
```

After setting PACKER_LOG=1, we discovered that this failure is being caused by being throttled by github:

```
+ PACKER_TYPE=amazon-ebs.al2
+ ./packer --version
1.7.4
+ PACKER_LOG=1
+ ./packer init .
2021/09/09 17:49:42 [INFO] Packer version: 1.7.4 [go1.16.6 linux amd64]
2021/09/09 17:49:42 Detected config directory from env var: /tmp/tmp.GZ133EOGJO
2021/09/09 17:49:42 [TRACE] discovering plugins in /local/TodWorker-nobody/00484ceb-6d6a-4d80-a6b3-7906e12d0835/env/MadisonGithubUtils-1.0/test-runtime
2021/09/09 17:49:42 Detected config directory from env var: /tmp/tmp.GZ133EOGJO
2021/09/09 17:49:42 [TRACE] discovering plugins in /tmp/tmp.GZ133EOGJO/.packer.d/plugins
2021/09/09 17:49:42 [TRACE] discovering plugins in .
2021/09/09 17:49:42 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/09/09 17:49:42 Detected config directory from env var: /tmp/tmp.GZ133EOGJO
2021/09/09 17:49:42 [INFO] PACKER_CONFIG env var set; attempting to open config file: /tmp/tmp.GZ133EOGJO/.packerconfig
2021/09/09 17:49:42 [WARN] Config file doesn't exist: /tmp/tmp.GZ133EOGJO/.packerconfig
2021/09/09 17:49:42 Detected config directory from env var: /tmp/tmp.GZ133EOGJO
2021/09/09 17:49:42 [INFO] Setting cache directory: /local/TodWorker-nobody/00484ceb-6d6a-4d80-a6b3-7906e12d0835/src/MadisonGithubUtils/test-runtime/packer_cache
2021/09/09 17:49:42 Detected config directory from env var: /tmp/tmp.GZ133EOGJO
e: Running in background, not using a TTY
2021/09/09 17:49:42 [TRACE] init: plugingetter.ListInstallationsOptions{FromFolders:[]string{"/local/TodWorker-nobody/00484ceb-6d6a-4d80-a6b3-7906e12d0835/env/MadisonGithubUtils-1.0/test-runtime/packer", ".", "/tmp/tmp.GZ133EOGJO/.packer.d/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc0000e4680)}}}}
2021/09/09 17:49:42 [TRACE] listing potential installations for "github.com/hashicorp/amazon" that match ">= 1.0.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/local/TodWorker-nobody/00484ceb-6d6a-4d80-a6b3-7906e12d0835/env/MadisonGithubUtils-1.0/test-runtime/packer", ".", "/tmp/tmp.GZ133EOGJO/.packer.d/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc0000e4680)}}}}
2021/09/09 17:49:42 [TRACE] for plugin github.com/hashicorp/amazon found 0 matching installation(s)
2021/09/09 17:49:42 [TRACE] getting available versions for the github.com/hashicorp/amazon plugin
2021/09/09 17:49:42 [DEBUG] github-getter: getting "https://api.github.com/repos/hashicorp/packer-plugin-amazon/git/matching-refs/tags"
2021/09/09 17:49:42 [TRACE] &{%!q(*github.Client=&{{0 0} 0xc00044b650 0xc000459c20 0xc000459cb0 packer-getter-github-1.7.4 {0 0} [{60 0 {{0 63766808924 0x8e1d720}}} {0 0 {{0 0 <nil>}}}] {0xc00068d340} 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00062ef10 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8 0xc00068d3c8}) "packer-getter-github-1.7.4"} getter could not get release: GET https://api.github.com/repos/hashicorp/packer-plugin-amazon/git/matching-refs/tags: 403 API rate limit exceeded for 205.XXX.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 39m01s]
2021/09/09 17:49:42 [DEBUG] will try to install: []
2021/09/09 17:49:42 [INFO] (telemetry) Finalizing.
no release version found for the github.com/hashicorp/amazon plugin matching the constraint(s): ">= 1.0.0"
2021/09/09 17:49:43 waiting for all plugin processes to complete...
```

#### Reproduction Steps

Using a single IP address, recreate and destroy the packer environment many times and run `packer init .` each time.

We also have this in our hcl file:

```
packer {
  required_plugins {
    amazon = {
      version = ">= 1.0.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}
```

### Packer version

1.7.4

### Simplified Packer Buildfile

the basic packer example build file in the aws tutorial should suffice: https://learn.hashicorp.com/tutorials/packer/aws-get-started-build-image?in=packer/aws-get-started

### Operating system and Environment details

AL2 linux, x86_64

### PR DESCRIPTION
**Pull request by azr**
Before, see #11259 or #11223

Now: (after actually spamming the api with no token)
```shellsession
❯ PACKER_GITHUB_API_TOKEN="" packer init .
Failed getting the "github.com/hashicorp/amazon" plugin:
1 error occurred:
        * List version or getting a plugin got rate limited. Try again in 13m28.672223s.
HINT: Set the PACKER_GITHUB_API_TOKEN env var with a token to get more requests.
GET https://api.github.com/repos/hashicorp/packer-plugin-amazon/git/matching-refs/tags: 403 API rate limit exceeded for 143.177.120.134. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 13m29s]


Failed getting the "github.com/hashicorp/googlecompute" plugin:
1 error occurred:
        * List version or getting a plugin got rate limited. Try again in 13m28.671754s.
HINT: Set the PACKER_GITHUB_API_TOKEN env var with a token to get more requests.
GET https://api.github.com/repos/hashicorp/packer-plugin-googlecompute/git/matching-refs/tags: 403 API rate limit of 60 still exceeded until 2021-10-13 14:47:23 +0200 CEST, not making remote request. [rate reset in 13m29s]


exit status 1
```

* after turning off my connection:
```
Failed getting the "github.com/hashicorp/amazon" plugin:
1 error occurred:
        * Get "https://api.github.com/repos/hashicorp/packer-plugin-amazon/git/matching-refs/tags": dial tcp: lookup api.github.com: no such host


Failed getting the "github.com/hashicorp/googlecompute" plugin:
1 error occurred:
        * Get "https://api.github.com/repos/hashicorp/packer-plugin-googlecompute/git/matching-refs/tags": dial tcp: lookup api.github.com: no such host


exit status 1
```

fix #11259

### CODE REVIEW

File: packer/plugin-getter/github/getter.go [hunk 1]
```diff
@@ -175,6 +175,8 @@ func (g *Getter) Get(what string, opts plugingetter.GetOptions) (io.ReadCloser,
 					},
 				},
 			}
+		} else {
+			log.Printf("[WARNING] github-getter: no GitHub token set, if you intend to install plugins often, please set the %s env var", ghTokenAccessor)
```
Comment (sylviamoss) [inline packer/plugin-getter/github/getter.go:179]: Nice!!

File: packer/plugin-getter/github/getter.go [hunk 2]
```diff
@@ -220,12 +222,24 @@ func (g *Getter) Get(what string, opts plugingetter.GetOptions) (io.ReadCloser,
...
-		// status is not considered a valid http status.
+		// here BareDo will return an err if the request failed or if the status
+		// is not considered a valid http status. So we have to close the body
+		// if it's not nil.
 		if resp != nil {
 			resp.Body.Close()
 		}
-		return nil, err
+		switch err := err.(type) {
+		case *github.RateLimitError:
```
Comment (sylviamoss) [inline packer/plugin-getter/github/getter.go:232]: Love this!

**Comment by azr** [comment]
Tests just passed, I was being rate limited because I was literally spamming the API. All good now.
