### PR TITLE
Retry fleet creating only on invalid IAM instance profile

### LINKED ISSUE #9516: Invalid IAM Instance Profile nameValue when using temporary_iam_instance_profile_policy_document
When specifying `temporary_iam_instance_profile_policy_document` with an `amazon-ebs` builder, builds on spot instances (e.g. when `spot_price` is specified) always fail due to the following error:

> Build 'amazon-ebs' errored: Error waiting for fleet request (REDACTED) to become ready:Your requested instance type (REDACTED) is not supported in your requested Availability Zone (REDACTED).Value (packer-5efcd988-d497-4c8a-3996-31840bf715cc) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile nameValue (packer-5efcd988-d497-4c8a-3996-31840bf715cc) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name

I believe this is due to eventual consistency with IAM since it may take some time for a newly created IAM role to become visible to another service (e.g. EC2 Spot Fleet). Running with the `-debug` option and intentionally pausing after the `Creating temporary role for this instance` step seems to resolve the issue. It may be possible to fix this bug by either adding a short sleep after the temporary IAM role creation or implementing retry/backoff on the spot fleet/instance creation.

### Packer version

1.6.0

### LINKED ISSUE #9952: builder/amazon-ebs: Fails to cleanup spot request on failure when using multiple instance types
#### Overview of the Issue
Opening this issue for further investigation as Packer does indicate that the cleanup failed and resources need to be deleted manually.

Sample error message below:
```
2020/09/16 20:56:08 ui error: ==> amazon-ebs: Error cleaning up security group. Please delete the group manually: err: DependencyViolation: resourc
e sg-087cfe036d0a25d01 has a dependent object
==> amazon-ebs:         status code: 400, request id: fdf93c2e-2a7f-47b3-8f4f-fa050f2a0db0; security group
```
#### Reproduction Steps

Run build with two different spot instance types, where one of the instance types is not available for use in the build region

### Packer version

Packer v1.6.3-dev (e05bf72d7)

### Simplified Packer Buildfile

```
{
    "builders": [
        {
            "type": "amazon-ebs",
            "region": "us-west-2",
            "ami_name": "packer-example-{{ timestamp }}",
            "source_ami_filter": {
                "filters": {
                    "virtualization-type": "hvm",
                    "name": "ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*",
                    "root-device-type": "ebs"
                },
                "owners": [
                    "099720109477"
                ],
                "most_recent": true
            },
            "ssh_username": "ubuntu",
            "spot_price": "auto",
            "spot_instance_types": "m5.xlarge, m5.large"
        }
    ]
}
```

### Log Fragments and crash.log files

<details>
<summary>Packer Log Output</summary>

```
2020/09/16 20:55:32 [INFO] Packer version: 1.6.3-dev (02549d6e0) [go1.15.2 linux amd64]
2020/09/16 20:55:32 Checking 'PACKER_CONFIG' for a config file path
2020/09/16 20:55:32 'PACKER_CONFIG' not set; checking the default config file path 2020/09/16 20:55:32 Attempting to open config file: /home/wilken/.packerconfig
2020/09/16 20:55:32 [WARN] Config file doesn't exist: /home/wilken/.packerconfig
2020/09/16 20:55:32 Setting cache directory: /home/wilken/Development/packer-templates/packer_cache
2020/09/16 20:55:32 Creating plugin client for path: /home/wilken/bin/packer.test
2020/09/16 20:55:32 Starting plugin: /home/wilken/bin/packer.test []string{"/home/wilken/bin/packer.test", "plugin", "packer-builder-amazon-ebs"}
2020/09/16 20:55:32 Waiting for RPC address for: /home/wilken/bin/packer.test
2020/09/16 20:55:32 packer.test plugin: [INFO] Packer version: 1.6.3-dev (02549d6e0) [go1.15.2 linux amd64]
2020/09/16 20:55:32 packer.test plugin: Checking 'PACKER_CONFIG' for a config file path
2020/09/16 20:55:32 packer.test plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/09/16 20:55:32 packer.test plugin: Attempting to open config file: /home/wilken/.packerconfig
2020/09/16 20:55:32 packer.test plugin: [WARN] Config file doesn't exist: /home/wilken/.packerconfig
2020/09/16 20:55:32 packer.test plugin: Setting cache directory: /home/wilken/Development/packer-templates/packer_cache
2020/09/16 20:55:32 packer.test plugin: args: []string{"packer-builder-amazon-ebs"}
2020/09/16 20:55:32 packer.test plugin: Plugin address: unix /tmp/packer-plugin947241287
2020/09/16 20:55:32 packer.test plugin: Waiting for connection...
2020/09/16 20:55:32 Received unix RPC address for /home/wilken/bin/packer.test: addr is /tmp/packer-plugin947241287
2020/09/16 20:55:32 packer.test plugin: Serving a plugin connection...
2020/09/16 20:55:32 Preparing build: amazon-ebs
2020/09/16 20:55:32 packer.test plugin: [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS or the configuration options aws_polling_delay_seconds and aws_polling_max_attempts to your desired values.
2020/09/16 20:55:32 ui: [1;32mamazon-ebs: output will be in this color.[0m
2020/09/16 20:55:32 ui:
2020/09/16 20:55:32 Build debug mode: false
2020/09/16 20:55:32 Force build: false
2020/09/16 20:55:32 On error:
2020/09/16 20:55:32 Waiting on builds to complete...
2020/09/16 20:55:32 Starting build run: amazon-ebs
2020/09/16 20:55:32 Running builder: amazon-ebs
2020/09/16 20:55:32 [INFO] (telemetry) Starting builder amazon-ebs
2020/09/16 20:55:32 packer.test plugin: Found region us-west-2
2020/09/16 20:55:32 packer.test plugin: [INFO] AWS Auth provider used: "SharedConfigCredentials: /home/wilken/.aws/credentials"
2020/09/16 20:55:32 ui: [1;32m==> amazon-ebs: Prevalidating any provided VPC information[0m
2020/09/16 20:55:32 ui: [1;32m==> amazon-ebs: Prevalidating AMI Name: packer-example-1600304132[0m
2020/09/16 20:55:33 packer.test plugin: Using AMI Filters {
2020/09/16 20:55:33 packer.test plugin:   Filters: [{
2020/09/16 20:55:33 packer.test plugin:       Name: "name",
2020/09/16 20:55:33 packer.test plugin:       Values: ["ubuntu/images/*ubuntu-xenial-16.04-amd64-server-*"]
2020/09/16 20:55:33 packer.test plugin:     },{
2020/09/16 20:55:33 packer.test plugin:       Name: "root-device-type",
2020/09/16 20:55:33 packer.test plugin:       Values: ["ebs"]
2020/09/16 20:55:33 packer.test plugin:     },{
2020/09/16 20:55:33 packer.test plugin:       Name: "virtualization-type",
2020/09/16 20:55:33 packer.test plugin:       Values: ["hvm"]
2020/09/16 20:55:33 packer.test plugin:     }],
2020/09/16 20:55:33 packer.test plugin:   Owners: ["099720109477"]
2020/09/16 20:55:33 packer.test plugin: }
2020/09/16 20:55:34 ui: [0;32m    amazon-ebs: Found Image ID: ami-003ba08113592046f[0m
2020/09/16 20:55:34 ui: [1;32m==> amazon-ebs: Creating temporary keypair: packer_5f62b404-80a1-5c24-b943-d2156bb0de55[0m
2020/09/16 20:55:34 ui: [1;32m==> amazon-ebs: Creating temporary security group for this instance: packer_5f62b406-f2e4-3c9a-1a10-fe230df16c7e[0m
2020/09/16 20:55:35 packer.test plugin: [DEBUG] Waiting for temporary security group: sg-087cfe036d0a25d01
2020/09/16 20:55:36 packer.test plugin: [DEBUG] Found security group sg-087cfe036d0a25d01
2020/09/16 20:55:36 ui: [1;32m==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...[0m
2020/09/16 20:55:36 ui: [1;32m==> amazon-ebs: Launching a spot AWS instance...[0m
2020/09/16 20:55:36 ui: [1;32m==> amazon-ebs: Interpolating tags for spot instance...[0m
2020/09/16 20:55:36 ui: [0;32m    amazon-ebs: Adding tag: "Name": "Packer Builder"[0m
2020/09/16 20:55:36 ui: [0;32m    amazon-ebs: Loading User Data File...[0m
2020/09/16 20:55:36 ui: [0;32m    amazon-ebs: Creating Spot Fleet launch template...[0m
2020/09/16 20:55:39 packer.test plugin: create request failed errors: [{
2020/09/16 20:55:39 packer.test plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/16 20:55:39 packer.test plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2b).",
2020/09/16 20:55:39 packer.test plugin:   LaunchTemplateAndOverrides: {
2020/09/16 20:55:39 packer.test plugin:     LaunchTemplateSpecification: {
2020/09/16 20:55:39 packer.test plugin:       LaunchTemplateId: "lt-0e8ed92871cb6b080",
2020/09/16 20:55:39 packer.test plugin:       Version: "1"
2020/09/16 20:55:39 packer.test plugin:     },
2020/09/16 20:55:39 packer.test plugin:     Overrides: {
2020/09/16 20:55:39 packer.test plugin:       InstanceType: "m5.large"
2020/09/16 20:55:39 packer.test plugin:     }
2020/09/16 20:55:39 packer.test plugin:   },
2020/09/16 20:55:39 packer.test plugin:   Lifecycle: "spot"
2020/09/16 20:55:39 packer.test plugin: } {
2020/09/16 20:55:39 packer.test plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/16 20:55:39 packer.test plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2c).",
2020/09/16 20:55:39 packer.test plugin:   LaunchTemplateAndOverrides: {
2020/09/16 20:55:39 packer.test plugin:     LaunchTemplateSpecification: {
2020/09/16 20:55:39 packer.test plugin:       LaunchTemplateId: "lt-0e8ed92871cb6b080",
2020/09/16 20:55:39 packer.test plugin:       Version: "1"
2020/09/16 20:55:39 packer.test plugin:     },
2020/09/16 20:55:39 packer.test plugin:     Overrides: {
2020/09/16 20:55:39 packer.test plugin:       InstanceType: "m5.large"
2020/09/16 20:55:39 packer.test plugin:     }
2020/09/16 20:55:39 ui error: [1;31m==> amazon-ebs: Error waiting for fleet request (fleet-5c6186e9-7ff7-4093-8412-0122f8d33c10) to become ready:Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2b).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2c).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2a).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2d).[0m
2020/09/16 20:55:39 packer.test plugin:   },
2020/09/16 20:55:39 packer.test plugin:   Lifecycle: "spot"
2020/09/16 20:55:39 packer.test plugin: } {
2020/09/16 20:55:39 packer.test plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/16 20:55:39 packer.test plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2a).",
2020/09/16 20:55:39 packer.test plugin:   LaunchTemplateAndOverrides: {
2020/09/16 20:55:39 packer.test plugin:     LaunchTemplateSpecification: {
2020/09/16 20:55:39 packer.test plugin:       LaunchTemplateId: "lt-0e8ed92871cb6b080",
2020/09/16 20:55:39 packer.test plugin:       Version: "1"
2020/09/16 20:55:39 packer.test plugin:     },
2020/09/16 20:55:39 packer.test plugin:     Overrides: {
2020/09/16 20:55:39 packer.test plugin:       InstanceType: "m5.large"
2020/09/16 20:55:39 packer.test plugin:     }
2020/09/16 20:55:39 packer.test plugin:   },
2020/09/16 20:55:39 packer.test plugin:   Lifecycle: "spot"
2020/09/16 20:55:39 packer.test plugin: } {
2020/09/16 20:55:39 packer.test plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/16 20:55:39 packer.test plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2d).",
2020/09/16 20:55:39 packer.test plugin:   LaunchTemplateAndOverrides: {
2020/09/16 20:55:39 packer.test plugin:     LaunchTemplateSpecification: {
2020/09/16 20:55:39 packer.test plugin:       LaunchTemplateId: "lt-0e8ed92871cb6b080",
2020/09/16 20:55:39 packer.test plugin:       Version: "1"
2020/09/16 20:55:39 packer.test plugin:     },
2020/09/16 20:55:39 packer.test plugin:     Overrides: {
2020/09/16 20:55:39 packer.test plugin:       InstanceType: "m5.large"
2020/09/16 20:55:39 packer.test plugin:     }
2020/09/16 20:55:39 packer.test plugin:   },
2020/09/16 20:55:39 packer.test plugin:   Lifecycle: "spot"
2020/09/16 20:55:39 packer.test plugin: }]
2020/09/16 20:55:40 ui: [1;32m==> amazon-ebs: No volumes to clean up, skipping[0m
2020/09/16 20:55:40 ui: [1;32m==> amazon-ebs: Deleting temporary security group...[0m
2020/09/16 20:55:40 packer.test plugin: Error deleting security group: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
2020/09/16 20:55:40 packer.test plugin: 	status code: 400, request id: 8eb79c14-f323-4f60-a311-cc71676c3ddf
2020/09/16 20:55:46 packer.test plugin: Error deleting security group: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
2020/09/16 20:55:46 packer.test plugin: 	status code: 400, request id: 926f9f0d-3504-4445-a79b-f10e1d52017a
2020/09/16 20:55:52 packer.test plugin: Error deleting security group: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
2020/09/16 20:55:52 packer.test plugin: 	status code: 400, request id: 6b21d6ca-9db1-419e-a5a2-8ea644de33c7
2020/09/16 20:55:57 packer.test plugin: Error deleting security group: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
2020/09/16 20:55:57 packer.test plugin: 	status code: 400, request id: 8e62c1fb-3370-4d50-8aec-4bb0d4eefa69
2020/09/16 20:56:03 packer.test plugin: Error deleting security group: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
2020/09/16 20:56:03 packer.test plugin: 	status code: 400, request id: fdf93c2e-2a7f-47b3-8f4f-fa050f2a0db0
2020/09/16 20:56:08 ui error: [1;31m==> amazon-ebs: Error cleaning up security group. Please delete the group manually: err: DependencyViolation: resource sg-087cfe036d0a25d01 has a dependent object
==> amazon-ebs: 	status code: 400, request id: fdf93c2e-2a7f-47b3-8f4f-fa050f2a0db0; security group ID: sg-087cfe036d0a25d01[0m
2020/09/16 20:56:08 ui: [1;32m==> amazon-ebs: Deleting temporary keypair...[0m
2020/09/16 20:56:09 [INFO] (telemetry) ending amazon-ebs
2020/09/16 20:56:09 ui error: [1;31mBuild 'amazon-ebs' errored after 37 seconds 240 milliseconds: Error waiting for fleet request (fleet-5c6186e9-7ff7-4093-8412-0122f8d33c10) to become ready:Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2b).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2c).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2a).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2d).[0m
2020/09/16 20:56:09 ui:
==> Wait completed after 37 seconds 240 milliseconds
2020/09/16 20:56:09 machine readable: error-count []string{"1"}
2020/09/16 20:56:09 ui error:
==> Some builds didn't complete successfully and had errors:
2020/09/16 20:56:09 machine readable: amazon-ebs,error []string{"Error waiting for fleet request (fleet-5c6186e9-7ff7-4093-8412-0122f8d33c10) to become ready:Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2b).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2c).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2a).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2d)."}
2020/09/16 20:56:09 ui error: --> amazon-ebs: Error waiting for fleet request (fleet-5c6186e9-7ff7-4093-8412-0122f8d33c10) to become ready:Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2b).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2c).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2a).Your requested instance type ( m5.large) is not supported in your requested Availability Zone (us-west-2d).
2020/09/16 20:56:09 ui:
==> Builds finished but no artifacts were created.
2020/09/16 20:56:09 [INFO] (telemetry) Finalizing.
2020/09/16 20:56:09 waiting for all plugin processes to complete...
2020/09/16 20:56:09 /home/wilken/bin/packer.test: plugin process exited
```
</details>

### PR DESCRIPTION
**Pull request by sylviamoss**
Closes https://github.com/hashicorp/packer/issues/9920
Closes #9516
Closes #9952

### CODE REVIEW

**Comment by sylviamoss** [comment]
@azr Do you mind running the tests from https://github.com/hashicorp/packer/pull/9810?

**Comment by sylviamoss** [comment]
I want to wait for the user's feedback before merging this PR.

**Review by nywilken — APPROVED** [review]
Results with 1.6.2
image

Results after fix
image


Slightly related to spot request creation I observed a cleanup issue where if you specify two spot instance types and if one type fails to launch (e.g "Your requested instance type ( m5.large) is not supported in your requested Availability Zone") the cleanup of the spot instances request fails does not happen. I'll open a separate issue for this investigation.

File: builder/amazon/common/step_run_spot_instance.go [hunk 1]
```diff
@@ -291,7 +290,7 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
 				// we can wait on those operations, this can be removed.
 				return true
 			}
-			return request.IsErrorRetryable(err)
+			return false
```
[the remark this answers is not in the document]
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:293]: Good! I'll change that. I had a hard time testing this, thanks for running the tests!

[the remark this answers is not in the document]
Comment (azr) [reply builder/amazon/common/step_run_spot_instance.go:293]: Yes good catch Wilken, I didn't read the `IsErrorRetryable` code when doing this; I think it would be a good idea to have errors be not retryable by default.

File: builder/amazon/common/step_run_spot_instance.go [hunk 2]
```diff
@@ -280,23 +278,22 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
...
 		},
 		RetryDelay: (&retry.Backoff{InitialBackoff: 500 * time.Millisecond, MaxBackoff: 30 * time.Second, Multiplier: 2}).Linear,
 	}.Run(ctx, func(ctx context.Context) error {
-		createOutput, err = ec2conn.CreateFleet(createFleetInput)
-
+		// Actually send the spot connection request.
+		err := req.Send()
```
Comment (azr) [inline builder/amazon/common/step_run_spot_instance.go:296]: Does using a request object changes something here ? The way I understood this that it changes nothing:

https://github.com/hashicorp/packer/blob/0fa60c68fbfcf5ef29485489a41f5afa0565bdee/vendor/github.com/aws/aws-sdk-go/service/ec2/api.go#L4071-L4072

```
// This method is useful when you want to inject custom logic or configuration
// into the SDK's request lifecycle. Such as custom headers, or retry logic.
```

File: builder/amazon/common/step_run_spot_instance.go [hunk 3]
```diff
@@ -306,25 +303,19 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
...
 			for _, outErr := range createOutput.Errors {
 				errString = errString + aws.StringValue(outErr.ErrorMessage)
 			}
 			err = fmt.Errorf(errString)
-			state.Put("error", err)
-			ui.Error(err.Error())
-			return multistep.ActionHalt
 		}
 		state.Put("error", err)
 		ui.Error(err.Error())
```
Comment (azr) [inline builder/amazon/common/step_run_spot_instance.go:321]: ah 🤦  I should have seen that in my first pass, but should this error handling be in the retry logic too ? 

So :
* If an instance was created don't retry and don't check the error
* retry if the error is retryable

File: builder/amazon/common/step_run_spot_instance.go (hunk 2 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:296]: I don't exactly remember if this was the reason but I had to change do keep the instance list in createOutput, the other way I think was overriding the variable all the time and loosing the successfully created instances. But I'll have to check that again.

File: builder/amazon/common/step_run_spot_instance.go (hunk 3 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:321]: Yeah, I think it might make sense to move it inside the retry 🤔

File: builder/amazon/common/step_run_spot_instance.go (hunk 2 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:296]: Passing to confirm the reason I said above

File: builder/amazon/common/step_run_spot_instance.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:291]: `ec2conn.CreateFleet` returns an array of error and we flat it into a single error to use it in the retry logic. Because of that, is not possible to use `IsAWSErr` because the error won't be identified as a `awserr.Error`.  So checking if the string contains the iamInstanceProfile error was the right way for the previous code

File: builder/amazon/common/step_run_spot_instance.go (hunk 2 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:296]: Passing to confirm what I said above.

File: builder/amazon/common/step_run_spot_instance.go (hunk 3 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:321]: Tried moving inside the retry logic and it started to become a bit messy. Had to check for nil values and error more than the current code

Comment (azr) [reply builder/amazon/common/step_run_spot_instance.go:321]: Ah, noes, but I think it's important because then we might create multiple instances from the retry.

Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:321]: But it already worked the way it is. The reported tested and is not creating multiple instances anymore. The retry will only retry with the iamInstanceProfile error which means it won't be possible to create any instance without it.

**Review by azr — APPROVED** [review]
Nice !

File: builder/amazon/common/step_run_spot_instance.go (hunk 3 above)
Comment (azr) [reply builder/amazon/common/step_run_spot_instance.go:321]: Got it, yes !

File: builder/amazon/common/step_run_spot_instance.go [hunk 4]
```diff
@@ -291,40 +289,39 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
...
 	}.Run(ctx, func(ctx context.Context) error {
 		createOutput, err = ec2conn.CreateFleet(createFleetInput)
-
 		if err == nil && createOutput.Errors != nil {
 			err = fmt.Errorf("errors: %v", createOutput.Errors)
 		}
+		// We can end up with errors because one of the allowed availability
+		// zones doesn't have one of the allowed instance types; as long as
+		// an instance is launched, these errors aren't important.
+		if len(createOutput.Instances) > 0 {
```
Comment (sylviamoss) [inline builder/amazon/common/step_run_spot_instance.go:303]: @azr I was able to move it to inside the retry without looking weird, I was doing something wrong in the morning.

File: builder/amazon/common/step_run_spot_instance.go [hunk 5]
```diff
@@ -291,40 +289,39 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
...
+			if err != nil && !strings.Contains(err.Error(), "Invalid IAM Instance Profile name") {
+				log.Printf("create request failed %v", err)
+				return nil
+			}
+		}
 		if err != nil {
 			log.Printf("create request failed %v", err)
 		}
```
Comment (azr) [inline builder/amazon/common/step_run_spot_instance.go:311]: Q, would it be a good idea to return nil since an instance was created ?:

```suggestion
			return nil
		}
		if err != nil {
			log.Printf("create request failed %v", err)
		}
```

File: builder/amazon/common/step_run_spot_instance.go (hunk 4 above)
Comment (azr) [reply builder/amazon/common/step_run_spot_instance.go:303]: nice work !

File: builder/amazon/common/step_run_spot_instance.go (hunk 5 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:311]: I can remove the `strings.Contains` check but I wanted to log the error anyways so the user will be aware that one or more of the instances have failed

Comment (azr) [reply builder/amazon/common/step_run_spot_instance.go]: is it possible that we ask for multiple instances at once ?

**Review by azr — APPROVED** [review]

File: builder/amazon/common/step_run_spot_instance.go (hunk 5 above)
Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go]: yes, I think that's why it's an array of errors because of the error of each instance creation. For the example that I'm using which a spot type is not available at the region, the array contains this error for one and the iam instance profile for the other one.

Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go]: The first error array return for the example I'm using
```
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: create request failed errors: [{
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2c).",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2a).",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2b).",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidParameterValue",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Value (packer-5f64bb68-c85d-337d-0212-9e404e424ac2) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.xlarge"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidParameterValue",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Value (packer-5f64bb68-c85d-337d-0212-9e404e424ac2) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.xlarge"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidParameterValue",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   ErrorMessage: "Value (packer-5f64bb68-c85d-337d-0212-9e404e424ac2) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:       InstanceType: "m5.xlarge"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:46 packer-builder-amazon-ebs plugin: }]

```

Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go]: The second one, which don't retry because the other instance was created
```
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin: create request failed for some instances errors: [{
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2c).",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     }
    amazon-ebs: Instance ID: i-09f2ed0c30b3f871d
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2a).",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin: } {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorCode: "InvalidFleetConfiguration",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   ErrorMessage: "Your requested instance type ( m5.large) is not supported in your requested Availability Zone (ap-southeast-2b).",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   LaunchTemplateAndOverrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     LaunchTemplateSpecification: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       LaunchTemplateId: "lt-0f027471f2862badf",
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       Version: "1"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     Overrides: {
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:       InstanceType: "m5.large"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:     }
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   },
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin:   Lifecycle: "spot"
2020/09/18 15:51:51 packer-builder-amazon-ebs plugin: }]

```
