### PR TITLE
Fix 10060

### LINKED ISSUE #10060: Regression in Openstack source with Packer 1.6.3
#### Overview of the Issue

`packer build` fails complaining of multiple source images, when using a `source_image_filter` with `most_recent = true`

#### Reproduction Steps

Define a source like the following
```hcl
source "openstack" "ovh" {
  source_image_filter {
    filters {
      name = "image_name"
    }

    most_recent = true
  }
}
```

`packer build .`

### Packer version

From `1.6.3`

### Operating system and Environment details

Tested on Linux and OSX

### Log Fragments and crash.log files
```
Error: 1 error(s) occurred:

* Only a source_image, a source_image_name or an external_source_image_url can be specified, not multiple.

  on source.pkr.hcl line 1:
  (source code not available)



==> Wait completed after 3 microseconds

==> Builds finished but no artifacts were created.
```

### PR DESCRIPTION
**Pull request by SwampDragons**
Rework the validation to fix 10060

Closes #10060

### CODE REVIEW

File: builder/openstack/run_config.go [hunk 1]
```diff
@@ -252,14 +252,21 @@ func (c *RunConfig) Prepare(ctx *interpolate.Context) []error {
...
-
 	if c.SourceImage == "" && c.SourceImageName == "" && c.ExternalSourceImageURL == "" && c.SourceImageFilters.Filters.Empty() {
 		errs = append(errs, errors.New("Either a source_image, a source_image_name, an external_source_image_url or source_image_filter must be specified"))
-	} else if !(hasOnlySourceImage || hasOnlySourceImageName || hasOnlyExternalSourceImageURL) {
-		errs = append(errs, errors.New("Only a source_image, a source_image_name or an external_source_image_url can be specified, not multiple."))
+	} else {
+		// Make sure we've only set one image source option
+		thereCanBeOnlyOne := []bool{len(c.SourceImageName) > 0, len(c.SourceImage) > 0, len(c.ExternalSourceImageURL) > 0, !c.SourceImageFilters.Filters.Empty()}
+		numSet := 0
+		for _, val := range thereCanBeOnlyOne {
```
Comment (azr) [inline builder/openstack/run_config.go:261]: hahah

Comment (azr) [reply builder/openstack/run_config.go:261]: here we are !

**Review by azr — APPROVED** [review]
Nice work ! This is a bug that I feared would be caused by a HCL re-prepare, turns out nope ! Pfiew.
