### PR TITLE
rpc/communicator fix race condition that causes stdout from ssh provi…

### LINKED ISSUE #4719: Shell provisioner truncates output when using `set -e` and `bash`
Hi!  I ran into an interesting scenario where useful error output from a shell provisioner was truncated:

Here is a provisioner snippet, note the `set -e`:

```
    {
      "type": "shell",
      "inline": [
	...<truncated>...
        "sudo -u service_user bash <<'DEPLOY_BASH'",
        "set -e",
	...<truncated>...
        "ln -nfs ${RELEASE_DIR} ${CURRENT_DIR}",
        "cd ${CURRENT_DIR}",
        "npm install",
	...<truncated>...
        "curl https://s3-us-west-2.amazonaws.com/static_assets/dist/dist.${SHA}.tar | tar -xv",
	...<truncated>...
        "DEPLOY_BASH"
      ]
    }
```

This would yield a failure that was opaque.  The output of the `npm install` was truncated, leading us to believe the problem was with our NPM libraries.  However the problem was later with the `tar` command on a malformed tar file.

Here is the output with `set -e`.  
https://gist.github.com/benmullin333/fd84c941f1a81f0e3048c955e2f1585a

Here is the output with the same provisioner, _without_ the `set -e`:
https://gist.github.com/benmullin333/bbe195dce4002cde47a7ac245206b1b5

I'm not sure if this falls under "user error" or not.  However, it would have been useful if someone had shared this information to save time.

### LINKED ISSUE #5050: Powershell provisioner does not return all output
The powershell provisioner does not always return all STDOUT content to the host.

It sometimes does, sometimes doesn't, so its a pain for debugging. 

I am also using TeamCity service messages at the start and end of the file (for log file grouping), so when it doesn't return all the output, it confuses TeamCity.

In my repro, it returns most of the stdout, but then returns the whole lot again encoded in the lovely WinRM xml.

- Packer version from `packer version`: `Packer v1.0.0`
- Host platform: `macOS Sierra 10.12.5 (16F73)` (also happens on ubuntu xenial)
- scripts and debug log:
https://gist.github.com/matt-richardson/26cf5c67077695a6d7c0d741b2019fae

### PR DESCRIPTION
**Pull request by SwampDragons**
Add wait groups to rpc provisioner to prevent race condition where the exit status can be set before the stdout copy has finished.

Closes #4719
Closes #5050

### CODE REVIEW

File: packer/rpc/communicator.go [hunk 1]
```diff
@@ -97,7 +112,9 @@ func (c *communicator) Start(cmd *packer.RemoteCmd) (err error) {
 
 		var finished CommandFinished
 		decoder := gob.NewDecoder(conn)
-		if err := decoder.Decode(&finished); err != nil {
+		err = decoder.Decode(&finished)
+		wg.Wait()
```
Comment (cbednarski) [inline packer/rpc/communicator.go]: Do we lose error output if we wait after the `if err != nil` block?

If these are functionally the same I'd put the `Wait` after for readability.

File: packer/rpc/communicator.go [hunk 2]
```diff
@@ -115,7 +132,12 @@ func (c *communicator) Start(cmd *packer.RemoteCmd) (err error) {
 func (c *communicator) Upload(path string, r io.Reader, fi *os.FileInfo) (err error) {
 	// Pipe the reader through to the connection
 	streamId := c.mux.NextId()
-	go serveSingleCopy("uploadData", c.mux, streamId, nil, r)
+	var wg sync.WaitGroup
+	wg.Add(1)
```
Comment (cbednarski) [inline packer/rpc/communicator.go]: 👍 I don't have a strong preference here but for wg(1) you could also use a channel. E.g. 
```
done := make(chan struct{})
go func() {
    close(done)
}
<-done
```

File: packer/rpc/communicator.go (hunk 1 above)
Comment (SwampDragons) [inline packer/rpc/communicator.go]: I have at least one person on the original issue (the OP) who's lost output when erroring out of a shell script, I imagine because of the `cmd.SetExited(123)`; I think waiting here is the safest option.

File: packer/rpc/communicator.go (hunk 2 above)
Comment (SwampDragons) [inline packer/rpc/communicator.go]: Yeah I see that's how the download works.  I have no strong preference either, other than laziness and not wanting to redo the PR.

Comment (cbednarski) [inline packer/rpc/communicator.go]: Fine with me!

File: packer/rpc/communicator.go (hunk 1 above)
Comment (cbednarski) [inline packer/rpc/communicator.go]: That makes sense to me, though I'm wondering if (specifically) a decoder error means we can't read the error response anyway. I can't be sure without exercising the branch conditions.

**Comment by mwhooker** [comment]
nice work on this!

**Comment by edmundcraske** [comment]
@SwampDragons do you reckon this could be the cause of #5142 ? I would potentially be willing to test a build with this PR reverted, not set up to do the build though :)

**Comment by SwampDragons** [comment]
@edmundcraske you're right -- I can build for you if you lmk your system.
