### PR TITLE
googlecompute-postprocessors: service account and export configs

### LINKED ISSUE #6953: googlecompute-export - doesn't support sharedVPCs
**- Packer version from `packer version`**
Packer v1.3.2

**- Host platform**
Google Cloud

**- Debug log output**
To much company/private data to scrub from entire output - pertinent info pasted
https://gist.github.com/obviousboy/cb5e104846ac6091c94d5ed0b9d38dd5

**Code**
https://gist.github.com/obviousboy/3ba38f725797db40924ec037d3445880 

**Issue**
Builder - GoogleCompute is able to create a host in a Service VPC project on a shared VPC subnet and complete its tasks. 

PostProcessors - GoogleCompute-Export is unable to to utilize a Shared VPC network and only attempts to find the default network (which has been removed). This causes the task to fail.

2018/11/02 11:05:43 ui error: ==> googlecompute (googlecompute-export): Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].network': 'glob
al/networks/default'. The referenced network resource cannot be found., invalid
==> googlecompute (googlecompute-export): Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].network': 'global/networks/default'. The refe
renced network resource cannot be found., invalid

### LINKED ISSUE #7006: GCE import post-processor doesn't support service accounts
Documentation for the GCE builder clearly states that service accounts are supported, however this does not appear to be true for the `googlecompute-import` post-processor.

Our use cases require that we build images locally (from credentialed GCE instances) before importing them into GCP as GCE images. Security requirements prevent us from using an account file in these cases.

### PR DESCRIPTION
**Pull request by Adezandee**
Extend auth for the GCE-post-processors to act like the GCE builder. I fetched some parts from #7015, and applied it to the exporter as requested by @rickard-von-essen.

I modified the exporter base image and `StartupScript` following Google's way of doing image exports which you can see here: https://github.com/GoogleCloudPlatform/compute-image-tools/tree/master/daisy_workflows/export

Closes #7006 
Closes #6953

### CODE REVIEW

File: post-processor/googlecompute-export/post-processor.go [hunk 1]
```diff
@@ -4,7 +4,7 @@ import (
 	"fmt"
 	"strings"
 
-	"github.com/hashicorp/packer/builder/googlecompute"
+	googlecompute "github.com/hashicorp/packer/builder/googlecompute"
```
Comment (rickard-von-essen) [inline post-processor/googlecompute-export/post-processor.go]: Was this automatically changed by your editor?

**Comment by rickard-von-essen** [comment]
This changes a lot of defaults, but I guess it's fine since they where unspecified before and the new values should improve the performance.

File: post-processor/googlecompute-export/post-processor.go (hunk 1 above)
Comment (Adezandee) [reply post-processor/googlecompute-export/post-processor.go]: No, I did this. Thats to clearly identify internal code import like inside the aws post processor

**Comment by Adezandee** [comment]
Indeed lots of default value changes, I used Google defaults available here https://github.com/GoogleCloudPlatform/compute-image-tools/blob/master/daisy_workflows/export/image_export.wf.json

File: post-processor/googlecompute-export/post-processor.go (hunk 1 above)
Comment (Adezandee) [reply post-processor/googlecompute-export/post-processor.go]: Well, I seems like its unnecessary. I'll remove it
