### PR TITLE
builder/azure-arm: Update logic for setting subscriptionID

### LINKED ISSUE #8515: MDI ID used for SIG publish missing subscriptionID when authenticating with managed identity
### Overview of the Issue
I am using Azure ARM builder to create image and store in shared image gallery. I am using Azure VM managed identity for Packer to authenticate.  However, this appears to be causing the statebag parameter for constants.ArmManagedImageSubscription to not be set.  
In step_publish_to_shared_image_gallery.go
line 102...
```
var managedImageSubscription = stateBag.Get(constants.ArmManagedImageSubscription).(string)
var mdiID = fmt.Sprintf("/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/images/%s", managedImageSubscription, targetManagedImageResourceGroupName, targetManagedImageName)

s.say(fmt.Sprintf(" -> MDI ID used for SIG publish     : '%s'", mdiID))
```
produces this output
```
==> azure-arm:  -> MDI ID used for SIG publish     : '/subscriptions//resourceGroups/tempimagebuildrg/providers/Microsoft.Compute/images/packertempwin2019dc'
```
resulting in this error
```
==> azure-arm: ERROR: -> LinkedAuthorizationFailed : The client has permission to perform action 'Microsoft.Resources/subscriptions/tempimagebuildrg/Microsoft.Compute/packertempwin2019dc/read' on scope '/subscriptions/12ef276f-c342-456f-b802-909283fed03a/resourceGroups/prod.pce.sharedservices.imagegallery.eastus2/providers/Microsoft.Compute/galleries/prod.pce.sharedservices.imagegallery.eastus2.01/images/GF-Base-WindowsServer-2019-Datacenter/versions/2019.352.22', however the linked subscription 'resourceGroups' was not found. 
```

#### Reproduction Steps
This is the packer config file
```
{
	"variables": {
		"virtual_network_name": "{{env `VIRTUAL_NETWORK_NAME`}}",
		"virtual_network_subnet_name": "{{env `VIRTUAL_NETWORK_SUBNET_NAME`}}",
		"virtual_network_resource_group_name": "{{env `VIRTUAL_NETWORK_RESOURCE_GROUP_NAME`}}",
		"gallery_resource_group": "{{env `GALLERY_RESOURCE_GROUP`}}",
		"gallery_name": "{{env `GALLERY_NAME`}}",
		"gallery_location": "{{env `GALLERY_LOCATION`}}",
		"gallery_image_version": "{{env `GALLERY_IMAGE_VERSION`}}",
		"ImageExpireDate": "{{env `GALLERY_IMAGE_EXPIRATION_DATE`}}",
		"managed_image_resource_group_name": "{{env `MANAGED_IMAGE_RESOURCE_GROUP_NAME`}}"
	},
	"builders": [
		{
			"type": "azure-arm",
			"os_type": "Windows",
			"image_publisher": "MicrosoftWindowsServer",
			"image_offer": "WindowsServer",
			"image_sku": "2019-Datacenter",
			"communicator": "winrm",
			"winrm_use_ssl": "true",
			"winrm_insecure": "true",
			"winrm_timeout": "10m",
			"winrm_username": "packer",
			"virtual_network_name": "{{user `virtual_network_name`}}",
			"virtual_network_subnet_name": "{{user `virtual_network_subnet_name`}}",
			"virtual_network_resource_group_name": "{{user `virtual_network_resource_group_name`}}",
			"managed_image_name": "packertempwin2019dc",
			"managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
			"location":"{{user `gallery_location`}}",
			"vm_size": "Standard_DS2_v2",
			"disk_additional_size": 500,
			"polling_duration_timeout": "3h",
			"shared_image_gallery_destination": {
				"resource_group": "{{user `gallery_resource_group`}}",
				"gallery_name": "{{user `gallery_name`}}",
				"image_name": "GF-Base-WindowsServer-2019-Datacenter",
				"image_version": "{{user `gallery_image_version`}}",
				"replication_regions": ["eastus", "eastus2", "northcentralus","uksouth","ukwest"]
			},
			"azure_tags": {
				"ImageExpireDate": "{{user `ImageExpireDate`}}",
				"ImageBase": "Windows-2019-Datacenter-latest"
			}
		}
	],
	"provisioners": [
		{
			"type": "powershell",
			"inline": [
				" # NOTE: the following *3* lines are only needed if the you have installed the Guest Agent.",
				"  while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 }",
				"  while ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running') { Start-Sleep -s 5 }",
				"  while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 }",

				"if( Test-Path $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml ){ rm $Env:SystemRoot\\windows\\system32\\Sysprep\\unattend.xml -Force}",
				"& $env:SystemRoot\\System32\\Sysprep\\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm",
				"while($true) { $imageState = Get-ItemProperty HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Setup\\State | Select ImageState; if($imageState.ImageState -ne 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { Write-Output $imageState.ImageState; Start-Sleep -s 10  } else { break } }"
			]
		}
	]
}
```

### Packer version

Packer v1.4.5

### Operating system and Environment details

Packer is running on a Azure Windows Server 2019 Datacenter VM.

### PR DESCRIPTION
**Pull request by nywilken**
Previously, when using managed identities, the Azure builder would set the subscriptionID in the Prepare method. But would not update it after getting the updated subscriptionID from the metadata server. This change updates the Run method to ensure a valid subscriptionID is saved to the statebag before continuing with an image build.

Closes #8515

### CODE REVIEW

**Comment by SwampDragons** [comment]
Looks good to me, but let's let @paulmey weigh in.

File: builder/azure/arm/builder.go [hunk 1]
```diff
@@ -64,6 +64,12 @@ func (b *Builder) Run(ctx context.Context, ui packer.Ui, hook packer.Hook) (pack
 		return nil, err
 	}
 
+	//When running Packer on an Azure instance FillParameters will update SubscriptionID from the instance
```
Comment (paulmey) [inline builder/azure/arm/builder.go]: It would help to mention this is particularly the case when using managed identity.
```suggestion
	//When running Packer on an Azure instance using Managed Identity, FillParameters will update SubscriptionID from the instance
```

**Comment by nywilken** [comment]
Thanks for the review folks :+1:
