### PR TITLE
Put the correct type in StateBag to match Azure go SDK

### LINKED ISSUE #10012: azure-arm crash on build EOF on create resource group
#### Overview of the Issue

When building a pretty simple image the packer builder crashes when trying to create the resource group. This happens regardless of if I provide a builder resource group or not.

#### Reproduction Steps

```
{
    "variables": {
        "subscription_id": "FILLIN",
        "managed_image_prefix": "packer-",
        "managed_image_resource_group_name": "myRG",
        "ssh_username": "packer",
        "ssh_password": "thisisatest123T%"
    },
    "sensitive-variables": [],
    "builders": [
        {
            "type": "azure-arm",
            "subscription_id": "{{user `subscription_id`}}",
            "ssh_username": "{{user `ssh_username`}}",
            "ssh_password": "{{user `ssh_password`}}",
            "ssh_pty": "true",
            "managed_image_name": "{{user `managed_image_prefix`}}-{{timestamp}}",
            "managed_image_resource_group_name": "{{user `managed_image_resource_group_name`}}",
            "os_type": "Linux",
            "image_publisher": "Canonical",
            "image_offer": "UbuntuServer",
            "image_sku": "18.04-LTS",
            "vm_size": "B2s",
            "location": "canadacentral"
        }
    ],
    "provisioners":[
        {
            "type": "file",
            "source": "./",
            "destination": "/tmp"
        }
        {
            "execute_command": "echo '{{user `ssh_pass`}}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'",
            "inline": [
               "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
            ],
            "inline_shebang": "/bin/sh -x",
            "type": "shell",
            "skip_clean": true
        }
    ]
}
```

Run `packer build packer.json`

### Packer version

Packer v1.6.3

### Operating system and Environment details

Ubuntu 20.04

### Log Fragments and crash.log files

https://gist.github.com/braunsonm/ea2b2f98b08e0eb209c6c0075c8f9c5d

Crash.log:
https://gist.github.com/braunsonm/2128f61d22884ae05e37377443859c7a

### LINKED ISSUE #10013: Packer 1.6.3 crashes on Azure build (panic: interface conversion: interface {} is map[string]string, not map[string]*string)
#### Overview of the Issue

After upgrading from packer 1.6.1 to 1.6.3, my azure-arm build suddenly started to fail with the following error: 

`panic: interface conversion: interface {} is map[string]string, not map[string]*string`

#### Reproduction Steps

Attempt to build an ubuntu-18.04 image in Azure with the following settings:

### Packer version
$ packer version
Packer v1.6.3

### Simplified Packer Buildfile

> "builders": [
>     {
>       "client_id": "{{ user `client_id`}}",
>       "client_secret": "{{ user `client_secret` }}",
>       "image_offer": "UbuntuServer",
>       "image_publisher": "Canonical",
>       "image_sku": "18.04-LTS",
>       "location": "East US",
>       "managed_image_name": "{{ user `vm_name` }}",
>       "managed_image_resource_group_name": "{{ user `rgname`}}",
>       "os_type": "Linux",
>       "subscription_id": "{{ user `subscription_id` }}",
>       "tenant_id": "{{ user `tenant_id` }}",
>       "type": "azure-arm",
>       "azure_tags": [
>         {
>           "group": "{{ user `group_name`}}"
>         }
>       ],
>       "virtual_network_name": "{{ user `network_name`}} ",
>       "virtual_network_resource_group_name": "{{ user `netrgname` }}",
>       "virtual_network_subnet_name": "{{ user `netsnname` }}",
>       "vm_size": "Standard_DS2_v2"
>     }
> }

### Operating system and Environment details

alpine 3.8 container, run via gitlab-ci on a Kubernetes 1.18.6 cluster

### Log Fragments and crash.log files

crash.log

> 2020/09/29 17:16:20 [INFO] Packer version: 1.6.3 [go1.15.2 linux amd64]
> 2020/09/29 17:16:20 Checking 'PACKER_CONFIG' for a config file path
> 2020/09/29 17:16:20 'PACKER_CONFIG' not set; checking the default config file path
> 2020/09/29 17:16:20 Attempting to open config file: /home/castellan/.packerconfig
> 2020/09/29 17:16:20 [WARN] Config file doesn't exist: /home/castellan/.packerconfig
> 2020/09/29 17:16:20 Setting cache directory: /builds/infrastructure-engineering/packer-rancher-node-template/packer_cache
> Running in background, not using a TTY
> 2020/09/29 17:16:20 Creating plugin client for path: /usr/local/bin/packer
> 2020/09/29 17:16:20 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-builder-azure-arm"}
> 2020/09/29 17:16:20 Waiting for RPC address for: /usr/local/bin/packer
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: [INFO] Packer version: 1.6.3 [go1.15.2 linux amd64]
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Checking 'PACKER_CONFIG' for a config file path
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: 'PACKER_CONFIG' not set; checking the default config file path
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Attempting to open config file: /home/castellan/.packerconfig
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: [WARN] Config file doesn't exist: /home/castellan/.packerconfig
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Setting cache directory: /builds/infrastructure-engineering/packer-rancher-node-template/packer_cache
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: args: []string{"packer-builder-azure-arm"}
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Plugin address: unix /tmp/packer-plugin770067422
> 2020/09/29 17:16:21 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin770067422
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Waiting for connection...
> 2020/09/29 17:16:21 packer-builder-azure-arm plugin: Serving a plugin connection...
> 2020/09/29 17:16:21 Creating plugin client for path: /usr/local/bin/packer
> 2020/09/29 17:16:21 Starting plugin: /usr/local/bin/packer []string{"/usr/local/bin/packer", "plugin", "packer-provisioner-ansible"}
> 2020/09/29 17:16:21 Waiting for RPC address for: /usr/local/bin/packer
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: [INFO] Packer version: 1.6.3 [go1.15.2 linux amd64]
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Checking 'PACKER_CONFIG' for a config file path
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: 'PACKER_CONFIG' not set; checking the default config file path
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Attempting to open config file: /home/castellan/.packerconfig
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: [WARN] Config file doesn't exist: /home/castellan/.packerconfig
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Setting cache directory: /builds/infrastructure-engineering/packer-rancher-node-template/packer_cache
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: args: []string{"packer-provisioner-ansible"}
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Plugin address: unix /tmp/packer-plugin438294049
> 2020/09/29 17:16:21 Received unix RPC address for /usr/local/bin/packer: addr is /tmp/packer-plugin438294049
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Waiting for connection...
> 2020/09/29 17:16:21 packer-provisioner-ansible plugin: Serving a plugin connection...
> 2020/09/29 17:16:21 Preparing build: azure-arm
> 2020/09/29 17:16:23 packer-provisioner-ansible plugin: ansible-playbook version: 2.10.1
> 2020/09/29 17:16:23 ui: [1;32mazure-arm: output will be in this color.[0m
> 2020/09/29 17:16:23 ui: 
> 2020/09/29 17:16:23 Build debug mode: false
> 2020/09/29 17:16:23 Force build: true
> 2020/09/29 17:16:23 On error: 
> 2020/09/29 17:16:23 Waiting on builds to complete...
> 2020/09/29 17:16:23 Starting build run: azure-arm
> 2020/09/29 17:16:23 Running builder: azure-arm
> 2020/09/29 17:16:23 [INFO] (telemetry) Starting builder azure-arm
> 2020/09/29 17:16:23 ui: [1;32m==> azure-arm: Running builder ...[0m
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: :: Configuration
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CaptureNamePrefix=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CaptureContainerName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: SharedGalleryImageVersionEndOfLifeDate=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ImagePublisher=Canonical
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ImageOffer=UbuntuServer
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ImageSku=18.04-LTS
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ImageVersion=latest
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ImageUrl=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CustomManagedImageName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CustomManagedImageResourceGroupName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: Location=East US
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: VMSize=Standard_DS2_v2
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ManagedImageResourceGroupName=IE-MachineImages
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ManagedImageName=rancher_node_template
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ManagedImageStorageAccountType=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ManagedImageOSDiskSnapshotName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ManagedImageDataDiskSnapshotPrefix=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: ResourceGroupName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: StorageAccount=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: TempComputeName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: TempResourceGroupName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: BuildResourceGroupName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: BuildKeyVaultName=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: BuildKeyVaultSKU=standard
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: VirtualNetworkName=TU-Network-East
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: VirtualNetworkSubnetName=TU-AZE-IOS-DB-16
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: VirtualNetworkResourceGroupName=Network-East-RG
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CustomDataFile=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: OSType=Linux
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: DiskCachingType=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: BootDiagSTGAccount=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: CustomResourcePrefix=
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: UserName=packer
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: Password=********************************
> 2020/09/29 17:16:23 ui: [1;32m==> azure-arm: Getting tokens using client secret[0m
> 2020/09/29 17:16:23 ui: [1;32m==> azure-arm: Getting tokens using client secret[0m
> 2020/09/29 17:16:23 ui: [0;32m    azure-arm: Creating Azure Resource Manager (ARM) client ...[0m
> 2020/09/29 17:16:23 packer-builder-azure-arm plugin: Azure request method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourcegroups/IE-MachineImages?api-version=2018-02-01" body=""
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: Azure response method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourcegroups/IE-MachineImages?api-version=2018-02-01" x-ms-request-id="48e5e987-1dc6-4458-b4c1-b13db8966f9f" body="{\"id\":\"/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourceGroups/IE-MachineImages\",\"name\":\"IE-MachineImages\",\"location\":\"eastus\",\"tags\":{\"group\":\"Infrastructure Engineering\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}" status="200 OK"
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: Azure response status="200 OK" method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourcegroups/IE-MachineImages?api-version=2018-02-01" x-ms-request-id="48e5e987-1dc6-4458-b4c1-b13db8966f9f" body="{\"id\":\"/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourceGroups/IE-MachineImages\",\"name\":\"IE-MachineImages\",\"location\":\"eastus\",\"tags\":{\"group\":\"Infrastructure Engineering\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}"
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: Azure request method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourceGroups/IE-MachineImages/providers/Microsoft.Compute/images/rancher_node_template?api-version=2018-04-01" body=""
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: Azure response status="404 Not Found" method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourceGroups/IE-MachineImages/providers/Microsoft.Compute/images/rancher_node_template?api-version=2018-04-01" x-ms-request-id="787cd3c1-97b1-4621-9bd5-9707aa6bfdc4" body="{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/images/rancher_node_template' under resource group 'IE-MachineImages' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}"
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: Azure response status="404 Not Found" method="GET" request="https://management.azure.com/subscriptions/ee76a4ac-76c6-4be1-9a70-3cfab25fec78/resourceGroups/IE-MachineImages/providers/Microsoft.Compute/images/rancher_node_template?api-version=2018-04-01" x-ms-request-id="787cd3c1-97b1-4621-9bd5-9707aa6bfdc4" body="{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/images/rancher_node_template' under resource group 'IE-MachineImages' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}"
> 2020/09/29 17:16:24 ui: [1;32m==> azure-arm: WARNING: Zone resiliency may not be supported in East US, checkout the docs at https://docs.microsoft.com/en-us/azure/availability-zones/[0m
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: panic: interface conversion: interface {} is map[string]string, not map[string]*string
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: goroutine 119 [running]:
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*StepCreateResourceGroup).Run(0xc0001a8030, 0x520d6c0, 0xc0000d8080, 0x520e300, 0xc000b7dda0, 0xc000b7dda0)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/step_create_resource_group.go:64 +0xa36
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/helper/multistep.(*BasicRunner).Run(0xc0001a8330, 0x520d6c0, 0xc0000d8080, 0x520e300, 0xc000b7dda0)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/helper/multistep/basic_runner.go:67 +0x21c
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/builder/azure/arm.(*Builder).Run(0xc0009dc000, 0x520d6c0, 0xc0000d8080, 0x5227f20, 0xc0008fa1b0, 0x518eb00, 0xc00035bfc0, 0x0, 0x0, 0x0, ...)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/builder/azure/arm/builder.go:285 +0x15a2
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: github.com/hashicorp/packer/packer/rpc.(*BuilderServer).Run(0xc000411300, 0x1, 0xc00049e050, 0x0, 0x0)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/home/circleci/project/packer/packer/rpc/builder.go:117 +0x1c4
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: reflect.Value.call(0xc0000b57a0, 0xc000e6bc70, 0x13, 0x4bd13c4, 0x4, 0xc000119f08, 0x3, 0x3, 0x4bd03ac, 0x2, ...)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:475 +0x8c7
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: reflect.Value.Call(0xc0000b57a0, 0xc000e6bc70, 0x13, 0xc000b87f08, 0x3, 0x3, 0x3dff320, 0x4d19268, 0x401c700)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/reflect/value.go:336 +0xb9
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: net/rpc.(*service).call(0xc000411380, 0xc0001c6370, 0xc00049f218, 0xc00049f220, 0xc0000e5b80, 0xc0005c6340, 0x3d82f60, 0xc00049e01c, 0x18a, 0x3c91be0, ...)
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x189
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: created by net/rpc.(*Server).ServeCodec
> 2020/09/29 17:16:24 packer-builder-azure-arm plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x445
> 2020/09/29 17:16:24 [INFO] (telemetry) ending azure-arm
> 2020/09/29 17:16:24 ui error: [1;31mBuild 'azure-arm' errored after 732 milliseconds 947 microseconds: unexpected EOF[0m
> 2020/09/29 17:16:24 ui: 
> ==> Wait completed after 733 milliseconds 29 microseconds
> 2020/09/29 17:16:24 machine readable: error-count []string{"1"}
> 2020/09/29 17:16:24 ui error: 
> ==> Some builds didn't complete successfully and had errors:
> 2020/09/29 17:16:24 machine readable: azure-arm,error []string{"unexpected EOF"}
> 2020/09/29 17:16:24 ui error: --> azure-arm: unexpected EOF
> 2020/09/29 17:16:24 ui: 
> ==> Builds finished but no artifacts were created.
> 2020/09/29 17:16:24 Cancelling builder after context cancellation context canceled
> 2020/09/29 17:16:24 Error cancelling builder: connection is shut down
> 2020/09/29 17:16:24 [INFO] (telemetry) Finalizing.
> 2020/09/29 17:16:24 /usr/local/bin/packer: plugin process exited
> 2020/09/29 17:16:24 waiting for all plugin processes to complete...
> 2020/09/29 17:16:24 /usr/local/bin/packer: plugin process exited
>

### PR DESCRIPTION
**Pull request by braunsonm**
The Azure Go SDK expects the tags format to use a pointer to the string for the map value.
The configuration from the builder is not a pointer so when storing in the state bag for
reference in later execution we convert it when creating the StateBag.

Fixes #10012
Fixes #10013

### CODE REVIEW

**Comment by braunsonm** [comment]
This was likely introduced from an update in the Azure Go SDK recently.

File: builder/azure/arm/builder.go [hunk 1]
```diff
@@ -390,7 +390,12 @@ func (b *Builder) getBlobAccount(ctx context.Context, client *AzureClient, resou
 func (b *Builder) configureStateBag(stateBag multistep.StateBag) {
 	stateBag.Put(constants.AuthorizedKey, b.config.sshAuthorizedKey)
 
-	stateBag.Put(constants.ArmTags, b.config.AzureTags)
+	tagsMap := make(map[string]*string)
+	for key, value := range b.config.AzureTags {
+		tagsMap[key] = &value
+	}
+	// Azure SDK expects string pointers for the values
+	stateBag.Put(constants.ArmTags, tagsMap)
```
Comment (nywilken) [inline builder/azure/arm/builder.go:398]: PR #9985 introduced a helper function `azcommon.MapToAzureTags` that converts tags from a simple map[string]string to a map[string]*string. 

This was not caught by the tests for step_create_resource because test for that step create the expected type. We need to add some test for this case and then update this line to look like 
```suggestion
   stateBag.Put(constants.ArmTags, azcommon.MapToAzureTags(b.config.AzureTags))
```

With that said we should probably add a type assertion check on [here](https://github.com/hashicorp/packer/blob/bdb1c47532655ceac13a14d06bc7e228b33db983/builder/azure/arm/step_create_resource_group.go#L64) to capture any failed conversions which will also prevent the Packer crash in #10012 . 

Something like

```go
tags, ok := state.Get(constants.ArmTags).(map[string]*string)
if !ok {                                        
    err := fmt.Errorf("failed to extract tags from state bag")                                                                                                                                                                                                                                      
    state.Put(constants.Error, err)                                                                                                                                                                                                                                                                    
    s.error(err)                                                                                                                                                                                                                                                                                  
    return multistep.ActionHalt                                                                                                                                                                                                                                                                        
  } 
```

**Review by nywilken — CHANGES_REQUESTED** [review]
Hello again thanks for opening up this PR. It is on the right track. There is a helper that should do what your code is doing. To keep the logic consistent the change should move to using the helper. 

Some additional test cases need to be added, possibly by just updating the existing to use the config and not a raw map[string]*string to prevent this in the future. We, the Packer maintainers, would like to get this fix rolled out as soon as possible so I am looking into the tests now. But if you could make the change to use the helper and test again on your end that would be great.

**Comment by braunsonm** [comment]
Hey @nywilken addressed your comments as you stated you're taking a look at the tests.

I would also like to roll this out as soon as possible. Why is there no integration tests in azure that would have caught this?

**Comment by braunsonm** [comment]
Not sure if you were looking at adding a test change to the builder but I added a case on the resource group creation.

**Comment by nywilken** [comment]
> Not sure if you were looking at adding a test change to the builder but I added a case on the resource group creation. This change is working on my end with a test packer config.

Thanks for the quick turnaround @braunsonm adding a test to the builder is what I was looking into as that is where we make the initial conversion. The test you have in place looks great. Interesting enough it looks like result is always multistep.ActionHalt for those test. But fails on master which is what we want. 

I wrote a quick test for the builder that requires two changes would you like for me to add as a comment or can I add as a commit to your branch? 

The acceptance tests that accounts for tags does not seem to be a thing so we should add that. As to why there are no tests already, slight oversight. We've have been working on improving acceptance tests across the builders. So this is a step in the right direction.

**Comment by braunsonm** [comment]
Sounds good, go ahead and commit to this branch @nywilken

**Review by nywilken — APPROVED** [review]
> Sounds good, go ahead and commit to this branch @nywilken

@braunsonm thanks for letting me push to your branch. I added two commits which should capture the additional tests. Going to get a second pair of eyes on the commits but this should be good to go. We are anticipating a 1.6.4 this week to address this regression along with #10000 

My only nit is the go.mod files I think those changes are from building the project. But if it needs to be dropped I'll square that away at merge time.

**Comment by nywilken** [comment]
@azr could you take a quick look over the changes. The changes have been tested with both JSON and HCL configs.

**Comment by nywilken** [comment]
@braunsonm if I didn't say it already. Thanks for working with me on getting this patched up. Great stuff!

**Comment by braunsonm** [comment]
First time using Packer today to find it odd that it wasn't working 😂 Happy to help!

File: builder/azure/arm/builder.go [hunk 2]
```diff
@@ -390,7 +390,7 @@ func (b *Builder) getBlobAccount(ctx context.Context, client *AzureClient, resou
 func (b *Builder) configureStateBag(stateBag multistep.StateBag) {
 	stateBag.Put(constants.AuthorizedKey, b.config.sshAuthorizedKey)
 
-	stateBag.Put(constants.ArmTags, b.config.AzureTags)
+	stateBag.Put(constants.ArmTags, packerAzureCommon.MapToAzureTags(b.config.AzureTags))
```
Comment (azr) [inline builder/azure/arm/builder.go:393]: ah bummer; I had missed that one ! LGTM ! Good fix !
