### PR TITLE
fix issue where -force is not working with vsphere builders

### LINKED ISSUE #9036: -force not working?
#### Overview of the Issue

When attempting to run a packer build in the packer container, using the vsphere-iso builder, -force isn't working to remove a leftover VM.  Not a huge issue, just annoying.

#### Reproduction Steps

Run a build and cancel the build leaving a leftover VM.  Power off the leftover VM and rerun a new build with -force.  The expected behaviour is for -force to remove the leftover VM and create new one, but it doesn't.

### Packer version

1.5.5

From `packer version`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

packer docker image

### Logs

 <details>
<summary>PACKER LOG</summary>
2020/04/09 19:24:05 Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 Setting cache directory: /workspace/packer_cache
Running in background, not using a TTY
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-builder-vsphere-iso"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: args: []string{"packer-builder-vsphere-iso"}
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin558768450
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Plugin address: unix /tmp/packer-plugin558768450
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Waiting for connection...
2020/04/09 19:24:05 packer-builder-vsphere-iso plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-windows-shell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin095649605
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: args: []string{"packer-provisioner-windows-shell"}
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Plugin address: unix /tmp/packer-plugin095649605
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Waiting for connection...
2020/04/09 19:24:05 packer-provisioner-windows-shell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-powershell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin849076698
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin849076698
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Waiting for connection...
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-file"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-file plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-file plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-file plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-file plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-file plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-file plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-file plugin: args: []string{"packer-provisioner-file"}
2020/04/09 19:24:05 packer-provisioner-file plugin: Plugin address: unix /tmp/packer-plugin682524482
2020/04/09 19:24:05 packer-provisioner-file plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin682524482
2020/04/09 19:24:05 packer-provisioner-file plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-shell-local"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: args: []string{"packer-provisioner-shell-local"}
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Plugin address: unix /tmp/packer-plugin442244314
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin442244314
2020/04/09 19:24:05 packer-provisioner-shell-local plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-provisioner-powershell"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-provisioner-powershell plugin: args: []string{"packer-provisioner-powershell"}
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Plugin address: unix /tmp/packer-plugin130778556
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin130778556
2020/04/09 19:24:05 packer-provisioner-powershell plugin: Serving a plugin connection...
2020/04/09 19:24:05 Creating plugin client for path: /bin/packer
2020/04/09 19:24:05 Starting plugin: /bin/packer []string{"/bin/packer", "plugin", "packer-post-processor-manifest"}
2020/04/09 19:24:05 Waiting for RPC address for: /bin/packer
2020/04/09 19:24:05 packer-post-processor-manifest plugin: [INFO] Packer version: 1.5.5 [go1.13.7 linux amd64]
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Checking 'PACKER_CONFIG' for a config file path
2020/04/09 19:24:05 packer-post-processor-manifest plugin: 'PACKER_CONFIG' not set; checking the default config file path
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Attempting to open config file: /tmp/.packerconfig
2020/04/09 19:24:05 packer-post-processor-manifest plugin: [WARN] Config file doesn't exist: /tmp/.packerconfig
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Setting cache directory: /workspace/packer_cache
2020/04/09 19:24:05 packer-post-processor-manifest plugin: args: []string{"packer-post-processor-manifest"}
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Plugin address: unix /tmp/packer-plugin520270914
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Waiting for connection...
2020/04/09 19:24:05 Received unix RPC address for /bin/packer: addr is /tmp/packer-plugin520270914
2020/04/09 19:24:05 packer-post-processor-manifest plugin: Serving a plugin connection...
2020/04/09 19:24:05 Build debug mode: false
2020/04/09 19:24:05 Force build: true
2020/04/09 19:24:05 On error: 
2020/04/09 19:24:05 Preparing build: vsphere-iso
2020/04/09 19:24:05 Waiting on builds to complete...
2020/04/09 19:24:05 Starting build run: vsphere-iso
2020/04/09 19:24:05 Running builder: vsphere-iso
2020/04/09 19:24:05 [INFO] (telemetry) Starting builder vsphere-iso
2020/04/09 19:24:06 [INFO] (telemetry) ending vsphere-iso
2020/04/09 19:24:06 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/04/09 19:24:06 machine readable: vsphere-iso,error []string{"error creating vm: The name 'W2K19StdBaseTemplate-packer-docker' already exists."}
==> Builds finished but no artifacts were created.
2020/04/09 19:24:06 [INFO] (telemetry) Finalizing.
2020/04/09 19:24:06 waiting for all plugin processes to complete...
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
2020/04/09 19:24:06 /bin/packer: plugin process exited
</details>

### PR DESCRIPTION
**Pull request by jhawk28**
add better error support to check if vm exists
use path.Join so that it looks up the VM correctly
turn off VM if it is still running

Closes #9036

### CODE REVIEW

File: builder/vsphere/clone/step_clone.go [hunk 1]
```diff
@@ -49,18 +52,28 @@ type StepCloneVM struct {
...
+
+			err := vm.Destroy()
+			if err != nil {
+				state.Put("error", fmt.Errorf("error destroying %s: %v", vmPath, err))
+			}
+		} else {
+			state.Put("error", fmt.Errorf("%s already exists, you can use -force flag to destroy it: %v", vmPath, err))
+			return multistep.ActionHalt
 		}
 	}
```
Comment (nywilken) [inline builder/vsphere/clone/step_clone.go:78]: Since these are mostly guard clauses lets take the happy-path approach to remove the if/else nesting. 

```go
  vm, err := d.FindVM(vmPath)                                                                                                                      
  if err != nil {                                                                                                                                  
    if _, ok := err.(*find.NotFoundError); !ok {                                                                                                   
      state.Put("error", fmt.Errorf("error looking up old vm: %v", err))                                                                           
      return multistep.ActionHalt                                                                                                                  
    }                                                                                                                                              
  }
                                                                                                          
  if err == nil && !s.Force {                                                                                                                      
    state.Put("error", fmt.Errorf("%s already exists, you can use -force flag to destroy it: %v", vmPath, err))                                    
    return multistep.ActionHalt                                                                                                                    
  }                                                                                                                                                
                                                                                                                                                   
  if err == nil && s.Force {                                                                                                                       
    ui.Say(fmt.Sprintf("the vm/template %s already exists, but deleting it due to -force flag", vmPath))                                           
                                                                                                                                                   
    // power off just in case it is still on                                                                                                       
    vm.PowerOff()                                                                                                                                  
                                                                                                                                                   
    err := vm.Destroy()                                                                                                                            
    if err != nil {                                                                                                                                
      state.Put("error", fmt.Errorf("error destroying %s: %v", vmPath, err))                                                                       
    }                                                                                                                                              
  }
```

File: builder/vsphere/iso/step_create.go [hunk 2]
```diff
@@ -100,18 +103,28 @@ type StepCreateVM struct {
 func (s *StepCreateVM) Run(_ context.Context, state multistep.StateBag) multistep.StepAction {
 	ui := state.Get("ui").(packer.Ui)
 	d := state.Get("driver").(*driver.Driver)
-	vmPath := fmt.Sprintf("%s/%s", s.Location.Folder, s.Location.VMName)
+	vmPath := path.Join(s.Location.Folder, s.Location.VMName)
 
 	vm, err := d.FindVM(vmPath)
+	if err != nil {
```
Comment (nywilken) [inline builder/vsphere/iso/step_create.go:109]: Same refactor as specified above.

File: builder/vsphere/clone/step_clone.go [hunk 3]
```diff
@@ -49,18 +52,28 @@ type StepCloneVM struct {
...
+		if _, ok := err.(*find.NotFoundError); !ok {
+			state.Put("error", fmt.Errorf("error looking up old vm: %v", err))
+			return multistep.ActionHalt
+		}
+	} else {
+		if s.Force {
+			ui.Say(fmt.Sprintf("the vm/template %s already exists, but deleting it due to -force flag", vmPath))
+
+			// power off just in case it is still on
+			vm.PowerOff()
```
Comment (nywilken) [inline builder/vsphere/clone/step_clone.go:68]: It looks `vm.PowerOff()` returns an error. Do we need to handle it?

File: builder/vsphere/clone/step_clone.go [hunk 4]
```diff
@@ -49,18 +52,28 @@ type StepCloneVM struct {
 func (s *StepCloneVM) Run(ctx context.Context, state multistep.StateBag) multistep.StepAction {
 	ui := state.Get("ui").(packer.Ui)
 	d := state.Get("driver").(*driver.Driver)
-	vmPath := fmt.Sprintf("%s/%s", s.Location.Folder, s.Location.VMName)
+	vmPath := path.Join(s.Location.Folder, s.Location.VMName)
```
Comment (nywilken) [inline builder/vsphere/clone/step_clone.go:55]: :100:

File: builder/vsphere/clone/step_clone.go (hunk 3 above)
Comment (jhawk28) [reply builder/vsphere/clone/step_clone.go:68]: we don't care about the  poweroff error, we only care about the destroy error.

File: builder/vsphere/clone/step_clone.go (hunk 1 above)
Comment (jhawk28) [reply builder/vsphere/clone/step_clone.go]: removed the nesting, but I used vm != nil since that is clearer as to why we are doing it instead of the err == nil.

File: builder/vsphere/clone/step_clone.go (hunk 4 above)
Comment (jhawk28) [reply builder/vsphere/clone/step_clone.go:53]: dedupe'd the code...

File: builder/vsphere/iso/step_create.go (hunk 2 above)
Comment (jhawk28) [reply builder/vsphere/iso/step_create.go:107]: dedupe'd the code...

**Comment by jhawk28** [comment]
the only functional difference in the dedupe is that the error for the destroy will now actually halt the process instead of just add an error to the state. I think this should be the correct behavior because if the vm isn't able to be destroyed, it will just error out later on the create.

**Comment by SwampDragons** [comment]
@jhawk28 you've been on fire 🔥 Thanks for all your recent contributions to this builder.

File: builder/vsphere/driver/vm.go [hunk 5]
```diff
@@ -98,6 +99,31 @@ func (d *Driver) FindVM(name string) (*VirtualMachine, error) {
...
+
+		// power off just in case it is still on
+		vm.PowerOff()
+
+		err := vm.Destroy()
+		if err != nil {
+			return fmt.Errorf("error destroying %s: %v", vmPath, err)
+		}
+	}
+	if force && vm != nil {
```
Comment (SwampDragons) [inline builder/vsphere/driver/vm.go:120]: Shouldn't this be !force?

**Comment by jhawk28** [comment]
> @jhawk28 you've been on fire 🔥 Thanks for all your recent contributions to this builder.

A big thanks to my company (Lockheed) for letting me work on it.

**Comment by SwampDragons** [comment]
This looks good. I'll spin up a cluster to run acceptance tests next week, and merge then.

**Comment by nywilken** [comment]
Hi @jhawk28 thanks again for the fix. I confirmed the fix is working as expected when the machine is powered on, suspended, and completely powered off. Nicely done :+1:
