### PR TITLE
hcl2_upgrade: special case: vsphere fix

### LINKED ISSUE #11167: Converting from json to HCL2 add "=" which packer cannot compile
Trying convert this to HCL2:

```json
{
    "variables": {
        "vsphere-server": "192.168.254.10",
        "vsphere-user": "XXXX@YYYY",
        "vsphere-password": "XXXX",
        "vsphere-datacenter": "local.aws",
        "vsphere-cluster": "local.aws",
        "vsphere-network": "pg-servers-102",
        "vsphere-datastore": "IAAS-DS-LUN01",
        "vm-name": "CentOS7-Template-packer-erez",
        "vm-cpu-num": "1",
        "vm-mem-size": "1024",
        "vm-disk-size": "25600",
        "ansible-version": "2.9.24",
        "ansible-branch": "release/k8s-v1.18.x"
    },
    "builders": [
        {
            "disable_shutdown": true,
            "type": "vsphere-clone",
            "vcenter_server": "{{user `vsphere-server`}}",
            "username": "{{user `vsphere-user`}}",
            "password": "{{user `vsphere-password`}}",
            "insecure_connection": "true",
            "datacenter": "{{user `vsphere-datacenter`}}",
            "cluster": "{{user `vsphere-cluster`}}",
            "network": "{{user `vsphere-network`}}",
            "datastore": "{{user `vsphere-datastore`}}",
            "vm_name": "{{user `vm-name`}}",
            "notes": "Build via Packer",
            "ssh_username": "root",
            "ssh_password": "Aa123456",
            "template": "erez's template",
            "CPUs": "{{user `vm-cpu-num`}}",
            "RAM": "{{user `vm-mem-size`}}",
            "RAM_reserve_all": false,
            "convert_to_template": false,
            "disk_controller_type": [
                "pvscsi",
                "pvscsi"
            ],
            "storage": [
                {
                    "disk_controller_index": 0,
                    "disk_size": 100000
                }
            ],
            "customize": {
                "linux_options": {
                    "host_name": "packer-test",
                    "domain": "test.internal"
                },
                "network_interface": {
                    "ipv4_address": "172.15.102.202",
                    "ipv4_netmask": "24"
                },
                "ipv4_gateway": "172.15.102.254",
                "dns_server_list": [
                    "192.168.254.1",
                    "192.168.254.2"
                ]
            }
        }
    ],
    "provisioners": [
        {
            "type": "shell",
            "inline": [
                "echo 'this section is for centOS 7 only'",
                "yum -y install epel-release",
                "curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py",
                "python get-pip.py --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org",
                "pip install ansible=={{user `ansible-version`}} docker docker-compose --ignore-installed --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org"
            ]
        },
        {
            "type": "ansible-local",
            "playbook_file": "playbooks/management.yml",
            "role_paths": [
                "./roles/management",
                "./roles/docker",
                "./roles/docker-compose",
                "./roles/nexus"
            ],
            "inventory_file": "environments/packer/packer.yaml"
        },
        {
            "type": "file",
            "source": "id_rsa",
            "destination": "~/.ssh/id_rsa"
        },
        {
            "type": "shell",
            "inline": [
                "git clone ssh://git@gitlab.e-bitbox.com:2222/elbitbox/ansible.git -b {{user `ansible-branch`}} --single-branch"
            ]
        }
    ]
}
```

  

this is the result:
```hcl
variable "ansible-branch" {
  type    = string
  default = "release/k8s-v1.18.x"
}

variable "ansible-version" {
  type    = string
  default = "2.9.24"
}

variable "vm-cpu-num" {
  type    = string
  default = "1"
}

variable "vm-disk-size" {
  type    = string
  default = "25600"
}

variable "vm-mem-size" {
  type    = string
  default = "1024"
}

variable "vm-name" {
  type    = string
  default = "CentOS7-Template-packer-erez"
}

variable "vsphere-cluster" {
  type    = string
  default = "local.aws"
}

variable "vsphere-datacenter" {
  type    = string
  default = "local.aws"
}

variable "vsphere-datastore" {
  type    = string
  default = "IAAS-DS-LUN01"
}

variable "vsphere-network" {
  type    = string
  default = "pg-servers-102"
}

variable "vsphere-password" {
  type    = string
  default = "Aa123456"
}

variable "vsphere-server" {
  type    = string
  default = "192.168.254.10"
}

variable "vsphere-user" {
  type    = string
  default = "e015524@iaas"
}


source "vsphere-clone" "autogenerated_1" {
  CPUs                = "${var.vm-cpu-num}"
  RAM                 = "${var.vm-mem-size}"
  RAM_reserve_all     = false
  cluster             = "${var.vsphere-cluster}"
  convert_to_template = false
  customize {
    dns_server_list = ["192.168.254.1", "192.168.254.2"]
    ipv4_gateway    = "172.15.102.254"
    linux_options = {
      domain    = "test.internal"
      host_name = "packer-test"
    }
    network_interface = {
      ipv4_address = "172.15.102.202"
      ipv4_netmask = "24"
    }
  }
  datacenter           = "${var.vsphere-datacenter}"
  datastore            = "${var.vsphere-datastore}"
  disable_shutdown     = true
  disk_controller_type = ["pvscsi", "pvscsi"]
  insecure_connection  = "true"
  network              = "${var.vsphere-network}"
  notes                = "Build via Packer"
  password             = "${var.vsphere-password}"
  ssh_password         = "Aa123456"
  ssh_username         = "root"
  storage {
    disk_controller_index = 0
    disk_size             = 100000
  }
  template       = "erez's template"
  username       = "${var.vsphere-user}"
  vcenter_server = "${var.vsphere-server}"
  vm_name        = "${var.vm-name}"
}


build {
  sources = ["source.vsphere-clone.autogenerated_1"]

  provisioner "shell" {
    inline = ["echo 'this section is for centOS 7 only'", "yum -y install epel-release", "curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py", "python get-pip.py --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org", "pip install ansible==${var.ansible-version} docker docker-compose --ignore-installed --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org"]
  }

  provisioner "ansible-local" {
    inventory_file = "environments/packer/packer.yaml"
    playbook_file  = "playbooks/management.yml"
    role_paths     = ["./roles/management", "./roles/docker", "./roles/docker-compose", "./roles/nexus"]
  }

  provisioner "file" {
    destination = "~/.ssh/id_rsa"
    source      = "id_rsa"
  }

  provisioner "shell" {
    inline = ["git clone ssh://git@gitlab.e-bitbox.com:2222/elbitbox/ansible.git -b ${var.ansible-branch} --single-branch"]
  }

}
```

Notice the = nearby the linux_options and the network_interface. Packer cannot compile this =.
Thanks

### PR DESCRIPTION
**Pull request by azr**
fix #11167

### CODE REVIEW

File: command/hcl2_upgrade.go [hunk 1]
```diff
@@ -562,6 +562,9 @@ func jsonBodyToHCL2Body(out *hclwrite.Body, kvs map[string]interface{}) {
 		case map[string]interface{}:
 			var mostComplexElem interface{}
 			for _, randomElem := range value {
+				if k == "linux_options" || k == "network_interface" {
+					break
+				}
```
Comment (azr) [inline command/hcl2_upgrade.go:567]: Because these only contained string values; hcl2_upgrade 'guessed' that this was a map[string]string instead of a block (without an equal sign).

This is quite a bad hack, but the only quick/simple way I can think of. A more complicated way would be to somehow fetch the underlying go-cty/hcl type from the configuration, and then generate HCL from that.

This would generate way more accurate HCL2, but would require a big refactor of `hcl2_upgrade`.

**Review by sylviamoss — APPROVED** [review]
Nice! 👍🏼
