### PR TITLE
Fix 8163

### LINKED ISSUE #8163: Race condition on spot request
#### Overview of the Issue

We use gitlab pipelines to build our system using AWS. Packer will create the main image and then deploy this at the last step. 

However, sometimes (most of the times actually), it fails with this error:

```
==> amazon-ebs: Error finding source instance.
==> amazon-ebs: Terminating the source AWS instance...
==> amazon-ebs: Error terminating instance, may still be around: UnauthorizedOperation: You are not authorized to perform this operation.
```

At firsts, it looks like an error with permissions, but when we look up the error in cloudtrail, it shows this:

```json
{
    "eventVersion": "1.05",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "<-redacted->",
        "arn": "arn:aws:iam::<-redacted->:user/vault-approle-<-redacted->",
        "accountId": "<-redacted->",
        "accessKeyId": "<-redacted->",
        "userName": "vault-approle-<-redacted->"
    },
    "eventTime": "2019-09-26T18:05:56Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "DescribeInstances",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "<-redacted->",
    "userAgent": "aws-sdk-go/1.22.2 (go1.12.8; linux; amd64)",
    "errorCode": "Client.InvalidInstanceID.NotFound",
    "errorMessage": "The instance ID 'i-<-redacted->' does not exist",
    "requestParameters": {
        "instancesSet": {
            "items": [
                {
                    "instanceId": "i-<-redacted->"
                }
            ]
        },
        "filterSet": {}
    },
    "responseElements": null,
    "requestID": "<-redacted->",
    "eventID": "<-redacted->",
    "eventType": "AwsApiCall",
    "recipientAccountId": "<-redacted->"
}
```

It is important to notice that if we look up that instance id in the console, it shows there. This lead us to think that it might be a race condition caused by the fact that the AWS EC2 API is [eventually consistent][1].

### Packer version

1.4.3

### Simplified Packer Buildfile

```json
{
  "variables": {
    "ami_name": "",
    "aws_region": "",
    "project_name": "",
    "security_group_id": "",
    "pkg_artifact": "",
    "subnet_id": "",
    "vpc_id": ""
  },
  "builders": [{
    "type": "amazon-ebs",
    "ami_block_device_mappings": [{
        "device_name": "/dev/sda1",
        "volume_size": 20,
        "volume_type": "gp2",
        "delete_on_termination": true
      },
      {
        "device_name": "/dev/sdf",
        "volume_size": 50,
        "volume_type": "gp2",
        "delete_on_termination": true
      }
    ],
    "ami_description": "Project: {{user `project_name`}}",
    "ami_name": "{{user `ami_name`}}",
    "force_deregister": true,
    "force_delete_snapshot": true,
    "instance_type": "t2.xlarge",
    "region": "{{user `aws_region`}}",
    "run_tags": {
      "Name": "{{user `project_name`}}-packer-builder"
    },
    "security_group_id": "{{user `security_group_id`}}",
    "shutdown_behavior": "terminate",
    "source_ami_filter": {
      "filters": {
        "virtualization-type": "hvm",
        "name": "ubuntu/images/*ubuntu-bionic-18.04-amd64-server-*",
        "root-device-type": "ebs"
      },
      "owners": [
        "<-redacted->"
      ],
      "most_recent": true
    },
    "ami_users": [
      "<-redacted->"
    ],
    "spot_price": "auto",
    "ssh_interface": "public_ip",
    "ssh_username": "ubuntu",
    "subnet_id": "{{user `subnet_id`}}",
    "tags": {
      "Name": "{{user `project_name`}}"
    },
    "vpc_id": "{{user `vpc_id`}}"
  }],
  "provisioners": []
}

```

### Operating system and Environment details

Ubuntu 18.04

[1]: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency

### PR DESCRIPTION
**Pull request by SwampDragons**
The describeInstances call can suffer from amazon's eventual-consistency, so let's do some retries. 

Also, we don't need to call it 3 times for spot instances. Remove extra, wasteful code. 

Closes #8163

### CODE REVIEW

File: builder/amazon/common/step_run_source_instance.go [hunk 1]
```diff
@@ -199,14 +199,34 @@ func (s *StepRunSourceInstance) Run(ctx context.Context, state multistep.StateBa
...
-	r, err := ec2conn.DescribeInstances(describeInstance)
-
+	// there's a race condition that can happen because of AWS's eventual
+	// consistency where even though the wait is complete, the describe call
+	// will fail. Retry a couple of times to try to mitigate that race.
+
+	var r *ec2.DescribeInstancesOutput
+	err = retry.Config{
+		Tries: 11,
+		ShouldRetry: func(error) bool {
```
Comment (azr) [inline builder/amazon/common/step_run_source_instance.go]: Watch out this will be another error

```suggestion
		ShouldRetry: func(err error) bool {
```

File: builder/amazon/common/step_run_spot_instance.go [hunk 2]
```diff
@@ -286,6 +286,32 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
...
+	// Set the instance ID so that the cleanup works properly
+	s.instanceId = instanceId
+
+	ui.Message(fmt.Sprintf("Instance ID: %s", instanceId))
+
+	// Get information about the created instance
+	var describeOutput *ec2.DescribeInstancesOutput
+	err = retry.Config{
+		Tries:       11,
+		ShouldRetry: func(error) bool { return true },
```
Comment (azr) [inline builder/amazon/common/step_run_spot_instance.go]: The Default behaviour is to always retry
```suggestion
```
