### PR TITLE
command/fmt: Ensure all variable files ending in `.pkrvars.hcl` get formatted

### LINKED ISSUE #10350: Unable to fmt .pkrvars.hcl extension
#### Overview of the Issue

It is not possible to format `*.pkrvars.hcl` variable file using `packer fmt` command. This should be possible using `fmt` command according to help:

```
Usage: packer fmt [options] [TEMPLATE]

  Rewrites all Packer configuration files to a canonical format. Both
  configuration files (.pkr.hcl) and variable files (.pkrvars) are updated.
  JSON files (.json) are not modified
```

1* `fmt` help documentation should rather include `*.pkrvars.hcl`, not just `*.pkrvars`.
2* formatting of variable files not working

#### Reproduction Steps
Error when formatting `*.pkrvars.hcl` extension:
```
packer fmt amazon2.pkrvars.hcl
Error: Cannot tell whether amazon2.pkrvars.hcl contains HCL2 configuration data
```

After renaming variable file to `*.pkr.hcl`, formatting works as expected:
```
mv amazon2.pkrvars.hcl amazon2.pkr.hcl
packer fmt amazon2.pkr.hcl 
echo $?
0
```

### Packer version
```
packer --version
1.6.6
```
### Simplified Packer Buildfile

```
cat amazon2.pkrvars.hcl 
ami_filter_name = "amzn2-ami-hvm-*-x86_64-gp2"
ami_filter_owners = [
  "137112412989"
]
```

### Operating system and Environment details

macOS Catalina 10.15.7

### Log Fragments and crash.log files

N/A

### PR DESCRIPTION
**Pull request by nywilken**
Before change
```
⇶  packer fmt -check /tmp/unformatted.pkrvars.hcl
Error: Cannot tell whether /tmp/unformatted.pkrvars.hcl contains HCL2 configuration data

⇶  echo $?
1
```

After fix
```
⇶  packer fmt -check /tmp/unformatted.pkrvars.hcl
/tmp/unformatted.pkrvars.hcl

⇶  echo $?
3

⇶  packer fmt -check command/test-fixtures/fmt
command/test-fixtures/fmt/unformatted.pkr.hcl
command/test-fixtures/fmt/unformatted.auto.pkrvars.hcl
command/test-fixtures/fmt/unformatted.pkrvars.hcl

```

Closes #10350

### CODE REVIEW

File: hcl2template/parser.go [hunk 1]
```diff
@@ -162,7 +164,7 @@ func (p *Parser) Parse(filename string, varFiles []string, argVars map[string]st
 
 	// parse var files
 	{
-		hclVarFiles, jsonVarFiles, moreDiags := GetHCL2Files(filename, hcl2VarFileExt, hcl2VarJsonFileExt)
+		hclVarFiles, jsonVarFiles, moreDiags := GetHCL2Files(filename, hcl2AutoVarFileExt, hcl2AutoVarJsonFileExt)
```
Comment (azr) [inline hcl2template/parser.go:167]: Oh, super good catch !

**Review by azr — APPROVED** [review]
Super good one, LGTM. I hadn't realised that we were reading all `.pkr.hcl` files from the same project folder ( unlike the docs stated ) that was def a bug. I hope the breaking change won't be too annoying.

File: command/fmt_test.go [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+	}
+
+	c.Ui = ui
+
+	args := []string{"-check=true", filepath.Join(testFixture("fmt"), "formatted.pkr.hcl")}
+	if code := c.Run(args); code != 0 {
+		fatalCommand(t, c.Meta)
+	}
+	expected := ""
+	assert.Equal(t, expected, strings.TrimSpace(s.String()))
```
Comment (azr) [inline command/fmt_test.go:28]: Totally for another PR but one nice thing we could have done is having a `input` file and an `expected` per folder, making the tests easy to read & add.

**Comment by nywilken** [comment]
> I hadn't realised that we were reading all `.pkr.hcl` files from the same project folder ( unlike the docs stated ) that was def a bug. I hope the breaking change won't be too annoying.

@azr is this in reference to the the `fmt` command or some other command? I'm not sure what the breaking change you are referring to is here.

**Review by sylviamoss — APPROVED** [review]
Nice! LGTM 👍🏼

File: hcl2template/parser.go (hunk 1 above)
Comment (azr) [reply hcl2template/parser.go:167]: @nywilken I was referring to this change here: before this the HCL2 parse would read all `.pkr.hcl` files in the folder, now it only reads `.auto.pkr.hcl` files ( which I think is a good way to go ).

Comment (azr) [reply hcl2template/parser.go:167]: So if anyone was mistakenly relying on this behaviour. Bang ! I say mistakenly because the docs says that only `.auto` files in the same folder will be auto parsed

Comment (nywilken) [reply hcl2template/parser.go:167]: Got it, thanks.  To confirm you mean `.auto.pkrvars.hcl` , right? If so then the behavior was correct to begin with. I just renamed the variable to so that I could use `hcl2VarFileExt` for the non-auto variable file extension :smile: I'm going to merge since this this is what we want. But do let me know if I misunderstood the case for `.pkr.hcl` files.

Comment (azr) [reply hcl2template/parser.go:167]: OOoohh right I misread the diff sorry ! Yup even better !
