### PR TITLE
aws: retry fetching blockdevicemapping if empty

### LINKED ISSUE #6420: amazon-ebsvolume: volume ID is not displayed
- Packer versions 1.1.0 and 1.2.4
- Linux
- [Logs](https://gist.github.com/kalrish/1b3cf428a7b4650ddf7d785024d687e4)
- [Template](https://github.com/kalrish/aws-vibes/blob/master/ec2/template-ebs-builds.json)

As can be seen, the volume ID is displayed neither by Packer itself nor by the `manifest` post-processor, so the issue might be in the builder.

May be related to #5486.

The strange thing is that this doesn't happen with [this other template](https://github.com/kalrish/aws-vibes/blob/master/ec2/template-ebs-sources.json), whose only differences are:

 -  the EBS volume is quite smaller; and
 -  provisioning takes longer.

### LINKED ISSUE #9476: amazon ebs surrogate: packer may not find any blockdevicemapping
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When using the amazon ebs surrogate builder with spot instances, some builds may fail due to an empty blockdevicemapping.

#### Reproduction Steps

Build an image with ebs-surrogate + spot instances + attach extra volume (did not try to reproduce on other combinations)

Here is the error when building:
```
==> amazon-ebssurrogate: 1 error occurred:
==> amazon-ebssurrogate: 	* Volume ID for device /dev/xvdf not found
```

Provisioners used do not matter.

### Packer version

1.6.0

### Simplified Packer Buildfile

Here is a minimal example that may fail (about 1/5 times):

<details>
```json
{
  "builders": [
    {
      "ami_name": "{{uuid}}",
      "ami_root_device": {
        "delete_on_termination": true,
        "device_name": "/dev/xvda",
        "source_device_name": "/dev/xvdf",
        "volume_size": 8,
        "volume_type": "gp2"
      },
      "ami_virtualization_type": "hvm",
      "ena_support": true,
      "launch_block_device_mappings": [
        {
          "delete_on_termination": true,
          "device_name": "/dev/xvdf",
          "volume_size": 8,
          "volume_type": "gp2"
        }
      ],
      "region": "us-west-2",
      "source_ami_filter": {
        "filters": {
          "architecture": "x86_64",
          "block-device-mapping.volume-type": "gp2",
          "name": "*amzn2-ami-hvm-*-x86_64-gp2",
          "root-device-type": "ebs",
          "virtualization-type": "hvm"
        },
        "most_recent": true,
        "owners": [
          "amazon"
        ]
      },
      "spot_instance_types": [
        "c5.large",
        "c5.xlarge",
        "c5.2xlarge"
      ],
      "spot_price": "auto",
      "sriov_support": true,
      "ssh_interface": "public_ip",
      "ssh_username": "ec2-user",
      "type": "amazon-ebssurrogate"
    }
  ],
  "min_packer_version": "1.6.0"
}
```
</details>

### Operating system and Environment details

I've reproduced this on a debian buster and a ubuntu 20.04 builder.

### Log Fragments and crash.log files

I've manually added the following patch:
```
diff --git i/builder/amazon/common/step_run_spot_instance.go w/builder/amazon/common/step_run_spot_instance.go
index 0f9e65aaf..d235ff396 100644
--- i/builder/amazon/common/step_run_spot_instance.go
+++ w/builder/amazon/common/step_run_spot_instance.go
@@ -394,11 +394,15 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
        }

        volumeIds := make([]*string, 0)
+       ui.Say(fmt.Sprintf("Public IP address: %s", *instance.PublicIpAddress))
+       ui.Say("BlockDeviceMappings")
        for _, v := range instance.BlockDeviceMappings {
+               ui.Say(*v.DeviceName)
                if ebs := v.Ebs; ebs != nil {
                        volumeIds = append(volumeIds, ebs.VolumeId)
                }
        }
+       ui.Say("End BlockDeviceMappings")

        if len(volumeIds) > 0 && len(s.VolumeTags) > 0 {
                ui.Say("Adding tags to source EBS Volumes")

```

The relevant logs give:
```
2020/06/24 11:47:49 ui: [1;32m==> amazon-ebssurrogate: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...[0m
2020/06/24 11:47:50 ui: [1;32m==> amazon-ebssurrogate: Launching a spot AWS instance...[0m
2020/06/24 11:47:50 ui: [1;32m==> amazon-ebssurrogate: Interpolating tags for spot instance...[0m
2020/06/24 11:47:50 ui: [0;32m    amazon-ebssurrogate: Adding tag: "Name": "Packer Builder"[0m
2020/06/24 11:47:50 ui: [0;32m    amazon-ebssurrogate: Loading User Data File...[0m
2020/06/24 11:47:50 ui: [0;32m    amazon-ebssurrogate: Creating Spot Fleet launch template...[0m
2020/06/24 11:47:51 ui: [0;32m    amazon-ebssurrogate: Sending spot request ()...[0m
2020/06/24 11:47:53 ui: [0;32m    amazon-ebssurrogate: Instance ID: i-aaaaaaaaaaa[0m
2020/06/24 11:47:55 ui: [1;32m==> amazon-ebssurrogate: Public IP address: xx.xx.xx.xx[0m
2020/06/24 11:47:55 ui: [1;32m==> amazon-ebssurrogate: BlockDeviceMappings[0m
2020/06/24 11:47:55 ui: [1;32m==> amazon-ebssurrogate: End BlockDeviceMappings[0m
```

After the spot instance is spawned, I manually queried the EC2 API and the mapping is present:

```
                    "BlockDeviceMappings": [
                        {
                            "DeviceName": "/dev/xvda",
                            "Ebs": {
                                "AttachTime": "2020-06-24T09:47:54.000Z",
                                "DeleteOnTermination": true,
                                "Status": "attached",
                                "VolumeId": "vol-000"
                            }
                        },
                        {
                            "DeviceName": "/dev/xvdf",
                            "Ebs": {
                                "AttachTime": "2020-06-24T09:47:54.000Z",
                                "DeleteOnTermination": true,
                                "Status": "attached",
                                "VolumeId": "vol-000"
                            }
                        }
                    ],
```

I suspect a race condition, due to the describeinstances call being right after the createfleetrequest call:

https://github.com/hashicorp/packer/blob/2b3935778e5a6e90088317a02a18f9a4e7723e93/builder/amazon/common/step_run_spot_instance.go#L280-L336

We could retry the request if the blockdevicemapping is empty.

Thanks!

### PR DESCRIPTION
**Pull request by adongy**
Closes #9476 
Closes #6420 

The PR does not include tests as I did not find any mocking utilities for the run_spot_instance step.

I have manually confirmed this seems to solve my issue (it retries a few seconds later and finds the mapping correctly).

### CODE REVIEW

File: builder/amazon/common/step_run_spot_instance.go [hunk 1]
```diff
@@ -324,6 +324,9 @@ func (s *StepRunSpotInstance) Run(ctx context.Context, state multistep.StateBag)
 		describeOutput, err = ec2conn.DescribeInstances(&ec2.DescribeInstancesInput{
 			InstanceIds: []*string{aws.String(instanceId)},
 		})
+		if len(describeOutput.Reservations) > 0 && len(describeOutput.Reservations[0].Instances) > 0 && len(describeOutput.Reservations[0].Instances[0].BlockDeviceMappings) == 0 {
```
Comment (sylviamoss) [inline builder/amazon/common/step_run_spot_instance.go:327]: Is it possible a case where not having `BlockDeviceMappings` is valid?

Comment (adongy) [reply builder/amazon/common/step_run_spot_instance.go:327]: Most of our builders use EBS volumes, which must make the root volume appear in the BlockDeviceMappings.

The only one I'm not sure is the instance one, as I've never actually used it.

Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:327]: I notice the rest of the code behaves like it is possible to have no BlockDeviceMappings and researched a bit to understand better how it works for `instance`. It turns out that for this one it is indeed possible to not have BlockDeviceMappings, this way this needs to be workout because it can't return an error at the end. 

I was thinking you can control the retry for this case to make sure that, for example, if it retries N times and still there are no BlockDeviceMappings, then don't return the error and let the rest of the code deal with it.

Comment (sylviamoss) [reply builder/amazon/common/step_run_spot_instance.go:327]: You can change the if condition to include `s.LaunchMappings != nil` because this will ensure that some BlockDeviceMappings is expected here. What do you think?

**Comment by sylviamoss** [comment]
Hello there! Just wanted to ping. Are you planning to keep working on this?

**Comment by SwampDragons** [comment]
I just did a couple of tests, and the instance builder _does not_ have block device mappings in the launched instance. I'm going to push up a small tweak to this PR that checks against the length of the mappings created by LaunchMappings so we can get it merged.

**Comment by adongy** [comment]
Hi! Sorry for the delay, as I did not have time to loop back to this PR. Thanks @SwampDragons and @sylviamoss for the fixes!
