### PR TITLE
hcl2_upgrade: allow to hcl2_upgrade with unknown builders, just log it

### LINKED ISSUE #11028: Working JSON breaks HCL2 upgrade - unknown builder type & builder missing ‘type’
#### Overview of the Issue

Originally described in the community forum post [Working JSON breaks HCL2 upgrade - unknown builder type & builder missing ‘type’](https://discuss.hashicorp.com/t/working-json-breaks-hcl2-upgrade-unknown-builder-type-builder-missing-type/24398):

With the release of 1.7.0 we took took a first run at converting our JSON definitions, unfortunately we made no progress and reported our problem in [Working JSON breaks after HCL2 upgrade - Error: Variables not allowed](https://discuss.hashicorp.com/t/working-json-breaks-after-hcl2-upgrade-error-variables-not-allowed/21220).

It looked like the issue was fixed in 1.7.1 and now that 1.7.2 is out we’ve tried taking another run. This time it seems we’ve hit an issue of trying to migrate JSON to HCL2 and move from Packer version < 1.7.0 to Packer 1.7.2

#### Reproduction Steps

Steps to reproduce this issue

Download gist [packer-issue-11028.pkr.json](https://gist.github.com/bbros-dev/bef4b61ffe0861c01915fb05e1c431a3#file-packer-issue-11028-pkr-json)
```
$ packer hcl2_upgrade packer-issue-11028.json 
unknown builder type: "upcloud"
```

### Packer version

From `packer version`

### Simplified Packer Buildfile

Gist:

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

```
$ uname -a
Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
### Log Fragments and crash.log files

```
$ packer hcl2_upgrade packer-issue-11028.json 
unknown builder type: "upcloud"
```

### PR DESCRIPTION
**Pull request by azr**
Closes #11028

### CODE REVIEW

File: command/hcl2_upgrade.go [hunk 1]
```diff
@@ -153,7 +153,7 @@ func (c *HCL2UpgradeCommand) RunContext(_ context.Context, cla *HCL2UpgradeArgs)
 
 	hdl, ret := c.GetConfigFromJSON(&cla.MetaArgs)
 	if ret != 0 {
-		return ret
+		c.Ui.Error(fmt.Sprintf("GetConfigFromJSON error"))
```
Comment (sylviamoss) [inline command/hcl2_upgrade.go:156]: This looks more like an internal error. I would change the text to be more friendly
```suggestion
		c.Ui.Error(fmt.Sprintf("Failed to get config from JSON"))
```

File: command/hcl2_upgrade.go [hunk 2]
```diff
@@ -255,8 +255,8 @@ func (c *HCL2UpgradeCommand) RunContext(_ context.Context, cla *HCL2UpgradeArgs)
 		return 1
 	}
 
-	c.Ui.Say(fmt.Sprintf("Successfully created %s ", cla.OutputFile))
-	return 0
+	c.Ui.Say(fmt.Sprintf("Successfully created %s. Exit %d", cla.OutputFile, ret))
```
Comment (sylviamoss) [inline command/hcl2_upgrade.go:258]: Will it be successful even with `ret=1`?

Comment (sylviamoss) [reply command/hcl2_upgrade.go:258]: I'm guessing it will partially write the output file, right?

File: command/test-fixtures/hcl2_upgrade/unknown_builder/expected.pkr.hcl [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+variable "aws_region" {
+  type = string
+}
+
+variable "aws_secret_key" {
+  type    = string
+  default = ""
+}
+
+source "potatoes" "autogenerated_1" {
```
Comment (sylviamoss) [inline command/test-fixtures/hcl2_upgrade/unknown_builder/expected.pkr.hcl:19]: I want this builder now! If it's building potatoes 🥔

File: command/hcl2_upgrade.go (hunk 2 above)
Comment (sylviamoss) [reply command/hcl2_upgrade.go:258]: Just saw the test and I got my question answered there :D

**Review by sylviamoss — APPROVED** [review]
LGTM! 👍🏼  
Only suggested a change in one of the error logs.

**Review by nywilken — APPROVED** [review]
Nice 👍. This looks good to me. 

Should we add a similar warning message for unknown provisioners or post-processors?

**Review by SwampDragons — APPROVED** [review]

File: command/hcl2_upgrade.go (hunk 1 above)
Comment (bbros-dev) [reply command/hcl2_upgrade.go:156]: Failures sound fatal.  Why not describe what is happening:

` Builder <X> not recognized. Format upgrade continuing.`

Comment (sylviamoss) [reply command/hcl2_upgrade.go:156]: I like the suggestion ☝🏼

Comment (bbros-dev) [reply command/hcl2_upgrade.go:156]: Great - Even topped-up on caffeine I wouldn't have reacted well to that error msg ;)

File: command/test-fixtures/hcl2_upgrade/unknown_builder/expected.pkr.hcl (hunk 3 above)
Comment (azr) [reply command/test-fixtures/hcl2_upgrade/unknown_builder/expected.pkr.hcl:19]: Hahaha ! 🥔🥔🥔🥔🥔

File: command/hcl2_upgrade.go (hunk 1 above)
Comment (azr) [reply command/hcl2_upgrade.go:156]: `GetConfigFromJSON` will actually tell more on error, ex:

https://github.com/hashicorp/packer/blob/00e503388eb3fec2d1504bb9f82bf2ee189073ff/command/build.go#L128-L135
