### PR TITLE
builder/azure-arm: Remove duplicate resource deletion steps

### LINKED ISSUE #9482: ResourceGroupNotFound Resource group pkr-Resource-Group- could not be found
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue

When the cleanup of resources groups are attempted, the following error appears:

`ResourceGroupNotFound : Resource group 'pkr-Resource-Group-<RANDOM>' could not be found`

This error occurs when using the `azure-arm` builder, with multiple base images (ubuntu, rhel, win2012, win2016, win2019).

#### Reproduction Steps

1. Download Packer config: [ubuntu.json](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/ubuntu.json)
1. Run [test_packer_cleanup.sh](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/test_packer_cleanup.sh)

### Packer version

`v1.6.0`

### Simplified Packer Buildfile

Packer config: [ubuntu.json](https://github.com/adamrushuk/Packer-Templates/blob/master/azure-test/ubuntu.json)

### Operating system and Environment details

`Ubuntu 18.04.4 LTS`

### Log Fragments and crash.log files

See [Packer Log gist](https://gist.github.com/adamrushuk/ce679fe475dce12327b9f43591e48d28)

### PR DESCRIPTION
**Pull request by nywilken**
This change removes StepDeleteResourceGroup from the ARM builder. The StepDeleteResourceGroup step was a combination of StepCreateResourceGroup#Cleanup and StepDeployTemplate#Cleanup. Which was causing soft errors on cleanup because the Azure builder was trying to access resources in the step cleanup functions that were deleted by StepDeleteResourceGroup. 

This change also removes the StepDeleteOSDisk and modifies the StepDeleteAdditionalDisk steps as they were found to be only working when the StepDeleteResourceGroup was being executed. More specifically, the DeleteResourceGroup step was deleting all deployment operations including the resource group associated with the build so the additional delete steps were essentially a noop. After removing the call to the DeleteResourceGroup step the following error was being thrown

```
Build 'azure-arm' errored: storage: service returned error: StatusCode=412, ErrorCode=LeaseIdMissing, ErrorMessage=There is currently a lease on the blob and no lease ID was specified in the request.                                                                                               
RequestId:05c17014-101e-0027-7218-704428000000
Time:2020-08-11T19:46:04.6437683Z, RequestInitiated=Tue, 11 Aug 2020 19:46:04 GMT, RequestId=05c17014-101e-0027-7218-704428000000, API Version=2018-03-28, QueryParameterName=, QueryParameterValue=                                                                                                  
``` 

#Closes #9482

#### Build Results Before Change
<details>
<summary>VHD basic build</summary>

```
==> azure-arm: The resource group was created by Packer, deleting ...
==> azure-arm: Deleting the temporary OS disk ...
==> azure-arm:  -> OS Disk : skipping, managed disk was used...
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> Additional Disk : skipping, managed disk was used...
==> azure-arm: Removing the created Deployment object: 'pkrdpxze28l7mdu'
==> azure-arm: ERROR: -> ResourceGroupNotFound : Resource group 'pkr-Resource-Group-xze28l7mdu' could not be found.
==> azure-arm:
==> azure-arm: Removing the created Deployment object: 'kvpkrdpxze28l7mdu'
==> azure-arm: ERROR: -> ResourceGroupNotFound : Resource group 'pkr-Resource-Group-xze28l7mdu' could not be found.
==> azure-arm:
Build 'azure-arm' finished.
```

</details>

#### Build results after change

<details>
<summary>Regression suite run, after change</summary>

```
RUNNING: /home/wilken/Development/regression-suite/regressions/output/c6a9ea41-4c7a-4cd2-a182-2dc716cef101/azure-test-1.json                      
checking logfile /home/wilken/Development/regression-suite/regressions/output/c6a9ea41-4c7a-4cd2-a182-2dc716cef101/packer_log_azure-test-1.txt    
searching for Welcome to PACKER
PASS: Found stdout "Welcome to PACKER" in logfile
searching for HELLO NEW USER; automatically generated aws password is:
PASS: Found stdout "HELLO NEW USER; automatically generated aws password is:" in logfile                                                          
searching for linuxBashScript
PASS: Found stdout "linuxBashScript" in logfile
searching for linuxBashInline
PASS: Found stdout "linuxBashInline" in logfile
searching for What is your name?
PASS: Found stdout "What is your name?" in logfile
searching for ['packer custom restart']
PASS: Found stdout "packer custom restart" in logfile
searching for ['""', 'whee']
PASS: Found stdout """" in logfile
PASS: Found stdout "whee" in logfile
searching for UnixBashScript
PASS: Found stdout "UnixBashScript" in logfile
```
</details>

<details>
<summary>Custom Key Vault Test</summary>

```
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...                                                    
==> azure-arm:  -> Deployment Resources within: pkrdp0dhkz0nm7c
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvm0dhkz0nm7c'
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrni0dhkz0nm7c'                                                                        
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkrip0dhkz0nm7c'                                                                        
==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvn0dhkz0nm7c'
==> azure-arm:  -> image : 'https://wilkentestpkr.blob.core.windows.net/images/pkros0dhkz0nm7c.vhd'                                               
==> azure-arm: Removing the created Deployment object: 'pkrdp0dhkz0nm7c'
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, not deleting ...                                                                     
Build 'azure-arm' finished.

==> Builds finished. The artifacts of successful builds are:
--> azure-arm: Azure.ResourceManagement.VMImage:
```
</details>

<details>
<summary>Additional Disk Test</summary>

```
==> azure-arm: Deleting the temporary Additional disk ...                                                                                          
==> azure-arm:  -> Additional Disk 1: 'https://wilkentestpkr.blob.core.windows.net/images/pkrdd0yxg9kkpm3-1.vhd'                                   
==> azure-arm:  -> Additional Disk 2: 'https://wilkentestpkr.blob.core.windows.net/images/pkrdd0yxg9kkpm3-2.vhd'                                   
==> azure-arm:                                                                                                                                     
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...                                                     
==> azure-arm:  -> Deployment Resources within: pkrdp0yxg9kkpm3                                                                                    
==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvm0yxg9kkpm3'                                                                           
==> azure-arm:  -> Microsoft.Network/networkInterfaces : 'pkrni0yxg9kkpm3'                                                                         
==> azure-arm:  -> Microsoft.Network/publicIPAddresses : 'pkrip0yxg9kkpm3'                                                                         
==> azure-arm:  -> Microsoft.Network/virtualNetworks : 'pkrvn0yxg9kkpm3'                                                                           
==> azure-arm:  -> image : 'https://wilkentestpkr.blob.core.windows.net/images/pkros0yxg9kkpm3.vhd'                                                
==> azure-arm: Removing the created Deployment object: 'pkrdp0yxg9kkpm3'                                                                           
==> azure-arm: 
==> azure-arm: The resource group was not created by Packer, deleting individual resources ...                                                    
==> azure-arm:  -> Deployment Resources within: kvpkrdp0yxg9kkpm3
==> azure-arm:  -> Microsoft.KeyVault/vaults/secrets : 'pkrkv0yxg9kkpm3/packerKeyVaultSecret'                                                     
==> azure-arm:  -> Microsoft.KeyVault/vaults : 'pkrkv0yxg9kkpm3'
==> azure-arm: Removing the created Deployment object: kvpkrdp0yxg9kkpm3'
```
</details>

<details>
<summary>Manged Disk Build</sumary>

```
==> azure-arm: Deleting the temporary Additional disk ...
==> azure-arm:  -> Additional Disk : skipping, managed disk was used...
==> azure-arm: Removing the created Deployment object: 'pkrdpq0qhdjt7e7'
==> azure-arm: Removing the created Deployment object: 'kvpkrdpq0qhdjt7e7'                                                                        
==> azure-arm: 
==> azure-arm: Cleanup requested, deleting resource group ...
==> azure-arm: Resource group has been deleted.
Build 'azure-arm' finished.
```
</details>

### Todos
- [x] Check that the reordering doesn't break the builder
- [x] Validate that all resources are properly deleted upon a successful build
- [x] Validate that build cancellations cleanup as expected
- [x] Move all deletion code into the actual cleanup method; refactoring out any unnecessary code.

### CODE REVIEW

File: builder/azure/arm/step_create_resource_group.go [hunk 1]
```diff
@@ -111,27 +111,30 @@ func (s *StepCreateResourceGroup) Cleanup(state multistep.StateBag) {
 	if state.Get(constants.ArmIsExistingResourceGroup).(bool) {
 		ui.Say("\nThe resource group was not created by Packer, not deleting ...")
 		return
-	} else {
-		ui.Say("\nCleanup requested, deleting resource group ...")
+	}
```
Comment (SwampDragons) [inline builder/azure/arm/step_create_resource_group.go:114]: Nice cleanup.

File: builder/azure/arm/step_delete_additional_disks.go [hunk 2]
```diff
@@ -35,8 +35,13 @@ func NewStepDeleteAdditionalDisks(client *AzureClient, ui packer.Ui) *StepDelete
 
 func (s *StepDeleteAdditionalDisk) deleteBlob(storageContainerName string, blobName string) error {
 	blob := s.client.BlobStorageClient.GetContainerReference(storageContainerName).GetBlobReference(blobName)
-	err := blob.Delete(nil)
+	_, err := blob.BreakLease(nil)
```
Comment (SwampDragons) [inline builder/azure/arm/step_delete_additional_disks.go:38]: Nice!

File: builder/azure/arm/step_deploy_template.go [hunk 3]
```diff
@@ -171,75 +259,11 @@ func (s *StepDeployTemplate) deleteImage(ctx context.Context, imageType string,
...
-		// deleted separately
-		ui.Say(fmt.Sprintf(" -> %s : '%s'", imageType, imageName))
-		err = s.deleteDisk(context.TODO(), imageType, imageName, resourceGroupName)
-		if err != nil {
-			ui.Error(fmt.Sprintf("Error deleting resource.  Please delete manually.\n\n"+
-				"Name: %s\n"+
-				"Error: %s", imageName, err))
-		}
-	}
+	return blob.Delete(nil)
```
Comment (SwampDragons) [inline builder/azure/arm/step_deploy_template.go:268]: Well this is simplified!
