### PR TITLE
provisioner/ansible: Quote extra-var packer_build_name to handle names with spaces

### LINKED ISSUE #9581: packer_build_name does not handle spaces
#### Overview of the Issue

If builder name contains spaces, packer_build_name does not handle this

#### Reproduction Steps

```
    "builders": [
        {
            "name": "Windows Server 2016 Core Containers",
...
```
```
==> Windows Server 2016 Core Containers: Executing Ansible: ansible-playbook -e packer_build_name=Windows Server 2016 Core Containers -e packer_builder_type=amazon-ebs -e ansible_password=***** -i /tmp/packer-provisioner-ansible840527656 ./main.yml -e ansible_connection=winrm -e ansible_winrm_transport=ntlm
```
```
Windows Server 2016 Core Containers: TASK [debug] *******************************************************************
Windows Server 2016 Core Containers: ok: [default] => {
Windows Server 2016 Core Containers:     "packer_build_name": "Windows"
Windows Server 2016 Core Containers: }
```
### Packer version

`1.5.6`

### PR DESCRIPTION
**Pull request by SwampDragons**
Quote it. 

Closes #9581

### CODE REVIEW

File: provisioner/ansible/provisioner_test.go [hunk 1]
```diff
@@ -509,7 +509,7 @@ func TestCreateCmdArgs(t *testing.T) {
 			ExtraArguments:  []string{"-e", "hello-world"},
 			AnsibleEnvVars:  []string{"ENV_1=pancakes", "ENV_2=bananas"},
 			callArgs:        []string{common.HttpAddrNotImplemented, "/var/inventory", "test-playbook.yml", "/path/to/privkey.pem"},
-			ExpectedArgs:    []string{"-e", "packer_build_name=packerparty", "-e", "packer_builder_type=fakebuilder", "-e", "ansible_ssh_private_key_file=/path/to/privkey.pem", "--ssh-extra-args", "'-o IdentitiesOnly=yes'", "-e", "hello-world", "-i", "/var/inventory", "test-playbook.yml"},
+			ExpectedArgs:    []string{"-e", "packer_build_name=\"packerparty\"", "-e", "packer_builder_type=fakebuilder", "-e", "ansible_ssh_private_key_file=/path/to/privkey.pem", "--ssh-extra-args", "'-o IdentitiesOnly=yes'", "-e", "hello-world", "-i", "/var/inventory", "test-playbook.yml"},
```
Comment (azr) [inline provisioner/ansible/provisioner_test.go:512]: here we could have used a backquote (`) to not have to escape the quote ("), I think this is good to go anyways.
