### PR TITLE
provisioner/shell: Fix envVarFile clean up issue

### LINKED ISSUE #8627: provisioner .EnvVarFile breaks with array of scripts
#### Overview of the Issue

I have a `template.json` which in some provisioner steps, specifies an `execute_command` with `{{.EnvVarFile}}` together with setting `use_env_var_file` true; when the `scripts` item is an array of scripts, then the **second** script fails with being unable to source the varfile.

This worked when I last touched this when @SwampDragons added support after Packer 1.2.5 with PR https://github.com/hashicorp/packer/pull/6636 to solve https://github.com/hashicorp/packer/issues/6522 but I just tried using Packer again for the first time in a while, v1.5.1, and it's broken.

`PACKER_LOG=1` output confirms: the same value of `{{.EnvVarFile}}` is passed to each script but the file on disk is deleted after the first script.

#### Reproduction Steps

`template.json` containing:

```
  "provisioners": [
    {
      "execute_command": "chmod +x {{ .Path }}; sudo -E sh -c '. {{.EnvVarFile}} && {{ .Path }}'",
      "expect_disconnect": true,
      "scripts": [
        "scripts/00_pre_update",
        "scripts/01_system_update"
      ],
      "use_env_var_file": true,
      "type": "shell"
    },
[...]
```

Running packer:

```
==> amazon-ebs: Connected to SSH!
==> amazon-ebs: Provisioning with shell script: scripts/00_pre_update
    amazon-ebs: Waiting for cloud-init ... [0]
    amazon-ebs: Waiting for cloud-init ... [1]
    amazon-ebs: Waiting for cloud-init ... [2]
    amazon-ebs: Waiting for cloud-init ... [3]
    amazon-ebs: Waiting for cloud-init ... [4]
    amazon-ebs: Waiting for cloud-init ... [5]
    amazon-ebs: Mon Jan 20 21:33:56 UTC 2020
==> amazon-ebs: Provisioning with shell script: scripts/01_system_update
==> amazon-ebs: sh: 1: .: Can't open /tmp/varfile_3996.sh
==> amazon-ebs: Provisioning step had errors: Running the cleanup provisioner, if present...
```

So whatever value `{{.EnvVarFile}}` had for the first invocation was correct at the time of executing the first invocation.  By the time the second script was run, whatever value was supplied to that second invocation was wrong.

### Packer version

`Packer v1.5.1`

### Simplified Packer Buildfile

The relevant sample is above in the reproduction step.  `packer-ebs` builder.

### Operating system and Environment details

Machine invoking Packer:  Ubuntu Eoan (19.10) on amd64.
Remote machine: Ubuntu Bionic LTS (filter match for `ubuntu/images/*/ubuntu-bionic-18.04-amd64-server-*`)

### Log Fragments and crash.log files

Short log: above in reproduction steps.

Running with PACKER_LOG=1, we see that indeed the varfile is being deleted after the first script, then passed to the second script unchanged.

<details>
<summary>PACKER_LOG=1 output showing too-early deletion of variables temp file</summary>

```
2020/01/20 17:03:27 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:27 packer_1.5.1 plugin: [DEBUG] starting remote command: chmod +x /tmp/script_5546.sh; sudo -E sh -c '. /tmp/varfile_9722.sh && /tmp/script_5546.sh'
    amazon-ebs: Waiting for cloud-init ... [0]
    amazon-ebs: Waiting for cloud-init ... [1]
    amazon-ebs: Waiting for cloud-init ... [2]
    amazon-ebs: Waiting for cloud-init ... [3]
    amazon-ebs: Waiting for cloud-init ... [4]
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] 184 bytes written for 'stdout'
    amazon-ebs: Mon Jan 20 22:03:32 UTC 2020
2020/01/20 17:03:32 [INFO] 0 bytes written for 'stderr'
2020/01/20 17:03:32 [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] 184 bytes written for 'stdout'
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] 0 bytes written for 'stderr'
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] starting remote command: rm -f /tmp/script_5546.sh
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] starting remote command: rm -f /tmp/varfile_9722.sh
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC client: Communicator ended with: 0
==> amazon-ebs: Provisioning with shell script: scripts/01_system_update
2020/01/20 17:03:32 packer_1.5.1 plugin: Opening scripts/01_system_update for reading
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] 5037 bytes written for 'uploadData'
2020/01/20 17:03:32 [INFO] 5037 bytes written for 'uploadData'
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Starting remote scp process:  scp -vt /tmp
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Started SCP session, beginning transfers...
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Copying input data into temporary file so we can read the length
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] scp: Uploading script_5546.sh: perms=C0644 size=5037
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] SCP session complete, closing stdin pipe.
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Waiting for SSH session to complete.
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] scp stderr (length 32): Sink: C0644 5037 script_5546.sh
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] starting remote command: chmod 0755 /tmp/script_5546.sh
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 [INFO] RPC endpoint: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC client: Communicator ended with: 0
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] Opening new ssh session
2020/01/20 17:03:32 packer_1.5.1 plugin: [DEBUG] starting remote command: chmod +x /tmp/script_5546.sh; sudo -E sh -c '. /tmp/varfile_9722.sh && /tmp/script_5546.sh'
2020/01/20 17:03:32 packer_1.5.1 plugin: [ERROR] Remote command exited with '2': chmod +x /tmp/script_5546.sh; sudo -E sh -c '. /tmp/varfile_9722.sh && /tmp/script_5546.sh'
2020/01/20 17:03:32 packer_1.5.1 plugin: [INFO] RPC endpoint: Communicator ended with: 2
2020/01/20 17:03:32 [INFO] 0 bytes written for 'stdout'
2020/01/20 17:03:32 [INFO] 42 bytes written for 'stderr'
==> amazon-ebs: sh: 1: .: Can't open /tmp/varfile_9722.sh
2020/01/20 17:03:32 [INFO] RPC client: Communicator ended with: 2
2020/01/20 17:03:32 [INFO] RPC endpoint: Communicator ended with: 2
```
</details>

### PR DESCRIPTION
**Pull request by nywilken**
This change ensures the deletion of the external envVarFile (use_env_var_file = true) occurs after all script files have been executed and deleted.

Closes #8627

<details>
<summary>Build results before change</summary>

```
> packer build build.pkr.hcl                                                                                                                                                             [~0]
docker: output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu:bionic
    docker: bionic: Pulling from library/ubuntu
    docker: Digest: sha256:8d31dad0c58f552e890d68bbfb735588b6b820a46e459672d96e585871acc110
    docker: Status: Image is up to date for ubuntu:bionic
    docker: docker.io/library/ubuntu:bionic
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/wilken/.packer.d/tmp476880774:/packer-files -d -i -t --entrypoint=/bin/sh -- ubuntu:bionic
    docker: Container ID: 812069b4d70746a6d4592a8f75c06867c6774b8b0bd81ade76eae7926a30f64b
==> docker: Using docker communicator to connect: 172.17.0.2
==> docker: Provisioning with shell script: sample.sh
    docker: Sample Script
    docker: wilken is NotForSale!
==> docker: Provisioning with shell script: foobar.sh
==> docker: /bin/sh: 1: .: Can't open /tmp/varfile_2555.sh
==> docker: Provisioning step had errors: Running the cleanup provisioner, if present...
==> docker: Killing the container: 812069b4d70746a6d4592a8f75c06867c6774b8b0bd81ade76eae7926a30f64b
Build 'docker' errored: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]

==> Some builds didn't complete successfully and had errors:
--> docker: Script exited with non-zero exit status: 2.Allowed exit codes are: [0]

==> Builds finished but no artifacts were created.
```
</details>

<details>
<summary>Build results after change</summary>
```
> packer build build.pkr.hcl
docker: output will be in this color.

==> docker: Creating a temporary directory for sharing data...
==> docker: Pulling Docker image: ubuntu:bionic
    docker: bionic: Pulling from library/ubuntu
    docker: Digest: sha256:8d31dad0c58f552e890d68bbfb735588b6b820a46e459672d96e585871acc110
    docker: Status: Image is up to date for ubuntu:bionic
    docker: docker.io/library/ubuntu:bionic
==> docker: Starting docker container...
    docker: Run command: docker run -v /home/wilken/.packer.d/tmp819845000:/packer-files -d -i -t --entrypoint=/bin/sh -- ubuntu:bionic
    docker: Container ID: d8ed9100ff5017379bfc0d80703b2b2d10c4104941663aa5ddbbf18f6dcf74a5
==> docker: Using docker communicator to connect: 172.17.0.2
==> docker: Provisioning with shell script: sample.sh
    docker: Sample Script
    docker: wilken is NotForSale!
==> docker: Provisioning with shell script: foobar.sh
    docker: FooBar Script
    docker: wilken is NotForSale!
==> docker: Committing the container
    docker: Image ID: sha256:a412e43f134431f2049a7d06d5d691aad3717d91dd2ee5e2575e05b89384a4b3
==> docker: Killing the container: d8ed9100ff5017379bfc0d80703b2b2d10c4104941663aa5ddbbf18f6dcf74a5
Build 'docker' finished.

==> Builds finished. The artifacts of successful builds are:
--> docker: Imported Docker image: sha256:a412e43f134431f2049a7d06d5d691aad3717d91dd2ee5e2575e05b89384a4b3
```
</details>

### CODE REVIEW

File: provisioner/shell/provisioner.go [hunk 1]
```diff
@@ -232,7 +231,9 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
 		}
 
 		p.config.envVarFile = tf.Name()
-		defer os.Remove(p.config.envVarFile)
+
+		// Don't think this is needed as there is already a call to delete tf.Name() after creating the file
+		//defer os.Remove(p.config.envVarFile)
```
Comment (nywilken) [inline provisioner/shell/provisioner.go]: Seeing as `p.config.envVarFile` is pointing to the local file I don't think we need this as its deletion is being deferred on line 221. But let me know if I am missing something.

File: provisioner/shell/provisioner.go [hunk 2]
```diff
@@ -345,19 +344,22 @@ func (p *Provisioner) Provision(ctx context.Context, ui packer.Ui, comm packer.C
...
+		// Delete the temporary file we created. We retry this a few times
+		// since if the above rebooted we have to wait until the reboot
+		// completes.
+		if err := p.cleanupRemoteFile(p.config.RemotePath, comm); err != nil {
+			return err
+		}
+
+	}
+
+	if !p.config.SkipClean {
```
Comment (nywilken) [inline provisioner/shell/provisioner.go]: Looks like we need to keep this file around if SkipClean is true so wrapping the deletion here. Something doesn't feel right code wise about the nested if here, but I might just be nitpicking. Open to any suggestions on how to clean this up if needed :smile:

File: provisioner/shell/provisioner.go (hunk 1 above)
Comment (SwampDragons) [reply provisioner/shell/provisioner.go]: This seems good but I'd rather you just delete the line instead of commenting it out.

File: provisioner/shell/provisioner.go (hunk 2 above)
Comment (SwampDragons) [reply provisioner/shell/provisioner.go]: Feels a bit weird but I don't see a way that is obviously more elegant. I guess you could defer the call to delete from inside the loop, but then we wouldn't retrieve the err (not a dealbreaker since it should probably not error the whole provision run anyway), and we'd have to check and only run the defer on the first loop or something to prevent a bunch of defers piling up.

Comment (nywilken) [reply provisioner/shell/provisioner.go]: I really do like that option. But our future selves will probably be like why didn't you just use an if :laughing: Thanks for the review!

Comment (SwampDragons) [reply provisioner/shell/provisioner.go]: yeah, and it's the same amount of code complexity either way. Just leave it as it is here.
