### PR TITLE
fix: move adding metadata step after waiting for uploading step

### LINKED ISSUE #8009: openstack packer provisioner with volume fails with error on ceph backend
There appears to be a regression.

I am using packer openstack builder with the following configuration:

```
  "builders": [
    {
    "type": "openstack",
    "domain_name": "Default",
    "networks": ["{{ user `openstack_provider_network_id`}}"],
    "region": "regionOne",
    "ssh_username": "centos",
    "security_groups": "packer_provisioner",
    "image_name": "{{ user `openstack_image_name`}}",
    "source_image_name": "{{ user `openstack_source_image_name`}}",
    "flavor": "packer",
    "use_blockstorage_volume": "true",
    "volume_size": 56,
    "image_disk_format": "raw"
    }
  ]
```

After successful provisioning on an openstack vm, packer attempts to convert the volume to an image. It fails. Observed behaviour with packer 1.4.3

```
==> openstack: Stopping server: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
    openstack: Waiting for server to stop: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
==> openstack: Detaching volume packer_5d5acea6-c511-ad7a-3649-145419dad7e1 (volume id: 4be153c6-0333-42a5-aa5e-4803703b06c4)
==> openstack: Waiting for volume packer_5d5acea6-c511-ad7a-3649-145419dad7e1 (volume id: 4be153c6-0333-42a5-aa5e-4803703b06c4) to become available...
==> openstack: Creating the image: redacted
==> openstack: Error setting image metadata: Bad request with: [POST https://redacted/v3/6e95f572ba4449fba97791427d25fea4/volumes/4be153c6-0333-42a5-aa5e-4803703b06c4/action], error message: {"badRequest": {"message": "Invalid volume: Updat
ing volume metadata is not allowed for volumes in uploading status.", "code": 400}}
==> openstack: Terminating the source server: a84e213c-7c5a-4b82-a54f-3c641d084d39 ...
==> openstack: Deleting volume: 4be153c6-0333-42a5-aa5e-4803703b06c4 ...
==> openstack: Deleting temporary keypair: packer_5d5acea6-8871-8905-ae16-dc92bd0b7d7e ...
Build 'openstack' errored: Error setting image metadata: Bad request with: [POST https://redacted/v3/6e95f572ba4449fba97791427d25fea4/volumes/4be153c6-0333-42a5-aa5e-4803703b06c4/action], error message: {"badRequest": {"message": "Invalid v
olume: Updating volume metadata is not allowed for volumes in uploading status.", "code": 400}}
```

Expected behaviour (observed with packer 1.3.5):

```==> openstack: Stopping server: fe32f84d-db19-4c26-b840-9eed7922d95a ...
    openstack: Waiting for server to stop: fe32f84d-db19-4c26-b840-9eed7922d95a ...
==> openstack: Detaching volume packer_5d5ad655-cc33-a139-42cf-13871c552be0 (volume id: fd98a29d-5baa-4be3-8865-f38cb128bb61)
==> openstack: Waiting for volume packer_5d5ad655-cc33-a139-42cf-13871c552be0 (volume id: fd98a29d-5baa-4be3-8865-f38cb128bb61) to become available...
==> openstack: Creating the image: redacted
    openstack: Image: 2c52db5e-d94b-4b85-b554-2d10695ae656
==> openstack: Waiting for image redacted (image id: 2c52db5e-d94b-4b85-b554-2d10695ae656) to become ready...
==> openstack: Terminating the source server: fe32f84d-db19-4c26-b840-9eed7922d95a ...
==> openstack: Deleting volume: fd98a29d-5baa-4be3-8865-f38cb128bb61 ...
==> openstack: Deleting temporary keypair: packer_5d5ad655-3417-81ec-9401-5a80d2cfb29b ...
```

I am using ceph backend for block storage. Perhaps the recent changes in this area have not been tested against ceph.

### PR DESCRIPTION
**Pull request by psinghal20**
Fixes #8009.

Moves call to set Metadata for image while using `BlockStorageVolume` in openstack provisioner after waiting for image to be uploaded. Setting metadata for a image while it's being uploaded in not allowed.

Related to #7792.

### CODE REVIEW

**Comment by psinghal20** [comment]
@SwampDragons Can you take a look at the failing build? I think the failure might be unrelated to this change.

File: builder/openstack/step_create_image.go [hunk 1]
```diff
@@ -45,6 +45,7 @@ func (s *stepCreateImage) Run(ctx context.Context, state multistep.StateBag) mul
 	// Block Storage service volume or regular Compute service local volume.
 	ui.Say(fmt.Sprintf("Creating the image: %s", config.ImageName))
 	var imageId string
+	var blockStorageClient *gophercloud.ServiceClient
 	if s.UseBlockStorageVolume {
 		// We need the v3 block storage client.
 		blockStorageClient, err := config.blockStorageV3Client()
```
Comment (azr) [inline builder/openstack/step_create_image.go]: watch out, out of this scope `blockStorageClient` will always be nil.
```suggestion
		blockStorageClient, err = config.blockStorageV3Client()
```

**Comment by azr** [comment]
@psinghal20; I triggered a build.

File: builder/openstack/step_create_image.go (hunk 1 above)
Comment (psinghal20) [reply builder/openstack/step_create_image.go]: Yes, missed it. Fixed :smile:

**Comment by SwampDragons** [comment]
Thanks!
