### PR TITLE
error cleanup provisioner

### LINKED ISSUE #6760: FEATURE: run a custom script with --on-error=cleanup
Hi Devs, 

Can we have an option to run a custom script with --on-error=cleanup before packer starts the default cleanup? 

We are subscribing to RHEL Satellite in start of the build process and then unsubscribe at the end when build finishes.  Now if build fails in middle, the unsubscribe commands doesn't run which leaves zombie subscriptions in the Satellite which is managed by another team.

Option of running a custom script will help us to implement try/catch and do our cleanup before packer starts it's default cleanup. 

Thanks.

### PR DESCRIPTION
**Pull request by SwampDragons**
Creates a new root-level config slot for a single "cleanup" provisioner, to be run only if Packer errors. The cleanup provisioner can be any provisioner, but the assumed use case is that it'll be  a shell or powershell provisioner.  It will be run after the provisioning run fails, but before the instance is shut down and cleaned up or aborted. 

Closes #6760

### CODE REVIEW

**Comment by SwampDragons** [comment]
Example usage: 

```
{
	"builders": [
		{
			"type": "null",
			"communicator": "none"
		}
	],
	"provisioners": [
		{
			"type": "shell-local",
			"inline": ["exit 2"]
		}
	],
	"error-cleanup-provisioner": {
		"type": "shell-local",
		"inline": [ "echo 'rubber ducky' > ducky.txt" ]
	}
}
```

File: builder/null/builder.go [hunk 1]
```diff
@@ -29,15 +29,13 @@ func (b *Builder) Prepare(raws ...interface{}) ([]string, error) {
 func (b *Builder) Run(ctx context.Context, ui packer.Ui, hook packer.Hook) (packer.Artifact, error) {
 	steps := []multistep.Step{}
 
-	if b.config.CommConfig.Type != "none" {
```
Comment (azr) [inline builder/null/builder.go]: Oh, yes nice one I see that the `communicator.StepConnect` has a `"none"` case.

File: go.mod [hunk 2]
```diff
@@ -97,6 +97,7 @@ require (
 	github.com/mitchellh/go-fs v0.0.0-20180402234041-7b48fa161ea7
 	github.com/mitchellh/go-homedir v1.0.0
 	github.com/mitchellh/go-vnc v0.0.0-20150629162542-723ed9867aed
+	github.com/mitchellh/gox v1.0.1 // indirect
```
Comment (azr) [inline go.mod]: the `go.mod` and `go.sum` changes seem unrelated to this PR.

File: template/parse.go [hunk 3]
```diff
@@ -242,6 +243,36 @@ func (r *rawTemplate) Template() (*Template, error) {
 		result.Provisioners = append(result.Provisioners, &p)
 	}
 
+	// Gather the error-cleanup-provisioner
+	if r.CleanupProvisioner != nil {
+		var p Provisioner
```
Comment (azr) [inline template/parse.go]: I think the body of this `for` could be refactored into a `func` to decode provisioners. So that bugs come and go only once.

[the remark this answers is not in the document]
Comment (SwampDragons) [reply template/parse.go]: Good call.

**Comment by SwampDragons** [comment]
post-processors run after the VM is shut down, so a cleanup script could easily be run as part of whatever calls the packer build to begin with. the special part about this provisioner is that it runs while the instance is still up, so the timing is unique and can't be handled by a wrapper the way a cleanup postprocessor could be.
