### PR TITLE
Retry command execution when VM session is locked

### LINKED ISSUE #8059: VM corruption on session lock timeout cleanup
Hi,

I am working on an OS/2 Warp base image, which relies on some `vboxmanage` subcommands to swap out floppies prior to `boot_command`. I noticed that if I leave the VM running at the end of the `vboxmanage` section, then Packer appears to corrupt the VM on its way out of a cleanup step.

Example:

```json
      "vboxmanage": [
        ["modifyvm", "{{.Name}}", "--memory", "{{ user `ram_MiB` }}"],
        ["modifyvm", "{{.Name}}", "--vram", "{{ user `vram_MiB` }}"],
        ["modifyvm", "{{.Name}}", "--cpus", "{{ user `cpus` }}"],
        ["storagectl", "{{.Name}}", "--name", "Floppy Controller", "--add", "floppy"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Installation.img"],
        ["modifyvm", "{{.Name}}", "--boot1", "floppy"],
        ["startvm", "{{.Name}}"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk01.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "120000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk02.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "30000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Installation.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk01.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "120000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "/tmp/Disk02.img"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "30000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "300000"],
        ["storageattach", "{{.Name}}", "--storagectl", "Floppy Controller", "--port", "0", "--device", "0", "--type", "fdd", "--medium", "emptydrive"],
        ["guestproperty", "wait", "{{.Name}}", "goodnight-moon", "--timeout", "10000"],
        ["controlvm", "{{.Name}}", "keyboardputscancode", "1c"]
      ],
```

For now I have left out the `startvm`'s corresponding `controlvm <VM name> poweroff`, since I hadn't gotten far enough with the floppy install process to begin writing the `boot_command`.

With a configuration like this, Packer executes the VBoxManage commands, and then after the `1c` (Enter) scancode, quickly times out attempting to get a session lock to start the already-started VM for the `boot_command`. The error looks like:

```console
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 stderr: VBoxManage: error: The machine 'os/2' is already locked by a session (or being locked or unlocked)
2019/09/02 18:45:38 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:38 packer: VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
==> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The machine 'os/2' is already locked by a session (or being locked or unlocked)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 failed to unlock port lockfile: close tcp 127.0.0.1:3836: use of closed network connection
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 failed to unlock port lockfile: close tcp 127.0.0.1:5973: use of closed network connection
==> virtualbox-iso: VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 Executing VBoxManage: []string{"storageattach", "os/2", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 stdout:
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 stderr: VBoxManage: error: Controller 'IDE Controller' does not support hotplugging
2019/09/02 18:45:38 packer: VBoxManage: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component SessionMachine, interface IMachine, callee nsISupports
2019/09/02 18:45:38 packer: VBoxManage: error: Context: "DetachDevice(Bstr(pszCtl).raw(), port, device)" at line 403 of file VBoxManageStorageController.cpp
==> virtualbox-iso: Deregistering and deleting VM...
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 Executing VBoxManage: []string{"unregistervm", "os/2", "--delete"}
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 stdout:
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 stderr: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:38 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:38 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:38 packer: 2019/09/02 18:45:38 Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:38 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:38 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:39 packer: 2019/09/02 18:45:39 Executing VBoxManage: []string{"unregistervm", "os/2", "--delete"}
2019/09/02 18:45:39 packer: 2019/09/02 18:45:39 stdout:
2019/09/02 18:45:39 packer: 2019/09/02 18:45:39 stderr: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:39 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:39 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:39 packer: 2019/09/02 18:45:39 Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:39 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:39 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:40 packer: 2019/09/02 18:45:40 Executing VBoxManage: []string{"unregistervm", "os/2", "--delete"}
2019/09/02 18:45:40 packer: 2019/09/02 18:45:40 stdout:
2019/09/02 18:45:40 packer: 2019/09/02 18:45:40 stderr: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:40 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:40 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:40 packer: 2019/09/02 18:45:40 Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:40 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:40 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:41 packer: 2019/09/02 18:45:41 Executing VBoxManage: []string{"unregistervm", "os/2", "--delete"}
2019/09/02 18:45:41 packer: 2019/09/02 18:45:41 stdout:
2019/09/02 18:45:41 packer: 2019/09/02 18:45:41 stderr: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:41 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:41 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:41 packer: 2019/09/02 18:45:41 Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:41 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:41 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:42 packer: 2019/09/02 18:45:42 Executing VBoxManage: []string{"unregistervm", "os/2", "--delete"}
2019/09/02 18:45:42 packer: 2019/09/02 18:45:42 stdout:
2019/09/02 18:45:42 packer: 2019/09/02 18:45:42 stderr: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:42 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:42 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
2019/09/02 18:45:42 packer: 2019/09/02 18:45:42 Retryable error: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
2019/09/02 18:45:42 packer: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:42 packer: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
==> virtualbox-iso: Error deleting VM: retry count exhausted. Last err: VBoxManage error: VBoxManage: error: Cannot unregister the machine 'os/2' while it is locked
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "Unregister(CleanupMode_DetachAllReturnHardDisksOnly, ComSafeArrayAsOutParam(aMedia))" at line 154 of file VBoxManageMisc.cpp
==> virtualbox-iso: Deleting output directory...
2019/09/02 18:45:43 [INFO] (telemetry) ending virtualbox-iso
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
2019/09/02 18:45:43 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2019/09/02 18:45:43 machine readable: virtualbox-iso,error []string{"Error starting VM: VBoxManage error: VBoxManage: error: The machine 'os/2' is already locked by a session (or being locked or unlocked)\nVBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports\nVBoxManage: error: Context: \"LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())\" at line 726 of file VBoxManageMisc.cpp"}
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp
==> Builds finished but no artifacts were created.
Build 'virtualbox-iso' errored: Error starting VM: VBoxManage error: VBoxManage: error: The machine 'os/2' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
2019/09/02 18:45:43 [INFO] (telemetry) Finalizing.
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error starting VM: VBoxManage error: VBoxManage: error: The machine 'os/2' is already locked by a session (or being locked or unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), Bstr(strEnv).raw(), progress.asOutParam())" at line 726 of file VBoxManageMisc.cpp

==> Builds finished but no artifacts were created.
2019/09/02 18:45:44 waiting for all plugin processes to complete...
2019/09/02 18:45:44 /Users/andrew/go/bin/packer: plugin process exited
2019/09/02 18:45:44 /Users/andrew/go/bin/packer: plugin process exited
2019/09/02 18:45:44 /Users/andrew/go/bin/packer: plugin process exited
```

That Packer aborts is to be expected. Unfortunately, Packer's cleanup trap does not leave the VM alone, nor does cleanup fully remove the VM. The VDI file for the virtual hard drive file appears to have been deleted before checking whether the rest of the VM is deletable (haha, session lock!) And so the resulting VM is left in a bad state. For this reason, VM removal should probably be skipped on session lock timeout.

As a workaround, I am manually deleting the carcass each time this happens. In the future I will add more `guestproperty wait` sleep time at that point, say 20 minutes which is plenty of time to tinker and debug the VM before cleanup triggers. Though it has been illuminating to see exactly how Packer and VirtualBox interact in this case.

- Packer version from `packer version`: Packer v1.4.3-dev
- Host platform: macOS Mojave 10.14.6

### LINKED ISSUE #8282: builder/virtualbox: Error removing iso due to virtualbox lock still being hold
#### Overview of the Issue

Packer is having errors removing/ejecting the guest additions iso from the device as you can see at the logs bellow.

This issue seems related to https://github.com/hashicorp/packer/issues/4432, which seems to hint that the problem also applies/happens to cdroms.

#### Reproduction Steps

packer build

### Packer version

1.4.4

### Simplified Packer Buildfile

```
...
    {
      "name": "ubuntu-{{user `version`}}-amd64-virtualbox",
      "type": "virtualbox-iso",
      "guest_os_type": "Ubuntu_64",
      "guest_additions_mode": "attach",
      "headless": true,
...
```

The full file is at https://github.com/rgl/ubuntu-vagrant/blob/master/ubuntu.json#L49.

### Operating system and Environment details

Packer is running on Windows 10 and launching an Ubuntu 18.04 guest in VirtualBox 6.0.14.

### Log Fragments and crash.log files

I've started having these errors removing the guest additions iso:

```
2019/10/27 09:16:08 packer.exe: 2019/10/27 09:16:08 [ERROR] Remote command exited without exit status or exit signal.
2019/10/27 09:16:08 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: [sudo] password for vagrant:[0m
2019/10/27 09:16:08 packer.exe: 2019/10/27 09:16:08 Waiting max 5m0s for shutdown to complete
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 VM shut down.
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 Executing VBoxManage: []string{"storageattach", "packer-ubuntu-18.04-amd64-virtualbox-1572167140", "--storagectl", "IDE Controller", "--port", "0", "--device", "1", "--medium", "none"}
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 stdout:
2019/10/27 09:16:09 packer.exe: 2019/10/27 09:16:09 stderr: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
2019/10/27 09:16:09 packer.exe: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
2019/10/27 09:16:09 packer.exe: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Error detaching ISO: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp[0m
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Error detaching ISO: VBoxManage error: VBoxManage.exe: error: Failed to get a console object from the direct session (VBOX_E_INVALID_OBJECT_STATE)
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Details: code VBOX_E_VM_ERROR (0x80bb0003), component MachineWrap, interface IMachine, callee IUnknown
==> ubuntu-18.04-amd64-virtualbox: VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Shared)" at line 336 of file VBoxManageStorageController.cpp[0m
2019/10/27 09:16:09 ui error: [1;31m==> ubuntu-18.04-amd64-virtualbox: Step "StepRemoveDevices" failed, aborting...[0m
```

Setting `"post_shutdown_delay": "2m"` works around the problem, but doing that feels more like an workaround rather than a root cause fix.

The problem might even be on VirtualBox (sorry, but I didn't try with an older version).

### PR DESCRIPTION
**Pull request by sylviamoss**
Whenever there's a session locking the VM, the driver should retry executing the command until the lock is released. If that's doesn't happen, after 5 retries, the current error will be returned to the parent method. 

Also, moving 2 seconds sleep after VM stop command to default config of `post_shutdown_delay` used [here](https://github.com/hashicorp/packer/blob/master/builder/virtualbox/common/step_shutdown.go#L72). 

With these changes, I expect to avoid other situations that be locked by session error.

Closes #8282
Closes #8059

### CODE REVIEW

File: builder/virtualbox/common/driver_4_2.go [hunk 1]
```diff
@@ -189,7 +186,18 @@ func (d *VBox42Driver) SuppressMessages() error {
 }
 
 func (d *VBox42Driver) VBoxManage(args ...string) error {
-	_, err := d.VBoxManageWithOutput(args...)
+	ctx := context.TODO()
+	err := retry.Config{
+		Tries: 5,
+		ShouldRetry: func(err error) bool {
+			return isLockedBySession(err.Error())
```
Comment (nywilken) [inline builder/virtualbox/common/driver_4_2.go]: Nit: Seeing as the isLockedBySession function is a one liner and not used anywhere else I would recommend replacing this line with then contents of the function; adding a comment mentioning that this error represents the VM being in a locked state.

```suggestion
			return strings.Contains(err.Error(), "VBOX_E_INVALID_OBJECT_STATE")
```

Comment (sylviamoss) [reply builder/virtualbox/common/driver_4_2.go]: thanks!! first I was thinking about making clear that is a session lock thing because the code is not that clear, but is a state thing as well so the method is not that necessary!
