### PR TITLE
Populating the PackerSensitiveVars variable

### LINKED ISSUE #12918: Sensitive variables are logged when escaped for powershell
#### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Overview of the Issue

When sensitive variables contain characters that require escaping the logs will print that sensitive variable in its escaped form.

#### Reproduction Steps

Run example from powershell with PACKER_LOG=1:

```
$Env:PACKER_LOG=1;& .\packer.exe build -var password="abc`$123" password.pkr.hcl
```

### Packer version

Packer v1.10.2

### Simplified Packer Template

```
variable "password" {
  type    = string
  sensitive = true
}

source "file" "basic-example" {
  content =  "Lorem ipsum dolor sit amet"
  target =  "dummy_artifact"
}

build {
  sources = ["sources.file.basic-example"]

  provisioner "powershell" {
    environment_vars = [
      "PASSWORD=${var.password}",
    ]
    inline = ["echo foo"]
  }
}
```

### Operating system and Environment details

Windows Server 2022

### Log Fragments and crash.log files

```
2024/04/12 10:11:48 packer.exe plugin: Env var <sensitive> converted to abc`$123 after escaping chars special to PS
```

[Full Logs](https://gist.github.com/zinkj/813d23131dc112aa0c75a52c7ad4fb83)

### PR DESCRIPTION
**Pull request by tanmay-hc**
### Description
This change populates the `PackerSensitiveVars` variable. This will help the provisioners to treat the sensitive variables differently.
This allows us to add a check to a log line not to print a log if a variable is sensitive, as can be seen in the powershell provisioner file.

### Resolved Issues
Closes #12918

### CODE REVIEW

**Review by kp2099 — COMMENTED** [review]
I'm not sure we should completely remove the output value of the environment variables, as it could be helpful for customers to see how they're being escaped in PowerShell.

**Comment by anurag5sh** [comment]
Can u once test if this works fine with machine readable format too? @tanmay-hc

**Comment by anurag5sh** [comment]
Since the LogSecretFilter already contains the sensitive variables to be masked, we can try the following if it works:

```
	// Split vars into key/value components
	for _, envVar := range p.config.Vars {
		envVar, err := interpolate.Render(envVar, &p.config.ctx)
		if err != nil {
			return
		}
		keyValue := strings.SplitN(envVar, "=", 2)
		
                //Skip sensitive variables   <---try this
		if packersdk.LogSecretFilter.FilterString(keyValue[1]) != keyValue[1] {
			continue
		}
		
                // Escape chars special to PS in each env var value
		escapedEnvVarValue := psEscape.Replace(keyValue[1])
		if escapedEnvVarValue != keyValue[1] {
			log.Printf("Env var %s converted to %s after escaping chars special to PS", keyValue[1],
				escapedEnvVarValue)
		}
		envVars[keyValue[0]] = escapedEnvVarValue
	}
```

We are essentially checking if the variable is masked by the logger, if so then skip the log.

File: provisioner/powershell/provisioner.go [hunk 1]
```diff
@@ -535,7 +535,16 @@ func (p *Provisioner) createFlattenedEnvVars(elevated bool) (flattened string) {
 		keyValue := strings.SplitN(envVar, "=", 2)
 		// Escape chars special to PS in each env var value
 		escapedEnvVarValue := psEscape.Replace(keyValue[1])
-		if escapedEnvVarValue != keyValue[1] {
+
+		isSensitive := false
+		for _, sensitiveVar := range p.config.PackerSensitiveVars {
```
Comment (anurag5sh) [inline provisioner/powershell/provisioner.go:540]: I think we can refactor to this something more simpler like
```
//Skip sensitive variables
if slices.Contains(p.config.PackerSensitiveVars, keyValue[1]) {
	continue
}
```
we can test if this may work.

**Review by anurag5sh — COMMENTED** [review]
Rest of the changes looks good to me.

**Review by anurag5sh — DISMISSED** [review]
Thanks for fixing the PackerSensitiveVars along with the logging issue. LGTM!

**Review by anshulsharma-hashicorp — DISMISSED** [review]
LGTM

**Review by anurag5sh — APPROVED** [review]
