### PR TITLE
don't error if metadata can't be set. Old versions of openstack don't…

### LINKED ISSUE #9190: Openstack,  error setting os-set_image_metadata
## Overview of the Issue
When creating an image on openstack, the last steps fail where it seems packer wants to set some metadata on the image but is unable to do so.

#### Reproduction Steps

Steps to reproduce this issue
Create a build.json with a builder such as:
```
  "builders": [
    {
      "type": "openstack",
      "communicator": "ssh",
      "ssh_pty": true,
      "name": "puppet",
      "flavor": "s2.medium.2",
      "ssh_username": "linux",
      "region": "eu-de",
      "use_blockstorage_volume": true,
      "image_name": "silver-packer-client-{{isotime}}",
      "source_image_filter": {
        "filters": {
          "name": "Standard_CentOS_7_latest"
        },
        "most_recent": true
      },
      "networks": [
        "{{user `network`}}"
      ],
      "floating_ip_network": "0a2228f2-7f8a-45f1-8e09-9039e1d09975",
      "security_groups": ["7217857b-1722-4afe-bbd6-4aeb82d47811"]

    },

```

Build completes, but during final steps of "wrapping up", the following error is displayed:
```
TestPackerBasic 2020-05-08T08:22:33+02:00 command.go:168: 2020/05/08 08:22:33 1588918953,,ui,error,==> puppet: Error setting image metadata: Bad request with: [POST https://openstack_url/v3/de92f894b64f4d1c99803d225315ff62/volumes/5cf66e2d-e970-4a1e-be21-127959bf4f8a/action]%!(PACKER_COMMA) error message: {"badRequest":{"message":"There is no such action: os-set_image_metadata"%!(PACKER_COMMA)"code":400}}
TestPackerBasic 2020-05-08T08:22:33+02:00 command.go:168: 1588918953,,ui,error,==> puppet: Error setting image metadata: Bad request with: [POST https://openstack_url/v3/de92f894b64f4d1c99803d225315ff62/volumes/5cf66e2d-e970-4a1e-be21-127959bf4f8a/action]%!(PACKER_COMMA) error message: {"badRequest":{"message":"There is no such action: os-set_image_metadata"%!(PACKER_COMMA)"code":400}}
```

### Packer version

From `packer version`
Versions tested: 1.5.1, 1.5.6

### PR DESCRIPTION
**Pull request by SwampDragons**
Don't fail the whole build if we can't set metadata on the blockstorage image. 
Closes #9190

### CODE REVIEW

File: builder/openstack/step_create_image.go [hunk 1]
```diff
@@ -65,7 +65,6 @@ func (s *stepCreateImage) Run(ctx context.Context, state multistep.StateBag) mul
 				err := fmt.Errorf("Error setting image metadata: %s", err)
```
Comment (azr) [inline builder/openstack/step_create_image.go:65]: Do we want to make of this a warning ?

Comment (SwampDragons) [reply builder/openstack/step_create_image.go:65]: Probably, yes.
