### PR TITLE
Say so when an only or an except option did not match anything

### LINKED ISSUE #11020: JSON to HCL2 migration: Valid template silently fails
Thank you for all the effort you have put into making packer, and for making it open source.

#### Overview of the Issue

`packer build -only=<builder-name> template.pkr.hcl` returns no artifacts and no meaningful information.

When migrating for JSON to HCL2 in Packer 1.7.2 there is a gotcha in the documented behavior.
Ideally when called with a builder name passed in via `-only`, such as `packer builder -only=builder-name some.pkr.hcl`, Packer should report that builder names were valid for JSON templates but are invalid for HCL templates.

At the very least Packer should report that it was unable to find a build source named `<only-parameter>`.

#### Reproduction Steps

Add builder name to the `-only` option, with a HCL template.

For the template given below:

```
packer build -only=upcloud template.pkt.hcl
```

### Packer version

```
$ packer version
Packer v1.7.2
```

### Simplified Packer Buildfile

```hcl
variable "username" {
  type = string
  default = "${env("UPCLOUD_API_DEVELOPMENT_USER")}"
}

variable "password" {
  type = string
  default = "${env("UPCLOUD_API_DEVELOPMENT_PASSWORD")}"
}

packer {
    required_plugins {
        upcloud = {
            version = ">=v1.0.0"
            source = "github.com/UpCloudLtd/upcloud"
        }
    }
}

source "upcloud" "test" {
  username = "${var.username}"
  password = "${var.password}"
  zone = "nl-ams1"
  storage_name = "ubuntu server 20.04"
  template_prefix = "ubuntu-server"
}

build {
  sources = ["source.upcloud.test"]
}
```

### Operating system and Environment details

```bash
$ uname -a
Linux desktop.local.lan 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### Log Fragments and crash.log files

```
Debug mode enabled. Builds will not be parallelized.

==> Wait completed after 4 microseconds

==> Builds finished but no artifacts were created.
```

Set the env var `PACKER_LOG=1` for maximum log detail.

```
$ PACKER_LOG=1 /usr/local/bin/packer build -debug -only=upcloud ubuntu/upcloud-test.pkr.hcl 2>&1 > ./s
cratch/packer-strace.log2021/05/16 17:58:10 [INFO] Packer version: 1.7.2 [go1.16.3 linux amd64]2021/05/16 17:58:10 [TRACE] discovering plugins in /usr/local/bin2021/05/16 17:58:10 [TRACE] discovering plugins in /home/user/.packer.d/plugins2021/05/16 17:58:10 [TRACE] discovering plugins in .2021/05/16 17:58:10 [INFO] PACKER_CONFIG env var not set; checking the default config file path2021/05/16 17:58:10 [INFO] PACKER_CONFIG env var set; attempting to open config file: /home/user/.packerconfig2021/05/16 17:58:10 [WARN] Config file doesn't exist: /home/user/.packerconfig2021/05/16 17:58:10 [INFO] Setting cache directory: /home/user/chef/packer/packer_cache2021/05/16 17:58:10 [TRACE] listing potential installations for "github.com/upcloudltd/upcloud" that match ">=v1.0.0". plugingetter.ListInstallationsOptions{FromFolders:[]string{"/usr/local/bin/packer", ".", "/home/user/.packer.d/plugins"}, BinaryInstallationOptions:plugingetter.BinaryInstallationOptions{APIVersionMajor:"5", APIVersionMinor:"0", OS:"linux", ARCH:"amd64", Ext:"", Checksummers:[]plugingetter.Checksummer{plugingetter.Checksummer{Type:"sha256", Hash:(*sha256.digest)(0xc000042380)}}}}
2021/05/16 17:58:10 [TRACE] Found the following "github.com/upcloudltd/upcloud" installations: [{/home/user/.packer.d/plugins/github.com/upcloudltd/upcloud/packer-plugin-upcloud_v1.0.0_x5.0_linux_amd64 v1.0.0}]
2021/05/16 17:58:10 [INFO] found external [-packer-default-plugin-name-] builders from upcloud plugin
2021/05/16 17:58:10 [TRACE] validateValue: not active for username, so skipping
2021/05/16 17:58:10 [TRACE] validateValue: not active for password, so skipping
2021/05/16 17:58:10 Build debug mode: true
2021/05/16 17:58:10 Force build: false
2021/05/16 17:58:10 On error:
2021/05/16 17:58:10 Waiting on builds to complete...
==> Wait completed after 5 microseconds
==> Builds finished but no artifacts were created.
2021/05/16 17:58:10 [INFO] (telemetry) Finalizing.
2021/05/16 17:58:11 waiting for all plugin processes to complete..
```

### PR DESCRIPTION
**Pull request by azr**
Before:

```shellsession
❯ packerdev build --only upcloud .vscode/only-test.pkr.hcl

==> Wait completed after 5 microseconds

==> Builds finished but no artifacts were created.

❯ packerdev build --except upcloud .vscode/only-test.pkr.hcl
Error: 2 error(s) occurred:

* 'username' must be specified
* 'password' must be specified

  on .vscode/only-test.pkr.hcl line 21:
  (source code not available)

==> Wait completed after 5 microseconds

==> Builds finished but no artifacts were created.
exit status 1
```

After:
```shellsession
❯ packerdev build --only upcloud .vscode/only-test.pkr.hcl
Warning: an 'only' option was passed, but did not match any build.

Possible build names: [upcloud.test].
These could also be matched with a glob pattern like: 'happycloud.*'



==> Wait completed after 5 microseconds

==> Builds finished but no artifacts were created.

❯ packerdev build --except upcloud .vscode/only-test.pkr.hcl
Error: 2 error(s) occurred:

* 'username' must be specified
* 'password' must be specified

  on .vscode/only-test.pkr.hcl line 21:
  (source code not available)

Warning: an 'except' option was passed, but did not match any build.

Possible build names: [upcloud.test].
These could also be matched with a glob pattern like: 'happycloud.*'



==> Wait completed after 5 microseconds

==> Builds finished but no artifacts were created.
exit status 1
```

Close #11020

### CODE REVIEW

**Review by sylviamoss — APPROVED** [review]
Nice!! 👍🏼

File: hcl2template/types.packer_config.go [hunk 1]
```diff
@@ -550,6 +554,22 @@ func (cfg *PackerConfig) GetBuilds(opts packer.GetBuildsOptions) ([]packersdk.Bu
 			res = append(res, pcb)
 		}
 	}
+	if len(opts.Only) > opts.OnlyMatches {
+		diags = append(diags, &hcl.Diagnostic{
+			Severity: hcl.DiagWarning,
+			Summary:  "an 'only' option was passed, but did not match any build.",
```
Comment (nywilken) [inline hcl2template/types.packer_config.go:560]: A bit of a weird edge case as a user would have to specify more `only` opts than actual defined sources. But I think it could be a bit misleading to the user if they accidentally fall into the edge case so I'm suggesting a small text change. See use case below. 
 
```suggestion
			Summary:  "an 'only' option was passed, but did not all matches were found for the given build.",
```


```bash
~>  packer build -debug -only=upcloud.test,amazon-ebs.example .
Error: 2 error(s) occurred:

* 'username' must be specified
* 'password' must be specified

  on source.pkr.hcl line 20:
  (source code not available)

Warning: an 'only' option was passed, but did not match any build.

Possible build names: [upcloud.test upcloud.example].
These could also be matched with a glob pattern like: 'happycloud.*'


Debug mode enabled. Builds will not be parallelized.

==> Wait completed after 10 microseconds

==> Builds finished but no artifacts were created.
```

**Review by nywilken — APPROVED** [review]
This looks great. Including a list of possible build names is a nice touch. I left a small suggestion on the warning message. But this is otherwise good to go.

**Review by SwampDragons — APPROVED** [review]
Hooray for helpful error messages!

File: hcl2template/types.packer_config.go (hunk 1 above)
Comment (azr) [reply hcl2template/types.packer_config.go:560]: Oh yeah that's a good idea !
