### PR TITLE
post-processor/vsphere: Fix password encoding in vsphere post-processor ovftool call

### LINKED ISSUE #9184: vpshere post-provisioner urlencoded password problem
As you all know troubleshooting `ovftool` is a nightmare as the logs don't bubble up.

For some reason this only seems to be a problem on import. Export is fine! 

However i've isolated a problem where `ovftool` fails on import whether or not the password is urlencoded or not the only way the ovftool import command sucessfully is to surround the `vi://` URL with single quotes.

```
ovftool output-vmware-iso/devops-packer-base-centos-1588816488.ova 'vi://USERNAME@vsphere.local:PASSWORD@VCENTER.FQDN.OR.IP/DATACENTER/host/ESXI.HOST.FQDN'
```

Or the password will have to be URL encoded before its put into the command, but I am having trouble getting that to consistently work.

Looks like this is brought up here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/packer-tool/kEdtattbOXQ/EbmyPrjxCAAJ and here 
https://github.com/hashicorp/packer/issues/6091

```
{
  "builders": [{
    "boot_wait": "5s",
    "boot_command": [
      "<esc>",
      "<wait>linux inst.ks=hd:/dev/fd0:ks.cfg<enter>"
    ],
    "floppy_files": [
      "ks.cfg"
    ],
    "type": "vmware-iso",
    "remote_username": "USERNAME",
    "remote_password": "{{user `vcenter_password`}}",
    "iso_checksum_type": "file",
    "iso_checksum": "http://spout.ussg.indiana.edu/linux/centos/7.8.2003/isos/x86_64/sha256sum.txt.asc",
    "guest_os_type": "centos7_64Guest",
    "iso_urls": "http://spout.ussg.indiana.edu/linux/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-Minimal-2003.iso",
    "vm_name": "devops-packer-base-centos-{{user `unix_timestamp`}}",
    "ssh_username": "USERNAME",
    "ssh_password": "PASSWORD",
    "disk_size": "40000",
    "remote_host": "HOST.IP",
    "remote_datastore": "DATASTORE",
    "remote_cache_datastore": "DATASTORE",
    "remote_cache_directory": "DIRECTORY",
    "network_adapter_type": "vmxnet3",
    "memory": "8000",
    "remote_type": "esx5",
    "format": "ova",
    "vnc_disable_password": true,
    "ssh_timeout": "40m",
    "keep_registered": false,
    "vmx_data": {
      "ethernet0.networkName": "VM Network"
    },
    "ovftool_options":[
      "--X:noPrompting"
    ]
  }
],
  "provisioners" :[{
    "type": "inspec",
    "profile": "inspec/base-os"
  }
],
"post-processors": [{
  "type": "vsphere",
  "cluster":"HOST.FQDN",
  "datacenter":"DATACENTER",
  "host": "VCENTER.FQDN",
  "password": "{{user `url_encoded_password`}}",
  "username": "USERNAME@vsphere.local",
  "datastore": "DATASTORE",
  "vm_name": "imported-devops-packer-base-centos-{{user `unix_timestamp`}}",
  "insecure": "true",
  "keep_input_artifact": true,
  "options":[
    "--X:noPrompting"
  ]
}]
}
```

### PR DESCRIPTION
**Pull request by SwampDragons**
Previously the vsphere post-processor code used QueryEscape to escape usernames and passwords, which is not entirely correct for special characters. Switch to using the URL struct, which encodes differently based on the part of URL that things are in. 

Still needs to be verified against issue #9184. Hasn't been tested yet. 

Closes #9184

### CODE REVIEW

File: post-processor/vsphere/post-processor.go [hunk 1]
```diff
@@ -115,6 +115,33 @@ func (p *PostProcessor) Configure(raws ...interface{}) error {
...
+
+	if p.config.ResourcePool != "" {
+		ovftool_uri += "/Resources/" + p.config.ResourcePool
+	}
+
+	u, err := url.Parse(ovftool_uri)
+	if err != nil {
+		return nil, fmt.Errorf("Couldn't generate uri for ovftool: %s", err)
+	}
+	u.User = url.UserPassword(p.config.Username, p.config.Password)
```
Comment (azr) [inline post-processor/vsphere/post-processor.go:133]: nice !

File: post-processor/vsphere/post-processor.go [hunk 2]
```diff
@@ -115,6 +115,33 @@ func (p *PostProcessor) Configure(raws ...interface{}) error {
...
+
+	if p.config.ESXiHost != "" {
+		if ipv4Regex.MatchString(p.config.ESXiHost) {
+			u.RawQuery = "ip=" + url.QueryEscape(p.config.ESXiHost)
+		} else if hostnameRegex.MatchString(p.config.ESXiHost) {
+			u.RawQuery = "dns=" + url.QueryEscape(p.config.ESXiHost)
+		}
+	}
```
Comment (azr) [inline post-processor/vsphere/post-processor.go:141]: This might lose potentially already present query parameters, one thing we can do:
```suggestion
	if p.config.ESXiHost != "" {
		q := u.Query()
		if ipv4Regex.MatchString(p.config.ESXiHost) {
			q.Add("ip", p.config.ESXiHost)
		else if hostnameRegex.MatchString(p.config.ESXiHost) {
			q.Add("dns", p.config.ESXiHost)
		}
		u.RawQuery = q.Encode()
	}
```

File: post-processor/vsphere/post-processor.go [hunk 3]
```diff
@@ -170,20 +178,24 @@ func (p *PostProcessor) PostProcess(ctx context.Context, ui packer.Ui, artifact
...
 
 	return artifact, false, false, nil
 }
 
-func (p *PostProcessor) filterLog(s string) string {
-	password := escapeWithSpaces(p.config.Password)
-	return strings.Replace(s, password, "<password>", -1)
+func filterLog(s string, u *url.URL) string {
+	password, passwordSet := u.User.Password()
+	if passwordSet {
```
Comment (azr) [inline post-processor/vsphere/post-processor.go:194]:
```suggestion
	if passwordSet && password != "" {
```

Just in case the password is set but empty ? https://play.golang.org/p/pYecpKxnuVf

**Comment by SwampDragons** [comment]
Once this is merged I am going to make a follow-up PR that cleans up the log filtering and fixes some stdin hanging that happens with invalid ovftool calls.

**Comment by SwampDragons** [comment]
This is ready for review; I have tested it with a password containing special characters and it works.

File: post-processor/vsphere/post-processor_test.go [hunk 4]
```diff
@@ -50,24 +71,33 @@ func TestEscaping(t *testing.T) {
 	cases := []escapeCases{
 		{`this has spaces`, `this%20has%20spaces`},
 		{`exclaimation_!`, `exclaimation_%21`},
-		{`hash_#_dollar_$`, `hash_%23_dollar_%24`},
```
Comment (SwampDragons) [inline post-processor/vsphere/post-processor_test.go:53]: This test is useful because it validates that there's a big difference between which vars were being encoded before versus which are being encoded now.

File: post-processor/vsphere/post-processor.go [hunk 5]
```diff
@@ -170,20 +180,24 @@ func (p *PostProcessor) PostProcess(ctx context.Context, ui packer.Ui, artifact
...
 
 	artifact = NewArtifact(p.config.Datastore, p.config.VMFolder, p.config.VMName, artifact.Files())
 
 	return artifact, false, false, nil
 }
 
-func (p *PostProcessor) filterLog(s string) string {
-	password := escapeWithSpaces(p.config.Password)
-	return strings.Replace(s, password, "<password>", -1)
+func filterLog(s string, u *url.URL) string {
```
Comment (SwampDragons) [inline post-processor/vsphere/post-processor.go:194]: Ignore this filter for now. It's going to be replaced in a follow-up PR.

**Comment by SwampDragons** [comment]
I think this pr has already been reviewed, so I'm going to merge it and open the follow-up which still needs review.
