### PR TITLE
Fix the version parsing in ChecksumFileEntry.init() so that plugins whose name contain v's can `packer init`

### LINKED ISSUE #10759: packer init fails to install plugins whose name contain a 'v'
#### Overview of the Issue

I'm the developer for the [packer-plugin-xenserver](https://github.com/ddelnano/packer-plugin-xenserver). I recently upgraded it to use the packer-plugin-sdk and noticed that I was unable to `packer init` despite following all the instructions for migrating to the SDK.

When running `packer init` with the following file in my current working directory I see the following output 
```
ddelnano@ddelnano-desktop:~/code/packer$ cat test.pkr.hcl
packer {
  required_plugins {
   xenserver= {
      version = ">= 0.3.0"
      source = "github.com/ddelnano/xenserver"
    }
   upcloud = {
      version = "= v1.0.0"
      source = "github.com/UpCloudLtd/upcloud"
    }
  }
}

ddelnano@ddelnano-desktop:~/code/packer$ /usr/local/bin/packer1.7 init test.pkr.hcl
could not find a local nor a remote checksum for plugin "github.com/ddelnano/xenserver" ">= 0.3.0"

```
I'm very confident that the packer-plugin-xenserver is compliant and there is something going on inside packer here.

#### Reproduction Steps

1. Install packer 1.7 or later
2.Create the `test.pkr.hcl` as mentioned above
3. Run `PACKER_LOG=1 packer init test.pkr.hcl` and see that it will not install
### Packer version
1.7

### PR DESCRIPTION
**Pull request by ddelnano**
This change addresses #10759 and allows me to get the [packer-plugin-xenserver](https://github.com/ddelnano/packer-plugin-xenserver/) (which was recently migrated to the packer-pluginsdk) working with `packer init`.

`TrimLeft` and `TrimRight` remove all leading and trailing occurrences of cutset (see [golang docs](https://golang.org/pkg/strings/#TrimLeft)). This creates problems where the packer plugin name contains a "v" because that is [passed into](https://github.com/hashicorp/packer/blob/4bbeec4733a51a0e90c4d42cc45782d4c72ce01b/packer/plugin-getter/plugins.go#L65) the "cutset" parameter and means that the leading "v" of the plugin version is stripped off on the [TrimLeft](https://github.com/hashicorp/packer/blob/4bbeec4733a51a0e90c4d42cc45782d4c72ce01b/packer/plugin-getter/plugins.go#L308). What we really want is to trim the suffix or prefix.

## Testing
- [x] Included a unit test for this change. I tried to avoid testing the private `init` function direclty but the other tests have a bunch of plugin files checked into the repo so that seemed like too much work for testing this simple logic
- [x] Verified that building packer from this branch fixes the issue reported in #10759
```
# See that I'm on this branch
ddelnano@ddelnano-desktop:~/code/packer$ git log --name-status HEAD^..HEAD
commit 2f28a9c34cad4f56490d9e65e05a99bb822892f4 (HEAD -> fix-packer-init-for-plugins-with-v-in-name, origin/fix-packer-init-for-plugins-with-v-in-name)
Author: Dom Del Nano <ddelnano@gmail.com>
Date:   Fri Mar 12 23:24:42 2021 -0800

    Fix the version parsing in ChecksumFileEntry.init() so that plugins whose name contains a 'v' work with packer init

M       packer/plugin-getter/plugins.go
M       packer/plugin-getter/plugins_test.go

# compile packer with this change
ddelnano@ddelnano-desktop:~/code/packer$ go build -o bin/packer

# See that packer successfully install the plugin
ddelnano@ddelnano-desktop:~/code/packer$  ./bin/packer init test.pkr.hcl
Installed plugin github.com/ddelnano/xenserver v0.3.0 in "/home/ddelnano/.packer.d/plugins/github.com/ddelnano/xenserver/packer-plugin-xenserver_v0.3.0_x5.0_linux_amd64"
```
- [x] See that packer 1.7 is unable to install the xenserver v0.3.0 plugin installed in the previous step
```
ddelnano@ddelnano-desktop:~/code/packer$ /usr/local/bin/packer1.7 version
Packer v1.7.0
ddelnano@ddelnano-desktop:~/code/packer$ /usr/local/bin/packer1.7 init test.pkr.hcl
could not find a local nor a remote checksum for plugin "github.com/ddelnano/xenserver" ">= 0.3.0"

``` 

Closes #10759

### CODE REVIEW

File: packer/plugin-getter/plugins_test.go [hunk 1]
```diff
@@ -27,6 +27,28 @@ var (
...
 )
 
+func TestChecksumFileEntry_init(t *testing.T) {
+	expectedVersion := "v0.3.0"
+	req := &Requirement{
+		Identifier: &addrs.Plugin{
+			Hostname:  "github.com/ddelnano/packer-plugin-xenserver",
+			Namespace: "",
+			Type:      "xenserver",
+		},
```
Comment (dsko1234) [inline packer/plugin-getter/plugins_test.go:37]: From how i understand the [plugin source syntax](https://www.packer.io/docs/plugins#source-addresses) of packer
packer doesn't use the normal url syntax, and instead constructs the plugin name like this:

https://$hostname/$namespace/packer-plugin-$type

it should be like this:
```
Identifier: &addrs.Plugin{
	Hostname:  "github.com",
	Namespace: "ddelnano",
	Type:      "xenserver",
},
```

I have run the tests like with this change and they do pass.

**Review by dsko1234 — CHANGES_REQUESTED** [review]

File: packer/plugin-getter/plugins_test.go (hunk 1 above)
Comment (ddelnano) [reply packer/plugin-getter/plugins_test.go]: I meant to circle back and make sure I got these fields right but I forgot. Updated this in my latest revision.

File: packer/plugin-getter/plugins_test.go [hunk 2]
```diff
@@ -27,6 +27,32 @@ var (
 	pluginFolderWrongChecksums = filepath.Join("testdata", "wrong_checksums")
 )
 
+func TestChecksumFileEntry_init(t *testing.T) {
```
Comment (sylviamoss) [inline packer/plugin-getter/plugins_test.go:30]: Nice!

**Review by sylviamoss — APPROVED** [review]
Nice catch! LGTM 👍🏼

File: packer/plugin-getter/plugins.go [hunk 3]
```diff
@@ -305,12 +305,12 @@ func (e ChecksumFileEntry) Arch() string        { return e.arch }
 //
 func (e *ChecksumFileEntry) init(req *Requirement) (err error) {
 	filename := e.Filename
-	res := strings.TrimLeft(filename, req.FilenamePrefix())
+	res := strings.TrimPrefix(filename, req.FilenamePrefix())
```
Comment (azr) [inline packer/plugin-getter/plugins.go:308]: Oh, nice catch, I completely meant to use `TrimPrefix` here !

**Review by azr — APPROVED** [review]
This LGTM, thanks for taking the time to make a PR !!
