### PR TITLE
fix ssh interface docs for amazon builders

### LINKED ISSUE #8565: Add documentation for ssh_interface option
#### Feature Description
The available options for the `ssh_interface` option should be documented (possibly per builder?), e.g. for Amazon public_ip, public_dns, private_ip, private_dns

#### Use Case(s)
I had problems connecting to my instance, changing the ssh_interface option to 'public_ip' solved this, however that wasn't obvious from the documentation and required quite a bit of googling.

### PR DESCRIPTION
**Pull request by SwampDragons**
Update docs to actually contain useful information on the amazon page. 

Closes #8565

### CODE REVIEW

File: builder/amazon/common/run_config.go [hunk 1]
```diff
@@ -377,8 +377,20 @@ type RunConfig struct {
 	WindowsPasswordTimeout time.Duration `mapstructure:"windows_password_timeout" required:"false"`
 
 	// Communicator settings
-	Comm         communicator.Config `mapstructure:",squash"`
-	SSHInterface string              `mapstructure:"ssh_interface"`
+	Comm communicator.Config `mapstructure:",squash"`
+
+	// One of `public_ip`, `private_ip`, `public_dns`, or `private_dns`. If
+	//    set, either the public IP address, private IP address, public DNS name
+	//    or private DNS name will used as the host for SSH. The default behaviour
```
Comment (nywilken) [inline builder/amazon/common/run_config.go]:
```suggestion
	//    or private DNS name will be used as the host for SSH. The default behaviour
```

Comment (SwampDragons) [reply builder/amazon/common/run_config.go]: Good catch. Pushed up a commit that fixes this and regenerates the code.
